### ISSUE TITLE
Cloud SQL Postgres support?

### ISSUE THREAD

**Issue by tmc** [GoogleCloudPlatform/k8s-config-connector#1]
On initial inspection it appears that only MySQL instances/dbs are in-scope here. Timeline/plans for Postgres support?

**Comment by kibbles-n-bytes** [comment]
Postgres is supported today. The `SQLInstance` resource maps to the common sqladmin [instance](https://cloud.google.com/sql/docs/mysql/admin-api/v1beta4/instances) resource. You can create a Postgres instance by applying something like the following:

```yaml
apiVersion: sql.cnrm.cloud.google.com/v1alpha2
kind: SQLInstance
metadata:
  name: postgres-instance-sample
spec:
  databaseVersion: POSTGRES_9_6
  settings:
    tier: db-custom-1-3840
```
