### ISSUE TITLE
Cloud Armor - Config Connector gives Invalid value for field 'resource.rateLimitOptions.enforceOnKeyConfigs'

### ISSUE THREAD

**Issue by henrique-freitas** [GoogleCloudPlatform/k8s-config-connector#1022]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

We started the task of managing the cloud resources we have using the config connector. The API behaves strangely when creating or updating the resource. in both cases the API rejects the call with `Invalid value for field 'resource.rateLimitOptions.enforceOnKeyConfigs, Only one of enforceOnKey and enforceOnKeyConfigs can be specified`

even when we create the policy manually in the Google Cloud console and export it using the command `config-connector export "//compute.googleapis.com/projects/my-project-id/global/securityPolicies/my-test-policy-2" --output my-test-policy-2.yaml` , and trying to apply using kubectl apply we received the same error.

In the documentation [ComputeSecurityPolicy](https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computesecuritypolicy)  there is a optional string field called `enforceOnKey`  In export command this field is not shown in the yaml file, we decided to put it with an empty value `enforceOnKey: "" ` and after that it worked normally without the error above, even though it was described as optional, it was a solution we found to solve the problem for now.

### Additional Diagnostic Information

Without the optional field `enforceOnKey: ""` set, returns :

`Message: Update call failed: error applying desired state: summary: Error updating SecurityPolicy "billhop-dev": googleapi: Error 400: Invalid value for field 'resource.rateLimitOptions.enforceOnKeyConfigs': ''. Only one of enforceOnKey and enforceOnKeyConfigs can be specified., invalid`

### Kubernetes Cluster Version

v1.27

### Config Connector Version

1.111.0

### Config Connector Mode

cluster mode

### Log Output

<img width="1510" alt="Screenshot 2023-11-21 at 15 00 51" src="https://github.com/GoogleCloudPlatform/k8s-config-connector/assets/23500408/73d05dde-6507-4cba-9856-46a784ee4c30">

### Steps to reproduce the issue

1. Install Config connector in cluster mode
2. All the required permission is already there
3. All the prerequisite steps are done by following this doc https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall

then
kubectl apply -f file.yaml -n "your-namespace"

### YAML snippets

```YAML
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSecurityPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: my-project-id
  name: my-test-policy-2
spec:
  resourceID: my-test-policy-1
  rule:
  - action: allow
    description: Default rule, higher priority overrides it
    match:
      config:
        srcIpRanges:
        - '*'
      versionedExpr: SRC_IPS_V1
    priority: 2147483647
  - action: rate_based_ban
    description: Throttle requests if >500 p/1min and ban if >1000 p /2min, IO-15
    match:
      config:
        srcIpRanges:
        - '*'
      versionedExpr: SRC_IPS_V1
    preview: true
    priority: 210000
    rateLimitOptions:
      banDurationSec: 300
      banThreshold:
        count: 1000
        intervalSec: 120
      conformAction: allow
      # enforceOnKey: "" To reproduce the error, leave this line commented out
      enforceOnKeyConfigs:
      - enforceOnKeyType: XFF_IP
      - enforceOnKeyType: HTTP_PATH
      exceedAction: deny(429)
      rateLimitThreshold:
        count: 500
        intervalSec: 60
  type: CLOUD_ARMOR
```
