### ISSUE TITLE
Default value for status.observedGeneration

### ISSUE THREAD

**Issue by fsommar** [GoogleCloudPlatform/k8s-config-connector#1047]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Would it make sense to add a default value of 0 for `status.observedGeneration` on KCC resources? 

[kpt live apply](https://kpt.dev/reference/cli/live/) uses [kstatus](https://github.com/kubernetes-sigs/cli-utils/tree/master/pkg/kstatus) to determine whether a resource is _ready_. If `status.conditions` is set, it'll use those in combination with `status.observedGeneration` if that's also set. KCC resources have both. However, when a resource is first created `status.observedGeneration` won't be set, which can give KPT the impression that the resource is _Current_. This can lead to behavior such as a resource flipping from _Current_ to _InProgress_ to _Failed_, but in actuality it was never in a successful state at all.

I noticed that by using default values in my test CRD, the resource will start immediately in _InProgress_ only to transition to _Current_ or some other state. Thus, it's never erroneously flipping from _Current_ to its actual state. This is because the initial resource will have `status.observedGeneration: 0` which is not equal to the first `metadata.generation`.

Are there any drawbacks to adding the default values?

---

## Reproducing the behavior

Create resources.yaml in an empty directory. Then run `kpt live apply --reconcile-timeout 5s --show-status-events .` and observe the result. Now change resources.yaml to remove the two `default`s, and run the same command again and observe the result.

```yaml
apiVersion: kpt.dev/v1alpha1
kind: ResourceGroup
metadata:
  name: inventory-status-test
  namespace: default
  labels:
    cli-utils.sigs.k8s.io/inventory-id: status-test
---
apiVersion: example.com/v1
kind: StatusResource
metadata:
  name: test
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: statusresources.example.com
spec:
  group: example.com
  names:
    kind: StatusResource
    plural: statusresources
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            status:
              type: object
              default: {}
              properties:
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        type: string
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    type: object
                  type: array
                observedGeneration:
                  type: integer
                  default: 0
          type: object
      served: true
      storage: true
      subresources:
        status: {}
```

### Output with defaults (note the timeout, which is the wanted behavior)
```
statusresource.example.com/test is InProgress: StatusResource generation is 1, but latest observed generation is 0
customresourcedefinition.apiextensions.k8s.io/statusresources.example.com is Current: CRD is established
inventory update started
inventory update finished
apply phase started
customresourcedefinition.apiextensions.k8s.io/statusresources.example.com apply successful
apply phase finished
reconcile phase started
customresourcedefinition.apiextensions.k8s.io/statusresources.example.com reconcile successful
reconcile phase finished
apply phase started
statusresource.example.com/test apply successful
apply phase finished
reconcile phase started
statusresource.example.com/test reconcile pending
statusresource.example.com/test reconcile timeout
reconcile phase finished
inventory update started
inventory update finished
apply result: 2 attempted, 2 successful, 0 skipped, 0 failed
reconcile result: 2 attempted, 1 successful, 0 skipped, 0 failed, 1 timed out
```

### Output without defaults (note that there's no timeout)
```
statusresource.example.com/test is InProgress: StatusResource generation is 1, but latest observed generation is 0
customresourcedefinition.apiextensions.k8s.io/statusresources.example.com is Current: CRD is established
inventory update started
inventory update finished
apply phase started
customresourcedefinition.apiextensions.k8s.io/statusresources.example.com apply successful
apply phase finished
reconcile phase started
customresourcedefinition.apiextensions.k8s.io/statusresources.example.com reconcile pending
customresourcedefinition.apiextensions.k8s.io/statusresources.example.com is Current: CRD is established
customresourcedefinition.apiextensions.k8s.io/statusresources.example.com reconcile successful
reconcile phase finished
apply phase started
statusresource.example.com/test apply successful
apply phase finished
reconcile phase started
statusresource.example.com/test reconcile pending
statusresource.example.com/test is Current: Resource is current
statusresource.example.com/test reconcile successful
reconcile phase finished
inventory update started
inventory update finished
apply result: 2 attempted, 2 successful, 0 skipped, 0 failed
reconcile result: 2 attempted, 2 successful, 0 skipped, 0 failed, 0 timed out
```
