### ISSUE TITLE
Reconciliation of SQLUser fails after label addition

### ISSUE THREAD

**Issue by marcoderama** [GoogleCloudPlatform/k8s-config-connector#105]
This is probably related to https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/67.

If I apply the SQLInstance and SQLUser yaml given below, all is good.  If I then make a trivial change to the SQLUser object, like adding a label, reconciliation fails with the seemingly unrelated error:
> 'Update call failed: the desired mutation for the following field(s) is invalid: [host]'

This is a problem because ultimately I'm trying manage a SQLUser object inside my own operator for a custom object type.  I want to add labels to the SQLUser object.  (And given the obscure error message, it took a while to look beyond the `host` spec.)

```
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: sqlinstance-sample
spec:
  databaseVersion: POSTGRES_9_6
  region: us-central1
  settings:
    tier: db-custom-1-3840
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: sqluser-sample
spec:
  host: '%'
  instanceRef:
    name: sqlinstance-sample
  password:
    value: bob
```
