### ISSUE TITLE
IAMPolicyMember: To allow mapping of member and multiple roles on the project

### ISSUE THREAD

**Issue by govinda-attal** [GoogleCloudPlatform/k8s-config-connector#106]
As the intent of IAMPolicy custom resource is to be full declaration at project level, and IAMPolicyMember is too granular for our use-case. It doesn't allow to specify multiple roles.

[IAM-Policy-Member](https://cloud.google.com/config-connector/docs/reference/resources#project_level_policy_member)

It could be great to have this extended or have additional CR say IAMPolicyMemberMapping where one member could be mapped to multiple resources.

Also, it would nice to have IAMPolicyMember support custom roles. https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/78

**Comment by tsawada** [comment]
It'd be great if IAMPolicyMember supports multiple roles, just like how it is grouped by members on the GCP Web console: https://console.cloud.google.com/iam-admin/iam
Currently, we have to prepare one yaml config per a role per a member. For resources like `project` where a member typically has many roles, we have to deal with lots of boilerplate configs.

suggested: ↓

```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kcc-iam-policy
spec:
  memberFrom:
    serviceAccountRef:
      name: service-account-for-kcc
  roles:
    - role: roles/storage.admin
    - role: roles/compute.admin
    - role: roles/network.admin
    - role: roles/iam.admin
        condition:
          title: some-condition
          expression: some-condition
  resourceRef:
    kind: Project
    external: projects/${PROJECT_ID?}
```

Without `roles` being available, we have to maintain 4 times more amount of text for the same settings.

**Comment by diviner524** [comment]
@tsawada Have you checked IAMPartialPolicy [1]? It lets you specify multiple roles in one Config Connector resource. Are there any feature gaps if you try to use this resource instead of IAMPolicyMember?

[1] https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iampartialpolicy

**Comment by tsawada** [comment]
Hi @diviner524, thanks for your suggestion.
I took a look at IAMPartialPolicy, and I agree that it is an improvement compared to IAMPolicyMember.
However, it is still not desirable for us. Using IAMPartialPolicy, the example I raised on [the above comment](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/106#issuecomment-1342219913) looks like this, which is still a few times more text compared to what I suggested.

```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: kcc-iam-policy
spec:
  bindings:
    - role: roles/storage.admin
      members:
        - memberFrom: null
          serviceAccountRef:
            name: service-account-for-kcc
    - role: roles/storage.admin
      members:
        - memberFrom: null
          serviceAccountRef:
            name: service-account-for-kcc
    - role: roles/compute.admin
      members:
        - memberFrom: null
          serviceAccountRef:
            name: service-account-for-kcc
    - role: roles/network.admin
      members:
        - memberFrom: null
          serviceAccountRef:
            name: service-account-for-kcc
    - role: roles/iam.admin
      condition:
        title: some-condition
        expression: some-condition
      members:
        - memberFrom: null
          serviceAccountRef:
            name: service-account-for-kcc
  resourceRef:
    kind: Project
    external: 'projects/${PROJECT_ID?}'
```

My point is that it'd be useful to have a resource that focuses on a member (which is what the web console is doing), rather than focusing on the role side. It might contradict with how these resources are structured internally though.

**Comment by lazarillo** [comment]
While this is a hassle because the *built* template is huge, I don't feel that this is too challenging or too much boilerplate in the repo if you use helm templating.  Eg, do something like

```yaml
{{- range $role := $.Values.roles }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
...
spec:
  role: roles/{{ $role }}
...
---
{{- end }}
```

Wouldn't something like that solve it for you?

**Comment by lazarillo** [comment]
Something like above also lets you have a different config connector "object" for each role, which is nice at some point so that things can be removed / edited in a more fine-grained fashion.

**Comment by JangGyeongSik** [comment]
Is there anything that has been updated later?

**Comment by JangGyeongSik** [comment]
I think it would be a good idea to solve this problem by writing IAMPartialPolicy as shown below.

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: B_PROJECT_ID
  name: iampartialpolicy-sa
spec:
  resourceRef:
    kind: Project
    external: projects/{A_PROJECT_ID}
  bindings:
    - role: roles/viewer
      members:
        - member: serviceAccount:sa@A_PROJECT_ID.iam.gserviceaccount.com
    - role: roles/iam.serviceAccountUser
      members:
        - member: serviceAccount:sa@A_PROJECT_ID.iam.gserviceaccount.com
    - role: roles/iam.workloadIdentityUser
      members:
        - member: serviceAccount:sa@A_PROJECT_ID.iam.gserviceaccount.com         
    - role: roles/iam.serviceAccountTokenCreator
      members:
        - member: serviceAccount:sa@A_PROJECT_ID.iam.gserviceaccount.com
```

**Comment by JangGyeongSik** [comment]
This is a separate topic, but it would be good to refer to the information below about how SA created in Project A is granted permission to other Projects such as B or C.

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: B_PROJECT_ID or C_PROJECT_ID
  name: iampartialpolicy-sa
spec:
  resourceRef:
    kind: Project
    external: projects/{A_PROJECT_ID}
  bindings:
    - role: roles/viewer
      members:
        - member: serviceAccount:sa@A_PROJECT_ID.iam.gserviceaccount.com
    - role: roles/iam.serviceAccountUser
      members:
        - member: serviceAccount:sa@A_PROJECT_ID.iam.gserviceaccount.com
    - role: roles/iam.workloadIdentityUser
      members:
        - member: serviceAccount:sa@A_PROJECT_ID.iam.gserviceaccount.com         
    - role: roles/iam.serviceAccountTokenCreator
      members:
        - member: serviceAccount:sa@A_PROJECT_ID.iam.gserviceaccount.com
```
