### ISSUE TITLE
Questions about IAMPartial Policy

### ISSUE THREAD

**Issue by JangGyeongSik** [GoogleCloudPlatform/k8s-config-connector#1072]
### **Describe your question** 

Hello!
Can't IAMPartialPolicy take the Custom Role created in Org and use it in the Project?

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: iampartialpolicy-sa-xxx-xxx
spec:
  resourceRef:
    kind: Project
    name: sample-project
  bindings:
     - role: organizations/xxxx/roles/CustomRole.xxx.xxx.xxx
       members:
         #- member: serviceAccount:sa-xxx-xxx@PROJECT_ID.iam.gserviceaccount.com
         - memberFrom:
             serviceAccountRef:
               name: sa-prod-xxx
     - role: organizations/xxxx/roles/CustomRole_xxxx
       members:
         - memberFrom:
             serviceAccountRef:
               name: sa-xxx-xxx
    - role: roles/CustomBigQueryConnectionAdmin   # It operates normally
      members:
        - memberFrom:
            serviceAccountRef:
              name: sa-xxx-xxx
```

The above example is the IAMPartialPolicy YAML.
I am getting the above error when using custom role imported from Org.

Update call failed: error setting policy: error applying changes: summary: Error setting IAM policy for project "projects/PROJET_ID": googleapi: Error 400: Role roles/Custome_Role is not supported for this resource., badRequest

Is it possible that IAMPartialPolicy cannot grant a custom role created in an Organization on a Project?

Or should I create IAMCustomRole with Config Connector and then define it in IAMPartialPolicy yaml?

TIA

**Comment by JangGyeongSik** [comment]
hello.
Thank you for your reply.

```shell
gcloud iam service-accounts add-iam-policy-binding SERVICE_ACCOUNT --member serviceAccount:SERVICE_ACCOUNT --role="organizations/ORG_ID/roles/CUSTOM_ROLE_ID"
```
Through the above command, we confirmed that binding is possible only in IAMPolicy.

In fact, when I defined the Config Connector in IAMPolicy yaml as shown below, it worked normally.

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
   name: project-id-iampolicy
spec:
   bindings:
   -members:
     - serviceAccount:SERVICE_ACCOUNT_ID@PROJECT_ID.iam.gserviceaccount.com
     role: organizations/ORG_ID/roles/CUSTOM_ROLE_ID
```
Thanks for the advice. @diviner524
