### ISSUE TITLE
Support VPC access connectorRef in CloudRun Job

### ISSUE THREAD

**Issue by svwijk** [GoogleCloudPlatform/k8s-config-connector#1077]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

The RunJob (cloudrun jobs) does not support vpcaccess via VPC connector, only via the new (beta) vpc egress method.

Please provide a way to connect a job to a vpc connector, much like is available in RunService (Cluid run service).

### Additional information

None

### Importance

Since we have a policy that requires cloudrun to egress via vpc, this is preventing us from switching to KCC over terraform

**Comment by diviner524** [comment]
@svwijk:
This field was intentionally hidden when the Job resource was introduced, due to some issue with the VPCAccess resource.

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/config/servicemappings/run.yaml#L32

The VPCAccess issue is now resolved, so the servicemappings config can be updated to enable this field. We also need a reference configuration similar to the Run resource below:

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/config/servicemappings/run.yaml#L223

We'll engage with the Cloud Run team internally to see if they can prioritize this change.

In the meantime, if you're interested in contributing, we'd be happy to review your change!

**Comment by svwijk** [comment]
@diviner524 :

From what i understand its ok to add the fields now, so i tried adding it in a simple commit:
https://github.com/svwijk/k8s-config-connector/commit/6c15093238c2fcb8eaa73161d8d381e23411ed0a

When i try to deploy a `RunJob`  using the updated CRD and servicemapping i still get a googleapi error:

input

```yaml
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunJob
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: merge
  creationTimestamp: "2023-12-22T14:14:11Z"
  finalizers:
  - cnrm.cloud.google.com/finalizer
  - cnrm.cloud.google.com/deletion-defender
  generation: 1
  name: job1
  namespace: 
  resourceVersion: "8264231"
  uid: d00dc6e0-06da-4517-8e75-46da3f720641
spec:
  location: europe-west4
  projectRef:
    name: projectnamegoeshere
  template:
    template:
      containers:
      - image: europe-west4-docker.pkg.dev/projectnamegoeshere/images/helloworld:latest
        name: job1
      serviceAccountRef:
        external: crunjob1sa@projectnamegoeshere.iam.gserviceaccount.com
      vpcAccess:
        connectorRef:
          external: projects/infraprojectnamegoeshere/locations/europe-west4/connectors/sbx-access-connector-001
        egress: ALL_TRAFFIC
```


But it looks like the googleapi  is returning a conflicting field:

```yaml
status:
  conditions:
  - lastTransitionTime: "2023-12-22T14:14:12Z"
    message: |-
      Update call failed: error applying desired state: summary: Error updating Job "projects/projectnamegoeshere/locations/europe-west4/jobs/job1": googleapi: Error 400: Violation in UpdateJobRequest.job.template.template.vpc_access.connector: one and only one of connector and network_interfaces must be set.
      Details:
      [
        {
          "@type": "type.googleapis.com/google.rpc.BadRequest",
          "fieldViolations": [
            {
              "description": "one and only one of connector and network_interfaces must be set.",
              "field": "Violation in UpdateJobRequest.job.template.template.vpc_access.connector"
            }
          ]
        }
      ]
    reason: UpdateFailed
    status: "False"
    type: Ready
  observedGeneration: 1

```

Is the actual bug  you mentioned earlier actually fixed, or did i forgot to fix something in my code?

I did not create a PR yet since the provision is still failing.
