### ISSUE TITLE
`GKEHubFeatureMembership` resource doesn't bind global `featureRef` with regional `membershipRef`

### ISSUE THREAD

**Issue by vedantthapa** [GoogleCloudPlatform/k8s-config-connector#1078]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

I have a regional `GKEHubMembership` resource with `northamerica-northeast1` as the value for it's `location` field and a global `GKEHubFeature` resource for service mesh. When I try to provision a `GKEHubFeatureMembership` resource with it's `location` field set to `northamerica-northeast1` that references two previous resources, I get an error saying -

```
Message: Update call failed: error applying desired state: googleapi: Error 404: Resource 'projects/<fleet-project-id>/locations/northamerica-northeast1/features/servicemesh' was not found
```
Alternatively, if I change the `location` field to `global` on `GKEHubFeatureMembership`, it raises the following error -
```
Message: Update call failed: error applying desired state: googleapi: Error 400: InvalidValueError for field membership_specs["projects/<fleet-project-id>/locations/global/memberships/cluster01"].feature_spec: does not match a current membership in this project. Keys should be in the form: projects/<fleet-project-id>/locations/{l}/memberships/{m}
```

The same setup works when using `glcoud` cli -
```
  gcloud container fleet mesh update \
     --management automatic \
     --memberships cluster01 \
     --project <fleet-project-id> \
     --location northamerica-northeast1
```

### Additional Diagnostic Information

Seems like the `location` field in the `GKEHubFeatureMembership` resource gets propagated down to the external references, thereby making them invalid.

### Kubernetes Cluster Version

v1.24.17-gke.2230000

### Config Connector Version

1.112.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

- Enable relevant APIs - `container.googleapis.com`, `mesh.googleapis.com`
- Create a [GKE autopilot cluster with config connector](https://cloud.google.com/config-connector/docs/concepts/installation-types).
- Replace `<fleet-project-id>` and `<cluster-name>` with the relevant details and apply the manifests.

### YAML snippets

```YAML
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeature
metadata:
  name: servicemesh
spec:
  projectRef:
    external: projects/<fleet-project-id>
  location: global
  resourceID: servicemesh
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  name: cluster01
  annotations:
    cnrm.cloud.google.com/project-id: <fleet-project-id>
spec:
  location: northamerica-northeast1
  endpoint:
    gkeCluster:
      resourceRef:
        name: <cluster-name>
---
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: test
spec:
  location: global
  projectRef:
    external: projects/<fleet-project-id>
  membershipRef:
    external: projects/<fleet-project-id>/location/northamerica-northeast1/memberships/cluster01
  featureRef:
    external: projects/<fleet-project-id>/locations/global/features/servicemesh
  mesh:
    management: MANAGEMENT_AUTOMATIC
```
