### ISSUE TITLE
SecretManagerSecret automatic replication no longer working

### ISSUE THREAD

**Issue by sthomson-wyn** [GoogleCloudPlatform/k8s-config-connector#1081]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

A SecretManagerSecret resource with `.spec.replication.auto = {}` yields

`Update call failed: cannot make changes to immutable field(s): [Field Name: replication.0.auto.#, Got: 0, Wanted: 1];`

### Additional Diagnostic Information

Unclear if this happens on a brand new resource, but this is happening for an existing resource

### Kubernetes Cluster Version

v1.27.4-gke.900

### Config Connector Version

1.112.0

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

Create yaml below, for an existing secret in GSM

### YAML snippets

```YAML
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: my-secret
  labels:
    dev-access : "false"
spec:
  resourceID: my_secret
  replication:
    automatic: true
```
