### ISSUE TITLE
IAMPolicyMember for Cloud Functions showing DCL error

### ISSUE THREAD

**Issue by tommycouri-bestbuy** [GoogleCloudPlatform/k8s-config-connector#1082]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

I'm testing out the IAMPolicyMember for Cloud Functions Invoker and seeing a DCL error when applying

### Additional Diagnostic Information

Update call failed: error getting referenced DCL resource, with reference project_name/: error retrieving resource 'project_name/' with GroupVersionKind 'cloudfunctions.cnrm.cloud.google.com/v1beta1, Kind=CloudFunctionsFunction': resource name may not be empty

### Kubernetes Cluster Version

v1.28.3

### Config Connector Version

1.111.0

### Config Connector Mode

namespaced mode (default)

### Log Output

Update call failed: error getting referenced DCL resource, with reference project_name/: error retrieving resource 'project_name/' with GroupVersionKind 'cloudfunctions.cnrm.cloud.google.com/v1beta1, Kind=CloudFunctionsFunction': resource name may not be empty

### Steps to reproduce the issue

Applying the yaml file below using kubectl 

### YAML snippets

```YAML
`apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name:  cf-test-invoker
spec:
  member: group:GROUP_NAME
  role: roles/cloudfunctions.invoker
  resourceRef:
    apiVersion: cloudfunctions.cnrm.cloud.google.com/v1beta1
    kind: CloudFunctionsFunction
    external: projects/project_name/locations/us-central1/functions/test-invoker`
```
