### ISSUE TITLE
ContainerCluster releaseChannel appears not to work

### ISSUE THREAD

**Issue by Jonpez2** [GoogleCloudPlatform/k8s-config-connector#109]
I'm using a ContainerCluster resource to create a GKE cluster in my project.  I tried to set it up to receive updates via the REGULAR release channel like so: 

apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
  name: cluster-xxx
spec:
  location: us-central1
  initialNodeCount: 1
  loggingService: logging.googleapis.com/kubernetes
  monitoringService: monitoring.googleapis.com/kubernetes
  releaseChannel:
    channel: "REGULAR"

But I got the following error:

  Warning  UpdateFailed  2s (x4 over 4s)    containercluster-controller  Update call failed: error applying desired state: node_version and min_master_version must be set to equivalent values on create

**Comment by tonybenchsci** [comment]
Actually a bigger problem we have faced was that if you don't get rid of the default nodePool, it has autoUpgrade set to "true", which when upgraded will get into an infinite loop fight against KCC's spec pinning and downgrading of the GKE version.

**Comment by Scorpiion** [comment]
I've been using releaseChannel and it works for me.

**Comment by Jonpez2** [comment]
here's a repo with my yamls https://github.com/Jonpez2/k8s-configconnector-problems

if you change <my-project> to your GCP project, then you should be able to uncomment the 'releasechannel' chunk in cluster.yaml, and that should repro the problem.

**Comment by Jonpez2** [comment]
Hi, anything more I can do to help repro/debug the problem?

Thanks!

**Comment by Jonpez2** [comment]
@Scorpiion - what do you do exactly to get releaseChannel working please?  Is it more than the little snippet I have in my repo?

Thanks!

**Comment by kibbles-n-bytes** [comment]
Hey @Jonpez2 , thanks for the repo with the YAML to reproduce. We're looking into your issue now and will update when we have more information.

**Comment by Jonpez2** [comment]
Excellent, thank you!

**Comment by Scorpiion** [comment]
Hi @Jonpez2, I done a test with releaseChannel and this works for me:

```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  namespace: xxxxxxxxxxxxxxxxxxxxxxxxxxx
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "false"
    cnrm.cloud.google.com/project-id: xxxxxxxxxxxxxxxxxxxxxxxxxxx
  name: stable-channel-test-cluster
spec:
  releaseChannel:
    channel: STABLE
  addonsConfig:
    httpLoadBalancing:
      disabled: false
    istioConfig:
      disabled: false
    networkPolicyConfig:
      disabled: false
  networkPolicy:
    enabled: true
  clusterAutoscaling:
    enabled: false
  initialNodeCount: 3 
  location: europe-north1-b
  loggingService: logging.googleapis.com/kubernetes
  masterAuth:
    clientCertificateConfig:
      issueClientCertificate: false
  monitoringService: monitoring.googleapis.com/kubernetes
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS
    machineType: n1-standard-2
    metadata:
      disable-legacy-endpoints: "true"
    oauthScopes:
      - https://www.googleapis.com/auth/servicecontrol
      - https://www.googleapis.com/auth/trace.append
      - https://www.googleapis.com/auth/devstorage.read_only
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
      - https://www.googleapis.com/auth/service.management.readonly
    serviceAccountRef:
      external: default
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
  enableIntranodeVisibility: true
```

Status from kubectl get ... of the cluster:
```
status:
  conditions:
  - lastTransitionTime: "2020-03-20T13:18:00Z"
    message: The resource is up to date
    reason: UpToDate
    status: "True"
    type: Ready
  endpoint: 35.228.87.118
  instanceGroupUrls:
  - https://www.googleapis.com/compute/beta/projects/xxxxxxxxxxxxxxx/zones/europe-north1-b/instanceGroups/gke-stable-channel-test--default-pool-xxxxxxxxxxxxxxxxxxxx
  masterVersion: 1.14.10-gke.24
  servicesIpv4Cidr: 10.63.240.0/20
```

**Comment by Jonpez2** [comment]
OK let me retry.  Hopefully it's pebkac!

**Comment by Jonpez2** [comment]
Oh wait this is on the default node pool for the cluster.  What do I do if
I need to define my own node pool (as I do in the repo?)

**Comment by Scorpiion** [comment]
That won't work until issue #110 is fixed. Maybe your problem was only #110 and we can close this issue?

**Comment by Jonpez2** [comment]
Hmm. Does that explain the output I got?

**Comment by xiaobaitusi** [comment]
Hi @Jonpez2 , is this still an issue for you? I tried the following yamls, it works for me. I'm using ConfigConnector version 1.5.1.
```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
  name: cluster-release-channel
spec:
  location: us-central1
  initialNodeCount: 1
  loggingService: logging.googleapis.com/kubernetes
  monitoringService: monitoring.googleapis.com/kubernetes
  # With the current version of configconnector, releaseChannel doesn't work:
  # https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/109
  releaseChannel:
    channel: "REGULAR"
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: main-nodepool-1
  labels:
    builduser: xxx
spec:
  location: us-central1
  initialNodeCount: 1
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 3
  nodeConfig:
    preemptible: false
    serviceAccountRef:
      name: svc-acct-109
    oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
    metadata:
      disable-legacy-endpoints: "true"
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: cluster-release-channel
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: svc-acct-109
  labels:
    builduser: xxx
spec:
  displayName: The service account used to run our services

```
