### ISSUE TITLE
Label values cannot contain characters such as "."

### ISSUE THREAD

**Issue by jastang** [GoogleCloudPlatform/k8s-config-connector#112]
**Issue**
According to the k8s documentation on label [syntax](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set), the `.` character should be allowed in label values. However, this is not supported for KCC resource definitions.

**Environment**
`kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-14T04:25:00Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.10-gke.17", GitCommit:"bdceba0734835c6cb1acbd1c447caf17d8613b44", GitTreeState:"clean", BuildDate:"2020-01-17T23:10:13Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

KCC Version: 1.4.0

**Steps to Reproduce**
N.B. This was observed for `kind:BigQueryTable`, but I did not test other resource types. Apply the following YAML (assumes the dataset exists)
```
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: manifest
  labels:
    source: ftp.ncbi.nlm.nih.gov
spec:
  datasetRef:
    name: pubmed
```

**Observed Behaviour**
```
status:
  conditions:
  - lastTransitionTime: "2020-03-08T15:40:57Z"
    message: 'Update call failed: error applying desired state: googleapi: Error 400:
      Label value "ftp.ncbi.nlm.nih.gov" has invalid characters., invalid'
    reason: UpdateFailed
    status: "False"
    type: Ready
```

**Expected Behaviour**
The Object Detail YAML in the GKE Object Browser should contain no errors.
