### ISSUE TITLE
replication.auto unknown field - means that ew cannot create SecretManagerSecret with auto replication and customer managed encryption key

### ISSUE THREAD

**Issue by WTPascoe** [GoogleCloudPlatform/k8s-config-connector#1124]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Attempting to apply a SecretManagerSecret yaml definition with replication.auto.customerManagedEncryption fails with the following error:

> Error from server (BadRequest): error when creating "secret.yaml": SecretManagerSecret in version "v1beta1" cannot be handled as a SecretManagerSecret: strict decoding error: unknown field "spec.replication.auto"

The [SecretManagerSecret](https://cloud.google.com/config-connector/docs/reference/resource-docs/secretmanager/secretmanagersecret) docs imply that this is the correct setting. 

![Screenshot 2024-01-15 at 13 56 27](https://github.com/GoogleCloudPlatform/k8s-config-connector/assets/58910271/f6e925cb-d645-40a2-a792-eb18eaf64449)

### Additional Diagnostic Information

This looks similar to https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/1081 but the conversation there implies that this is likely related to the terraform component. I believe that my issue is different because the resource cannot be created in EKS at all.

Creating SecretManagerSecret with replication set to `userManaged` allows us to set CMEK values as expected.

I've replicated this on an existing cluster and a new cluster created on Friday 12 January.

### Kubernetes Cluster Version

Server Version: v1.28.4-gke.1083000 

### Config Connector Version

1.102.0

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

1. Create KMS keyring - choose 'Multi-region' and select 'global' as the multi-region value
2. Create a software key in the keyring
3. attempt to create a secretmanagersecret resource using the yaml snippet

### YAML snippets

```YAML
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: my-secret
  namespace: backend
  annotations:
    cnrm.cloud.google.com/project-id: my_gcp_project_id
spec:
  replication:
    auto:
      customerManagedEncryption:
      kmsKeyRef:
        external: projects/my_gcp_project_id/locations/global/keyRings/my_keyring/cryptoKeys/my_key
```
