### ISSUE TITLE
Enable attaching policy tags to BigQuery table columns without relying on service-generated resource IDs

### ISSUE THREAD

**Issue by karolinajoksaite** [GoogleCloudPlatform/k8s-config-connector#1278]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Context
We are creating and managing BigQuery tables, taxonomies, and policy tags via Config Connector. We're trying to assign policy tags on BigQuery table columns programmatically via schema annotations by utilising the [schema field](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/46a80be9785870f3b38a5485d8db656920867658/crds/bigquery_v1beta1_bigquerytable.yaml#L57):
```yaml
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
spec:
  schema: |
    [
     ...
     {
       "name": "ssn",
       "type": "STRING",
       "mode": "REQUIRED",
       "policyTags": {
         "names": ["projects/project-id/locations/location/taxonomies/taxonomy-id/policyTags/policytag-id"]
       }
     },
     ...
    ]
  |
```
Above example taken from here: https://cloud.google.com/bigquery/docs/column-level-security-intro#example_use_case

### Problem
To do this we are required to add the full policy tag path which includes the taxonomy and policy tag resource IDs. However, these resource IDs are not known until the resources are created as they are service-generated. This means we can't add them to our schema annotations programmatically.

### What we have tried
- We have tried to use the `resourceID` field in the DataCatalogPolicyTag & DataCatalogTaxonomy resources to **acquire** the resource IDs of the resources, but the fields don't exist when the resources are defined so they can't be accessed:
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/46a80be9785870f3b38a5485d8db656920867658/crds/datacatalog_v1beta1_datacatalogpolicytag.yaml#L114-L117
https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/46a80be9785870f3b38a5485d8db656920867658/crds/datacatalog_v1beta1_datacatalogtaxonomy.yaml#L124-L127
- We looked at alternative ways of specifying taxonomies and policy tags, but there aren't any that we've encountered that wouldn't require the service-generated IDs to be passed in.

### Request

We would like to propose a way to assign policy tags to BigQuery columns in Config Connector in a manner that doesn't require referencing service-generated resource IDs.

Perhaps using a `resourceRef` may help, as addressed in another issue: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/349

### Importance

This is a big blocker for us as we are unable to proceed with creating and managing BigQuery tables, taxonomies, and policy tags via Config Connector as we are unable to programmatically attach policy tags to table columns due to the reliance on service-generated IDs.

Urgency wise we would like to get issue resolved within the next few months.
