### ISSUE TITLE
cannot use `external` in resourceRef for IAMPolicyMember

### ISSUE THREAD

**Issue by jsun6383** [GoogleCloudPlatform/k8s-config-connector#140]
**Describe the bug**
Using `external` for resourceRef in IAMPolicyMember fails schema validation without `kind` attribute. e.g.

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicy-workload-identity-test-sa
  namespace: test
spec:
  resourceRef:
    external: test-sa@myprojectid.iam.gserviceaccount.com
  role: roles/iam.workloadIdentityUser
  member: serviceAccount:myprojectid.svc.id.goog[test/test-sa]
```

fail with the error:

```
KNV2010: unable to create resource: KNV2010: failed to create "iam.cnrm.cloud.google.com/v1beta1, Kind=IAMPolicyMember", ... "role":"roles/iam.workloadIdentityUser"}}: validation failure list:
spec.resourceRef.kind in body is required
```

**ConfigConnector Version**

Doesn't seem to specify a version (maybe due to been installed via Anthos?)

```json
kubectl get ns cnrm-system  -o json | jq
{
  "apiVersion": "v1",
  "kind": "Namespace",
  "metadata": {
    "annotations": {
      "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"labels\":{\"cnrm.cloud.google.com/system\":\"true\"},\"name\":\"cnrm-system\",\"namespace\":\"\"}}\n"
    },
    "creationTimestamp": "2020-04-14T02:59:42Z",
    "labels": {
      "cnrm.cloud.google.com/system": "true"
    },
    "name": "cnrm-system",
    "resourceVersion": "7490",
    "selfLink": "/api/v1/namespaces/cnrm-system",
    "uid": "b72b39d7-2d3a-42e7-a97f-1a5cf42c057a"
  },
  "spec": {
    "finalizers": [
      "kubernetes"
    ]
  },
  "status": {
    "phase": "Active"
  }
}
```

**To Reproduce**
*Steps to reproduce the behavior:*

create a service account without config connector with the name:

```test-sa@myprojectid.iam.gserviceaccount.com```

replace myprojectid accordingly.

ran yaml

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicy-workload-identity-test-sa
  namespace: test
spec:
  resourceRef:
    external: test-sa@myprojectid.iam.gserviceaccount.com
  role: roles/iam.workloadIdentityUser
  member: serviceAccount:myprojectid.svc.id.goog[test/test-sa]
```

**Comment by jcanseco** [comment]
Hi @jsun6383, specifying `kind` is still required for `IAMPolicy` and `IAMPolicyMember` even if you're using `external`. The `kind` is needed by Config Connector to be able to determine what kind of resource the external reference is referencing.

We plan to improve the documentation around external references in the coming weeks to alleviate some of the confusion around the feature.

Closing this issue now, though please let us know if you have any other questions or concerns.

**Comment by jsun6383** [comment]
hi @jcanseco,

I've tried specifying `kind`. 

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicy-workload-identity-test-sa
  namespace: test
spec:
  resourceRef:
    kind: IAMServiceAccount
    external: test-sa@myprojectid.iam.gserviceaccount.com
  role: roles/iam.workloadIdentityUser
  member: serviceAccount:myprojectid.svc.id.goog[test/test-sa]
```

I get the following error:
```
error getting policy member: error getting resource config for referenced resource: failed to load ServiceMapping for GroupVersionKind /, Kind=IAMServiceAccount: unable to find service mapping with name ''
```

I also tried with `kind` and `apiVersion`:

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicy-workload-identity-test-sa
  namespace: test
spec:
  resourceRef:
    kind: IAMServiceAccount
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    external: test-sa@myprojectid.iam.gserviceaccount.com
  role: roles/iam.workloadIdentityUser
  member: serviceAccount:myprojectid.svc.id.goog[test/test-sa]
```
i get the following error:
```
error getting policy member: error getting resource config for referenced resource: no ResourceConfig found for kind IAMServiceAccount with an IDTemplate that matches the id kubernetes-sa@non-coreservicesdev-9514.iam.gserviceaccount.com
```

It seems i cannot use a service account that is not created by config connector in IAMPolicyMember.

Can you please confirm?

**Comment by jcanseco** [comment]
Hi @jsun6383

Ah, I see the problem. The format of `external` when referencing an `IAMServiceAccount` from an `IAMPolicy` or `IAMPolicyMember` is `projects/{project}/serviceAccounts/{account_id}@{project}.iam.gserviceaccount.com`.

Can you try the following?

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicy-workload-identity-test-sa
  namespace: test
spec:
  resourceRef:
    kind: IAMServiceAccount
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    external: projects/myprojectid/serviceAccounts/test-sa@myprojectid.iam.gserviceaccount.com
  role: roles/iam.workloadIdentityUser
  member: serviceAccount:myprojectid.svc.id.goog[test/test-sa]
```
