### ISSUE TITLE
Cannot upgrade (manual or release channel) ContainerCluster or ContainerNodePool versions

### ISSUE THREAD

**Issue by tonybenchsci** [GoogleCloudPlatform/k8s-config-connector#142]
**Describe the bug**
We create GKE clusters using KCC without specifying the `ContainerNodePool:spec/version` nor `ContainerCluster:spec/nodeVersion`. After "The resource is up to date", the spec has acquired the current versions/nodeVersion of the master/node(s) created. If we have a Release Channel set, then there is an infinitely loop (gke upgrades, kcc downgrades) of version flip-flopping during the scheduled upgrade; our workaround is to always delete the default nodepool with `cnrm.cloud.google.com/remove-default-node-pool` annotation, and then create ContainerNodePools with `spec/management/autoUpgrade` set to `false`. In addition, if we manually upgrade a nodepool version via the GCP Console, then the version will be downgraded by KCC, causing temporary downtime but no loop as gke gives up upgrading. 

**ConfigConnector Version**
We consistently see this on all versions, and have explicitly installed and used:
```bash
1.7.0
1.6.1
1.4.0
1.0.0
```

**To Reproduce**

Run `kubectl apply -f -` on the following YAML, and then manually upgrade node/master version in GCP Console UI. 

Alternatively wait for scheduled gke upgrade, after doing any of:
- Set `ContainerNodePool:spec/management/autoUpgrade:`:`true`
- Add`ContainerCluster:spec/releaseChannel/channel`:`STABLE`
- Remove `ContainerCluster:metadata/annotations/cnrm.cloud.google.com/remove-default-node-pool: "true"` 

*YAML snippets:*
```yaml
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
  name: koma
  namespace: <REDACTED>
spec:
  authenticatorGroupsConfig:
    securityGroup: gke-security-groups@<REDACTED>.com
  initialNodeCount: 1
  ipAllocationPolicy:
    clusterIpv4CidrBlock: /14
    servicesIpv4CidrBlock: /20
  location: us-central1-a
  loggingService: logging.googleapis.com/kubernetes
  masterAuthorizedNetworksConfig:
    cidrBlocks:
    - cidrBlock: 104.132.0.0/14
      displayName: google-office
    - cidrBlock: <REDACTED>
      displayName: office
  monitoringService: monitoring.googleapis.com/kubernetes
  workloadIdentityConfig:
    identityNamespace: <REDACTED>.svc.id.goog
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: koma1
  namespace: <REDACTED>
spec:
  autoscaling:
    maxNodeCount: 5
    minNodeCount: 1
  clusterRef:
    name: koma
  initialNodeCount: 1
  location: us-central1-a
  management:
    autoRepair: true
    autoUpgrade: false
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS
    machineType: n1-standard-2
    metadata:
      disable-legacy-endpoints: "true"
    oauthScopes:
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/trace.append
```
