### ISSUE TITLE
Deletion of folder (with deletion-policy: abandon) does not work if not empty

### ISSUE THREAD

**Issue by Scorpiion** [GoogleCloudPlatform/k8s-config-connector#145]
**Describe the bug**
I tried to delete a folder only from KCC but not the underlying folder, it did not work. The folder did have projects inside.

**ConfigConnector Version**
```bash 
1.7.1
```

**To Reproduce**
*Steps to reproduce the behavior:*

*YAML snippets:*
```yaml
# Top level namespace used for folders
apiVersion: v1
kind: Namespace
metadata:
  name: global-resources
  annotations:
    cnrm.cloud.google.com/folder-id: "xxxxxx" # Folder where subfolders are created
    cnrm.cloud.google.com/project-id: xxxxxxxxxxx # Project id of project where the config connector is running

---

apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  namespace: global-resources
  name: xxxxxxxxxxxxxxxxx
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon # Don't delete GCP resource if KCC entry is deleted
spec:
  displayName: xxxxxxxxxxxxxxxxx

```
I got this error message:
```
status:
  conditions:
  - lastTransitionTime: "2020-04-16T11:20:33Z"
    message: 'Delete call failed: error deleting resource: Error deleting folder ''xxxxxxxxxxxx'':
      googleapi: Error 400: Precondition check failed., failedPrecondition'
    reason: DeleteFailed
    status: "False"
    type: Ready
  createTime: "2020-04-15T22:45:07.790Z"
  lifecycleState: ACTIVE
  name: folders/xxxxxxxxxxxx
```

I would have expected that I could delete the folder from KCC only because of the `cnrm.cloud.google.com/deletion-policy: abandon` annotation. The folder does have projects inside it, so if the folder would have actually been deleted it's correct, but in this case I'm just uninstalling YAML files so I can reinstall the KCC cluster.
