### ISSUE TITLE
The value can't handle names with '-'

### ISSUE THREAD

**Issue by zicongmei** [GoogleCloudPlatform/k8s-config-connector#1482]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Example: https://user.git.corp.google.com/zicong/kcc-alice/+/5879f41df59cb4a7d18a11bee835fd0ec7c3c986/composition/01-composition.yaml#80. See [error messages](https://paste.googleplex.com/4828819151650816). The error disappears after I change the name from `oidc-issuer` to `issuer`.

### Additional Diagnostic Information

https://paste.googleplex.com/4828819151650816

### Kubernetes Cluster Version

v1.27.8-gke.1067004

### Config Connector Version

1.113.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

Apply the yaml of https://user.git.corp.google.com/zicong/kcc-alice/+/5879f41df59cb4a7d18a11bee835fd0ec7c3c986/composition/01-composition.yaml

### YAML snippets

```YAML
- type: jinja2
    name: attach
    valuesFrom:
    - name: oidc-issuer
      resourceRef:
        group: ""
        version: v1
        kind: ConfigMap
        name: "{{ attachedakses.metadata.name }}-issuer"
      fieldRef:
      - path: ".data.oidc"
        as: url
```
