### ISSUE TITLE
Support specifying BigQuery schema as YAML

### ISSUE THREAD

**Issue by krismolendyke** [GoogleCloudPlatform/k8s-config-connector#149]
Currently the BigQuery [schema](https://www.terraform.io/docs/providers/google/r/bigquery_table.html#schema) field must be a JSON string.  This makes configuration management, particularly code review, of schema changes difficult.  

My enhancement request is to support specifying `schema` as a YAML document.

Thanks!

**Comment by jcanseco** [comment]
Hi @krismolendyke, thank you for filing this issue. We'll look into it and let you know if we have any updates.

**Comment by tdigangi** [comment]
+1 
Adding a long json string into yaml is messy. 
In addition it would be great if there was a way to pull in even a _schema.json_  file into the schema field requiring a string. If it was possible to pull in from a local path or gsc object this would be very beneficial.

**Example GCS:**
```
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: customerdatatable
spec:
  description: "A table of customer data"
  datasetRef:
    name: customerdatasecret
  friendlyName: customer_data_table
  schema: gs://some-bucket/schema.json
```
**Example local path:**
```
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: customerdatatable
spec:
  description: "A table of customer data"
  datasetRef:
    name: customerdatasecret
  friendlyName: customer_data_table
  schema: ./path/to/schema.json
```
