### ISSUE TITLE
Datastream is not created when avroFileFormat is set in the spec

### ISSUE THREAD

**Issue by w32-blaster** [GoogleCloudPlatform/k8s-config-connector#1507]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

When creating a new `datastreamstream` (v1alpha1 version) and specifying the `avroFileFormat` a google API 400 error is returned (BadRequest)

### Additional Diagnostic Information

The following error message is returned:
```
  Warning  UpdateFailed  30s (x5 over 61s)  datastreamstream-controller  Update call failed: error applying desired state: summary: Error updating Stream "projects/xxxxx/locations/us-central1/streams/xxxx": googleapi: Error 400: Request contains an invalid argument.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "File format is not specified",
        "field": "destination_config.gcs_destination_config.file_format"
      }
    ]
  }
]
```

### Kubernetes Cluster Version

1.28

### Config Connector Version

1.114.0

### Config Connector Mode

namespaced mode (default)

### Log Output

```
{
insertId: "v6j751kyvcx2huyw"
jsonPayload: {
error: "summary: Error updating Stream "projects/xxxxxx/locations/us-central1/streams/xxxxx": googleapi: Error 400: Request contains an invalid argument.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "File format is not specified",
        "field": "destination_config.gcs_destination_config.file_format"
      }
    ]
  }
]"
logger: "datastreamstream-controller"
msg: "error applying desired state"
resource: {
name: "xxxx"
namespace: "xx"
}
timestamp: "2024-04-04T10:40:33.552Z"
}
labels: {
compute.googleapis.com/resource_name: "xxxxxx"
k8s-pod/apps_kubernetes_io/pod-index: "0"
k8s-pod/cnrm_cloud_google_com/component: "cnrm-controller-manager"
k8s-pod/cnrm_cloud_google_com/system: "true"
k8s-pod/controller-revision-hash: "cnrm-controller-manager-9b84fb4bb"
k8s-pod/statefulset_kubernetes_io/pod-name: "cnrm-controller-manager-0"
}
logName: "projects/xxxxx/logs/stdout"
receiveTimestamp: "2024-04-04T10:40:36.080893860Z"
resource: {
labels: {
cluster_name: "xxxxxx"
container_name: "manager"
location: "us-central1"
namespace_name: "cnrm-system"
pod_name: "cnrm-controller-manager-0"
project_id: "xxxxxx"
}
type: "k8s_container"
}
severity: "ERROR"
timestamp: "2024-04-04T10:40:33.552409267Z"
}
```

### Steps to reproduce the issue

1. Include the CRD DatastreamStream from config-connector
2. Apply the resource from the yaml snippet below
3. Describe the new resource or check the google logs for cnrm-controller

### YAML snippets

```YAML
apiVersion: datastream.cnrm.cloud.google.com/v1alpha1
kind: DatastreamStream
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
  name: datapipeline-stream-manual
  namespace: xx
spec:
  backfillAll: {}
  desiredState: RUNNING
  destinationConfig:
    destinationConnectionProfile: projects/xxxxx/locations/us-central1/connectionProfiles/bucket-connection
    gcsDestinationConfig:
      avroFileFormat:
      fileRotationInterval: 15s
      fileRotationMb: 5
  displayName: datapipeline-stream
  location: us-central1
  projectRef:
    external: xxxx
  resourceID: datapipeline-stream
  sourceConfig:
    mysqlSourceConfig:
      maxConcurrentBackfillTasks: 0
    sourceConnectionProfile: projects/xxxx/locations/us-central1/connectionProfiles/datapipeline-mysql
```
