### ISSUE TITLE
cnrm-webhook-manager/SQLInstance issues with v1.7.1

### ISSUE THREAD

**Issue by marcoderama** [GoogleCloudPlatform/k8s-config-connector#151]
I do local dev work with Config Connector on kind and have had no issues related to my setup until upgrading to Config Connector 1.7.1 from 1.6.0.  When I change _only_ the version of Config Connector in the setup...

   * The `cnrm-webhook-manager` won't startup
   * I can no longer create a particular SQLInstance

It looks like it may have something to do with application default credentials, but I cannot figure out what to change.  I can't see anything related in the release notes.  My guess is that I'm missing something pretty simple...  Any help would be appreciated.

In particular...

The `cnrm-webhook-manager` is in CrashLoopBackoff with the logs containing only:
> 2020/04/22 17:06:31 [INFO] Authenticating using DefaultClient...
2020/04/22 17:06:31 [INFO]   -- Scopes: [https://www.googleapis.com/auth/compute https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/ndev.clouddns.readwrite https://www.googleapis.com/auth/devstorage.full_control https://www.googleapis.com/auth/userinfo.email]
2020/04/22 17:06:31 error creating namespace annotation defaulter handler: error creating tf provider: error configuring provider: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.error adding the validating webhooks

The relevant bits of my SQLInstance (including spec and message after trying to apply) are shown here.  (And yes, the namespace `thenamespace` has the requisite `cnrm.cloud.google.com/project-id` annotation.)
```
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: resource
  generation: 2
  name: sqlinstance-sample1002
  namespace: thenamespace
spec:
  databaseVersion: POSTGRES_9_6
  region: us-central1
  settings:
    tier: db-custom-1-3840
status:
  conditions:
  - lastTransitionTime: "2020-04-22T16:45:53Z"
    message: 'Update call failed: error fetching live state: error converting resource
      config: error resolving container value: no annotation found that matches one
      of the required containers'
```
The `cnrm-controller-manager` log contains the same message, including stack trace (available if you want it).

In case it matters, the kind version is
`kind v0.7.0 go1.13.1 linux/amd64`

**Comment by caieo** [comment]
Hi @marcoderama, 

Thanks for the detailed context around your issue. Are you working on Minikube or a GKE Cluster?We've noticed a credentials issue when using KCC on Minikube, where the application default credentials that are usually available on GKE clusters are not available with Minikube. Our workaround is to have you manually mount a volume with application credentials to your cnrm-webhook-manager deployment pod. Edit your `cnrm-webhook-manager` deployment pod and add this to the pod template object:
```
volumes:
- name: gcp-service-account
  secret:
    secretName: gcp-key
```
Then add this to the webhook container object:
```
env:
- name: GOOGLE_APPLICATION_CREDENTIALS
  value: /var/secrets/google/key.json
volumeMounts:
- mountPath: /var/secrets/google
   name: gcp-service-account
```
Let me know if these steps need clarification. This is a temporary fix that we'll add to our release bundles. 

As for your SQLInstance issue, we ask that users wait until the webhook is ready before trying to create CRDs. We'll revisit the installation order between the webhooks and CRDs to hopefully avoid this issue. Please try the workaround and then reapply the SQLInstance after the webhooks are created successfully.
