### ISSUE TITLE
BigQueryTable support for Policy Tags 

### ISSUE THREAD

**Issue by tdigangi** [GoogleCloudPlatform/k8s-config-connector#152]
Currently, if you deploy a BQ table with a policyTags in the schema. The apply runs successful however the output schema does not contain the policyTag. This means that we cannot apply the tag that would enable [column level security](https://cloud.google.com/bigquery/docs/column-level-security#command-line)

**KCC deployment**
```
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: customerdatatable
spec:
  description: "A table of customer data"
  datasetRef:
    name: customerdatasecret
  friendlyName: customer_data_table
  schema: '[{"description":"The name of the customer","mode":"REQUIRED","name":"name","type":"STRING"},{"description":"Social Security Number","mode":"REQUIRED","name":"ssn","type":"STRING","policyTags":{"names":["projects/[project-id]/locations/us/taxonomies/[some_number]/policyTags/[some_number]"]}},{"description":"Number of purchases","mode":"NULLABLE","name":"purchases","type":"INTEGER"}]'
```

**Policy Tag Schema closeup**
```
[
  {
    "description": "Social Security Number",
    "mode": "REQUIRED",
    "name": "ssn",
    "type": "STRING",
    "policyTags": {
      "names":
      ["projects/[project-id]/locations/us/taxonomies/[some_number]/policyTags/[some_number]"]
    }
  }
]
```
**Deployed Schema**
`bq show --format=prettyjson --schema --dataset_id customerdatasecret customerdatatable`

**Output Table**
```
[
  {
    "description": "The name of the customer",
    "mode": "REQUIRED",
    "name": "name",
    "type": "STRING"
  },
  {
    "description": "Social Security Number",
    "mode": "REQUIRED",
    "name": "ssn",
    "type": "STRING"
  },
  {
    "description": "Number of purchases",
    "mode": "NULLABLE",
    "name": "purchases",
    "type": "INTEGER"
  }
]
```
