### ISSUE TITLE
ContainerNodePool doesn't work without `spec.location` set 

### ISSUE THREAD

**Issue by errordeveloper** [GoogleCloudPlatform/k8s-config-connector#160]
**Describe the bug**

`spec.location` is optional in `ContainerNodePool`, and it would appear natural if location was inherited from `spec.clusterRef`, however without `spec.location` set a weird error message occurs.

```YAML
- apiVersion: container.cnrm.cloud.google.com/v1beta1
  kind: ContainerNodePool
  metadata:
    labels:
      cluster: ilya-test-cluster-3
    name: ilya-test-cluster-3-bug
    namespace: test-clusters
 spec:
    clusterRef:
      name: ilya-test-cluster-3
    initialNodeCount: 0
    management:
      autoRepair: false
      autoUpgrade: false
    nodeConfig:
      diskSizeGb: 100
      diskType: pd-standard
      metadata:
        disable-legacy-endpoints: "true"
      oauthScopes:
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
  status:
    conditions:
    - lastTransitionTime: "2020-04-28T20:51:57Z"
      message: 'Update call failed: error fetching live state: error importing resource:
        Import id "cilium-ci//ilya-test-cluster-3/ilya-test-cluster-3-bug" doesn''t
        match any of the accepted formats: [projects/(?P<project>[^/]+)/locations/(?P<location>[^/]+)/clusters/(?P<cluster>[^/]+)/nodePools/(?P<name>[^/]+)
        (?P<project>[^/]+)/(?P<location>[^/]+)/(?P<cluster>[^/]+)/(?P<name>[^/]+)
        (?P<location>[^/]+)/(?P<cluster>[^/]+)/(?P<name>[^/]+)]'
      reason: UpdateFailed
      status: "False"
      type: Ready
```
Re-creating with `spec.location` set makes this go away.

**ConfigConnector Version**

1.7.2
