### ISSUE TITLE
ContainerNodePool resource doesn't have accurate NodeCount set when Autoscaling

### ISSUE THREAD

**Issue by nitishkrishna** [GoogleCloudPlatform/k8s-config-connector#163]
My cluster has a NodePool created with ConfigConnector with Autoscaling Limits set min=1 max=3.

I had scaled this up using a test deployment and noticed that NodeCount on the Resource was set at 2 when there were actually 3 nodes in each zone.

![Screen Shot 2020-05-04 at 11 42 45 AM](https://user-images.githubusercontent.com/6496935/81002210-b8822280-8dfd-11ea-93bb-5fbb7eadfc83.png)

When I turned off autoscaling on this resource, it actually deleted nodes.

Is there a known time lag where the ConfigConnector Controller takes time to update NodeCount on the resource? When creating a new NodePool it waits till all Nodes are Ready to set this field but that didn't happen in this (autoscaling) case.

**ConfigConnector Version**
1.7.0

**To Reproduce**

- Create new ContainerNodePool with autoscaling min=1, max=3
- Autoscale NodePool up to 3 nodes with fake workload
- `kubectl describe containernodepool <name>` -> will not show accurate nodeCount under spec.
- Turn off autoscaling -> this will actually delete nodes

*YAML snippets:*
```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: xxx
  generateName: sample-nodepool-
  labels:
    nodepool: sample-nodepool
  name: sample-nodepool-szqv4
  namespace: default
spec:
  clusterRef:
    external: xyz
  initialNodeCount: 1
  location: us-west1
  management: {}
  maxPodsPerNode: 110
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS
    machineType: n1-standard-1
    metadata:
      additionalProperties: ""
      disable-legacy-endpoints: "true"
    minCpuPlatform: Intel Skylake
    oauthScopes:
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    serviceAccountRef:
      external: default
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
  nodeCount: 2
  upgradeSettings:
    maxSurge: 1
    maxUnavailable: 0
  version: 1.15.11-gke.9
```
