### ISSUE TITLE
SQLInstance reconciles/updates every 20 mins even if there is no actual update

### ISSUE THREAD

**Issue by maqiuyujoyce** [GoogleCloudPlatform/k8s-config-connector#164]
**Describe the bug**
The MySQL instance created using Config Connector is automatically updated every 20 mins.

**ConfigConnector Version**
1.7.0

**To Reproduce**
*Steps to reproduce the behavior:*
Simply apply the YAML and after the SQLInstance is UpToDate, check the resource status every 20 mins. You'll find that the the `lastTransitionTime` in the status is changed.

*YAML snippets:*

```yaml
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: basic-instance
spec:
  databaseVersion: MYSQL_5_6
  region: us-central1
  settings:
    tier: db-n1-standard-1
```
