### ISSUE TITLE
how to ref the IP of cloudsql once its done in deployment

### ISSUE THREAD

**Issue by thecloudgeek** [GoogleCloudPlatform/k8s-config-connector#166]
Hello,

We're trying to create a deployment that also uses CNRM to provision a cloudsql instance in the same spec file. But what we can't seem to figure out is how can one reference the IP of the cloudsql instance once it comes up in the deployment ref.

So if we had a structure like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-nomad
  namespace: demo
spec:
  ...
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: OVERLAY
  name: grafana-db-03
  namespace: monitoring
spec:
  databaseVersion: POSTGRES_11
  region: OVERLAY
  settings:
    availabilityType: REGIONAL
    backupConfiguration:
      enabled: true
    ipConfiguration:
      ...
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: OVERLAY
  name: grafana
  namespace: monitoring
spec:
  instanceRef:
    name: grafana-db-03
  host: "%"
  password:
    valueFrom:
      secretKeyRef:
        name: grafana-db-creds
        key: GF_DATABASE_PASSWORD
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: grafana
  namespace: monitoring
spec:
  charset: UTF8
  collation: en_US.UTF8
  instanceRef:
    name: grafana-db-03
```

Once k8s creates the cloudsql instance, how can I reference its IP in the `kind: Deployment` for example...
