### ISSUE TITLE
ComputeSharedVPCServiceProject can't be detached from the host project after the referenced GCP project is deleted

### ISSUE THREAD

**Issue by maqiuyujoyce** [GoogleCloudPlatform/k8s-config-connector#167]
**Describe the bug**
Deleting the ComputeSharedVPCServiceProject resource after the referenced GCP project is deleted doesn't actually detach this referenced GCP project from the shared vpc host project.

**ConfigConnector Version**
1.7.0

**To Reproduce**
1. Run `kubectl apply -f .` to create all the resources specified in the YAML snippets section.
2. Verify via gcloud or Cloud Console that `shared-vpc-service-proj` is a shared vpc service project attached to `shared-vpc-host-proj`. (The project names match the YAML snippets but need to be changed in the actual reproduction.)
3.  `kubectl delete project shared-vpc-service-proj --wait`
4.  `kubectl delete computesharedvpcserviceproject serviceproject -n shared-vpc-host`
5. Verify via gcloud or Cloud Console that `shared-vpc-service-proj` can still be found as a shared vpc service project attached to `shared-vpc-host-proj`.

But if we follow the same steps using gcloud or the REST API, `shared-vpc-host-proj` will no longer have any service project.

*YAML snippets:*

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: shared-vpc-host-proj
  name: shared-vpc-host
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: shared-vpc-service-proj
  name: shared-vpc-service
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/organization-id: [ORG]
  name: shared-vpc-host-proj
spec:
  name: shared-vpc-host-proj
  billingAccountRef:
    external: [BILLING ACCOUNT]
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/organization-id: [ORG]
  name: shared-vpc-service-proj
spec:
  name: shared-vpc-service-proj
  billingAccountRef:
    external: [BILLING ACCOUNT]
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  namespace: shared-vpc-host
  name: compute.googleapis.com
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  namespace: shared-vpc-service
  name: compute.googleapis.com
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSharedVPCHostProject
metadata:
  namespace: shared-vpc-host
  name: hostproject
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSharedVPCServiceProject
metadata:
  namespace: shared-vpc-host
  name: serviceproject
spec:
  projectRef:
    namespace: [DEFAULT NAMESPACE]
    name: shared-vpc-service-proj
```
