### ISSUE TITLE
firestoreindex error message

### ISSUE THREAD

**Issue by trodge** [GoogleCloudPlatform/k8s-config-connector#170]
**Describe the bug**

The FireStoreIndex sample fails to update with the following error message:
```

Name:         firestoreindex-sample
Namespace:    tjr-test-155
Labels:       <none>
Annotations:  cnrm.cloud.google.com/management-conflict-prevention-policy: none
              cnrm.cloud.google.com/project-id: tjr-test-155
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"firestore.cnrm.cloud.google.com/v1beta1","kind":"FirestoreIndex","metadata":{"annotations":{},"name":"firestoreindex-sample...
API Version:  firestore.cnrm.cloud.google.com/v1beta1
Kind:         FirestoreIndex
Metadata:
  Creation Timestamp:  2020-05-08T17:25:29Z
  Finalizers:
    cnrm.cloud.google.com/finalizer
    cnrm.cloud.google.com/deletion-defender
  Generation:        7
  Resource Version:  2419
  Self Link:         /apis/firestore.cnrm.cloud.google.com/v1beta1/namespaces/tjr-test-155/firestoreindexes/firestoreindex-sample
  UID:               6555b7d5-665c-4e4b-aa8f-d8906fa9087a
Spec:
  Collection:  sample-collection
  Fields:
    Field Path:  field1
    Order:       ASCENDING
    Field Path:  field2
    Order:       DESCENDING
  Query Scope:   COLLECTION
Status:
  Conditions:
    Last Transition Time:  2020-05-08T17:25:30Z
    Message:               Update call failed: error applying desired state: Error creating Index: googleapi: Error 404: Project 'tjr-test-155' does not exist.
    Reason:                UpdateFailed
    Status:                False
    Type:                  Ready
Events:
  Type     Reason        Age                From                       Message
  ----     ------        ----               ----                       -------
  Warning  UpdateFailed  18s (x3 over 38s)  firestoreindex-controller  Update call failed: error applying desired state: Error creating Index: googleapi: Error 404: Project 'tjr-test-155' does not exist.
  Normal   Updating      1s (x4 over 44s)   firestoreindex-controller  Update in progress
```

**ConfigConnector Version**
1.7.1

**To Reproduce**
Apply the YAML in samples/resources/firestoreindex

*YAML snippets:*

```yaml
apiVersion: firestore.cnrm.cloud.google.com/v1beta1
kind: FirestoreIndex
metadata:
  name: firestoreindex-sample
spec:
  collection: sample-collection
  fields:
  - fieldPath: field1
    order: ASCENDING
  - fieldPath: field2
    order: DESCENDING
  queryScope: COLLECTION
```
