### ISSUE TITLE
Error creating new SQLInstance

### ISSUE THREAD

**Issue by jjhuff** [GoogleCloudPlatform/k8s-config-connector#171]
**Describe the bug**
SQLInstance not becoming ready. Following is in the events for the object.
  Warning  UpdateFailed  1s (x10 over 5s)  sqlinstance-controller  Update call failed: error fetching live state: error converting resource config: error resolving container value: no annotation found that matches one of the required containers

**ConfigConnector Version**
1.9.0

**To Reproduce**
*Steps to reproduce the behavior:*
See below

*YAML snippets:*
```yaml
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: dataservice-dev
  namespace: dev
spec:
  region: us-central1
  databaseVersion: POSTGRES_11
  settings:
    tier: db-n1-standard-2
    diskAutoresize: true
    ipConfiguration:
      ipv4Enabled: false
      privateNetworkRef:
        external: projects/${GOOGLE_CLOUD_PROJECT}/global/networks/default
    backupConfiguration:
      enabled: true
```
