### ISSUE TITLE
containernodepool: Status doesn't change once fully provisioned, if nodeCount is set

### ISSUE THREAD

**Issue by jonnylangefeld** [GoogleCloudPlatform/k8s-config-connector#178]
**Describe the bug**
When a new container node pool is created, after it finished provisioning, only the events are updated, but not the status:

```
Status:
  Conditions:
    Last Transition Time:  2020-05-13T20:57:56Z
    Message:               Update in progress
    Reason:                Updating
    Status:                False
    Type:                  Ready
Events:
  Type    Reason    Age                From                          Message
  ----    ------    ----               ----                          -------
  Normal  Updating  4m1s               containernodepool-controller  Update in progress
  Normal  UpToDate  6s (x12 over 20s)  containernodepool-controller  The resource is up to date
```

The status says still 'Update in progress' while the events say 'The resource is up to date'.

It set the `UpToDate` events a lot of times, maybe it has to be with that?

**ConfigConnector Version**
Run the following command to get the current ConfigConnector version
```bash 
1.9.0
```

**To Reproduce**
*Steps to reproduce the behavior:*
Create new containernodepool resource and wait until its fully provisioned on GCP.

*YAML snippets:*

```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: cruise-paas-ci-dev-2afe
  name: sample-nodepool-green
  namespace: default
spec:
  nodeCount: 1
  clusterRef:
    external: <cluster>
  location: <location>
  nodeLocations:
    - <node-location>
  maxPodsPerNode: 110
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS
    machineType: n1-standard-1
    metadata:
      additionalProperties: ""
      disable-legacy-endpoints: "true"
    minCpuPlatform: Intel Skylake
    oauthScopes:
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
    serviceAccountRef:
      external: default
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
    taint:
      - effect:  NO_SCHEDULE
        key:     dedicated
        value:   test
    labels:
      dedicated: test
  upgradeSettings:
    maxSurge: 1
    maxUnavailable: 0
  version: 1.15.11-gke.11
```

**Comment by jonnylangefeld** [comment]
After a little more digging, it seems to be caused by setting the `nodeCount`. The example above works if `autoscaling` is used instead:
```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: cruise-paas-ci-dev-2afe
  name: sample-nodepool-green
  namespace: default
spec:
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 3
  clusterRef:
    external: <cluster>
  location: <location>
  nodeLocations:
    - <node-location>
  maxPodsPerNode: 110
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    imageType: COS
    machineType: n1-standard-1
    metadata:
      additionalProperties: ""
      disable-legacy-endpoints: "true"
    minCpuPlatform: Intel Skylake
    oauthScopes:
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
    serviceAccountRef:
      external: default
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
    taint:
      - effect:  NO_SCHEDULE
        key:     dedicated
        value:   test
    labels:
      dedicated: test
  upgradeSettings:
    maxSurge: 1
    maxUnavailable: 0
  version: 1.15.11-gke.11
```

Now it looks like it should:
```
Status:
  Conditions:
    Last Transition Time:  2020-05-13T22:46:53Z
    Message:               The resource is up to date
    Reason:                UpToDate
    Status:                True
    Type:                  Ready
  Instance Group Urls:
    https://www.googleapis.com/compute/v1/projects/cruise-paas-ci-dev-2afe/zones/us-central1-a/instanceGroupManagers/gke-paas-ci-us-centr-sample-nodepool--f0bb197d-grp
Events:
  Type    Reason    Age   From                          Message
  ----    ------    ----  ----                          -------
  Normal  Updating  101s  containernodepool-controller  Update in progress
  Normal  UpToDate  87s   containernodepool-controller  The resource is up to date
```

I'll adjust the title to reflect that this happens when `nodeCount` is set.
