### ISSUE TITLE
PROJECT: cannot make change to container annotation cnrm.cloud.google.com/folder-id

### ISSUE THREAD

**Issue by tdigangi** [GoogleCloudPlatform/k8s-config-connector#181]
**Describe the bug**
When trying to change the folder number in the _cnrm.cloud.google.com/folder-id_ annotation of the already deployed project. I receive the following message.

`Step #1: Error: UPGRADE FAILED: cannot patch "ui-tst-lpi-zn-972" with kind Project: admission webhook "deny-immutable-field-updates.cnrm.cloud.google.com" denied the request: error validating container annotations: cannot make change to container annotation cnrm.cloud.google.com/folder-id`

**ConfigConnector Version**
1.8.0

**To Reproduce**
Using helm install the following snippet with the initial folder number. Once deployed run an upgrade with the new folder number.

*YAML snippets:*

```yaml
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  name: "{{ $.Values.labels.business_entity }}-{{ $.Values.labels.team_id }}-{{ $.Values.labels.function }}-{{ $.Values.labels.environment }}-{{ $.Values.randNum }}"
  annotations:
     cnrm.cloud.google.com/auto-create-network: "false"
     cnrm.cloud.google.com/folder-id: "<this is changed after install>"
  labels:
    business_entity: {{ $.Values.labels.business_entity }}
spec:
  name: "{{ $.Values.labels.business_entity }}-{{ $.Values.labels.team_id }}-{{ $.Values.labels.function }}-{{ $.Values.labels.environment }}-{{ $.Values.randNum }}"
  billingAccountRef:
    external: "{{ $.Values.billingAccount }}"
```
