### ISSUE TITLE
External reference to Spanner instance in SpannerDatabase

### ISSUE THREAD

**Issue by marcoderama** [GoogleCloudPlatform/k8s-config-connector#182]
I've created a Spanner instance using the template [here](https://cloud.google.com/config-connector/docs/how-to/getting-started#updating_a_resource).  I've created spanner databases therein using the GCP console and all is good.

I would like to create a SpannerDatabase within this instance using Config Connector.  I thought I'd try:
```
apiVersion: spanner.cnrm.cloud.google.com/v1beta1
kind: SpannerDatabase
metadata:
  name: spannerdatabase-spanner-test
spec:
  instanceRef:
    external: projects/myproject/instances/spannerinstance-sample
```
That fails with a rather long status.conditions[0].message that starts with:
`Update call failed: error applying desired state: Error creating Database: googleapi: got HTTP response code 404 with body`
and ends with:
`<p>The requested URL <code>/v1/projects/myproject/instances/projects/myproject/instances/spannerinstance-sample/databases?alt=json</code> was not found on this server.  <ins>That’s all we know.</ins>`

The duplication in "`projects/myproject/instances/projects/myproject/instances`" looked fishy to me...  It looked like the operator is prefixing with `projects/myproject/instances/` so I tried again with just
```
spec:
  instanceRef:
    external: spannerinstance-sample
```
and it worked!

This is unlike external references I've seen elsewhere.  e.g. 
```
kind: SQLInstance
spec:
  settings:
    ipConfiguration:
      privateNetworkRef:
        external: projects/myproject/global/networks/dev-network
```
I expected the fully spec'ed path to be correct given the description of "IAM External Reference Format" in the [SpannerInstance reference documentation](https://cloud.google.com/config-connector/docs/reference/resources#spannerinstance).

Are both styles correct somehow or is something off here?

This is using Config Connector v1.7.1 btw.
