### ISSUE TITLE
IAMWorkloadIdentityPool not created

### ISSUE THREAD

**Issue by torfjor** [GoogleCloudPlatform/k8s-config-connector#1839]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Desired manifest:

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMWorkloadIdentityPool
metadata:
  name: federation
  namespace: spire-federation
spec:
  disabled: false
  location: global
  projectRef:
    external: pgs-project-prod
```

KCC fails to create the underlying resource:

```shell
$ kubectl logs -n cnrm-system -l cnrm.cloud.google.com/scoped-namespace=spire-federation | grep iamworkloadidentitypool-controller | jq
{
  "severity": "error",
  "timestamp": "2024-05-18T06:34:59.217Z",
  "msg": "Reconciler error",
  "controller": "iamworkloadidentitypool-controller",
  "controllerGroup": "iam.cnrm.cloud.google.com",
  "controllerKind": "IAMWorkloadIdentityPool",
  "IAMWorkloadIdentityPool": {
    "name": "federation",
    "namespace": "spire-federation"
  },
  "namespace": "spire-federation",
  "name": "federation",
  "reconcileID": "9d9a7ab9-80f3-4d42-acbd-d6028f04be33",
  "error": "Update call failed: error fetching live state: error reading underlying resource: operation not done."
}
{
  "severity": "info",
  "timestamp": "2024-05-18T06:34:59.217Z",
  "logger": "iamworkloadidentitypool-controller",
  "msg": "starting reconcile",
  "resource": {
    "name": "federation",
    "namespace": "spire-federation"
  }
}
```

### Additional Diagnostic Information

.

### Kubernetes Cluster Version

v1.27.5-gke.200

### Config Connector Version

1.117.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

Apply resource in description.
