### ISSUE TITLE
Enable APIs?

### ISSUE THREAD

**Issue by max-sixty** [GoogleCloudPlatform/k8s-config-connector#185]
Currently I get failures like:

```
    message: 'Update call failed: error applying desired state: Error creating Trigger:
      googleapi: Error 403: Cloud Build API has not been used in project [...]
      before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudbuild.googleapis.com/overview?project=[...]
      then retry. If you enabled this API recently, wait a few minutes for the action
      to propagate to our systems and retry.'
```

Is it possible to have these optionally enabled through config connector?

**Comment by max-sixty** [comment]
Back in 2018, pre-config connector, we build this to do something similar: https://github.com/SixtyCapital/infrastructure/blob/master/sixtyctl/gcp.py#L65

**Comment by AlexBulankou** [comment]
Config Connector supports `ServiceUsage` resource: [docs](https://cloud.google.com/config-connector/docs/reference/resources#service)

example:
```
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/disable-dependent-services: "false"
  name: cloudbuild.googleapis.com
```
