### ISSUE TITLE
"unable to parse logging sink id" when creating new LogSink

### ISSUE THREAD

**Issue by ssmall** [GoogleCloudPlatform/k8s-config-connector#1876]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

When trying to create a cross-project LogSink, ConfigConnector shows the following status:

```
Update call failed: error fetching live state: error importing resource: unable to parse logging sink id "projects/source-project###dest-project"
```

### Additional Diagnostic Information

None

### Kubernetes Cluster Version

v1.29.1-gke.1589020

### Config Connector Version

1.102.0

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

1. `kubectl apply` with the provide YAML snippet
2. `kubectl describe logginglogsink/dest-project`

### YAML snippets

```YAML
apiVersion: logging.cnrm.cloud.google.com/v1beta1
kind: LoggingLogSink
metadata:
  name: dest-project
  annotations:
    cnrm.cloud.google.com/project-id: source-project
spec:
  description: Routes logs from source-project to dest-project
  projectRef:
    external: projects/source-project
  uniqueWriterIdentity: true # must be true for cross-project log sinks
  destination:
    loggingLogBucketRef:
      external: logging.googleapis.com/projects/dest-project/locations/global/buckets/source-project
```
