### ISSUE TITLE
Watch, but not modify

### ISSUE THREAD

**Issue by Stono** [GoogleCloudPlatform/k8s-config-connector#188]
**Describe the bug**
Hello!
This is somewhat linked to https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/93, in that I'd like the ability to reconcile and empty CRD from an existing resource.

Eg if i created:

```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: 'false'
    cnrm.cloud.google.com/project-id: at-delivery-platform-testing
  name: delivery-platform
spec:
  location: europe-west4-a
```

It would go and populate the rest.

However, my reason for doing this is because I would also like it to continually reconcile that CRD with the current state (which we actually manage outside of kubernetes using other IAC tools).  

The reason we want this is because we want to be able to watch these CRD's for changes, and perform actions on them.  This is because many of our product teams want to programmatically perform certain actions when things like GKE upgrades or Node Pool Upgrades happen.

Is this something you would consider implementing?  Eg Read-Only reconciliation of resources?

**Comment by Stono** [comment]
This isn't a bug, not sure why it was tagged as such :-) Definitely a feature request.

**Comment by caieo** [comment]
Hi @Stono,
(re: why this was probably tagged as a bug, you may have used the bug issue template and it was automatically tagged as a bug)

Thanks for bringing this up! We're aware of this scenario and are currently working on a solution where you can indicate "externally-managed fields" to Config Connector. This will indicate to Config Connector which fields should reflect the latest known value in the underlying API. Does this (future) solution sound like it might address your use case?

**Comment by Stono** [comment]
It certainly does!

It would be great if you could do it at the entire resource level though, not just field

**Comment by spew** [comment]
Stono, this won't help you if you have an outside actor or service managing the resource, but if you want to bring the resource in wholesale to KCC we now offer this feature, from issue #93  as you noted. Documentation is [here](https://cloud.google.com/config-connector/docs/how-to/importing-existing-resources).

**Comment by Stono** [comment]
Yeah we do, we manage our resources with terraform - we are just wanting to observe them as CRDs on the cluster

**Comment by spew** [comment]
KCC manages drift by overwriting any changes it sees by external forces. As @caieo said, we are working on a feature where fields you do not specify would be considered externally managed and therefore KCC would not combat drift it detects on those fields.

So if you were to bring in the resources you are managing with terraform, KCC will fight any changes you make with terraform until you "import" the changes. 

One option is that you install KCC with a service account that only has "roles/reader" access to your project and then use the import tool I linked to above to bring the resources into KCC.

**Comment by Stono** [comment]
Ahhh when it was suggested you’d be able to mark fields as externally managed I thought that meant the value would track the externally managed value, not just drift.

So my original feature request is still valid and that’s for the ability to have kcc track an external resource being changed outside of kcc

**Comment by spew** [comment]
Yes, KCC will track the externally managed value (when the feature is available). The way to think about it is KCC will remember what you specified in your YAML & spec. Anything that is not specified will be considered externally managed and KCC will track the value but will not overwrite any changes.

**Comment by Stono** [comment]
So to be super clear, if i had a resource like this:
```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: 'false'
    cnrm.cloud.google.com/project-id: at-delivery-platform-testing
  name: delivery-platform
spec:
  location: europe-west4-a
```

it would get populated with all the other fields, and those values would track as they change externally?
