### ISSUE TITLE
Creating SQLInstance with only private IP

### ISSUE THREAD

**Issue by marcoderama** [GoogleCloudPlatform/k8s-config-connector#189]
I create SQLInstances that I want wired to a preexisting private network with a spec including:

```
  spec:
    settings:
      ipConfiguration:
        privateNetworkRef:
          external: projects/myproject/global/networks/dev-network
```
Until recently, that would create a SQLInstance with a private IP and _no_ public IP, which is exactly what I wanted.  I see now though, that my instances are getting created with a public IP as well.  (The only change on my end was a move from Config Connector 1.7.1 to 1.9.2.)

* Is that expected behavior?
* If so, how does one create a SQLInstance with only a private IP?
   * I see the example sets `ipv4Enabled: false`, and my testing indicates that that indeed does get me a private IP and no public IP.
   * Is setting `ipv4Enabled: false` the canonical way to do this?  If so, what's the logic, when the private IP is also an ipv4 address?
