### ISSUE TITLE
GKE pods can't reach CloudSQL on private IP

### ISSUE THREAD

**Issue by paulczar** [GoogleCloudPlatform/k8s-config-connector#201]
**Describe the bug**

Following the examples given in this repo I should be able to deploy a CloudSQL instance with a private IP and connect to it from a GKE Pod.  I cannot.

**ConfigConnector Version**
Run the following command to get the current ConfigConnector version
```bash 
kubectl get ns cnrm-system -o jsonpath='{.metadata.annotations.cnrm\.cloud\.google\.com/version}' 
```

1.11.0

**To Reproduce**

deploy the following Manifests:

```yaml
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: demo-db
  namespace: cloudsql
  annotations:
    cnrm.cloud.google.com/project-id: <my-project-id>
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: demo-db
  namespace: cloudsql
  annotations:
    cnrm.cloud.google.com/project-id: <my-project-id>
spec:
  addressType: INTERNAL
  location: global
  purpose: VPC_PEERING
  prefixLength: 16
  networkRef:
    name: demo-db
---
apiVersion: servicenetworking.cnrm.cloud.google.com/v1beta1
kind: ServiceNetworkingConnection
metadata:
  name: demo-db
  namespace: cloudsql
  annotations:
    cnrm.cloud.google.com/project-id: <my-project-id>
spec:
  networkRef:
    external: demo-db
  reservedPeeringRanges:
  - name: demo-db
  service: servicenetworking.googleapis.com
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: demo-db2
  namespace: cloudsql
  annotations:
    cnrm.cloud.google.com/project-id: <my-project-id>
spec:
  region: us-central1
  databaseVersion: POSTGRES_9_6
  settings:
    tier: db-custom-1-3840
    ipConfiguration:
      ipv4Enabled: false
      requireSsl: false
      privateNetworkRef:
        name: demo-db
  rootPassword:
    valueFrom:
      secretKeyRef:
        key: password
        name: demo-db
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-db
  namespace: cloudsql
stringData:
  password: this-is-a-bad-password
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: <my-project-id>
  name: cloudsql
```

It all seems to deploy okay, and I see the cloudSQL instance in my gcp console where I can get the IP of `10.82.0.3`.  However I can't connect to that:

```
kubectl -n cloudsql run -ti --restart=Never --image postgres:13-alpine --rm psql -- psql -h 10.82.0.3

psql: error: could not connect to server: could not connect to server: Operation timed out
	Is the server running on host "10.82.0.3" and accepting
	TCP/IP connections on port 5432?
pod "psql" deleted
pod cloudsql/psql terminated (Error)
```

I also tried port 3307 as that's the port cloud-proxy would try to use.

Thinking that maybe it still needed a sqlproxy I went ahead and figured that out and came up with the following yaml:

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: demo-db-proxy
  namespace: cloudsql
  annotations:
    cnrm.cloud.google.com/project-id: <my-project-id>
spec:
  displayName: demo-db-proxy workload identity
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: demo-db-proxy-sql-client
  namespace: cloudsql
  annotations:
    cnrm.cloud.google.com/project-id: <my-project-id>
spec:
  member: serviceAccount:demo-db-proxy@<my-project-id>.iam.gserviceaccount.com
  role: roles/cloudsql.client
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/<my-project-id>
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: demo-db-proxy-workload-id
  namespace: cloudsql
  annotations:
    cnrm.cloud.google.com/project-id: <my-project-id>
spec:
  member: serviceAccount:<my-project-id>.svc.id.goog[cloudsql/demo-db-proxy]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/<my-project-id>
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-db-proxy
  namespace: cloudsql
  annotations:
    cnrm.cloud.google.com/project-id: <my-project-id>
    iam.gke.io/gcp-service-account: demo-db-proxy@<my-project-id>.iam.gserviceaccount.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-db-proxy
  namespace: cloudsql
spec:
  selector:
    matchLabels:
      app: demo-db-proxy
  template:
    metadata:
      labels:
        app: demo-db-proxy
    spec:
      serviceAccountName: demo-db-proxy
      containers:
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.17
        command:
        - /cloud_sql_proxy
        - -ip_address_types=PRIVATE
        - -instances=<my-project-id>:us-central1:demo-db2=tcp:0.0.0.0:5432
        securityContext:
          runAsNonRoot: true
          runAsUser: 65534
---
apiVersion: v1
kind: Service
metadata:
  name: demo-db-proxy
  namespace: cloudsql
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: demo-db-proxy
  type: ClusterIP
```

but when I tried to connect to that I got:

```
k -n cloudsql logs -f demo-db-proxy-689796f8c8-z97b2                                  
2020/06/05 22:49:41 current FDs rlimit set to 1048576, wanted limit is 8500. Nothing to do here.
2020/06/05 22:49:46 Listening on 0.0.0.0:5432 for XXX:us-central1:demo-db2
2020/06/05 22:49:46 Ready for new connections
2020/06/05 22:53:28 New connection for "XXX:us-central1:demo-db2"
2020/06/05 22:54:00 couldn't connect to "XXXus-central1:demo-db2": dial tcp 10.82.0.3:3307: connect: connection timed out

```

I'm certain my manifests match up with the examples, so I'm guessing there's some important step missing in the docs.  Do I need a certain type of GKE cluster?  the one I created is fairly standard cluster created via:

```
gcloud beta container clusters create gcc-cloudsql \
  --num-nodes=1 --zone us-central1-c \
  --cluster-version 1.16 --machine-type n1-standard-2 \
  --workload-pool=${PROJECT_ID}.svc.id.goog
```

Otherwise, maybe there's a route or a firewall step?  this is a fresh project, so there's no firewalls or routes beside the defaults, so I'm certain I haven't got anything blocking it that shouldn't.

**Comment by paulczar** [comment]
```
$ gcloud sql instances list
NAME      DATABASE_VERSION  LOCATION       TIER              PRIMARY_ADDRESS  PRIVATE_ADDRESS  STATUS
demo-db2  POSTGRES_9_6      us-central1-c  db-custom-1-3840  -                10.82.0.3        RUNNABLE
```

**Comment by paulczar** [comment]
```
$ gcloud sql instances describe demo-db2
backendType: SECOND_GEN
connectionName: XXX:us-central1:demo-db2
databaseVersion: POSTGRES_9_6
etag: e325512d152eb3f52d13762ce80ca6ad95f0c31838431fc6dedca603e78beed8
gceZone: us-central1-c
instanceType: CLOUD_SQL_INSTANCE
ipAddresses:
- ipAddress: 10.82.0.3
  type: PRIVATE
kind: sql#instance
name: demo-db2
project: XXX
region: us-central1
selfLink: https://sqladmin.googleapis.com/sql/v1beta4/projects/XXXX/instances/demo-db2
serverCaCert:
  cert: |-
    -----BEGIN CERTIFICATE-----
 
    -----END CERTIFICATE-----
  certSerialNumber: '0'
  commonName: C=US,O=Google\, Inc,CN=Google Cloud SQL Server CA,dnQualifier=0b13fc6f-c6e8-4cb2-a473-83106e55ecfe
  createTime: '2020-06-05T21:21:37.614Z'
  expirationTime: '2030-06-03T21:22:37.614Z'
  instance: demo-db2
  kind: sql#sslCert
  sha1Fingerprint: 1e4357f626e8ce22357c5a98631dbcbe5d958ba1
serviceAccountEmailAddress: p87697109829-yn6glv@gcp-sa-cloud-sql.iam.gserviceaccount.com
settings:
  activationPolicy: ALWAYS
  backupConfiguration:
    binaryLogEnabled: false
    enabled: false
    kind: sql#backupConfiguration
    startTime: 01:00
  dataDiskSizeGb: '10'
  dataDiskType: PD_SSD
  ipConfiguration:
    ipv4Enabled: false
    privateNetwork: projects/XXX/global/networks/demo-db
    requireSsl: false
  kind: sql#settings
  locationPreference:
    kind: sql#locationPreference
    zone: us-central1-c
  pricingPlan: PER_USE
  replicationType: SYNCHRONOUS
  settingsVersion: '11'
  storageAutoResize: true
  storageAutoResizeLimit: '0'
  tier: db-custom-1-3840
  userLabels:
    cnrm-lease-expiration: '1591400855'
    cnrm-lease-holder-id: brdb8ekinp3smaoq0u3g
    managed-by-cnrm: 'true'
state: RUNNABLE
```

**Comment by paulczar** [comment]
Ok so this is definitely a documentation bug more so than it is a code bug.  Here's what I found.

In order for a compute instance resource to access the private-ip of a of a SQLinstance it must be deployed into the same network as the SQLinstance.

Since we're trying to use GKE, the POD must be in the same network to access the private-ip of a SQLinstance.

The way to do this is to create the GKE cluster as a [VPC-native cluster](https://cloud.google.com/kubernetes-engine/docs/how-to/alias-ips) `--enable-ip-alias`.  Whatever network that cluster is deployed to is the network that the servicenetwork peering must be set up to use.

Since there is a bug where you can't create a servicenetworkingconnection in the same run as the sqlinstance [148](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/148) we must create the networking first.

Assuming you want to use the `default` network ... the following should work:

```
PROJECT_ID=$(gcloud config get-value project)

# create the cluster
gcloud container clusters create gcc-cloudsql \
  --num-nodes=1 --zone us-central1-c \
  --cluster-version 1.16 --machine-type n1-standard-2 \
  --workload-pool=${PROJECT_ID}.svc.id.goog \
  --enable-ip-alias

# create the peer networking
```bash
gcloud compute addresses create cloudsql-peer \
    --global \
    --purpose=VPC_PEERING \
    --prefix-length=16 \
    --description="peering range for CloudSQL" \
    --network=default \
    --project=$PROJECT_ID

gcloud services vpc-peerings connect \
    --service=servicenetworking.googleapis.com \
    --ranges=cloudsql-peer \
    --network=default \
    --project=$PROJECT_ID
```

With that in place (we could have done the previous step via GCC and waited until the resources were fully created in gcloud before moving on) the following manifest will create a database that's accessible from a Pod ( either directly or through sqlproxy ):

```yaml
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: demo-db
spec:
  region: us-central1
  databaseVersion: POSTGRES_9_6
  settings:
    tier: db-custom-1-3840
    ipConfiguration:
      ipv4Enabled: false
      requireSsl: false
      privateNetworkRef:
        external: default
```
