### ISSUE TITLE
How can I refer to a sslCertificate from ComputeTargetHTTPSProxy

### ISSUE THREAD

**Issue by jlpettersson** [GoogleCloudPlatform/k8s-config-connector#206]
I want to setup a global load balancer for a `.dev` domain, those are HSTS-registered, so **https** is required.

When creating a  `ComputeTargetHTTPSProxy` and referring to a named sslCertificated that I have in my Google Cloud Console, e.g. found with `gcloud compute ssl-certificates list` - this does NOT work.

I have tried with:

```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeTargetHTTPSProxy
metadata:
  name: target-https-proxy
spec:
  urlMapRef:
    name: my-url-map
  sslCertificates:
  - name: my-domain-cert-in-console
  location: global
```

I get this error in the `status`

```
status:
  conditions:
  - lastTransitionTime: "2020-06-14T07:46:01Z"
    message: reference ComputeSSLCertificate /my-domain-cert-in-console is not found
    reason: DependencyNotFound
    status: "False"
    type: Ready
```

and if I would refere to another k8s config-connector CRD, there is *no way* to create a managed cert using the config-connector, currently: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/207 instead I have to go to [Create SSL Certificate (manually)](https://console.cloud.google.com/net-services/loadbalancing/advanced/sslCertificates/add) ...but then, it can not be used. :(
