### ISSUE TITLE
Can not refer to managed cert in ComputeSSLCertificate

### ISSUE THREAD

**Issue by jlpettersson** [GoogleCloudPlatform/k8s-config-connector#207]
**Describe the bug**

When creating a [ComputeSSLCertificate](https://cloud.google.com/config-connector/docs/reference/resources#computesslcertificate) there is no way to specify a domain-name so that I can get a _manage_ certificate.

It is possible to declare a domain that should get a _managed_ certificate in the [REST documentation](https://cloud.google.com/compute/docs/reference/rest/v1/sslCertificates)

```
  "managed": {
    "domains": [
      string
    ],
    "status": enum,
    "domainStatus": {
      object
    }
  },
```

and go to a shop to **buy** a domain name SSL certificate is unrealistic **5** years after LetsEncrypt.

**ConfigConnector Version**
```
1.9.2
```

**To Reproduce**
*Steps to reproduce the behavior:*

*YAML snippets:*

```yaml
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSSLCertificate
metadata:
  name: my-domain-cert
spec:
  location: global
```

**Comment by tonybenchsci** [comment]
Our company would like this as well. Relates to https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/107

**Comment by tonybenchsci** [comment]
Deployment Manager does this as well:

```
name: glb-gke-certificate--site-reagent-cname
  type: compute.beta.sslCertificate
  properties:
    type: MANAGED
    managed:
      domains:
```

**Comment by caieo** [comment]
Hi @jlpettersson and @tonybenchsci , we marked #107 as a "Resource request"/"Enhancement" but never fully updated the thread. 

The reason we have yet to implement managed certs in ComputeSSLCertificate is because there is a separate resource for [ComputeManagedSSLCertificates](https://www.terraform.io/docs/providers/google/r/compute_managed_ssl_certificate.html) (I'm showing this TF resource because we rely on TF). We still are investigating whether we should merge the two resources or just implement the ComputeManagedSSLCertificate as a separate resource. 

Just to get an understanding, can you explain if supporting managed certs is an important use-case to you?

**Comment by gorankarlic** [comment]
Any updates on config connector support for Google-managed SSL certificates?

Exporting via ` config-connector bulk-export --project my_project_id --on-error continue --output all.yaml` right now creates the following _invalid_ configuration:

```yaml
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSSLCertificate
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: my_project_id
  name: my_managed_ssl_cert
spec:
  location: global
```

But one can reference an external, existing, manually created, managed SSL certificate in a`ComputeTargetHTTPSProxy` like this:

```yaml
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeTargetHTTPSProxy
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: my_project_id
  name: my_target_https_proxy
spec:
  location: global
  quicOverride: NONE
  sslCertificates:
  - external: https://www.googleapis.com/compute/v1/projects/my_project_id/global/sslCertificates/my_managed_ssl_cert
...
```
