### ISSUE TITLE
Error with cnrm-webhook-manager in version 1.12.1

### ISSUE THREAD

**Issue by TravRan** [GoogleCloudPlatform/k8s-config-connector#212]
**Describe the bug**
When installing version 1.12.1, I get the error below after running 
```
kubectl apply -f install-bundle-namespaced/0-cnrm-system.yaml \
 -f install-bundle-namespaced/crds.yaml
```
```
Readiness probe failed: cat: can't open '/tmp/ready': No such file or directory
```
**ConfigConnector Version**
1.12.1

*YAML snippets:*

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    cnrm.cloud.google.com/version: 1.12.1
  labels:
    cnrm.cloud.google.com/component: cnrm-webhook-manager
    cnrm.cloud.google.com/system: "true"
  name: cnrm-webhook-manager
  namespace: cnrm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      cnrm.cloud.google.com/component: cnrm-webhook-manager
      cnrm.cloud.google.com/system: "true"
  template:
    metadata:
      annotations:
        cnrm.cloud.google.com/version: 1.12.1
      labels:
        cnrm.cloud.google.com/component: cnrm-webhook-manager
        cnrm.cloud.google.com/system: "true"
    spec:
      containers:
      - args:
        - --stderrthreshold=INFO
        command:
        - /configconnector/webhook
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: gcr.io/cnrm-eap/webhook:4925e84
        imagePullPolicy: Always
        name: webhook
        readinessProbe:
          exec:
            command:
            - cat
            - /tmp/ready
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          limits:
            cpu: 40m
            memory: 64Mi
          requests:
            cpu: 20m
            memory: 32Mi
        securityContext:
          privileged: false
          runAsNonRoot: true
          runAsUser: 1000
      serviceAccountName: cnrm-webhook-manager
      terminationGracePeriodSeconds: 10
```
