### ISSUE TITLE
 LoggingLogSink does not support destination of type Google Project

### ISSUE THREAD

**Issue by apresti12** [GoogleCloudPlatform/k8s-config-connector#2188]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Configuring a log sink with a destination of type GoogleProject is required to get Error Reporting to work in the destination project.  This configuration is well documented and clearly supported in non-config-connector deployment methods.  In config connector, this destination is just missing:

```
type LogsinkDestination struct {
	// +optional
	BigQueryDatasetRef *v1alpha1.ResourceRef `json:"bigQueryDatasetRef,omitempty"`

	/* Only `external` field is supported to configure the reference. */
	// +optional
	LoggingLogBucketRef *v1alpha1.ResourceRef `json:"loggingLogBucketRef,omitempty"`

	// +optional
	PubSubTopicRef *v1alpha1.ResourceRef `json:"pubSubTopicRef,omitempty"`

	// +optional
	StorageBucketRef *v1alpha1.ResourceRef `json:"storageBucketRef,omitempty"`
}
```

### Additional Diagnostic Information

This should be possible to implement, it's already supported in gcloud
```
gcloud logging sinks create my-sink logging.googleapis.com/projects/my-destination-project
```
[doc](https://cloud.google.com/sdk/gcloud/reference/logging/sinks/create)

### Kubernetes Cluster Version

1.27.11

### Config Connector Version

v1.119.0

### Config Connector Mode

cluster mode

### Log Output

```
k explain logginglogsink.spec.destination
GROUP:      logging.cnrm.cloud.google.com
KIND:       LoggingLogSink
VERSION:    v1beta1

FIELD: destination <Object>

DESCRIPTION:
    <empty>
FIELDS:
  bigQueryDatasetRef    <Object>
    <no description>

  loggingLogBucketRef   <Object>
    Only `external` field is supported to configure the reference.

  pubSubTopicRef        <Object>
    <no description>

  storageBucketRef      <Object>
    <no description>
```   

### Steps to reproduce the issue

The option is just missing

**Comment by WrathUM** [comment]
+1

**Comment by susanilmh** [comment]
+1

**Comment by soumilk91** [comment]
+1

**Comment by svwijk** [comment]
We ran into the same constraint but found a workaround.
If you specify an external `storageBucketRef` with the URI pointing to the project id the logs will be send to the project.

Example:
```yaml
  spec:
    destination:
      storageBucketRef:
        external: logging.googleapis.com/projects/my-destination-project-id
    filter: resource.type="bigquery_project" AND logName:"cloudaudit.googleapis.com"
    projectRef:
      name: my-source-project
    resourceID: logginglogsink-sample-folder
    uniqueWriterIdentity: true
```
