### ISSUE TITLE
IAMPolicyMember is not created

### ISSUE THREAD

**Issue by pjocke** [GoogleCloudPlatform/k8s-config-connector#219]
**Describe the bug**

**ConfigConnector Version**
1.10.0 (GKE 1.16 add-on)

**To Reproduce**
Use the two examples in

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/samples/resources/iamserviceaccount/iam_v1beta1_iamserviceaccount.yaml
and

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/samples/resources/iampolicymember/external-project-level-policy-member/iam_v1beta1_iampolicymember.yaml

The service account is created as expected, but the IAM policy mapping is not.

**Comment by pjocke** [comment]
`nomos status` says that everything is fine, and the `importer` log does not give any errors.

**Comment by pjocke** [comment]
I might also add that I do not have the `cnrm.cloud.google.com/project-id` annotation on my namespace but rather on the resources themselves:

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: test-sa-1
  annotations:
    cnrm.cloud.google.com/project-id: "dev-gke-test"
spec:
  displayName: Test service account
```

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-test-sa-1
  annotations:
    cnrm.cloud.google.com/project-id: "dev-gke-test"
spec:
  member: serviceAccount:test-sa-1@dev-gke-test.iam.gserviceaccount.com
  role: roles/storage.admin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/dev-gke-test
```
