### ISSUE TITLE
Support multiple serviceusage in single namespace 

### ISSUE THREAD

**Issue by tdigangi** [GoogleCloudPlatform/k8s-config-connector#223]
Currently you are only able specify a service in a single namespace once. Otherwise you will recieve the following error:

` Error: rendered manifests contain a resource that already exists. Unable to continue with install: Service "compute.googleapis.com" in namespace "singlename space" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "new-project": current value is "existing-project"`

**The following deployment will error**
```yaml
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: project-1
  name: compute.googleapis.com
  namespace:  single-namespace
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: project-2
  name: compute.googleapis.com
  namespace:  single-namespace
```

The rational because for separation of duty reasons the customer may wish to house all projects/services in a single namespace giving only the single WI GSA access to enable services across the organization.

**Comment by xiaobaitusi** [comment]
Hi @tdigangi , thanks for making the feature request. We are gong to implement an enhancement to allow specifying the resource id in the spec in case that users don't want to/cannot use the metadata.name as the GCP resource name. In your case, you can have the following example yamls to achieve declaring the same serviceusage for different projects in a single namespace. The field name is TBD. Does it work for you? 

```yaml
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: project-1
  name: compute-service-project1
  namespace:  single-namespace
spec:
  resourceId: compute.googleapis.com
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: project-2
 name: compute-service-project2
  namespace:  single-namespace
spec:
  resourceId: compute.googleapis.com
```
