### ISSUE TITLE
Issue with tainted GPU node pool

### ISSUE THREAD

**Issue by jonnylangefeld** [GoogleCloudPlatform/k8s-config-connector#228]
**Describe the bug**
Config Connector runs into a deadlock in the following condition:
* create a container node pool with GPU `guestAccelerator` and a custom taint (see yaml example)
* run into `GCE_STOCKOUT` (you would assume that only happens with a lot of requested resources. But we run into this fairly often with 1 node per zone, 3 zones and 4 accelerators.)

First, through the stockout issue, the following warning event is attached to the container nodepool:
```
Warning  UpdateFailed  5m28s  containernodepool-controller  Update call failed: error applying desired state: Error waiting for creating GKE NodePool:
           (1) Google Compute Engine: Not all instances running in IGM after 1m11.073025757s. Expect 1. Current errors: [GCE_STOCKOUT]: Instance 'gke-paas-kubeflow-de-gpu-nvidia-tesla-1f96ce8b-f75t' creation failed: The zone 'projects/cruise-paas-kubeflow-dev-45ef/zones/us-central1-b' does not have enough resources available to fulfill the request.  '(resource type:compute)'
           (2) Google Compute Engine: Not all instances running in IGM after 1m33.007163884s. Expect 1. Current errors: [GCE_STOCKOUT]: Instance 'gke-paas-kubeflow-de-gpu-nvidia-tesla-ef8cc55a-bblt' creation failed: The zone 'projects/cruise-paas-kubeflow-dev-45ef/zones/us-central1-a' does not have enough resources available to fulfill the request.  '(resource type:compute)'.
```

Which is expected at this point due to not enough available resources.
But then following there are a lot of warning events like the following:
```
Warning  UpdateFailed  5m26s                  containernodepool-controller  Update call failed: the desired mutation for the following field(s) is invalid: [nodeConfig.0.Taint.1.Value nodeConfig.0.Taint.1.Effect nodeConfig.0.Taint.1.Key nodeConfig.0.Taint.#]
```

That happens because GKE automatically adds another taint on top of the custom taint like the following:
```
"taints": [
    {
        "key": "dedicated",
        "value": "gpu",
        "effect": "NO_SCHEDULE"
    },
    {
        "key": "nvidia.com/gpu",
        "value": "present",
        "effect": "NO_SCHEDULE"
    }
]
```
On a healthy containernodepool, that gets populated back to the containernodepool spec. Like any other default on GKE side. In a healthy case, the containernodepool would have two taints at this point.
But after the stockout error was hit, that's not the case. But instead the above error comes up through every reconciliation and it never gets out of this state again.

**ConfigConnector Version**
`1.11.1`

**To Reproduce**
*Steps to reproduce the behavior:*

* create a node pool with GPU `guestAccelerator` and a custom taint (see yaml example)
* run into `GCE_STOCKOUT`

*YAML snippets:*

```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: <project-id>
  name: gpu-nvidia-tesla-t4-q5rfk
  namespace: nodepools
spec:
  autoscaling:
    maxNodeCount: 1000
    minNodeCount: 0
  clusterRef:
    external: <cluster>
  initialNodeCount: 1
  location: us-central1
  management:
    autoRepair: true
    autoUpgrade: true
  maxPodsPerNode: 64
  nodeConfig:
    diskSizeGb: 500
    diskType: pd-ssd
    guestAccelerator:
    - count: 4
      type: nvidia-tesla-t4
    imageType: COS
    machineType: n1-standard-32
    metadata:
      disable-legacy-endpoints: "true"
    minCpuPlatform: Intel Skylake
    oauthScopes:
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/devstorage.read_only
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/devstorage.read_write
    serviceAccountRef:
      external: <service account>
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    taint:
    - effect: NO_SCHEDULE
      key: dedicated
      value: gpu
  nodeLocations:
  - us-central1-a
  - us-central1-b
  - us-central1-f
  upgradeSettings:
    maxSurge: 20
    maxUnavailable: 0
  version: 1.15.11-gke.15
```
