### ISSUE TITLE
Authentication via Workload Identity does not work when the Cluster master version differs from the Node version

### ISSUE THREAD

**Issue by oceanful** [GoogleCloudPlatform/k8s-config-connector#233]
**Describe the bug**

Authentication via Workload Identity does not work when the Cluster master version differs from the Node version.

The runtime is not able to find default credentials.

**ConfigConnector Version**
1.9.1

**To Reproduce**

1. Configure the Deployment to use a `serviceAccountName`
1. Setup the ServiceAccount and iam roles.
1. If the cluster master version and node version differ, the runtime cannot find default credentials.

```
panic: google: could not find default credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
```

The problem persists until the node is upgraded to match the version of the cluster master.

*YAML snippets:*

```yaml
apiVersion: apps/v1
kind: Deployment
spec:
  template:
    spec:
      serviceAccountName: myserver
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: myserver
  annotations:
    iam.gke.io/gcp-service-account: myserver@<project>.iam.gserviceaccount.com
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: myserver-workload-identity
spec:
  role: roles/iam.workloadIdentityUser
  member: serviceAccount:<project>.svc.id.goog[default/myserver]
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: myserver
```
