### ISSUE TITLE
Does latest version 1.120.1 support ConfigConnector namespaced mode?

### ISSUE THREAD

**Issue by kallentrustle** [GoogleCloudPlatform/k8s-config-connector#2362]
### Describe your question

Today I installed version 1.120.1 manually on my GKE cluster. When I applied my ConfigConnector manifest, `mode: namespaced`, I got this error:

```
The ConfigConnector "configconnector.core.cnrm.cloud.google.com" is invalid:
* <nil>: Invalid value: "": "spec" must validate at least one schema (anyOf)
* spec.mode: Unsupported value: "namespaced": supported values: "cluster"

apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  mode: namespaced
  googleServiceAccount: "sa-mygccname@PROJECT_ID.iam.gserviceaccount.com"
  stateIntoSpec: Absent
 ```
I looked at the release notes, and didn't see anything about namespaced mode no longer being supported. GCP docs say you can use namespaced: https://cloud.google.com/config-connector/docs/how-to/install-namespaced

On a different GKE cluster where ConfigConnector is installed as an addon, version 1.102.0, I've been successfully using (testing) it in namespaced mode. I'm hoping to use this same setup in the newest version ...
