### ISSUE TITLE
RunService manifest invalid: vpcAccess.networkInterfaces

### ISSUE THREAD

**Issue by kallentrustle** [GoogleCloudPlatform/k8s-config-connector#2375]
### Describe your question

Hello again. I'm trying to convert our current GCP Cloud Run services to config-connector so we can deploy using ArgoCD. When I try to deploy my test service, I get error below. I'm reading the schema spec, but I don't see what I'm doing wrong. https://cloud.google.com/config-connector/docs/reference/resource-docs/run/runservice

I'm running version 1.120.1 of connector installed manually to my GKE cluster.

Can anyone help? Many thanks in advance.

The error:
```
$ argocd app get argocd/hello-cloudrain
..snip..
run.cnrm.cloud.google.com  RunService  staging    hello-cloudrain  OutOfSync
Missing        RunService.run.cnrm.cloud.google.com "hello-cloudrain" is
invalid: [<nil>: Invalid value: "":
"spec.template.vpcAccess.networkInterfaces[0].subnetworkRef" must validate one
and only one schema (oneOf). Found none valid, <nil>: Invalid value: "":
"spec.template.vpcAccess.networkInterfaces[0].subnetworkRef" must not validate
the schema (not), <nil>: Invalid value: "":
"spec.template.vpcAccess.networkInterfaces[0].networkRef" must validate one and
only one schema (oneOf). Found none valid, <nil>: Invalid value: "":
"spec.template.vpcAccess.networkInterfaces[0].networkRef" must not validate the
schema (not)]
```
 
This is the runservice.yaml:
```
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: hello-cloudrain
  annotations:
    cnrm.cloud.google.com/project-id: PROJECT_ID
spec:
  ingress: "INGRESS_TRAFFIC_ALL"
  location: "us-central1"
  launchStage: "GA"
  projectRef:
    external: projects/PROJECT_ID
  template:
    maxInstanceRequestConcurrency: 80
    scaling:
      minInstanceCount: 1
      maxInstanceCount: 2
    serviceAccountRef:
      external: sa-gcp-xxxxxx@PROJECT_ID.iam.gserviceaccount.com
    containers:
    - env:
      - name: GOOGLE_CLOUD_PROJECT
        value: PROJECT_ID
      image: us-central1-docker.pkg.dev/PROJECT_ID/kallen-test/hello-python:098771d
      ports:
      - name: http1
        containerPort: 8080
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
      startupProbe:
        failureThreshold: 2
        initialDelaySeconds: 10
        periodSeconds: 240
        tcpSocket:
          port: 8080
        timeoutSeconds: 240
    vpcAccess:
      egress: PRIVATE_RANGES_ONLY
      networkInterfaces:
      - networkRef:
          external: "https://www.googleapis.com/compute/v1/projects/PROJECT_ID/global/networks/MY_NETWORK"
          name: MY_NETWORK
        subnetworkRef:
          external: "https://www.googleapis.com/compute/v1/projects/PROJECT_ID/regions/us-central-1/subnetworks/MY_NETWORK-subnet"
          name: MY_NETWORK-subnet
  traffic:
    - percent: 100
      type: "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
```

**Comment by kallentrustle** [comment]
Hi. I don't know why I was getting the error I had asked about. But I want to follow up here and provide the manifest that is working for me, and is the one I was driving towards when I opened this issue. For posterity:
```
---
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: my-app-woooo
spec:
  ingress: "INGRESS_TRAFFIC_INTERNAL_ONLY"
  location: "us-central1"
  launchStage: "GA"
  projectRef:
    external: projects/PROJECT_ID
  template:
    maxInstanceRequestConcurrency: 80
    timeout: '300s'
    scaling:
      maxInstanceCount: 100
      minInstanceCount: 0
    serviceAccountRef:
      external: sa-deploy-me@PROJECT_ID.iam.gserviceaccount.com
    vpcAccess:
      egress: PRIVATE_RANGES_ONLY
      networkInterfaces:
      - networkRef:
          external: projects/PROJECT_ID/global/networks/my-network
        subnetworkRef:
          external: projects/PROJECT_ID/regions/us-central1/subnetworks/my-network-us-central1
    containers:
    - env:
      - name: GOOGLE_CLOUD_PROJECT
        value: PROJECT_ID
      - name: FOO
        value: http://10.24.0.33:80
      - name: BAR
        value: streltzi
      - name: API_AUTH_PRIVATE_KEY
        valueSource:
          secretKeyRef:
            secretRef:
              external: projects/PROJECT_NUMBER/secrets/my-app-woooo-secret
            versionRef:
              external: "latest"
      image: "us-central1-docker.pkg.dev/MY_OTHER_PROJECT_ID/woooo-repo/my-app-woooo/my-app-woooo:6574877"
      name: my-app-woooo
      ports:
      - containerPort: 8080
        name: http1
      resources:
        startupCpuBoost: true
        cpuIdle: false
        limits:
          cpu: 1000m
          memory: 512Mi
      startupProbe:
        failureThreshold: 1
        periodSeconds: 240
        tcpSocket:
          port: 8080
        timeoutSeconds: 240
      livenessProbe:
        httpGet:
          path: "/health"
          port: 8080
        initialDelaySeconds: 10
        periodSeconds: 10
        failureThreshold: 3
        timeoutSeconds: 3
  traffic:
    - percent: 100
      type: "TRAFFIC_TARGET_ALLOCATION_TYPE_LATEST"
```
