### ISSUE TITLE
RunService fails to update: error converting to DCL resource object

### ISSUE THREAD

**Issue by tsawada** [GoogleCloudPlatform/k8s-config-connector#2401]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

After updating Config Connector from v1.102.0 to v1.120.1, RunService resources fail to reconcile with the following message:

```
Update call failed: error fetching live state: error converting to DCL resource object: error resolving the value of the container field for resource ****: couldn't resolve the value for container field project
```

We tried deleting the RunServcie k8s resource, but it didn't help.

### Additional Diagnostic Information

None

### Kubernetes Cluster Version

v1.28.0

### Config Connector Version

1.120.1

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

Update to v1.120.1

### YAML snippets

```YAML
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: "****"
spec:
  description: ""
  ingress: "INGRESS_TRAFFIC_ALL"
  location: "us-central1"
  projectRef:
    external: "projects/****"
  template:
    containers:
      - image: "****"
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
    scaling:
      maxInstanceCount: 1
    serviceAccountRef:
      external: ****
    timeout: "600s"
```
