### ISSUE TITLE
MySQL SQLUser keeps trying to recreate user

### ISSUE THREAD

**Issue by esn89** [GoogleCloudPlatform/k8s-config-connector#2416]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

MySQL SQLUser keeps trying to recreate user/group.

I am using CloudSQL Authentication for MySQL:

```yaml
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.project }}
  name: engineers
  namespace: demo
spec:
  instanceRef:
    name: demodb
    namespace: demo
  resourceID: engineers@mycompany.com
  type: CLOUD_IAM_GROUP
```

The ConfigConnector has applied it and I can see this GROUP listed as a user in the MySQL DB:

```
mysql> SELECT user,host FROM mysql.user;
+----------------------------+----------------------+
| user                       | host                 |
+----------------------------+----------------------+
| cloudiamgroup              | %                    |
| cloudsqlreplica            | %                    |
| cloudsqlsuperuser          | %                    |
| root                       | %                    |
| cloudsqlexport             | 127.0.0.1            |
| cloudsqlimport             | 127.0.0.1            |
| cloudsqlobservabilityadmin | 127.0.0.1            |
| cloudsqloneshot            | 127.0.0.1            |
| root                       | 127.0.0.1            |
| cloudsqlexport             | ::1                  |
| cloudsqlimport             | ::1                  |
| cloudsqlobservabilityadmin | ::1                  |
| cloudsqloneshot            | ::1                  |
| root                       | ::1                  |
| cloudsqlapplier            | localhost            |
| cloudsqlimport             | localhost            |
| cloudsqlobservabilityadmin | localhost            |
| mysql.infoschema           | localhost            |
| mysql.session              | localhost            |
| mysql.sys                  | localhost            |
| root                       | localhost            |
| engineers                   | mycompany.com |
+----------------------------+----------------------+
23 rows in set (0.00 sec)
```

However, the `SQLUser` never seems to be in a good state:

```
Update call failed: error applying desired state: summary: Error, failed to insert user engineers@mycompany.com into instance demodb: googleapi: Error 400: Invalid request: Database user 'engineers' cannot be created because a user exists with the same name., invalid
```

![img](https://imgur.com/a/gqzrMnc)

### Additional Diagnostic Information

![img](https://imgur.com/a/099rfzc)

### Kubernetes Cluster Version

1.27.11-gke.1062004 

### Config Connector Version

1.118.1

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

```json
{"severity":"error","timestamp":"2024-08-05T18:06:51.444Z","msg":"Reconciler error","controller":"sqluser-controller","controllerGroup":"sql.cnrm.cloud.google.com","controllerKind":"SQLUser","SQLUser":{"name":"engineers-group","namespace":"demo"},"namespace":"demo","name":"engineers-group","reconcileID":"5ce51512-c3f0-4a1c-9269-5818cc33730e","error":"Update call failed: error applying desired state: summary: Error, failed to insert user engineers@mycompany.com into instance demodb: googleapi: Error 400: Invalid request: Database user 'engineers' cannot be created because a user exists with the same name., invalid"}
```

### YAML snippets

```YAML
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: {{ .Values.project }}
  name: sls-engg-group
  namespace: demo
spec:
  instanceRef:
    name: demodb
    namespace: demo
  resourceID: engineers@mycompany.com
  type: CLOUD_IAM_GROUP
```
