### ISSUE TITLE
CRD out of sync with GKE API for containerclusters

### ISSUE THREAD

**Issue by jonnylangefeld** [GoogleCloudPlatform/k8s-config-connector#244]
The [GKE API deprecated](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.locations.clusters#Cluster) `initialNodeCount` and `nodeConfig`, which defined the nodes of the default node pool in lieu of a `nodePools` array.

The [`containercluster` crd](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/crds/container_v1beta1_containercluster.yaml) doesn't reflect that change yet. However it's a valuable change that allows for creation of multiple node pools via the cluster resource.

Currently there is also no way of creating no default node pool at all.

**Comment by jcanseco** [comment]
Hi @jonnylangefeld, am I correct to understand that you want to create a cluster without a default node pool, and then create multiple custom node pools for that cluster?

While there is no way to create a cluster without a default node pool using Config Connector today, you can have the default node pool deleted upon cluster creation by setting the `cnrm.cloud.google.com/remove-default-node-pool` annotation to `true` and setting `spec.initialNodeCount` to 1.

Then, to create custom node pools for a cluster, you can create `ContainerNodePool` resources that reference your `ContainerCluster`.

So for example, putting the above points together, you can do something like the following:

```yaml
# My cluster
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
  name: my-cluster
spec:
  location: us-west1-a
  initialNodeCount: 1
---
# My node pools 1 and 2
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: my-node-pool-1
spec:
  location: us-west1-a
  nodeConfig:
    machineType: n1-standard-1
  clusterRef:
    name: my-cluster
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: my-node-pool-2
spec:
  location: us-west1-a
  nodeConfig:
    machineType: n1-standard-1
  clusterRef:
    name: my-cluster
```

Would something like this be able to fit your use-case?
