### ISSUE TITLE
MonitoringUptimeCheckConfig ContentMatchers[0].Content cannot be updated

### ISSUE THREAD

**Issue by minhnnhat** [GoogleCloudPlatform/k8s-config-connector#2469]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

In a MonitoringUptimeCheckConfig resource, the contentMatchers[].content field is not listed as immutable, but if the field is updated on an existing resource it goes into updateFailed with this message: 
'Update call failed: error applying desired state: infeasible update: ({true <nil> ContentMatchers[0].Content}) would require recreation'

### Additional Diagnostic Information

na

### Kubernetes Cluster Version

v1.29.6-gke.1254000

### Config Connector Version

1.120.1

### Config Connector Mode

namespaced mode (default)

### Log Output

Update call failed: error applying desired state: infeasible update: ({true <nil> ContentMatchers[0].Content}) would require recreation

### Steps to reproduce the issue

- Create a MonitoringUptimeCheckConfig resource with contentMatchers.content and contentMatchers.matcher.
- It created successfully.
- Then update the contentMatchers.content field.
- Failed to update with above error.

### YAML snippets

```YAML
apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringUptimeCheckConfig
metadata:
  name: check-jwt-public-keys
spec:
  contentMatchers:
  - content: .*\s.*(.*\"4j-ZJQ\"\s.*)\s(.*\"D-V_8g\"\s.*)\s(.*\"JJAn2A\"\s.*)\s(.*\"PzDuTA\"\s.*)\s(.*\"nPC_3g\"\s.*).*\s.*
    matcher: MATCHES_REGEX
  displayName: Check JWT public keys
  httpCheck:
    path: /iap/verify/public_key
    port: 443
    requestMethod: GET
    useSsl: true
    validateSsl: true
  monitoredResource:
    filterLabels:
      host: www.gstatic.com
      project_id: redacted
    type: uptime_url
  period: 60s
  projectRef:
    external: projects/redacted
  resourceID: check-jwt-public-keys-redacted
  selectedRegions:
  - EUROPE
  - ASIA_PACIFIC
  - USA_VIRGINIA
  timeout: 10s
```
