### ISSUE TITLE
Mismatched BigQuery KCC Go struct and BigQuery KCC CRD schema

### ISSUE THREAD

**Issue by NeilluANZx** [GoogleCloudPlatform/k8s-config-connector#2495]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

I'm trying to create a BigQuery dataset programmatically with an Authorized Dataset configuration using KCC in Go.
In Go, I'm creating a dataset object using the [BigQuery KCC Go struct](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/9b204cb0496dc130d690958b25300a033151560c/pkg/clients/generated/apis/bigquery/v1beta1/bigquerydataset_types.go#L38) and then generating a YAML file from it. However, with the current BigQuery KCC Go struct, I'm unable to specify the `targetTypes`, and the generated YAML for the Authorized Dataset part doesn't fully align with the structure described in the BigQuery CRD schema either.

```
## Rendered from Go Struct
access:
- dataset:
    datasetId: testing_product_v1_bq_consumption
    projectId: anz-x-some-project-dev-1234

## CRD Schema definition
access:
- dataset:
    dataset:
      datasetId: string
      projectId: string
    targetTypes:
    - string
 ```

### Additional Diagnostic Information

there is no `targetTypes` field within currently Go Struct
```
type BigQueryDatasetSpec struct {
	/* An array of objects that define dataset access for one or more entities. */
	// +optional
	Access []DatasetAccess `json:"access,omitempty"`
}

type DatasetAccess struct {
	Dataset *DatasetDataset `json:"dataset,omitempty"`
}

type DatasetDataset struct {
	DatasetId string `json:"datasetId"`
	ProjectId string `json:"projectId"`
}
```

### Kubernetes Cluster Version

n/a

### Config Connector Version

n/a

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

there is no targetTypes field within currently Go Struct
```
type BigQueryDatasetSpec struct {
	/* An array of objects that define dataset access for one or more entities. */
	// +optional
	Access []DatasetAccess `json:"access,omitempty"`
}

type DatasetAccess struct {
	Dataset *DatasetDataset `json:"dataset,omitempty"`
}

type DatasetDataset struct {
	DatasetId string `json:"datasetId"`
	ProjectId string `json:"projectId"`
}
```

### YAML snippets

```YAML
## Rendered from Go Struct for Authorized Dataset access block
access:
- dataset:
    datasetId: testing_product_v1_bq_consumption
    projectId: anz-x-some-project-dev-1234

## required CRD Schema definition
access:
- dataset:
    dataset:
      datasetId: string
      projectId: string
    targetTypes:
    - string
```
