### ISSUE TITLE
Default description of DNSManagedZone is "Managed by Terraform"

### ISSUE THREAD

**Issue by errordeveloper** [GoogleCloudPlatform/k8s-config-connector#254]
**Describe the bug**

I haven't set the description, but it's being set somehow, and it's not "Managed by Config Connector", but "Managed by Terraform", and it's confusing, since we aren't using Terraform for this (albeit we use it elsewhere).

**ConfigConnector Version**
Run the following command to get the current ConfigConnector version
```bash 
kubectl get ns cnrm-system -o jsonpath='{.metadata.annotations.cnrm\.cloud\.google\.com/version}' 
```

**To Reproduce**
*Steps to reproduce the behavior:*

*YAML snippets:*

```yaml
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: foo-example-com
  namespace: dns
spec:
  dnsName: "foo.example.com."
```
And after it's create, inside the API it shows up like this:
```
$ kubectl get -n dns DNSManagedZone  -o yaml foo-example-com
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: foo-example-com
  namespace: dns
spec:
  description: Managed by Terraform
  dnsName: foo.example.com.
  visibility: public
status: {}
```
