### ISSUE TITLE
ContainerNodePool no status update, no logs

### ISSUE THREAD

**Issue by sthomson-wyn** [GoogleCloudPlatform/k8s-config-connector#2562]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

When creating a ContainerNodePool, the status never updates, no logs are emmitted suggesting what is wrong

### Additional Diagnostic Information

![image](https://github.com/user-attachments/assets/35d51764-f3d3-481a-9526-fc5ea7172f80)
![image](https://github.com/user-attachments/assets/9a300031-63fa-40e9-9e4b-bb7ced16a3e5)

### Kubernetes Cluster Version

v1.27.11-gke.1062004

### Config Connector Version

1.115.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

Create containernodepool per yaml snippet, wait. Nothing happens

### YAML snippets

```YAML
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: {project}
    cnrm.cloud.google.com/state-into-spec: Absent
  name: stateless-c
  namespace: {project}
spec:
  clusterRef:
    external: {clusterName}
  initialNodeCount: 0
  location: us-central1
  management:
    autoRepair: true
    autoUpgrade: true
  maxPodsPerNode: 64
  networkConfig:
    podRange: k8s-pods
  nodeConfig:
    diskSizeGb: 32
    diskType: pd-balanced
    gvnic:
      enabled: true
    imageType: COS_CONTAINERD
    labels:
      node-type: stateless
    loggingVariant: DEFAULT
    machineType: e2-custom-8-12288
    metadata:
      cluster-type: regional
      disable-legacy-endpoints: "true"
      node-type: stateless
    oauthScopes:
    - https://www.googleapis.com/auth/logging.write
    - https://www.googleapis.com/auth/monitoring
    - https://www.googleapis.com/auth/ndev.clouddns.readwrite
    - https://www.googleapis.com/auth/servicecontrol
    - https://www.googleapis.com/auth/trace.append
    - https://www.googleapis.com/auth/compute
    - https://www.googleapis.com/auth/devstorage.read_only
    - https://www.googleapis.com/auth/service.management.readonly
    preemptible: true
    serviceAccountRef:
      external: default
    shieldedInstanceConfig:
      enableIntegrityMonitoring: true
      enableSecureBoot: true
    spot: false
    tags:
    - subnet-{subnet}
    taint:
    - effect: NO_SCHEDULE
      key: cloud.google.com/gke-preemptible
      value: "true"
    workloadMetadataConfig:
      mode: GKE_METADATA
  nodeCount: 0
  nodeLocations:
  - us-central1-a
  - us-central1-b
  - us-central1-c
  upgradeSettings:
    maxSurge: 1
    maxUnavailable: 0
    strategy: SURGE
```
