### ISSUE TITLE
Error when deleting then recreating a ContainerNodePool with deletion-policy: abandon

### ISSUE THREAD

**Issue by jlgeering** [GoogleCloudPlatform/k8s-config-connector#260]
**Describe the bug**
When deleting then recreating a ContainerNodePool with deletion-policy: abandon, the status of the resource ends up being: 

```
status:
  conditions:
    - lastTransitionTime: '2020-08-28T06:55:45Z'
      message: >-
        Update call failed: error applying desired state: googleapi: Error 400:
        At least one of ['node_version', 'image_type', 'updated_node_pool',
        'locations', 'workload_metadata_config', 'upgrade_settings',
        'kubelet_config', 'linux_node_config', 'tags', 'taints', 'labels'] must
        be specified., badRequest
      reason: UpdateFailed
      status: 'False'
      type: Ready
```

**ConfigConnector Version**
1.19.1

**To Reproduce**

*cluster.yaml:*

```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/remove-default-node-pool: "true"
  name: blue
spec:
  location: europe-west6-b  
  initialNodeCount: 1
  loggingService: logging.googleapis.com/kubernetes
  monitoringService: monitoring.googleapis.com/kubernetes
  authenticatorGroupsConfig:
    securityGroup: _REDACTED_
  ipAllocationPolicy:
    clusterIpv4CidrBlock: ""
  masterAuth:
    clientCertificateConfig:
      issueClientCertificate: false
  maintenancePolicy:
    recurringWindow:
      startTime: "2020-01-01T00:30:00Z"
      endTime: "2020-01-01T04:30:00Z"
      recurrence: "FREQ=WEEKLY;BYDAY=MO,TU,WE,TH"
  releaseChannel:
    channel: REGULAR
  workloadIdentityConfig:
    identityNamespace: _REDACTED_
```

*pool.yaml:*

```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
  name: blue-a
spec:
  location: europe-west6-b  
  initialNodeCount: 3
  autoscaling:
    minNodeCount: 3
    maxNodeCount: 6
  clusterRef:
    name: blue
  management:
    autoRepair: true
    autoUpgrade: true
  nodeConfig:
    diskSizeGb: 25
    diskType: pd-ssd
    machineType: e2-standard-2
    preemptible: false
    oauthScopes:
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
      - "https://www.googleapis.com/auth/devstorage.read_only"
  upgradeSettings:
    maxSurge: 2
    maxUnavailable: 0
```

*steps to reproduce:*

```
kubectl apply -f cluster.yaml
kubectl apply -f pool.yaml
kubectl delete -f pool.yaml
kubectl apply -f pool.yaml
```
