### ISSUE TITLE
cannot make changes to immutable field(s): [Field Name: topic, Got: projects/<project_id>/topics/<topic>, Wanted: _deleted-topic_]

### ISSUE THREAD

**Issue by wrdls** [GoogleCloudPlatform/k8s-config-connector#2619]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

We're migrating PubSub config from Terraform to Config Connector. 
We're are only getting started with this process which means we have some bugs in our migration script and things got a bit messy.
After working through the issues we now get this error on our PubSubSubscriptions:

```
[Field Name: topic, Got: projects/<project_id>/topics/<topic>, Wanted: _deleted-topic_]
```

The referenced PubSubTopic looks healthy both in Kubernetes as in GCP so we're a bit puzzled why ConfigConnector is reporting this as `_deleted-topic_`.

I tried to recreate the ConfigConnector resources with `abandon` but this didn't help.

```shell
$ kubectl get pubsubtopic -l app=foo | rg -v NAME | awk '{print $1}' | xargs kubectl patch pubsubtopic -p '{"metadata":{"annotations":{"cnrm.cloud.google.com/deletion-policy":"abandon"}}}' --type=merge
$ kubectl delete pubsubsubscription -l app=foo
$ kubectl delete pubsubsubtopic -l app=foo
```

### Additional Diagnostic Information

```yaml
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: <project_id>
    cnrm.cloud.google.com/state-into-spec: merge
  finalizers:
    - cnrm.cloud.google.com/finalizer
    - cnrm.cloud.google.com/deletion-defender
  name: <topic_name>
  namespace: default
spec:
  messageRetentionDuration: 172800s
  messageStoragePolicy:
    allowedPersistenceRegions:
      - australia-southeast1
  resourceID: <topic_name>
status:
  conditions:
    - lastTransitionTime: '2024-09-04T06:49:10Z'
      message: The resource is up to date
      reason: UpToDate
      status: 'True'
      type: Ready
  observedGeneration: 1
```

```yaml
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: <project_id>
  name: <subscription_name>
  namespace: default
spec:
  ackDeadlineSeconds: 10
  enableExactlyOnceDelivery: false
  enableMessageOrdering: false
  expirationPolicy:
    ttl: ''
  filter: ''
  messageRetentionDuration: 172800s
  resourceID: <subscription_name>
  retainAckedMessages: false
  retryPolicy:
    maximumBackoff: 10s
    minimumBackoff: 0s
  topicRef:
    name: <topic_name>
    namespace: default
status:
  conditions:
    - lastTransitionTime: '2024-09-04T06:49:22Z'
      message: >-
        Update call failed: cannot make changes to immutable field(s): [Field
        Name: topic, Got:
        projects/<project_id>/topics/<topic_name>,
        Wanted: _deleted-topic_]; please refer to our troubleshooting doc:
        https://cloud.google.com/config-connector/docs/troubleshooting
      reason: UpdateFailed
      status: 'False'
      type: Ready
  observedGeneration: 1
```

### Kubernetes Cluster Version

v1.29.7-gke.1104000

### Config Connector Version

1.121.0

### Config Connector Mode

cluster mode

### Log Output

```
2024-09-04T07:18:19.722563780Z {"severity":"error","timestamp":"2024-09-04T07:18:19.722Z","msg":"Reconciler error","controller":"pubsubsubscription-controller","controllerGroup":"pubsub.cnrm.cloud.google.com","controllerKind":"PubSubSubscription","PubSubSubscription":{"name":"<pubsubsubscription_name>","namespace":"default"},"namespace":"default","name":"<pubsubsubscription_name>","reconcileID":"03ec1bb4-f193-4124-9a87-1516079127e0","error":"Update call failed: cannot make changes to immutable field(s): [Field Name: topic, Got: projects/<project_id>/topics/<topic_name>, Wanted: _deleted-topic_]; please refer to our troubleshooting doc: https://cloud.google.com/config-connector/docs/troubleshooting"}
```

### Steps to reproduce the issue

Create a mess by creating Config Connector resources that try to change idempotent fields of existing resources.

...
