### ISSUE TITLE
Error 400: Precondition check failed when creating a service network connection

### ISSUE THREAD

**Issue by mruoss** [GoogleCloudPlatform/k8s-config-connector#270]
**Describe the bug**

I am trying to create a resource of type ServiceNetworkingConnection. I receive the following error from the API: Update call failed: error fetching live state: error reading underlying resource: googleapi: Error 400: Precondition check failed., failedPrecondition

Am I doing something wrong?

**ConfigConnector Version**

1.20

**To Reproduce**
*Steps to reproduce the behavior:*

Apply the yaml below.

*YAML snippets:*

```yaml
apiVersion: servicenetworking.cnrm.cloud.google.com/v1beta1
kind: ServiceNetworkingConnection
metadata:
  name: sql-instance-test1
spec:
  networkRef:
    external: default
  reservedPeeringRanges:
    - name: sql-instance-test1
  service: "servicenetworking.googleapis.com"
```
