### ISSUE TITLE
SQLInstance Error 400: The incoming request contained invalid data., invalidRequest

### ISSUE THREAD

**Issue by PurseChicken** [GoogleCloudPlatform/k8s-config-connector#2706]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

After updating the config connector operator to 1.122.0, I am now seeing the following error on all SQLInstance manifests:

`Update call failed: error updating: updating SQLInstance my-sql-instance failed: googleapi: Error 400: The incoming request contained invalid data., invalidRequest`

My SQLInstance manifests all look very similar to the following:

```
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/project-id: my-gcp-project
  name: my-gcp-project-my-sql-instance
  namespace: my-namespace
spec:
  databaseVersion: POSTGRES_16
  region: us-west3
  resourceID: my-sql-instance
  settings:
    availabilityType: REGIONAL
    backupConfiguration:
      enabled: true
      pointInTimeRecoveryEnabled: true
    databaseFlags:
      - name: cloudsql.iam_authentication
        value: 'on'
    diskSize: 100
    ipConfiguration:
      requireSsl: true
    maintenanceWindow:
      day: 1
      hour: 4
      updateTrack: stable
    tier: db-custom-2-8192
```

### Additional Diagnostic Information

I have not been able to find any other logs that point to what the issue could be. That said, I have this same issue for 4 different SQLInstance manifests.

### Kubernetes Cluster Version

v1.30.3-gke.1639000

### Config Connector Version

1.122.0

### Config Connector Mode

namespaced mode (default)

### Log Output

{"SQLInstance":{…}, "controller":"sqlinstance-controller", "controllerGroup":"sql.cnrm.cloud.google.com", "controllerKind":"SQLInstance", "error":"Update call failed: error updating: updating SQLInstance my-sql-instance failed: googleapi: Error 400: The incoming request contained invalid data., invalidRequest", "msg":"Reconciler error", "name":"my-gcp-project-my-sql-instance", "namespace":"my-namespace", "reconcileID":"f7964001-890b-478f-80e7-67d9f2262cd5", "timestamp":"2024-09-16T22:59:48.295Z"}

### Steps to reproduce the issue

Apply a SQLInstance manifest.
