### ISSUE TITLE
Strategies for integrating with kustomize?

### ISSUE THREAD

**Issue by max-sixty** [GoogleCloudPlatform/k8s-config-connector#271]
I'm hoping to use similar environments across dev / staging / prod projects, and to use config-connector to deploy them. I've been trying to use kustomize to manage the differing environments.

As an example, here's an IAM Policy — note the binding member requires a reference to the project:
```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: argo-policy
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: argo-iam
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:my_dev_project.svc.id.goog[default/workflow-service-account]
```

I'd need to change `my_dev_project` to `my_prod_project` for the prod project version of these manifests. My understanding is that it's not really possible to interpolate strings using kustomize. One of the main selling points to this form of declarative management of resources was to sync resources across environments.

Has anyone found a good solution to cases like these? Or alternative approaches?
