### ISSUE TITLE
folder-id annotation does not work with prepending "folders/" like projects does

### ISSUE THREAD

**Issue by snuggie12** [GoogleCloudPlatform/k8s-config-connector#280]
**Describe the bug**
If you try to create a folder that is nested inside of another folder you cannot supply the folder-id in the format of "folders/12345678". If you do so it will prepend its own "folders/" creating "folders/folders/12345678" which is not valid.

This is not true if you create a project and use the folder-id annotation in the format of "folders/12345678".

**ConfigConnector Version**
Run the following command to get the current ConfigConnector version
```bash 
1.19.0
```

**To Reproduce**
*Steps to reproduce the behavior:*
1. Create a folder using any method
2. Create another folder using kcc. Fill in the following annotation:
```
cnrm.cloud.google.com/folder-id: folders/<folder id from step 1>
```
3. Optionally, create a project using the same annotation and it should succeed.

*YAML snippets:*

```yaml
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Folder
metadata:
  annotations:
    # Replace "${FOLDER_ID?}" with the numeric ID for your parent folder
    cnrm.cloud.google.com/folder-id: "folders/${FOLDER_ID?}"
  name: folder-sample-in-folder
spec:
  displayName: Config Connector sample
```
