### ISSUE TITLE
How do I know which fields are mutable/immutable and which are not? And is immutability a limitation of config connector or gcp?

### ISSUE THREAD

**Issue by red8888** [GoogleCloudPlatform/k8s-config-connector#290]
I created a reserved IP with config connector:

```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: sdfsdfdsf
  labels:
    sdfsdfd: "sdfsdfdf"
spec:
  addressType: EXTERNAL
  description: blah123
  location: global
  ipVersion: IPV
```

I added a label to the manifest and deployed but the new label didnt appear on the resource:
```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: sdfsdfdsf
  labels:
    sdfsdfd: "sdfsdfdf"
    newlabel: "sdfsfsdfsfsdfs"
spec:
  addressType: EXTERNAL
  description: blah123
  location: global
  ipVersion: IPV
```

Is this the case with ALL metadata labels for config connector resources or is this just an issue with the ComputeAddress field? I might want to update the labels of a resource and I want to confirm config connector supports that. I also tried updating just the _value_ of the "sdfsdfd" label that was created first and the label's value didnt change either.

My other question is about immutable fields. I tried changing the description but got an error:
```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: sdfsdfdsf
  labels:
    sdfsdfd: "sdfsdfdf"
    anotherlabel: "sdfsfsdfsfsdfs"
spec:
  addressType: EXTERNAL
  description: sdflskdjf sdlfkjsdlkfj sldkf jslkdjf sldkf
  location: global
  ipVersion: IPV
```

error: `denied the request: cannot make changes on immutable fields: [description]`. My first question is if this is a limitation of the resource itself or is config connector preventing me from updating the description field?

Where do I go to see what is and is not immutable? The docs dont seem to have this info: https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computeaddress

I already use terraform heavily and its very flexible with updating already created resources where GCP allows this because its just using the GCP APIs. Before I start using config connector I want to make sure it doesnt have a bunch of weird limitations I dont see when using terraform or gcloud to create resources.

Thanks!
