### ISSUE TITLE
Bigtables Garbage Collection Policy is not applicable

### ISSUE THREAD

**Issue by wesam80** [GoogleCloudPlatform/k8s-config-connector#300]
**Describe the bug**
When applying a simple BigtableGCPolicy like the one [here ](https://cloud.google.com/config-connector/docs/reference/resource-docs/bigtable/bigtablegcpolicy#sample_yamls ) in the documentation, the objects are created properly, but the policy is not really applied. 

![image](https://user-images.githubusercontent.com/1942720/98276394-e63e5480-1f63-11eb-8d92-0ce77b736e83.png)

If the policy is updated using the cli  `cbt` it works fine

**ConfigConnector Version**
1.27.1

**To Reproduce**
*Steps to reproduce the behavior:*

*YAML snippets:*
```yaml
apiVersion: bigtable.cnrm.cloud.google.com/v1beta1
kind: BigtableGCPolicy
metadata:
  name: bigtablegcpolicy-sample
spec:
  tableRef:
    name: bigtablename
  columnFamily: quote
  instanceRef:
    name: clustername
  mode: INTERSECTION
  maxAge:
  - days: 30
  maxVersion:
  - number: 10
```

Then check the GC policies on the field using `cbt` command line, it will show <never>

If the policy is update manually `cbt setgcpolicy ...` it will work fine
