### ISSUE TITLE
A basic and minimal ComputeInstanceTemplate doesn't materialize.

### ISSUE THREAD

**Issue by bshimc** [GoogleCloudPlatform/k8s-config-connector#310]
**Describe the bug**
A basic and minimal ComputeInstanceTemplate doesn't materialize.  The resource is created without any feedback saying there's a problem. When I run `kubectl describe` on the resource, there are no events.

**ConfigConnector Version**
Run the following command to get the current ConfigConnector version
```bash 
kubectl get ns cnrm-system -o jsonpath='{.metadata.annotations.cnrm\.cloud\.google\.com/version}' 
1.27.1
```

**To Reproduce**
Apply the resource (below).  Observe that `gcloud compute instance-templates list` doesn't show anything.  There are no logs for `resource.type="gce_instance_template"`.  The DEBUG/INFO log spew for the KCC-related controllers is so high (4000/minute) that it's extremely difficult to tease out any information from that source.

*YAML snippets:*

```yaml
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstanceTemplate
metadata:
  name: my-template
spec:
  machineType: e2-highcpu-16
  disk:
  - sourceImageRef:
      external: projects/cos-cloud/global/images/family/cos-stable
    autoDelete: true
    boot: true
    diskType: pd-ssd
    diskSizeGb: 48
    type: PERSISTENT
```
