### ISSUE TITLE
Cannot update permissions of a custom role

### ISSUE THREAD

**Issue by flunderpero** [GoogleCloudPlatform/k8s-config-connector#313]
**Describe the bug**
When I try to update an existing role, I get this panic:
```
{ "controller": "iamcustomrole-controller", "msg": "Reconciler error", "request": "tkt-dev-pero/faas", "logger": "controller-runtime.controller", "error": "INTERNAL ERROR: panic: observed a panic: expected state's set to have value explicitly provided in spec
	/go/src/cnrm.googlesource.com/cnrm/pkg/execution/builtin.go:26 +0x57
	panic(0x33f67e0, 0xc000f068e0)
		/usr/local/go/src/runtime/panic.go:975 +0x3e3
	cnrm.googlesource.com/cnrm/pkg/krmtotf.convertTFSetToKCCSet(0x3192820, 0xc002b23040, 0x3192820, 0xc001f27ba0, 0xc000bc3400, 0xc0016e2c38, 0x3a150e3, 0xb, 0x51849a, 0xc0038430a8)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/tftokrm.go:502 +0xa82
	cnrm.googlesource.com/cnrm/pkg/krmtotf.convertTFMapToKCCMap(0xc0037db980, 0xc003516600, 0xc000bbe300, 0xc0016e2c38, 0x0, 0x0, 0xc001c3b4a0, 0x0)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/tftokrm.go:338 +0xa8c
	cnrm.googlesource.com/cnrm/pkg/krmtotf.ConvertTFObjToKCCObj(0xc0037db980, 0xc003516600, 0xc000bbe300, 0xc0016e2c38, 0x0, 0x0, 0xc001c3b4a0, 0xc002e30000)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/tftokrm.go:230 +0x7a
	cnrm.googlesource.com/cnrm/pkg/krmtotf.GetSpecAndStatusFromState(0xc0016e2b00, 0xc002eaad20, 0x0, 0x0)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/tftokrm.go:24 +0xcd
	cnrm.googlesource.com/cnrm/pkg/krmtotf.resolveUnmanagedFields(0xc0037daf60, 0xc0016e2b00, 0xc002eaad20, 0x0, 0x0, 0x100)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/krmtotf.go:145 +0xb6
	cnrm.googlesource.com/cnrm/pkg/krmtotf.krmResourceToTFResourceConfig(0xc0016e2b00, 0xc002eaad20, 0x41ca2c0, 0xc00022f540, 0xc000f4f640, 0x1, 0x0, 0xc002eaad20, 0x0, 0x0)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/krmtotf.go:57 +0x17d
	cnrm.googlesource.com/cnrm/pkg/krmtotf.KRMResourceToTFResourceConfigWithGCPManagedFields(...)
		/go/src/cnrm.googlesource.com/cnrm/pkg/krmtotf/krmtotf.go:46
	cnrm.googlesource.com/cnrm/pkg/controller/tf.(*Reconciler).sync(0xc00022f540, 0x41ae6c0, 0xc00005a1f8, 0xc0016e2b00, 0x41f2f00, 0x0, 0x0)
		/go/src/cnrm.googlesource.com/cnrm/pkg/controller/tf/controller.go:229 +0x546
	cnrm.googlesource.com/cnrm/pkg/controller/tf.(*Reconciler).Reconcile(0xc00022f540, 0xc001136ff0, 0xc, 0xc001136fd0, 0x4, 0x0, 0x0, 0x0, 0x0)
		/go/src/cnrm.googlesource.com/cnrm/pkg/controller/tf/controller.go:142 +0xbf3
	cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00194cb40, 0x350a1a0, 0xc001f44020, 0x137461723400)
		/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:256 +0x161
	cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00194cb40, 0x137461723400)
		/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:232 +0xae
	cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc00194cb40)
		/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:211 +0x2b
	cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc001f95e30)
		/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f
	cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc001f95e30, 0x41204c0, 0xc001fbef00, 0xc001fc4201, 0xc00087e300)
		/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3
	cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc001f95e30, 0x3b9aca00, 0x0, 0x1, 0xc00087e300)
		/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0xe2
	cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc001f95e30, 0x3b9aca00, 0xc00087e300)
		/go/src/cnrm.googlesource.com/cnrm/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d
	created by cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1
		/go/src/cnrm.googlesource.com/cnrm/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:193 +0x305
	" }
```

Der CRNM-Service-Account has the owner role in our organization. 

I don't get the panic if I specify exactly the permissions that there are already set in the custom role. Removing a role works, too. But when I try to add one I don't see any event in the custom resource and get the panic in the logs.

**ConfigConnector Version**

1.27.1

**To Reproduce**
*Steps to reproduce the behavior:*

*YAML snippets:*

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMCustomRole
metadata:
  name: myrole
spec:
  title: MYROLE
  description: Just some role
  permissions:
    - cloudkms.cryptoKeyVersions.useToDecrypt
    - cloudtrace.traces.patch
    - errorreporting.errorEvents.create
    - iam.serviceAccountKeys.get
    - iam.serviceAccounts.signJwt
    - pubsub.subscriptions.consume
    - pubsub.subscriptions.create
    - pubsub.subscriptions.get
    - pubsub.topics.attachSubscription
    - pubsub.topics.create
    - pubsub.topics.get
    - pubsub.topics.publish
    - spanner.instances.get
    - storage.buckets.get
    - storage.objects.create
    - storage.objects.delete
    - storage.objects.get
    - storage.objects.list
    - storage.objects.update
  stage: BETA
```
