### ISSUE TITLE
Is there a way to reference the values of resources created with kcc?

### ISSUE THREAD

**Issue by red8888** [GoogleCloudPlatform/k8s-config-connector#334]
This is specifically I'm working around:
https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing
![image](https://user-images.githubusercontent.com/6265399/101213445-6251b800-3648-11eb-88a7-ac5b7e87888a.png)

I want to create internal load balancers and attach a GCP reserved private IP address. This is frustratingly not possible (I don't know why gcp doesnt support this boooo), but what I can do is create a reserved private IP and assign the IP of that reserved IP to the load balancer via `loadBalancerIP` like this:

```
---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  annotations:
    cloud.google.com/load-balancer-type: Internal
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.123.123 # I can get this value from a reserved IP I previously created
  selector:
    app: myapp
  ports:
  - name: http
    port: 80
    targetPort: app
    protocol: TCP
```

I can create a reserved private IP with kcc, but can I reference the value of that IP in the same manifest like this?
```
---
  apiVersion: compute.cnrm.cloud.google.com/v1beta1
  kind: ComputeAddress
  metadata:
    name: myip
  spec:
    addressType: INTERNAL
    location: us-west2
    ipVersion: IPV4
    subnetworkRef:
      external: https://www.googleapis.com/compute/v1/projects/myproject/regions/us-west2/subnetworks/mynetwork

---
apiVersion: v1
kind: Service
metadata:
  name: myservice
  annotations:
    cloud.google.com/load-balancer-type: Internal
spec:
  type: LoadBalancer
  # Get the value of the "Address" field from the myip resource
  loadBalancerIP: myip.Spec.Address
  selector:
    app: myapp
  ports:
  - name: http
    port: 80
    targetPort: app
    protocol: TCP
```

Is something like this possible? I would be useful for many other resources as well if it is

**Comment by maqiuyujoyce** [comment]
Hi @red8888 , thank you for your question and sorry for the frustration you've been through. Unfortunately, references like `myip.Spec.Address` is not supported in Config Connector. Currently, an additional step is needed when you want to reference to a reserved IP address in other Kubernetes objects.

We've already received some other requests about exposing a generated IP address to a non Config Connector resource, e.g. issue #88 , and we are looking into potential options. Because the IP address is referenced outside of the scope of Config Connector, we'll need to use a different resource as the "bridge" for other Kubernetes resources to consume the IP address. One option would be that Config Connector creates a Kubernetes Service to expose the generated IP address. Does it sound like a working solution for you? (We might land on a different solution, but this is something we are considering.)

**Comment by red8888** [comment]
My specific issue with the resource is really that gcp doesnt support reserved IPs for internal LBs yet. If it did I could just add an annotation to the service like I can with the ingress to use a reserved IP.

But generally speaking maybe this is more a k8s limitation than anything else? Is referencing these sorts of properties between CRDs not supported natively? 

Frankly I'm too ignorant of the internals to know what the right solution is. The nicest user experience would be what I explained in my question (referencing the value of a field of a resource that k8s hasn't created yet)- perhaps that is just not possible. This is a common patter of IaC tools I have used like terraform, cloudformation, etc so thats why I natively asked if it was possible but seems like its not? For example in terraform I can create a new VPC and in the same config reference the ID of that VPC (whatever it is when its created) for configuring other resources.

**Comment by maqiuyujoyce** [comment]
Hi @red8888 , thank you for your questions and suggestions.

Referencing fields among resources is not natively supported in K8s, so Config Connector needs to design and implement the support of those scenarios from scratch. For example, the [resource reference](https://cloud.google.com/config-connector/docs/how-to/creating-resource-references) in Config Connector is supported via the `[field]Ref` fields.

Referencing the generated IP is another common request we've received and we are looking into how to better support it. Because of the limitation of K8s, we cannot make a K8s Service reference to a Config Connector resource, and the UX will likely be different from other IaC tools you've used. That's why we are proposing that we can have Config Connector create a Kubernetes Service to expose the generated IP address. Feel free to share your comments with us so that we know if our proposal works for you.

**Comment by tonybenchsci** [comment]
@maqiuyujoyce Would it be more scaleable (for all current and future resource types) to adopt something more generic like IBM/composable kinds? Or do you have optimism that KCC will roll out some mechanism to expose all auto-generated `spec`/`status` fields that may be needed as inputs to other resources?

**Comment by toumorokoshi** [comment]
Hey @tonybenchsci! overall we are looking at trying to find the right general abstractions to enable better composability.

Specifically with IP addresses, we're looking at potentially providing some intermediary object to expose the IP address to be referenced by others, such as [Endpoints or EndpointSlices](https://kubernetes.io/docs/concepts/services-networking/service/#services-without-selectors). Of course this would require the `Service` kind above to be able to consume an IP address by an `Endpoint`.

More generally we're investigating with partner tools such as [kpt](https://googlecontainertools.github.io/kpt/) to expose some way to do arbitrary references and populating of values client-side.

> Would it be more scaleable (for all current and future resource types) to adopt something more generic like IBM/composable kinds? 

Do you have links or an example? 

> Or do you have optimism that KCC will roll out some mechanism to expose all auto-generated spec/status fields that may be needed as inputs to other resources?

I don't think we'd ever go as far as exposing every spec and status field as some referencable resource. So we're working with other Kubernetes folks to figure out if there's a better pattern for the more general references that we need to construct to provide a good IaC experience via Kubernetes.

**Comment by bshihr** [comment]
@toumorokoshi have "primitives" like ConfigMaps and or Secrets been considered as an intermediary for composability?  This would seem natural fit for the application layer e.g. IAPIdentityAwareProxyClient status is usually consumed by injecting into a binary (via command-line args, env vars, etc).  However, it doesn't address composing between primitives (your example of a Service derived from some kind of KCC CRD).

**Comment by toumorokoshi** [comment]
> @toumorokoshi have "primitives" like ConfigMaps and or Secrets been considered as an intermediary for composability? This would seem natural fit for the application layer e.g. IAPIdentityAwareProxyClient status is usually consumed by injecting into a binary (via command-line args, env vars, etc). However, it doesn't address composing between primitives (your example of a Service derived from some kind of KCC CRD).

Definitely! I think for places where there are clear intermediary resources, we'll try to use them.

One area we're also thinking about is whether references need to be more generic: it may be difficult to play whack-a-mole by continuing to add these abstractions one by one, resource per resource. 

update on priority: we haven't been able to prioritize looking into this work, but we know this is a pretty big pain point and will probably start sketching some designs to scope the work in the next quarter or two.

**Comment by mhubig** [comment]
I came here looking for a way to get some metadata (mostly the ip address) from a KCC created Cloud SQL database into my workload. 

One possible way to get those kind of composability would be to combine ConfigMaps/Secrets with a way to specify outputs like it's done by terraform.

I would imagine an outputs API which could be used to instruct the KCC controller to create a ConfigMap containing the specified output variables. One could then use this config map to inject the output variables into a workload. One additional benefit of this solution would be a implicit dependency between the KCC resource and the workload.

```yaml
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: mysql-private-instance
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  settings:
    tier: db-f1-micro
    ipConfiguration:
      ipv4Enabled: true
      privateNetworkRef:
        name: mysql-private-network
  outputs:
    configmap: mysql-private-instance
    fields:
    - name: IP_ADDRESS
      value: this.ipv4_address
```
