### ISSUE TITLE
Enhancement: Way to lookup and reference service accounts with project numbers in their name

### ISSUE THREAD

**Issue by karlkfi** [GoogleCloudPlatform/k8s-config-connector#340]
In order to use GKE on a Shared VPC, you must configure GCP role bindings (IAMPolicyMember) against GCP service accounts that are created by GCP automatically. These GSAs have the project number in their name. 

In order to avoid needing to template or interpolate these resources, KCC should provide a way to look up the service accounts and reference them in IAMPolicyMembers.

Examples:

```
# Grant GKE in the "platform-project" (123456789012) project permission to use the Shared VPC
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: gke-platform-project-network-user
  namespace: projects
  annotations:
    cnrm.cloud.google.com/project-id: admin-project
spec:
  member: "serviceAccount:service-123456789012@container-engine-robot.iam.gserviceaccount.com"
  role: roles/compute.networkUser
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: network-project

---

# Grant "Google APIs Service Agent" in the "platform-project" (123456789012) project permission to use the Shared VPC
# https://cloud.google.com/iam/docs/service-accounts#google-managed
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: gcp-platform-project-network-user
  namespace: projects
  annotations:
    cnrm.cloud.google.com/project-id: admin-project
spec:
  member: "serviceAccount:123456789012@cloudservices.gserviceaccount.com"
  role: roles/compute.networkUser
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: network-project

--- 

# Grant GKE in the "platform-project" (123456789012) project permission to act as the "Google APIs Service Agent"
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: gke-platform-project-service-agent-user
  namespace: projects
  annotations:
    cnrm.cloud.google.com/project-id: admin-project
spec:
  member: "serviceAccount:service-123456789012@container-engine-robot.iam.gserviceaccount.com"
  role: roles/container.hostServiceAgentUser
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: network-project
```

**Comment by caieo** [comment]
Hi @karlkfi, thank you for this suggestion. In the future, we definitely want to support referencing service accounts by name. However, for your request in particular, I can't think of a great way to look up service accounts based on project numbers without including some amount of templating/assumptions about the SA name. Can you provide some more information on the urgency of this enhancement request?

**Comment by karlkfi** [comment]
The service accounts that use project number are almost always generated by GCP services. The two listed, for example, are from gke and cloudservices. It would be nice to be able to lookup the service account being used by a GCP service and reference it that way, but I don't know if there's an API for that yet.

**Comment by karlkfi** [comment]
I've now found some other use cases where I would like to avoid interpolating the service account email. One idea would be to have a `memberRef` in IAMPolicyMember that allows referencing IAMServiceAccount resources. 

Then we would just need a way to get a service account from a serviceusage Service, so we can use it as a memberRef. This could be done with a `serviceRef` in the IAMServiceAccount spec. The complication is it couldn't be managed by KCC. It would just a reference, like a Terraform data resource.

Another option would be to put a `memberServiceRef` in the IAMPolicyMember and do the lookup all in the controller.

**Comment by karlkfi** [comment]
I think the info we need is in here: `gcloud services list  --format json`

**Comment by karlkfi** [comment]
```
$ gcloud services list  --format json | jq -r '.[] | select(.name == "projects/685587273718/services/container.googleapis.com") | .serviceAccounts[].email'
service-685587273718@container-engine-robot.iam.gserviceaccount.com
```

**Comment by yashsaini77** [comment]
Hi @karlkfi, do you know if we can delete the automatically created default compute service account somehow with kcc

**Comment by caieo** [comment]
Hi @karlkfi, thank you for brainstorming some suggestions for us! We will discuss your ideas and update this thread for further clarification and updates.

@yashsaini77, currently, we do not support acquiring generated service accounts (part of what Karl is asking for). Therefore, ConfigConnector cannot delete automatically created default Compute service accounts, which is what you were asking for in #341.

**Comment by lostick** [comment]
@caieo do you guys plan to support this in the future? I'm facing the same issue where I can't create a Project and add it to the SharedVPC in one go, as the Project Number is not stored anywhere.

If we could have a way to lookup generated service accounts such as `xxxxxxxxxxxxxx@cloudservices.gserviceaccount.com` or `service-xxxxxxxxxxxxxx@container-engine-robot.iam.gserviceaccount.com`) dynamically, it's be great.

**Comment by caieo** [comment]
@lostick, we have plans to support this in the future, but don't have a solidified timeline yet (looking like sometime in Q3). We'll update this thread with more details as we finalize them!

**Comment by DWSR** [comment]
Hi @caieo,

Any word on the status of this? I'm running into the same situation as @lostick where adding things to a Shared VPC is a two-step process, which isn't great.

An experience like this would be really nice:

```yaml
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  name: container.googleapis.com
  annotations:
    cnrm.cloud.google.com/project-id: my-cool-project
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  name: my-cool-project
# elided for brevity
---
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
name: my-cool-project
# elided for brevity
---
apiVersion: iam.cnrm.cloud.google.com/v1beta2
kind: IAMPolicyMember
metadata:
name: shared-vpc-container-grant
spec:
  memberFrom:
    serviceRef:
      name: container.googleapis.com
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: my-shared-vpc-project
```
