### ISSUE TITLE
Not able to assign custom service account in GKE

### ISSUE THREAD

**Issue by yashsaini77** [GoogleCloudPlatform/k8s-config-connector#342]
I am using this YAML file to create a GKE cluster with a custom node pool, secret and a service account and I want the newly created service account to be assigned to this cluster but it is not happening and it barely gives any error in logs and it just creates the cluster [with no node pool] and service account.

apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: $PROJECT_ID
  labels:
    label-one: "value-one"
  name: containernodepool-sample
spec:
  location: us-west1-c
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 3
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    tags:
      - tagone
      - tagtwo
    preemptible: false
    minCpuPlatform: "Intel Haswell"
    serviceAccountRef:
      name: kcc-demo
    oauthScopes:
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
    metadata:
      disable-legacy-endpoints: "true"
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: containernodepool-dep

---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
    cnrm.cloud.google.com/project-id:  $PROJECT_ID
  name: containernodepool-dep
spec:
  location: us-west1-c
  initialNodeCount: 2
  networkRef:
    name: computeinstance-dep-cloudmachine
  subnetworkRef:
    name: computeinstance-dep-cloudmachine 
  masterAuth:
    username: "user"
    password:
      valueFrom:
        secretKeyRef:
          name: containernodepool-dep
          key: password
    clientCertificateConfig:
      issueClientCertificate: false
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: dev-kcc
  name: containernodepool-dep
stringData:
  password: password12345678
---

apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: $PROJECT_ID
  name: kcc-demo

**Comment by caieo** [comment]
Hi @yashsaini77, thanks for reporting this. Just to get a better understanding of what is working and what isn't, were you able to create the cluster, service account, and secret without issue? 

I can't tell from the formatting of your YAML text, but for the ContainerNodePool, you need to make sure the `serviceAccountRef` is in the same block as the `nodeConfig` because the field is technically `nodeConfig.serviceAccountRef`. 
```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  labels:
    label-one: "value-one"
  name: containernodepool-sample
spec:
  location: us-east1-c
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 3
  nodeConfig:
    diskSizeGb: 100
    diskType: pd-standard
    tags:
      - tagone
      - tagtwo
    preemptible: false
    minCpuPlatform: "Intel Haswell"
    oauthScopes:
      - "https://www.googleapis.com/auth/logging.write"
      - "https://www.googleapis.com/auth/monitoring"
    guestAccelerator:
      - type: "nvidia-tesla-k80"
        count: 1
    metadata:
      disable-legacy-endpoints: "true"
    serviceAccountRef:
      name: kcc-demo
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: containernodepool-dep
```
I followed your posted YAMLs (and only omitted the ContainerCluster's `spec.networkRef` & `spec.subnetworkRef` fields), which worked for me.

If your ContainerNodePool is the main problem, can you run a `kubectl describe containernodepools.container.cnrm.cloud.google.com containernodepool-sample` and copy what you see from there? And for a sanity check, please confirm that your ContainerCluster is created & UpToDate (you can also run a `kubectl describe` on it).
