### ISSUE TITLE
Unable to create `CertificateManagerDNSAuthorization` if resource has KRM-style label

### ISSUE THREAD

**Issue by andyyaldoo** [GoogleCloudPlatform/k8s-config-connector#3457]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Unable to create/update `CertificateManagerDNSAuthorization` if the resource contains KRM style label (prefixed with `/`). Status:
```
Status:
  Conditions:
    Last Transition Time:  2025-01-07T04:57:35Z
    Message:               Update call failed: error creating: creating DnsAuthorization projects/test-project/locations/global/dnsAuthorizations/auth-com: googleapi: Error 400: resource labels are invalid: key "app.kubernetes.io/managed-by" contains invalid character '.' at index 2
    Reason:                UpdateFailed
    Status:                False
    Type:                  Ready
  Observed Generation:     1
```

I tried creating another resource (pubsub topic) with same labels, and I was able to successfully create it.
I suspect this is a bug specific to CertificateManagerAPI. According to [this](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/607#:~:text=The%20current%20behavior%20is%20that%20labels%20in%20the%20metadata%20field%20of%20a%20Config%20Connector%20resource%20are%20also%20added%20to%20the%20associated%20Google%20Cloud%20resource%20except%20those%20in%20KRM%2Dstyle%20(labels%20that%20include%20a%20prefix%20denoted%20with%20a%20%27/%27)), KRM-style label should not be passed to any GCP API

### Additional Diagnostic Information

None

### Kubernetes Cluster Version

Client Version: v1.31.3 Kustomize Version: v5.4.2 Server Version: v1.30.6-gke.1125000

### Config Connector Version

1.126.0

### Config Connector Mode

namespaced mode (default)

### Log Output

```
Events:
  Type     Reason        Age                  From                                           Message
  ----     ------        ----                 ----                                           -------
  Warning  UpdateFailed  14s (x7 over 2m22s)  certificatemanagerdnsauthorization-controller  Update call failed: error creating: creating DnsAuthorization projects/test-project/locations/global/dnsAuthorizations/auth-com: googleapi: Error 400: resource labels are invalid: key "app.kubernetes.io/managed-by" contains invalid character '.' at index 2
```

### Steps to reproduce the issue

1. Create [Config Controller instance](https://cloud.google.com/kubernetes-engine/enterprise/config-controller/docs/manage-resources#create-instance)
2. Grant [permission](https://cloud.google.com/kubernetes-engine/enterprise/config-controller/docs/manage-resources#grant-permission)
3. Apply the yaml snippets below. The yaml snippet contain 3 resources. 1 CertificateManagerDNSAuthorization with `app.kubernetes.io/managed-by` label, 1 CertificateManagerDNSAuthorization without that label, and 1 pubsub topic with that label.

The pubsub topic will be created just fine but only one of the `CertificateManagerDNSAuthorization` will be created. The one that has `app.kubernetes.io/managed-by` label will have a status of `UpdateFailed`

### YAML snippets

```YAML
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerDNSAuthorization
metadata:
  namespace: config-control
  name: auth-com
  labels:
    label-one: "value-one"
    app.kubernetes.io/managed-by: test
spec:
  domain: test.auth.dev
  projectRef:
    external: test-project
---
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerDNSAuthorization
metadata:
  namespace: config-control
  name: auth-1-com
  labels:
    label-one: "value-one"
spec:
  domain: test-1.auth.dev
  projectRef:
    external: test-project
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: test-project
  labels:
    label-one: "value-one"
    app.kubernetes.io/managed-by: test
  name: example-topic
  namespace: config-control
```

**Comment by procinger** [comment]
I encountered the same issue today.  When I deploy the following manifest with kubectl, everything works as expected
```
apiVersion: certificatemanager.cnrm.cloud.google.com/v1beta1
kind: CertificateManagerDNSAuthorization
metadata:
  name: example
spec:
  location: global
  domain: example.net
  projectRef:
    external: "<some-project-id>"
```
But as soon as I deploy the manifest via ArgoCD, I get the same error. The reason is, ArgoCD patches all resources with the label `argocd.argoproj.io/instance`.

If I change the tracking in ArgoCD from label to annotation, the resource is created as expected, which I will use as a workaround for now.

But it would still be nice if we could use KRM style labels.
