### ISSUE TITLE
Controller manager crashes when using the googleAPIsBundle parameter with a ComputeForwardingRule

### ISSUE THREAD

**Issue by rolandkool** [GoogleCloudPlatform/k8s-config-connector#3489]
### Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

With Config Connector version 1.125, the first version to support the `googleAPIsBundle` parameter on a `ComputeForwardingRule` resource, the controller manager crashes. 

### Additional Diagnostic Information

Error from the log:

> {"severity":"info","timestamp":"2025-01-14T15:07:28.088Z","msg":"Observed a panic in reconciler: assignment to entry in nil map","controller":"computeforwardingrule-controller","controllerGroup":"compute.cnrm.cloud.google.com","controllerKind":"ComputeForwardingRule","ComputeForwardingRule":{"name":"privategoogleapis","namespace":"somenamespace"},"namespace":"somenamespace","name":"privategoogleapis","reconcileID":"ba9486dc-2e69-47d8-9544-fcf9853ffbc3"}
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map

### Kubernetes Cluster Version

1.30

### Config Connector Version

1.125.0

### Config Connector Mode

cluster mode

### Log Output

See Additional Diagnostics

### Steps to reproduce the issue

Example resource:
```
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeForwardingRule
metadata:
  name: privategoogleapis
spec:
  ipAddress:
    addressRef:
      name: privategoogleapis
  location: global
  target:
    googleAPIsBundle: all-apis
```

### YAML snippets

```YAML
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeForwardingRule
metadata:
  name: privategoogleapis
spec:
  ipAddress:
    addressRef:
      name: privategoogleapis
  location: global
  target:
    googleAPIsBundle: all-apis
```

**Comment by gemmahou** [comment]
For Private Service Connect forwarding rules that forward traffic to Google APIs, a network must be provided. Additionally, the loadBalancingScheme field need to be explicitly set to `""`(empty string), to avoid the default value of "EXTERNAL". 
Here's my working configuration:
```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeForwardingRule
metadata:
  name: rule0219
spec:
  description: "A global forwarding rule"
  location: global
  target:
    # a supported Google APIs bundle (global-only)
    googleAPIsBundle: "all-apis"
  loadBalancingScheme: ""
  ipAddress:
    addressRef:
      name: default
  networkRef:
    name: default
```
I will add sample yaml and the field requirements to our doc.

**Comment by rolandkool** [comment]
Hi,

I've tried again with version 1.128 and added the `loadBalancingScheme` parameter as well with a value of `""`. The network setting was already set, just forgot to add to my example yaml in the description of this issue.

Unfortunately, the controller still crashes with the same error. Any progress on finding the cause of the panic?

**Comment by gemmahou** [comment]
Would you mind sharing the full yaml configuration so I can reproduce the panic? Having the complete configuration will make it easier for me to spot any missing configuration and locate the issue.

**Comment by rolandkool** [comment]
```
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  annotations:
    cnrm.cloud.google.com/reconcile-interval-in-seconds: "86400"
  name: mynetwork
spec:
  autoCreateSubnetworks: false
  routingMode: GLOBAL
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  annotations:
    cnrm.cloud.google.com/reconcile-interval-in-seconds: "86400"
  name: privategoogleapis
spec:
  address: a.b.c.d
  addressType: INTERNAL
  location: global
  networkRef:
    name: mynetwork
  purpose: PRIVATE_SERVICE_CONNECT
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeForwardingRule
metadata:
  annotations:
    cnrm.cloud.google.com/reconcile-interval-in-seconds: "86400"
  name: privategoogleapis
spec:
  ipAddress:
    addressRef:
      name: privategoogleapis
  loadBalancingScheme: ""
  location: global
  networkRef:
    name: mynetwork
    namespace: mynamespace
  target:
    googleAPIsBundle: all-apis
```
