### ISSUE TITLE
Support for Network Services endpoint config selectors

### ISSUE THREAD

**Issue by JamesDuncanNz** [GoogleCloudPlatform/k8s-config-connector#350]
Added support for [Network Services endpoint config selectors](https://cloud.google.com/sdk/gcloud/reference/alpha/network-services/endpoint-config-selectors)

**Comment by rk185151** [comment]
I am trying to create a GCLB and add the NEGs (container-native LB) to a BackendService (sample manifest below) - 

Here is a similar example in Google docs
https://cloud.google.com/kubernetes-engine/docs/how-to/standalone-neg#attaching_a_load_balancer_to_your_standalone_negs

Also, based on the config connector docs - ComputeBackendService can reference NetworkEndPointGroup. Documentation was not clear, but looking at the KCC samples it seems only ComputeNetworkEndpointGroup is supported - ComputeNetworkEndpointGroup is for InstanceGroup only.

I can add ServiceNetworkEndpointGroup to a GCLB via cloud console and gcloud cli. I would like to do the same from KCC manifest. Is this already available and maybe I missed it? If not, is there an ETA for this support in KCC.

```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendService
metadata:
  name: sample-bes
  annotations:
    cnrm.cloud.google.com/project-id: $PROJECT_ID
spec:
  description: emerald selling configuration backend service
  portName: http
  timeoutSec: 30
  healthChecks:
  - healthCheckRef:
      name: sample-svc-hc
      namespace: config-connector
  loadBalancingScheme: EXTERNAL
  location: us-east1
  protocol: HTTP
  connectionDrainingTimeoutSec: 300
  backend:
  - balancingMode: RATE
    capacityScaler: 1
    description: A network endpoint group serving this backend with all its available capacity, as calculated by number of simultaneous connections.
    maxRatePerEndpoint: 5
    group:
      networkEndpointGroupRef:
        name: pod-svc-neg
        namespace: my-services
```

**Comment by caieo** [comment]
@rk185151, thanks for chiming in with your friction point and giving us your scenario. Is the `ServiceNetworkEndpointGroup` resource you expect the same as the `NetworkServicesEndpointConfigSelector` @JamesDuncanNz requested? 

The `NetworkServicesEndpointConfigSelector` resource is estimated to be implemented by the end of May. We apologize for how long it has taken.

**Comment by rk185151** [comment]
@caieo, perhaps it is similar. As I have stated above, in my quest to setup external LB via config connector, creating BackEndService with reference to service NEGs did not work
```
    group:
      networkEndpointGroupRef:
        name: pod-svc-neg
        namespace: my-services
 ```
The error description states `Reason: DependencyNotFound` and `Message: reference ComputeNetworkEndpointGroup ... is not found` - Here I would like point to the type name in the Message for `ComputeNetworkEndpointGroup`. 

Based on the config connector docs for ComputeNetworkEndpointGroup - represents compute instance group instead of container-native load balancing using `ServiceNetworkEndpointGroup`. Via Cloud Console and gcloud cli I was able to add the NEGs to a backendservice - just not avaiable in config connector.

gcloud cli example 
```
gcloud compute backend-services add-backend my-bes --global \
   --network-endpoint-group pod-svc-neg \
   --network-endpoint-group-zone us-east1-b \
   --balancing-mode RATE --max-rate-per-endpoint 5
```
