### ISSUE TITLE
Container NodePool Metadata error

### ISSUE THREAD

**Issue by travisrandolph-bestbuy** [GoogleCloudPlatform/k8s-config-connector#351]
**Describe the bug**
I'm trying to set the nodeconfig metadata below. It looks like setting enable-oslogin isn't supported. Could we have it added so that we can set this metadata on our nodes?
```
Metadata:
  Block - Project - Ssh - Keys:  true
  Disable - Legacy - Endpoints:  true
  Enable - Oslogin:              true
```
Error:
```
Update call failed: error applying desired state: summary: error creating NodePool: googleapi: Error 400: Cluster.node_config.metadata.key cannot be the reserved key "enable-oslogin"., badRequest, detail: 
```

**ConfigConnector Version**
Run the following command to get the current ConfigConnector version
1.33.0

**To Reproduce**
Create a NodePool with enableoslogin eq true.

*YAML snippets:*
```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: {REDACTED}
spec:
  location: us-central1
  nodeLocations:
  - us-central1-a
  - us-central1-b
  - us-central1-c
  initialNodeCount: 1
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 10
  nodeConfig:
    serviceAccountRef:
      name: {REDACTED}
    imageType: COS
    machineType: n2-standard-2
    tags:
      - {REDACTED}
      - {REDACTED}
    preemptible: false
    oauthScopes:
      - https://www.googleapis.com/auth/gke-default
    metadata:
      disable-legacy-endpoints: "true"
      block-project-ssh-keys: "true"
      enable-oslogin: "true"
    shieldedInstanceConfig:
        enableSecureBoot: true
        enableIntegrityMonitoring: true
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: {REDACTED}
```
