### ISSUE TITLE
Error when trying to set a scope alias on NodePool

### ISSUE THREAD

**Issue by travisrandolph-bestbuy** [GoogleCloudPlatform/k8s-config-connector#353]
**Describe the bug**
I'm trying to add the alias 'gke-default' to a node pool. It's sending an error that the scope doesn't exist. Are scope alias' supported by KCC?

Error
```
Update call failed: error applying desired state: summary: error creating NodePool: googleapi: Error 400: Scope does not exist: gke-default., badRequest, detail: 
```
**ConfigConnector Version**
1.33.0

**To Reproduce**
Deploy a NodePool using the gke-default scope.

*YAML snippets:*
```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: {REDACTED}
spec:
  location: us-central1
  nodeLocations:
  - us-central1-a
  - us-central1-b
  - us-central1-c
  initialNodeCount: 1
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 10
  nodeConfig:
    serviceAccountRef:
      name: {REDACTED}
    imageType: COS
    machineType: n2-standard-2
    tags:
      - {REDACTED}
      - {REDACTED}
    preemptible: false
    oauthScopes:
      - gke-default
    metadata:
      disable-legacy-endpoints: "true"
      block-project-ssh-keys: "true"
    shieldedInstanceConfig:
        enableSecureBoot: true
        enableIntegrityMonitoring: true
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: {REDACTED}
```
