### ISSUE TITLE
CloudBuildTrigger has trouble updating after v1.33.0

### ISSUE THREAD

**Issue by tonybenchsci** [GoogleCloudPlatform/k8s-config-connector#357]
**Describe the bug**
Any changes to CloudBuildTrigger `spec.github` will return 
```
"Update call failed: error applying desired state: summary: Error updating
      Trigger \"projects/b6i-cicd/triggers/00d81165-513f-4c20-b722-f93e9823acac\":
      googleapi: Error 400: Invalid value at 'trigger.github' (oneof), oneof field
      'event' is already set. Cannot set 'push'\nDetails:\n[\n  {\n    \"@type\":
      \"type.googleapis.com/google.rpc.BadRequest\",\n    \"fieldViolations\": [\n
      \     {\n        \"description\": \"Invalid value at 'trigger.github' (oneof),
      oneof field 'event' is already set. Cannot set 'push'\",\n        \"field\":
      \"trigger.github\"\n      }\n    ]\n  }\n], detail: "
```

Behaviour suggests that KCC merges the mappings (key-value) rather than overwrite, and then complains that there are two 'event' defined.

**ConfigConnector Version**
1.33.0 (previously on 1.26.0)

**To Reproduce**
Create a CloudBuildTrigger, then change the YAML from, say triggering on push to on pull.

*YAML snippets:*

```yaml
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: frontend-e2e-tests
spec:
  description: End-to-end tests on frontend pull requests.
  disabled: true
  filename: frontend/cloudbuild_e2e_tests.yaml
  github:
    owner: <BLAH>
    name:  <BLAH>
    pullRequest:
      branch: .*
  includedFiles:
  # Defines the frontend.
  - "frontend/**"

```
