### ISSUE TITLE
`ContainerCluster` update failed with `googleapi: Error 501: Unimplemented.`

### ISSUE THREAD

**Issue by ushuz** [GoogleCloudPlatform/k8s-config-connector#3640]
### Describe your question

We are using Config Controller and `ContainerCluster` object to provision a new GKE cluster. The cluster has been successfully created, but `ContainerCluster` object is stuck in `UpdateFailed` state with a `501 Unimplemented` error:

```
Status:
  Conditions:
    Last Transition Time:  2025-02-07T15:32:07Z
    Message:               Update call failed: error applying desired state: summary: googleapi: Error 501: Unimplemented.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.RequestInfo",
    "requestId": "0x0000ffff"
  },
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "container.googleapis.com",
    "reason": "UNIMPLEMENTED"
  }
]
, notImplemented
    Reason:             UpdateFailed
    Status:             False
    Type:               Ready
```

No relevant error logs can be found in `container.googleapis.com` API's audit logs either.

**Comment by ShivaniKamathBelman** [comment]
Any updates on this? I am also receiving a similar error, using acm module but want to opt out since it is enterprise only

**Comment by ushuz** [comment]
Based on [Config Connector][1] and [Terraform][2] docs, the following fields do not accept `MODE_UNSPECIFIED` values, which are however part of the YAML export from GCP. After commenting them out, the `Error 501: Unimplemented` went away.
```
...
  protectConfig:
    workloadConfig:
      auditMode: MODE_UNSPECIFIED
    workloadVulnerabilityMode: WORKLOAD_VULNERABILITY_MODE_UNSPECIFIED
...
  securityPostureConfig:
    mode: MODE_UNSPECIFIED
    vulnerabilityMode: VULNERABILITY_MODE_UNSPECIFIED
...
```

[1]: https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containercluster
[2]: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#nested_workload_identity_config
