### ISSUE TITLE
cnrm.cloud.google.com/project-id not applied to resources

### ISSUE THREAD

**Issue by dinvlad** [GoogleCloudPlatform/k8s-config-connector#368]
**Describe the bug**

According to the [doc](https://cloud.google.com/config-connector/docs/how-to/organizing-resources/project-scoped-resources), `cnrm` resources should be able to "pick up" `cnrm.cloud.google.com/project-id` annotation if it's defined on the namespace.

However, my resources are currently failing to be deployed with
```
      error building a minimal unstructured skeleton for the IAM resource:
      error building unstructured skeleton from referenced resource: couldn''t get
      resource id for resource reference: error getting import ID for referenced resource:
      no value found for annotation cnrm.cloud.google.com/project-id
```

**ConfigConnector Version**
`1.30.0`

**To Reproduce**
*Steps to reproduce the behavior:*

*YAML snippets:*

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: test
  annotations:
    cnrm.cloud.google.com/project-id: test-project
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: address
  namespace: test
spec:
  location: global
```

**Comment by dinvlad** [comment]
Weirdly, when I just deleted and re-deployed these namespaces, it worked. It appears as if there was some kind of race condition, and ComputeAddress did not "see" the namespace being created with the right annotation at first.

**Comment by caieo** [comment]
@dinvlad, sorry you ran into this. As you observed, your bug might be due a race condition where the namespace was not fully updated with the new annotation before creating the ComputeAddress.

**Comment by dinvlad** [comment]
Thanks! It would be great for the resource annotation updater to keep watching the namespace, to automatically update the resource annotation when namespace gets updated.

That being said, in my case the namespace was created _with_ the annotation, so I was expecting there wouldn't be a moment where its not yet "applied" to the namespace.

**Comment by spew** [comment]
Thanks @dinvlad if you run into this issue again or have more insight into the pattern that cause the issue can you please open up a new issue?

**Comment by scottd018** [comment]
Running into the same issue here with a `ContainerCluster` resource.  The namespace is created as follows **before** ever attempting to deploy a config connector resource (e.g. they are in separate manifests and there is a solid period of time before attempting the `ContainerCluster` deployment):

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/operator-version: 1.87.0
    cnrm.cloud.google.com/project-id: test-project
  labels:
    cnrm.cloud.google.com/operator-system: "true"
    kubernetes.io/metadata.name: google-system
  name: google-system
```

Creating the `ContainerCluster` results in the following error in `status.conditions`:

```
    conditions:
    - lastTransitionTime: "2022-06-09T12:13:41Z"
      message: 'Update call failed: error fetching live state: error getting ID for
        resource: no value found for annotation cnrm.cloud.google.com/project-id'
      reason: UpdateFailed
      status: "False"
      type: Ready
```

Deleting and re-deploying the resource allows it to create successful.  This happens intermittently and is not consistent.
