### ISSUE TITLE
CloudBuildTrigger: Error creating Trigger: googleapi: Error 409: trigger already exists

### ISSUE THREAD

**Issue by karlkfi** [GoogleCloudPlatform/k8s-config-connector#370]
When attempting to update a CloudBuildTrigger, by kubectl apply or edit to change a step, the apply succeeds but then KCC reverts the spec change and sets the condition as not-ready.

```
  status:
    conditions:
    - lastTransitionTime: "2021-01-20T01:27:09Z"
      message: 'Update call failed: error applying desired state: summary: Error creating
        Trigger: googleapi: Error 409: trigger (610865723911, source-repo-cicd-trigger)
        already exists, detail: '
      reason: UpdateFailed
      status: "False"
      type: Ready
```

**ConfigConnector Version**
1.31.1

**To Reproduce**
TODO (don't want to share my whole build pipeline)

**Comment by spew** [comment]
I am seeing this issue even when creating a new CloudBuildTrigger

**Comment by caieo** [comment]
@karlkfi, does this issue still occur for you? I tried to reproduce it on your version (1.31.1) and on the most recent version and was unable to. I tried reproducing it by creating & updating a build trigger using a template file and also using a SourceRepoRepository.

**Comment by karlkfi** [comment]
I had to abandon the CloudBuildTrigger and delete it, because the Cloud Build team complained it was causing KCC to spam their API. So I don't have a failing CloudBuildTrigger handy to test on.

I can maybe try to reproduce by deleting the current one and re-creating, but I'll lose all my history.

So I'll probably have to make another to try to repo.

**Comment by karlkfi** [comment]
I wanted to use the config-connector CLI to export the CloudBuildTrigger, but that's not working. There's no resource name format listed, so I can't do a single export, and bulk-export doesn't include it...

**Comment by karlkfi** [comment]
I pulled the original yaml out of my git history and applied it. Still getting the same errors:

```
  status:
    conditions:
    - lastTransitionTime: "2021-02-19T01:36:01Z"
      message: 'Update call failed: error applying desired state: summary: Error creating
        Trigger: googleapi: Error 409: trigger (610865723911, source-repo-cicd-trigger)
        already exists, detail: '
      reason: UpdateFailed
      status: "False"
      type: Ready
```

FWIW, KCC was also updated on this cluster a couple weeks ago:

```
$ acp-version.sh
ACP: 0.0.380
ConfigSync: v1.6.1-rc.4
Cork: v0.4.1
Gatekeeper: anthos1.4.0-25ca799.g1
KCC: 1.37.0
```

**Comment by caieo** [comment]
@karlkfi thanks for adding more info on what you had to do to workaround your issue and for giving this a try again. Just checking, before you applied the original configuration, was there already an existing CloudBuildTrigger? And was the resource toggling between "UpToDate"/"UpdateFailed" or "Updating"/"UpdateFailed"? 

>I wanted to use the config-connector CLI to export the CloudBuildTrigger, but that's not working. There's no resource name format listed, so I can't do a single export, and bulk-export doesn't include it...

Our CLI relies on the resource to be supported by Cloud Asset Inventory. Unfortunately, it looks like CloudBuildTrigger is not one of the supported resource types yet ([link](https://cloud.google.com/asset-inventory/docs/supported-asset-types))

**Comment by karlkfi** [comment]
> Just checking, were you trying to acquire and update an existing build trigger?

Yes.

> And was the resource toggling between "UpToDate"/"UpdateFailed" or "Updating"/"UpdateFailed"?

Don't remember now. Had to delete the resource. I think it was Updating/UpdateFailed, but I'm not 100% certain.

**Comment by karlkfi** [comment]
Confirmed: Updating -> UpdateFailed

**Comment by karlkfi** [comment]
I deleted the trigger in Cloud Console and now the CloudBuildTrigger error has changed to:

```
status:
  conditions:
  - lastTransitionTime: "2021-03-03T21:51:41Z"
    message: 'Update call failed: error applying desired state: summary: Error creating
      Trigger: googleapi: Error 403: The caller does not have permission, detail: '
    reason: UpdateFailed
    status: "False"
    type: Ready
```
