### ISSUE TITLE
Bigtable clusters are not labelled as managed by cnrm

### ISSUE THREAD

**Issue by fsommar** [GoogleCloudPlatform/k8s-config-connector#371]
**Describe the bug**
Bigtable clusters created via a managed Bigtable instance are not labelled as managed by cnrm.

**ConfigConnector Version**
1.34.0

**To Reproduce**
Create a `BigtableInstance` using e.g. the YAML snippet below. Verify that the instance itself has the label `managed-by-cnrm: true`:

```sh
# gcloud bigtable instances describe bigtable-sample
displayName: bigtable-sample
labels:
  cnrm-lease-expiration: '111111111'
  cnrm-lease-holder-id: abcdefgh01234
  managed-by-cnrm: 'true'
name: projects/[REDACTED]/instances/bigtable-sample
state: READY
type: PRODUCTION
```

Observe that the clusters created by the instance KRM do not have the label `managed-by-cnrm: true`:

```sh
# gcloud bigtable clusters describe us-central --instance=bigtable-sample
defaultStorageType: SSD
location: projects/[REDACTED]/locations/us-central1-a
name: projects/[REDACTED]/instances/bigtable-sample/clusters/us-central
serveNodes: 1
state: READY
```

As far as I understand, the cluster _is_ managed by cnrm, although it might be considered indirectly or implicitly so. Would it be possible to propagate the label to clusters from an instance? We first entertained the idea of assuming that any child resource of a managed resource is itself managed. That does not hold true for BigQuery datasets and tables, and probably doesn't generalize to more things either.

*YAML snippets:*

```yaml
apiVersion: bigtable.cnrm.cloud.google.com/v1beta1
kind: BigtableInstance
metadata:
  name: bigtable-sample
spec:
  cluster:
  - clusterId: us-central
    zone: us-central1-a
    numNodes: 1
```
