### ISSUE TITLE
ComputeSecurityPolicy: Missing Regional scope option

### ISSUE THREAD

**Issue by ap0phi5** [GoogleCloudPlatform/k8s-config-connector#3783]
### Checklist

- [x] I did not find a related open enhancement request.
- [x] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [x] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

There seems currently no way to scope a Cloud Armor policy to **regional** (from global) using KCC.

I believe Terraform have gone down the route of having a separate resource-type for Regional Security Policy, however there is no equivalent here.
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_region_security_policy

```
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: my-app-backend-policy
spec:
  default:
    securityPolicy: my-app-regional-policy
  targetRef:
    group: ""
    kind: Service
    name: my-app
```
