### ISSUE TITLE
Enabling cross-namespace resource refs, with minimal service account management

### ISSUE THREAD

**Issue by toumorokoshi** [GoogleCloudPlatform/k8s-config-connector#379]
Hello!

In namespace mode, Config Connector uses a different service account for every namespace that it manages. In that model, when there is a need to reference a resource in another namespace, the permissions to read resource from that namespace must also be granted to the corresponding KSA as well.

Is there a simple way to enable these cross-namespace reads? One cumbersome strategy is to enumerate all apiGroup / resource combinations into a ClusterRole, then attach the binding to the specific service account:

```
# project-viewer is needed for IAMMemberPolicy projectRef
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: project-viewer
rules:
- apiGroups:
  - resourcemanager.cnrm.cloud.google.com
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-viewer-networking
  namespace: projects
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: project-viewer
subjects:
- kind: ServiceAccount
  name: cnrm-controller-manager-networking
  namespace: cnrm-system
```

But I believe this would require:

- one ClusterRole per apiGroup that Config Connector owns (not to mention new ones added later)
- one RoleBinding per ClusterRole / namespace combination (since there's a separate KSA per namespace)

Is there a simple set that could be applied once, and scale to new versions of KCC and linear per namespace?
