### ISSUE TITLE
ContainerNodePool stuck in infinite update loop

### ISSUE THREAD

**Issue by cypres** [GoogleCloudPlatform/k8s-config-connector#3798]
### Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

On Feb 20th, GKE [added](https://cloud.google.com/kubernetes-engine/docs/release-notes#February_20_2025) a new automatic label `goog-gke-node-pool-provisioning-model`. This causes a constant diff to happen, something that has been [fixed](https://github.com/hashicorp/terraform-provider-google/pull/21082) in the terraform provider.

Unfortunately, even with `cnrm.cloud.google.com/state-into-spec: absent`, this causes container node pools created after Feb 20th to constantly be out-of-sync, and config connector keeps trying to reconcile it creating new operatines in an infinite loop.

To break the loop we can set it on the kubernetes resource as well
```
resourceLabels:
  goog-gke-node-pool-provisioning-model: on-demand
```

Would it be possible to get the terraform provider code in configconnector updated with the fix https://github.com/hashicorp/terraform-provider-google/pull/21082 ?

### Additional Diagnostic Information

None needed?

### Kubernetes Cluster Version

1.29

### Config Connector Version

1.128.0

### Config Connector Mode

cluster mode

### Log Output

{"error":"summary: googleapi: Error 400: Cluster is running incompatible operation operation-1740527253984-ea460d6c-64f0-44ac-a6aa-e88c23ca1433.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.RequestInfo",
    "requestId": "0x7e3eb49ee966916"
  },
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "container.googleapis.com",
    "reason": "CLUSTER_ALREADY_HAS_OPERATION"
  }
]
, failedPrecondition", "logger":"containernodepool-controller", "msg":"error applying desired state", "resource":{…}, "timestamp":"2025-02-26T00:25:35.148Z"}

### Steps to reproduce the issue

Create a node pool in a GKE cluster after Feb 20th 2025, filling out resourceLabels.

### YAML snippets

```YAML
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: absent
  name: my-nodepool
spec:
  nodeConfig:
    labels:
      service_name: my-service
    resourceLabels:
      service_name: my-service
```
