### ISSUE TITLE
Add support for Google Cloud SQL Query Insights

### ISSUE THREAD

**Issue by ve6yeq** [GoogleCloudPlatform/k8s-config-connector#385]
Recently, a new feature [Query Insights](https://cloud.google.com/sql/docs/postgres/insights-overview) was added to Google Cloud SQL for PostgreSQL. This is enabled with the following new keys on the SQLInstance resource:
```
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
settings:
    insightsConfig:
      queryInsightsEnabled: true
      queryStringLength: 1024
      recordApplicationTags: true
      recordClientAddress: true
```

 As there is strict checking of allowed keys, the following patch needs to be applied:
```
diff --git a/crds/sql_v1beta1_sqlinstance.yaml b/crds/sql_v1beta1_sqlinstance.yaml
index c20c085..24cc9c3 100644
--- a/crds/sql_v1beta1_sqlinstance.yaml
+++ b/crds/sql_v1beta1_sqlinstance.yaml
@@ -337,6 +337,21 @@ spec:
                     requireSsl:
                       type: boolean
                   type: object
+                insightsConfig:
+                  description: Query Insights helps you detect, diagnose, and prevent query performance problems.
+                  properties:
+                    queryInsightsEnabled:
+                      description: Enable Query Insights on this Instance.
+                      type: boolean
+                    queryStringLength:
+                      description: The query string length in bytes to be stored by the query insights feature. Default length is 1024 bytes. Allowed range: 256 to 4500 bytes.
+                      type: integer
+                    recordApplicationTags:
+                      description: Enable the storage of application tags.
+                      type: boolean
+                    recordClientAddress:
+                      description: Enable the storage client IP addresses.
+                      type: boolean
                 locationPreference:
                   properties:
                     followGaeApplication:
```
