### ISSUE TITLE
Unable to set StorageBucketAccessControl (HTTP 400)

### ISSUE THREAD

**Issue by jacek-jablonski** [GoogleCloudPlatform/k8s-config-connector#394]
Hi,

I am unable to set StorageBucketAccessControl using config connector. I am defining bucket like this:

```yaml
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: xxx-helm-charts
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
spec:
  storageClass: REGIONAL
  location: europe-west4
  bucketPolicyOnly: true
  versioning:
    enabled: false
---
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucketAccessControl
metadata:
  name: xxx-helm-charts-acl
spec:
  bucketRef:
    name: xxx-helm-charts
  entity: chartmuseum@xxx.iam.gserviceaccount.com
  role: WRITER
```

In logs I can see:

```
"Update call failed: error fetching live state: error reading underlying resource: summary: Error when reading or editing StorageBucketAccessControl "xxx-helm-charts/chartmuseum@xxx.iam.gserviceaccount.com": googleapi: Error 400: Invalid Value, invalid, detail: "
```

Is something wrong with my declarations?
