### ISSUE TITLE
Pod Security Policy

### ISSUE THREAD

**Issue by rhysxevans** [GoogleCloudPlatform/k8s-config-connector#396]
**Describe the bug**
When enabling the config connector (at least via the GUI) on a GKE cluster with pod security enabled, the service fails to start

**ConfigConnector Version**
Run the following command to get the current ConfigConnector version
```
kubectl get ns configconnector-operator-system -o yaml

apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/operator-version: 1.31.1
    components.gke.io/component-name: configconnector
    components.gke.io/component-version: 1.31.1
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{"cnrm.cloud.google.com/operator-version":"1.31.1","components.gke.io/component-name":"configconnector","components.gke.io/component-version":"1.31.1"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","cnrm.cloud.google.com/operator-system":"true"},"name":"configconnector-operator-system"}}

```

**To Reproduce**

1) Enable pod security policy on GKE cluster
2) Enable Config Connector
3) View status `kubectl describe statefulset.apps/configconnector-operator -n configconnector-operator-system`

```
 Warning  FailedCreate  2m12s (x64 over 12h)  statefulset-controller  create Pod configconnector-operator-0 in StatefulSet configconnector-operator failed error: pods "configconnector-operator-0" is forbidden: unable to validate against any pod security policy: []
```

Is it possible to add a "default" psp policy on deployment, or at least provide a psp policy that can be applied. Also the documentation needs to be updated to include the PSP requirements

Any thoughts/help/advice is appreciated

Thanks

**Comment by rhysxevans** [comment]
FYI - the below allows the pod to start, but is no means secure or recommended , and is me just hacking to get it working

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configconnector-operator-manager-role-psp
  labels:
  annotations:
    cnrm.cloud.google.com/operator-version: 1.31.1
    components.gke.io/component-name: configconnector
    components.gke.io/component-version: 1.31.1
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - configconnector-operator-manager-role-psp

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: configconnector-operator-system-psp
  annotations:
    cnrm.cloud.google.com/operator-version: 1.31.1
    components.gke.io/component-name: configconnector
    components.gke.io/component-version: 1.31.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: configconnector-operator-manager-role-psp
subjects:
- kind: ServiceAccount
  name: configconnector-operator
  namespace: configconnector-operator-system

---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: configconnector-operator-manager-role-psp
  labels:
  annotations:
    cnrm.cloud.google.com/operator-version: 1.31.1
    components.gke.io/component-name: configconnector
    components.gke.io/component-version: 1.31.1
spec:
  privileged: true
  allowPrivilegeEscalation: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
```
