### ISSUE TITLE
Give a documentation of the use case where the member can be a group

### ISSUE THREAD

**Issue by irvifa** [GoogleCloudPlatform/k8s-config-connector#397]
Give a documentation of the use case where the member can be a group as well, since the current deifinifion is only for [serviceAccount and user](https://cloud.google.com/config-connector/docs/how-to/securing-access-to-resources), example:

```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: policy-a
spec:
  member: group:<some-google-group>
  role: roles/container.developer
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: svc-account-a
```

Above manifest will give access from the group to the speficied service account.
