### ISSUE TITLE
ComputeSharedVPCServiceProject stuck Deleting if Project has been deleted

### ISSUE THREAD

**Issue by karlkfi** [GoogleCloudPlatform/k8s-config-connector#402]
I deleted a Project before deleting the ComputeSharedVPCServiceProject with a projectRef to the deleted project. Then I tried to delete the ComputeSharedVPCServiceProject, but now it's stuck in Deleting:

```
status:
  conditions:
  - lastTransitionTime: "2021-02-11T01:23:18Z"
    message: Deletion in progress
    reason: Deleting
    status: "False"
    type: Ready
```

KCC Version: 1.37.0

**To Reproduce**
1. Make a Project, Network, and ComputeSharedVPCHostProject
2. Make another Project and ComputeSharedVPCServiceProject
3. Delete the Project & wait for deletion
4. Delete the ComputeSharedVPCServiceProject & wait for deletion

```
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  name: ${SERVICE_PROJECT_ID}
  namespace: projects
  annotations:
    cnrm.cloud.google.com/auto-create-network: 'false'
    cnrm.cloud.google.com/folder-id: "${PARENT_FOLDER_ID}"
spec:
  name: ${SERVICE_PROJECT_ID}
  billingAccountRef:
    external: ${BILLING_ACCOUNT}
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSharedVPCServiceProject
metadata:
  name: ${SERVICE_PROJECT_ID}
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: ${HOST_PROJECT_ID}
spec:
  projectRef:
    name: ${SERVICE_PROJECT_ID}
    namespace: projects
```

This minimal reproduction isn't exactly how I got here, but I assume it will fail too. 

If it doesn't, there might be some additional complexity to this bug regarding having to abandon resources in a deleted namespace, due to #375. In my case, the Project was in a namespace being deleted and the ComputeSharedVPCServiceProject was in a different namespace. Both got deleted at the same time (give or take) by ConfigSync and may have triggered a race condition.
