### ISSUE TITLE
IAMPolicyMember UpdateFailed Error 400: Request contains an invalid argument.

### ISSUE THREAD

**Issue by karlkfi** [GoogleCloudPlatform/k8s-config-connector#404]
IAMPolicyMember update is failing for unknown reason:

```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: gcp-org-admins-platform-dev-exp-envb-8654-owner-permissions
  namespace: projects
  annotations:
    cnrm.cloud.google.com/project-id: environset2-envb
spec:
  member: group:platform-admins@example.com
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: platform-dev-exp-envb-8654
status:
  conditions:
  - lastTransitionTime: "2021-02-20T02:08:25Z"
    message: 'Update call failed: error setting policy member: error applying changes:
      summary: Request "Create IAM Members roles/owner group:platform-admins@example.com
      for \"project \\\"projects/platform-dev-exp-envb-8654\\\"\"" returned error:
      Error applying IAM policy for project "projects/platform-dev-exp-envb-8654":
      Error setting IAM policy for project "projects/platform-dev-exp-envb-8654":
      googleapi: Error 400: Request contains an invalid argument., badRequest, detail: '
    reason: UpdateFailed
    status: "False"
    type: Ready
```

KCC v1.37.0

I'm not sure why this one is failing and another similar one in another project is working. 

I've tried deleting it and having ConfigSync recreate it, but I still get the same error.

The similar one that works is:

```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: gcp-org-admins-platform-stg-exp-envb-3130-owner-permissions
  namespace: projects
  annotations:
    cnrm.cloud.google.com/project-id: environset2-envb
spec:
  member: group:gcp-org-admins@example.com
  role: roles/owner
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: platform-stg-exp-envb-3130
status:
  conditions:
  - lastTransitionTime: "2021-02-17T20:26:53Z"
    message: The resource is up to date
    reason: UpToDate
    status: "True"
    type: Ready
```

Possibly related this this issue: https://github.com/hashicorp/terraform-provider-google/issues/4276
