### ISSUE TITLE
retryPolicy.[maximum|minimum]Backoff doesn't accept documented fractional digits

### ISSUE THREAD

**Issue by daniellervik** [GoogleCloudPlatform/k8s-config-connector#409]
**Describe the bug**
The [pubsub_v1beta1_pubsubsubscription retryPolicy object](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/crds/pubsub_v1beta1_pubsubsubscription.yaml#L250-L261) describes `maximumBackoff` and `minimumBackoff` accepting fractional digits in the optional durations:
> A duration in seconds with up to nine fractional digits, terminated by 's'. Example: "3.5s".

They only seem to accept non-fractional durations, e.g. `"3s"`.

**ConfigConnector Version**
1.36.0

**To Reproduce**
1. Set PubSubSubscription's `spec.retryPolicy.minimumBackoff: "60.0s"`. Apply changes. Expected outcome: The subscription resource starts flickering between `Updating`/`UpToDate` indefinitely.
2. Changing to `spec.retryPolicy.minimumBackoff: "60s"` and applying works as expected and it settles as `UpToDate`.

*YAML snippets:*

1. With fractional digits, retries to apply indefinitely
```yaml
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: some-subscription
  namespace: some-namespace
spec:
  retryPolicy:
    minimumBackoff: 60.0s
  topicRef:
    name: some-subscribed-topic
```

2. Without fractional digits, works as expected
```yaml
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: some-subscription
  namespace: some-namespace
spec:
  retryPolicy:
    minimumBackoff: 60s
  topicRef:
    name: some-subscribed-topic
```

**Comment by toumorokoshi** [comment]
Thanks for the bug report! sorry you're having issues.

I can reproduce the case (here's a more complete example)

```
apiVersion: v1
kind: Namespace
metadata:
  name: gh-409
  annotations:
    "cnrm.cloud.google.com/project-id": <redacted>
---
  apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
  kind: PubSubSubscription
  metadata:
    namespace: gh-409
    labels:
      label-one: "value-one"
    name: pubsubsubscription-sample
  spec:
    ackDeadlineSeconds: 15
    messageRetentionDuration: 86400s
    retryPolicy:
      minimumBackoff: 60.1s
    retainAckedMessages: false
    topicRef:
      name: pubsubsubscription-dep
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: pubsubsubscription-dep
  namespace: gh-409
```

We're taking a look and will try to come back with an ETA to fix.
