### ISSUE TITLE
Exporting existing DNSRecordSet to YAML

### ISSUE THREAD

**Issue by denizdogan** [GoogleCloudPlatform/k8s-config-connector#417]
Is there any way to export an existing DNS record set using the config-connector CLI? I can't find the resource name format in [this link](https://cloud.google.com/asset-inventory/docs/resource-name-format).

**Comment by denizdogan** [comment]
Even with `bulk-export`, I just get the corresponding `DNSManagedZone`, no `DNSRecordSet`.

**Comment by denizdogan** [comment]
I am able to get some YAML output by using `gcloud` as such:

```console
$ gcloud dns record-sets export outputfile -z=zone-name --project my-project
```

This generates output like this:

```yaml
---
kind: dns#resourceRecordSet
name: my.domain.
rrdatas:
- ...
ttl: 21600
type: NS
---
kind: dns#resourceRecordSet
name: my.domain.
rrdatas:
- ...
ttl: 21600
type: SOA
---
...etc...
```

I could manually translate this into DNSRecordSet resources pretty easily, but it would still be good to know if there's something I'm missing in config-connector?
