### ISSUE TITLE
Mismatch between exported YAML and what's expected by kubectl

### ISSUE THREAD

**Issue by denizdogan** [GoogleCloudPlatform/k8s-config-connector#418]
After I exported a managed DNS zone, this is what config-connector produced:

```yaml
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  annotations:
    cnrm.cloud.google.com/force-destroy: "false"
    cnrm.cloud.google.com/project-id: my-project
  name: my-domain
spec:
  description: my.domain
  dnsName: my.domain.
  resourceID: "3151325756419757619"
  visibility: public
```

However, when I tried to diff it using kubectl, I got this error:

>Error from server: admission webhook "deny-unknown-fields.cnrm.cloud.google.com" denied the request: unknown field "spec.resourceID"

Looking at [the specification for the Config Connector DNSManagedZone YAML](https://cloud.google.com/config-connector/docs/reference/resource-docs/dns/dnsmanagedzone) it looks like `spec.resourceID` is a valid field, albeit immutable, but can be used for "acquisition", which I assume is what I'm doing.

What am I missing?
