### ISSUE TITLE
Empty updates to GCP during SQLInstance reconciliation

### ISSUE THREAD

**Issue by knp-sap** [GoogleCloudPlatform/k8s-config-connector#4207]
### Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Updating to Config Connector 1.129.2 causes empty updates to be sent to GCP during each reconciliation of `SQLInstance`, interfering with the daily scheduled backups and preventing them from being taken.

### Additional Diagnostic Information

With the update, all `SQLInstance` types are reconciled using the new direct controller (instead of the legacy Terraform-based controller).

### Kubernetes Cluster Version

v1.31.6

### Config Connector Version

1.129.2

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

Update Config Connector from `1.128.0` to `1.129.2` and then watch the operations of the SQL Instance in GCP.

### YAML snippets

```YAML
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/mutable-but-unreadable-fields: '{}'
    cnrm.cloud.google.com/observed-secret-versions: '{}'
    cnrm.cloud.google.com/project-id: "test"
    cnrm.cloud.google.com/state-into-spec: absent
  finalizers:
  - cnrm.cloud.google.com/finalizer
  - cnrm.cloud.google.com/deletion-defender
  name: test
  namespace: test
spec:
  databaseVersion: POSTGRES_13
  region: europe-west3
  resourceID: test
  settings:
    availabilityType: REGIONAL
    backupConfiguration:
      backupRetentionSettings:
        retainedBackups: 30
      enabled: true
      pointInTimeRecoveryEnabled: true
    databaseFlags:
    - name: temp_file_limit
      value: "3145728"
    deletionProtectionEnabled: true
    diskSize: 10
    insightsConfig:
      queryInsightsEnabled: true
    ipConfiguration:
      requireSsl: true
    tier: db-g1-small
```
