### ISSUE TITLE
SQLInstance constantly updating which breaks dependencies

### ISSUE THREAD

**Issue by b4nst** [GoogleCloudPlatform/k8s-config-connector#424]
## Checklist

- [ x ] I did not find a related open issue.
- [ x ] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ x ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

When deploying a SQLInstance, the resource is virtually never "Ready". I think it's related to #153 and KCC adding some lease label to the instance. This behavior breaks the dependency used on `SQLDatabase` and `SQLUser` resources. They fail to be deployed with `DependencyNotReady` status, which is totally correct since the SQLInstance target is never `Ready`.

### Kubernetes Cluster Version

v1.17.17-gke.2800

### Config Connector Mode

1.38.1

### YAML snippets

```yaml
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: SQLDatabase
metadata:
  name: db
spec:
  instanceRef:
    name: instance

---

apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/management-conflict-prevention-policy: resource
    cnrm.cloud.google.com/observed-secret-versions: '{}'
  name: instance
spec:
  databaseVersion: POSTGRES_11
  region: us-central1
  settings:
    activationPolicy: ALWAYS
    availabilityType: ZONAL
    backupConfiguration:
      enabled: true
      pointInTimeRecoveryEnabled: true
      startTime: "03:00"
    diskAutoresize: true
    diskType: PD_SSD
    tier: db-custom-2-7680
```

**Comment by b4nst** [comment]
Also setting `cnrm.cloud.google.com/management-conflict-prevention-policy: "none"` annotation on SQLInstance did not help.

Currently my workaround is referencing the instance with `external` but that's obviously not what I want to do.

**Comment by xiaobaitusi** [comment]
Hi @b4nst , thanks for reporting the issue.

I attempted to repro it using your provided yaml snippet with `cnrm.cloud.google.com/management-conflict-prevention-policy: "none"`.
```
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
  name: instance-424
spec:
  databaseVersion: POSTGRES_11
  region: us-central1
  settings:
    activationPolicy: ALWAYS
    availabilityType: ZONAL
    backupConfiguration:
      enabled: true
      pointInTimeRecoveryEnabled: true
      startTime: "03:00"
    diskAutoresize: true
    diskType: PD_SSD
    tier: db-custom-2-7680
```
I didn't encounter the observation that SQLInstance constantly updating.  From the log, I can see that the periodical reconciliation reports that the underlying resource is already up to date as expected.

```
{"severity":"info","logger":"sqlinstance-controller","msg":"starting reconcile","resource":{"namespace":"test","name":"instance-424"}}
{"severity":"info","logger":"sqlinstance-controller","msg":"underlying resource already up to date","resource":{"namespace":"test","name":"instance-424"}}
{"severity":"info","logger":"sqlinstance-controller","msg":"successfully finished reconcile","resource":{"namespace":"test","name":"instance-424"}}
``` 

Can you check the log for more debugging information? Is KCC the only actor managing your sql instance?
