### ISSUE TITLE
configconnector-operator constantly using >500m CPU

### ISSUE THREAD

**Issue by abaudoux** [GoogleCloudPlatform/k8s-config-connector#431]
## Checklist

- [x ] I did not find a related open issue.
- [x ] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

configconnector-operator is constantly using a lot of CPU (>500m).

### Kubernetes Cluster Version

Client Version: v1.19.7
Server Version: v1.18.12-gke.1210

### Config Connector Version

1.31.1

### Config Connector Mode

cluster

## Log Output

See attached logs of configconnector-operator:

[logs2.txt](https://github.com/GoogleCloudPlatform/k8s-config-connector/files/6169710/logs2.txt)

## Steps to Reproduce

Install config connector

### Steps to reproduce the issue
Just installed config connector

**Comment by toumorokoshi** [comment]
Hi! Sorry to hear you're having issues.

I tried to reproduce, and none of the operator installations I have (including a from-scratch one I brought up just now) have CPU beyond 150ms (see screenshot).

![2021-03-19-154945_1619x415_scrot](https://user-images.githubusercontent.com/391240/111849436-d730c100-88ca-11eb-96da-ed0f15c388d0.png)

Could you post a screenshot of what you're seeing in the Cloud UI?

In addition, have you published any `ConfigConnector` or `ConfigConnectorContext`resources? typically the operator reads those and does nothing unless there is a delta on those resources.

Regarding the logs, there's nothing that looks out of the ordinary.

**Comment by abaudoux** [comment]
Hi, 

Yes, I've published a `ConfigConnector` : I've followed some instructions to be able to create GCP resources from k8s, so I've applied the following config : 
```
# configconnector.yaml
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  # the name is restricted to ensure that there is only one
  # ConfigConnector resource installed in your cluster
  name: configconnector.core.cnrm.cloud.google.com
spec:
 mode: cluster
 googleServiceAccount: "<My GCP SA>@<My Project ID>.iam.gserviceaccount.com"
```

Here is a screenshot of what I'm seeing in the UI:

<img width="1405" alt="Screenshot 2021-03-20 at 20 26 02" src="https://user-images.githubusercontent.com/741343/111883430-88168900-89bb-11eb-84d5-8ed9fad663e4.png">

The hole in the graph is when I tried to uninstall-reinstall configConnector, without any improvement to the CPU usage
