### ISSUE TITLE
SQLInstance absent parameter ignored

### ISSUE THREAD

**Issue by dionborsboom** [GoogleCloudPlatform/k8s-config-connector#4349]
### Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

I'm not sure if this is a bug or intended behavior, but it broke our setup since v1.129.2 and is costing us a lot of money.

For resource `SQLInstance`, we purposefully omit the `activationPolicy` parameter from the spec, because we have jobs running that turn off CloudSQL instances after work hours. After upgrading config connector to v1.129.2, config connector starts the instance again immediately. I assume this is caused by the move to the direct reconciler. It is causing **a lot** of extra cost in our landscape.

We have set the `cnrm.cloud.google.com/state-into-spec: absent` annotation. Unless I misunderstand, this should prevent a diff if we don't include the `activationPolicy` spec in the `SQLInstance` manifest and prevent config connector from changing the `activationPolicy`, starting the instance again?

### Additional Diagnostic Information

-

### Kubernetes Cluster Version

v1.31.5-gke.1233000

### Config Connector Version

1.129.2

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

1. provision SQLInstance with below yaml
2. turn off instance via console
3. config connector starts the instance back up

### YAML snippets

```YAML
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: absent
  name: myinstance
  namespace: mynamespace
spec:
  databaseVersion: POSTGRES_15
  region: europe-west4
  resourceID: myinstance
  settings:
    availabilityType: ZONAL
    backupConfiguration:
      backupRetentionSettings:
        retainedBackups: 7
        retentionUnit: COUNT
      enabled: true
      pointInTimeRecoveryEnabled: false
      startTime: "00:00"
      transactionLogRetentionDays: 7
    databaseFlags:
    - name: autovacuum_work_mem
      value: "209715"
    - name: autovacuum_max_workers
      value: "3"
    - name: autovacuum_analyze_scale_factor
      value: "0.02"
    - name: autovacuum_vacuum_scale_factor
      value: "0.04"
    - name: autovacuum_vacuum_cost_limit
      value: "400"
    - name: pg_stat_statements.track_utility
      value: "off"
    - name: log_min_messages
      value: notice
    - name: cloudsql.iam_authentication
      value: "on"
    deletionProtectionEnabled: true
    diskAutoresize: true
    diskSize: 10
    diskType: PD_HDD
    insightsConfig:
      queryInsightsEnabled: true
      queryStringLength: 1024
      recordApplicationTags: true
      recordClientAddress: true
    ipConfiguration:
      enablePrivatePathForGoogleCloudServices: false
      ipv4Enabled: false
      privateNetworkRef:
        external: projects/myproject/global/networks/mynetwork
      requireSsl: true
      sslMode: TRUSTED_CLIENT_CERTIFICATE_REQUIRED
    maintenanceWindow:
      day: 7
      hour: 3
      updateTrack: stable
    tier: db-custom-1-4096
```
