### ISSUE TITLE
CloudIdentityGroup cannot adopt existing groups

### ISSUE THREAD

**Issue by rolandkool** [GoogleCloudPlatform/k8s-config-connector#4439]
### Checklist

- [x] I did not find a related open enhancement request.
- [x] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [x] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Hi,

The `CloudIdentityGroup` resource does not seem to be able to adopt an existing Google Group. Creating a new one works fine, but when creating a `CloudIdentityGroup` resource for a group that already exists, the following error is returned:

> [
  {
    "@type": "type.googleapis.com/google.rpc.ResourceInfo",
    "description": "Error(2018): Cannot create group 'adoptgroup@myorg.com' because it already exists.",
    "owner": "domain:cloudidentity.googleapis.com",
    "resourceType": "cloudidentity.googleapis.com/Group"
  }
]

Would be useful to have adoption support otherwise, if something happens with the Kubernetes resource, the group becomes unmanageable (recreation is not really an option)

**Comment by gemmahou** [comment]
Could you share the details of the existing group, and the configuration yaml file you used to acquire that group?

**Comment by rolandkool** [comment]
The yaml looked like this:
```
---
apiVersion: cloudidentity.cnrm.cloud.google.com/v1beta1
kind: CloudIdentityGroup
metadata:
  name: adopt-group
spec:
  displayName: adoptgroup
  groupKey:
    id: adoptgroup@myorg.com
  parent: customers/<custid>
  labels:
    cloudidentity.googleapis.com/groups.discussion_forum: ""
```

The group I tested with has already been removed, so can't provide those exact details. But typically, our groups look like this:
```
gcloud identity groups describe somegroup@myorg.com
additionalGroupKeys:
- id: somegroup@myorg.com
- id: somegroup@myorg.com.test-google-a.com
createTime: '2020-10-09T14:00:36.657149Z'
description: Some description of groups puprose
displayName: somegroup
groupKey:
  id: somegroup@myorg.com
labels:
  cloudidentity.googleapis.com/groups.discussion_forum: ''
name: groups/<random id>
parent: customers/<customer id>
updateTime: '2025-04-29T16:21:48.825808Z'
```

**Comment by gemmahou** [comment]
This resource is special because its unique identifier is server-generated. So to acquire the resource, you should provide an `resourceID` and its value should be the server-generated name of the group: `groups/<random id>`.

Could you try below yaml and lmk if it works?
```
apiVersion: cloudidentity.cnrm.cloud.google.com/v1beta1
kind: CloudIdentityGroup
metadata:
  name: adopt-group
spec:
  **resourceID: groups/<random id>**
  displayName: adoptgroup
  groupKey:
    id: adoptgroup@myorg.com
  parent: customers/<custid>
  labels:
    cloudidentity.googleapis.com/groups.discussion_forum: ""
```

A similar resource is [ComputeFirewallPolicy](https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computefirewallpolicy#spec), see the description of its `resourceID` field: `The service-generated name of the resource. Used for acquisition only. Leave unset to create a new resource.`

We should fix our documentation for CloudIdentityGroup.
