### ISSUE TITLE
SQLInstance keeps trying to update edition

### ISSUE THREAD

**Issue by dionborsboom** [GoogleCloudPlatform/k8s-config-connector#4460]
### Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

We add the `edition` parameter to all our `sqlinstances`. For about 50% of our instances, config connector keeps trying to update the edition parameter every reconcile since the direct reconciler has been released in 1.129.2. I inspected the CloudSQL Admin API and in some cases it seems like the CloudSQL API silenty drops the edition parameter. Config connector is healthy otherwise as it reports the condition to be `UpToDate`.

![Image](https://github.com/user-attachments/assets/b3bbdb6d-360c-42de-b41d-a99e2f0ceed1)

I'm not sure if this is a bug with config connector or with the CloudSQL Admin API, but the resulting behavior from config connector is causing operational issues. The update does cause an operation on the CloudSQL Admin API. This can block other operations like starting exports. If an instance was turned off with the `activationPolicy: NEVER` and then trying to start it again with `activationPolicy: ALWAYS` the instance does not start, because it can't update the edition parameter at the same time as activationPolicy. So we have to manually start the instance from the API first.

In the audit logs we see the following patch payload from config connector every reconcile:
```
{
  "project": "myproject",
  "instance": "myinstance",
  "body": {
    "settings": {
      "edition": "ENTERPRISE",
      "tier": "db-custom-4-4096"
    }
  },
  "@type": "type.googleapis.com/google.cloud.sql.v1beta4.SqlInstancesPatchRequest"
}
```

This is the result from the CloudSQL Admin API when I do a get request on the same instance after the update. Note the missing edition param:
```
{
  "kind": "sql#instance",
  "state": "RUNNABLE",
  "databaseVersion": "POSTGRES_15",
  "settings": {
    "authorizedGaeApplications": [],
    "tier": "db-custom-4-4096",
    "kind": "sql#settings",
    "userLabels": {
      "managed-by-cnrm": "true"
    },
    "availabilityType": "ZONAL",
    "pricingPlan": "PER_USE",
    "replicationType": "SYNCHRONOUS",
    "activationPolicy": "ALWAYS",
    "ipConfiguration": {
      "privateNetwork": "projects/myproject/global/networks/mynetwork",
      "authorizedNetworks": [],
      "sslMode": "TRUSTED_CLIENT_CERTIFICATE_REQUIRED",
      "ipv4Enabled": false,
      "requireSsl": true,
      "enablePrivatePathForGoogleCloudServices": false
    },
    "locationPreference": {
      "zone": "europe-west4-b",
      "kind": "sql#locationPreference"
    },
    "databaseFlags": [
      {
        "name": "random_page_cost",
        "value": "1"
      },
      {
        "name": "autovacuum_work_mem",
        "value": "209715"
      },
      {
        "name": "autovacuum_max_workers",
        "value": "4"
      },
      {
        "name": "autovacuum_analyze_scale_factor",
        "value": "0.02"
      },
      {
        "name": "autovacuum_vacuum_scale_factor",
        "value": "0.04"
      },
      {
        "name": "autovacuum_vacuum_cost_limit",
        "value": "400"
      },
      {
        "name": "pg_stat_statements.track_utility",
        "value": "off"
      },
      {
        "name": "cloudsql.enable_pgaudit",
        "value": "on"
      },
      {
        "name": "pgaudit.log_parameter",
        "value": "on"
      },
      {
        "name": "log_min_messages",
        "value": "notice"
      },
      {
        "name": "log_lock_waits",
        "value": "on"
      },
      {
        "name": "cloudsql.iam_authentication",
        "value": "on"
      }
    ],
    "dataDiskType": "PD_SSD",
    "maintenanceWindow": {
      "updateTrack": "stable",
      "kind": "sql#maintenanceWindow",
      "hour": 3,
      "day": 7
    },
    "backupConfiguration": {
      "startTime": "23:00",
      "kind": "sql#backupConfiguration",
      "backupRetentionSettings": {
        "retentionUnit": "COUNT",
        "retainedBackups": 7
      },
      "enabled": true,
      "replicationLogArchivingEnabled": false,
      "pointInTimeRecoveryEnabled": false,
      "transactionLogRetentionDays": 7,
      "transactionalLogStorageState": "TRANSACTIONAL_LOG_STORAGE_STATE_UNSPECIFIED"
    },
    "insightsConfig": {
      "queryInsightsEnabled": true,
      "recordClientAddress": true,
      "recordApplicationTags": true,
      "queryStringLength": 1024
    },
    "connectorEnforcement": "NOT_REQUIRED",
    "settingsVersion": "9273",
    "storageAutoResizeLimit": "0",
    "storageAutoResize": true,
    "dataDiskSizeGb": "2198",
    "deletionProtectionEnabled": true,
    "replicationLagMaxSeconds": 31536000,
    "enableGoogleMlIntegration": false
  },
  "etag": "",
  "ipAddresses": [
    {
      "type": "PRIVATE",
      "ipAddress": "redacted"
    }
  ],
  "serverCaCert": {
    "kind": "sql#sslCert",
    "certSerialNumber": "0",
    "cert": "redacted",
    "commonName": "C=US,O=Google\\, Inc,CN=Google Cloud SQL Server CA,dnQualifier=70cf0bb4-5529-4c35-b787-e5d8680f7ad3",
    "sha1Fingerprint": "redacted",
    "instance": "myinstance",
    "createTime": "2021-02-19T13:45:58.799Z",
    "expirationTime": "2031-02-17T13:46:58.799Z"
  },
  "instanceType": "CLOUD_SQL_INSTANCE",
  "project": "myproject",
  "serviceAccountEmailAddress": "redacted@gcp-sa-cloud-sql.iam.gserviceaccount.com",
  "backendType": "SECOND_GEN",
  "selfLink": "https://content-sqladmin.googleapis.com/v1/projects/myproject/instances/myinstance",
  "connectionName": "myproject:europe-west4:myinstance",
  "name": "myinstance",
  "region": "europe-west4",
  "gceZone": "europe-west4-b",
  "scheduledMaintenance": {
    "canReschedule": true,
    "startTime": "2025-05-04T03:00:00Z",
    "scheduleDeadlineTime": "2025-06-01T03:00:00Z"
  },
  "databaseInstalledVersion": "POSTGRES_15_10",
  "availableMaintenanceVersions": [
    "POSTGRES_15_12.R20250302.00_07"
  ],
  "maintenanceVersion": "POSTGRES_15_10.R20250112.01_03",
  "createTime": "2021-02-19T13:44:36.835Z",
  "sqlNetworkArchitecture": "OLD_NETWORK_ARCHITECTURE",
  "satisfiesPzi": false,
  "includeReplicasForMajorVersionUpgrade": false
}
```

In the console, it says the instance is on Enterprise edition:
![Image](https://github.com/user-attachments/assets/b5ae04ef-5103-4fc4-9d06-549c7ab71e49)

### Additional Diagnostic Information

-

### Kubernetes Cluster Version

v1.31.5-gke.1233000

### Config Connector Version

1.130.2

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

See yaml below

### YAML snippets

```YAML
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/mutable-but-unreadable-fields: '{"spec":{"settings":{"ipConfiguration":{"sslMode":"TRUSTED_CLIENT_CERTIFICATE_REQUIRED"}}}}'
    cnrm.cloud.google.com/observed-secret-versions: '{}'
    cnrm.cloud.google.com/project-id: myproject
    cnrm.cloud.google.com/state-into-spec: absent
  creationTimestamp: "2025-03-27T14:12:14Z"
  finalizers:
  - cnrm.cloud.google.com/finalizer
  - cnrm.cloud.google.com/deletion-defender
  generation: 3
  name: myinstance
  namespace: mynamespace
spec:
  databaseVersion: POSTGRES_15
  region: europe-west4
  resourceID: myinstance
  settings:
    availabilityType: ZONAL
    backupConfiguration:
      backupRetentionSettings:
        retainedBackups: 7
        retentionUnit: COUNT
      enabled: true
      pointInTimeRecoveryEnabled: false
      startTime: "23:00"
      transactionLogRetentionDays: 7
    databaseFlags:
    - name: random_page_cost
      value: "1"
    - name: autovacuum_work_mem
      value: "209715"
    - name: autovacuum_max_workers
      value: "4"
    - name: autovacuum_analyze_scale_factor
      value: "0.02"
    - name: autovacuum_vacuum_scale_factor
      value: "0.04"
    - name: autovacuum_vacuum_cost_limit
      value: "400"
    - name: pg_stat_statements.track_utility
      value: "off"
    - name: cloudsql.enable_pgaudit
      value: "on"
    - name: pgaudit.log_parameter
      value: "on"
    - name: log_min_messages
      value: notice
    - name: log_lock_waits
      value: "on"
    - name: cloudsql.iam_authentication
      value: "on"
    deletionProtectionEnabled: true
    diskAutoresize: true
    diskType: PD_SSD
    edition: ENTERPRISE
    insightsConfig:
      queryInsightsEnabled: true
      queryStringLength: 1024
      recordApplicationTags: true
      recordClientAddress: true
    ipConfiguration:
      enablePrivatePathForGoogleCloudServices: false
      ipv4Enabled: false
      privateNetworkRef:
        external: projects/myproject/global/networks/mynetwork
      requireSsl: true
      sslMode: TRUSTED_CLIENT_CERTIFICATE_REQUIRED
    maintenanceWindow:
      day: 7
      hour: 3
      updateTrack: stable
    tier: db-custom-4-4096
status:
  availableMaintenanceVersions:
  - POSTGRES_15_12.R20250302.00_10
  conditions:
  - lastTransitionTime: "2025-05-01T12:45:28Z"
    message: The resource is up to date
    reason: UpToDate
    status: "True"
    type: Ready
  connectionName: myproject:europe-west4:myinstance
  firstIpAddress: redacted
  instanceType: CLOUD_SQL_INSTANCE
  ipAddress:
  - ipAddress: redacted
    type: PRIVATE
  observedGeneration: 3
  privateIpAddress: redacted
  selfLink: https://sqladmin.googleapis.com/sql/v1beta4/projects/myproject/instances/myinstance
  serverCaCert:
    cert: |-
      redacted
    commonName: C=US,O=Google\, Inc,CN=Google Cloud SQL Server CA,dnQualifier=70cf0bb4-5529-4c35-b787-e5d8680f7ad3
    createTime: "2021-02-19T13:45:58.799Z"
    expirationTime: "2031-02-17T13:46:58.799Z"
    sha1Fingerprint: redacted
  serviceAccountEmailAddress: redacted@gcp-sa-cloud-sql.iam.gserviceaccount.com
```
