### ISSUE TITLE
Using Config Connector for referencing existing cloud resources

### ISSUE THREAD

**Issue by eyalzek** [GoogleCloudPlatform/k8s-config-connector#453]
**Describe the feature or resource**

Basically, I would like to create a resource that only fetches a reference to an existing resource (in terraform terms this would be a data source as opposed to resource), e.g:

```yaml
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: ${GCP_PROJECT}
  name: mysql-instance
```

and this will look for an existing resource (as it does now), but instead of creating it if it doesn't exist or updating it's spec, just keep a reference of it's status and possibly spec.

**Importance**

This feature would be a nice-to-have. One of the benefits of using config connector, is that in certain cases you get access to attributes of a the cloud resource you created and this saves you the trouble of "hardcoding" those values. An example would be creating a `SQLInstance` and using [composable](https://github.com/IBM/composable) to create an endpoint + svc to point to this instance. However, sometimes we prefer provisioning these resources with other tools (namely terraform) since it fits our use case and workflow much better. We can still create an endpoint and "hardcode" the IP of the instance (again, staying in the sql instance scenario), but it would have nice to get that benefit of referencing a resource without necessarily managing it with config connector. In terms of implementation, I can see this functionality being trigger by an annotation, for example `cnrm.cloud.google.com/management-policy: reference/manage` or something similar.
