### ISSUE TITLE
🐛 Bug Report: ComputeGlobalNetworkEndpoint Requires ip_address Even with INTERNET_FQDN_PORT NEG

### ISSUE THREAD

**Issue by marandalucas** [GoogleCloudPlatform/k8s-config-connector#4541]
### Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

When creating a ComputeGlobalNetworkEndpoint resource using Config Connector (KCC) and linking it to a ComputeGlobalNetworkEndpointGroup (NEG) of type INTERNET_FQDN_PORT, the resource fails to reconcile. Even though only a fqdn and port are provided (as expected for this NEG type), the controller throws an error indicating that ip_address is missing.

This appears to be a bug in the reconciliation logic, where the controller attempts to fetch a non-required field (ip_address) despite the endpoint being FQDN-based.

### Additional Diagnostic Information

Additional Diagnostic Information

- Config Connector version installed: v1.130.2
- CRDs used (ComputeGlobalNetworkEndpoint, ComputeGlobalNetworkEndpointGroup): synced to version v1.118.0 (latest available for these CRDs at the time)
- Kubernetes version: v1.29
- NEG type: INTERNET_FQDN_PORT
- NEG and endpoint are in the same namespace
- NEG becomes Ready, but the endpoint fails to reconcile
- Error shown in ComputeGlobalNetworkEndpoint.status.conditions:

`Update call failed: error fetching live state: error getting ID for resource: unable to resolve missing value: ip_address
`
 
- NEG remains with size: 0 after applying the manifest
- Manually attaching the endpoint using gcloud works fine:

```
gcloud compute network-endpoint-groups update example-neg \
  --add-endpoint="fqdn=google.com,port=443" \
  --global \
  --project=my-project
```

### Kubernetes Cluster Version

1.32.2

### Config Connector Version

1.130.2

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

1. Apply a ComputeGlobalNetworkEndpointGroup manifest:

```
apiVersion: compute.cnrm.cloud.google.com/v1alpha1
kind: ComputeGlobalNetworkEndpointGroup
metadata:
  name: example-neg
  namespace: example-ns
  annotations:
    cnrm.cloud.google.com/project-id: my-project
spec:
  defaultPort: 443
  networkEndpointType: INTERNET_FQDN_PORT
  projectRef:
    external: my-project

```

2. Apply a ComputeGlobalNetworkEndpoint manifest:

```
apiVersion: compute.cnrm.cloud.google.com/v1alpha1
kind: ComputeGlobalNetworkEndpoint
metadata:
  name: example-endpoint
  namespace: example-ns
  annotations:
    cnrm.cloud.google.com/project-id: my-project
spec:
  globalNetworkEndpointGroup: example-neg
  fqdn: "google.com"
  projectRef:
    external: my-project
```

3. Wait for reconciliation and observe that the endpoint is not marked as Ready.

5. Check status for the error:
`unable to resolve missing value: ip_address
`

Manually attach the endpoint using gcloud CLI:

```
gcloud compute network-endpoint-groups update example-neg \
  --add-endpoint="fqdn=google.com,port=443" \
  --global \
  --project=my-project

```

Confirm that the endpoint is successfully added and NEG.size is updated.

### YAML snippets

```YAML

```
