### ISSUE TITLE
 SQLUser cant be used with CLOUD_IAM_SERVICE_ACCOUNT?

### ISSUE THREAD

**Issue by red8888** [GoogleCloudPlatform/k8s-config-connector#459]
Trying to do this: 
```
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: my-sdfsdf323423@my-project.iam.gserviceaccount.com
spec:
  type: CLOUD_IAM_SERVICE_ACCOUNT
  instanceRef:
    external: myDB
```

Getting this error: 
`failed to create resource: SQLUser.sql.cnrm.cloud.google.com my-sdfsdf323423@my-project.iam.gserviceaccount.com" is invalid: metadata.name: Invalid value: "my-sdfsdf323423@my-project.iam.gserviceaccount.com": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

I need to specify the email name of the user right? How is this supposed to work?

[This is the gcloud command](https://cloud.google.com/sql/docs/postgres/create-manage-iam-users#creating-a-database-user): `gcloud sql users create EMAIL --instance=INSTANCE_NAME --type=cloud_iam_service_account`

Is this a bug or something?
