### ISSUE TITLE
ComputeInstance networkInterface immutable 

### ISSUE THREAD

**Issue by Atoms** [GoogleCloudPlatform/k8s-config-connector#461]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)

## Bug Description
When using config sync (https://cloud.google.com/kubernetes-engine/docs/add-on/config-sync/how-to/installing) and trying to create ComputeInstance with YAML:
```YAML
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  name: xxx
  namespace: xxx-namespace
spec:
  attachedDisk:
    - deviceName: xxx-data-disk
      mode: READ_WRITE
      sourceDiskRef:
        name: xxx-data-disk
  bootDisk:
    initializeParams:
      size: 20
      sourceImageRef:
        external: centos-cloud/centos-8
      type: pd-ssd
  hostname: xxx.domain.tld
  machineType: e2-medium
  networkInterface:
    - subnetworkRef:
        name: global
        namespace: xxx-namespace
  zone: europe-west3-a
``` 
Config Connector creates resource, and adds fields from API 
```
  networkInterface:
  - name: nic0
    networkIp: x.x.x.x
    networkRef:
      external: https://www.googleapis.com/compute/v1/projects/xxx-namespace/global/networks/xxx
    subnetworkProject: xxx-project
    subnetworkRef:
      name: global
      namespace: xxx-namespace
``` 

In config sync logs I get the error `This may indicate ACM is fighting with another controller over the resource.` Which means that Config Sync tries to push manifest which is in git for that ComputeInstance, once it's done, ConfigConnector sees that it's missing network interface and updates it from API. And let the fight begin. 

Tried to update manifest with API updated information (network interface) now my error is:
```YAML
status:
  conditions:
  - lastTransitionTime: "2021-04-27T12:52:08Z"
    message: 'Update call failed: cannot make changes to immutable field(s): [networkInterface.#]'
    reason: UpdateFailed
    status: "False"
    type: Ready
```
And this is happening even network interface nic0 is same as config connector expects 

### Kubernetes Cluster Version

```shell
$ kubectl version --short
Client Version: v1.19.7
Server Version: v1.19.9-gke.1400
```
### Config Connector Version
```shell
 $ kubectl get ns cnrm-system -o jsonpath='{.metadata.annotations.cnrm\.cloud\.google\.com/version}'
1.47.0
```
### Config Connector Mode
```shell
$ kubectl get ConfigConnector "configconnector.core.cnrm.cloud.google.com" -o=jsonpath="{@.spec.mode}"
cluster
```
## Log Output
```
{"severity":"error","logger":"controller-runtime.manager.controller.computeinstance-controller","msg":"Reconciler error","reconciler group":"compute.cnrm.cloud.google.com","reconciler kind":"ComputeInstance","name":"xxx","namespace":"xxx-namespace","error":"Update call failed: cannot make changes to immutable field(s): [networkInterface.#]"}
```

from config sync output:

```
W0505 03:47:58.710771       1 fight_logger.go:43] KNV2005: syncer excessively updating resource, approximately 6 times per minute. This may indicate ACM is fighting with another controller over the resource.

source: ComputeInstance/xxxx/xxx.yml
namespace: xxx-namespace
metadata.name: xxx
group: compute.cnrm.cloud.google.com
version: v1beta1
kind: ComputeInstance
```

## Steps to Reproduce

This issue reproduce needs config sync, which tries to apply manifest all the time.

**Comment by Atoms** [comment]
ok, found issue when created this issue :) networkInterface is list but elements where not configured properly, there should be one list item in my case:
```YAML
  networkInterface:
    - name: nic0
      networkRef:
        external: https://www.googleapis.com/compute/v1/projects/xxx/global/networks/xxx
      subnetworkProject: xxxx
      subnetworkRef:
        name: global
        namespace: xxx-namespace
```
not
```
  networkInterface:
    - name: nic0
      networkRef:
        external: https://www.googleapis.com/compute/v1/projects/xxx/global/networks/xxx
      subnetworkProject: xxx
    - subnetworkRef:
        name: global
        namespace: xxx-namespace
```
Issue was with copy/paste problem
