### ISSUE TITLE
Direct-reconciler  fails to  Essentialcontactscontact create resource with cannot resolve parent for contact

### ISSUE THREAD

**Issue by svwijk** [GoogleCloudPlatform/k8s-config-connector#4615]
### Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

When using the direct reconciler opt-in [1] for the essential contact resource, the controller fails to create essential contact resources when referencing a project as parent in spec.

Create a spec witout using the direct-controller optin works.

[1]: https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/docs/features/optin.md

### Additional Diagnostic Information

Spec:

```
apiVersion: essentialcontacts.cnrm.cloud.google.com/v1alpha1
kind: EssentialContactsContact
metadata:
  name: svanwijkmydomain
  namespace: sybren2sbx1
spec:
  email: svanwijk@mydomain.com
  languageTag: en
  notificationCategorySubscriptions:
  - ALL
  parent: projects/my-project-name-5c1
```
The controller creates the resource:

```
{"severity":"info","timestamp":"2025-05-22T12:50:07.511Z","logger":"essentialcontactscontact-controller","msg":"starting reconcile","resource":{"name":"svanwijkmydomain","namespace":"sybren2sbx1"}}
{"severity":"info","timestamp":"2025-05-22T12:50:07.542Z","logger":"essentialcontactscontact-controller","msg":"creating/updating underlying resource","resource":{"name":"svanwijkmydomain","namespace":"sybren2sbx1"}}
{"severity":"info","timestamp":"2025-05-22T12:50:08.149Z","logger":"essentialcontactscontact-controller","msg":"successfully finished reconcile","resource":{"name":"svanwijkmydomain","namespace":"sybren2sbx1"},"time to next reconciliation":"7m32.890301465s"}
{"severity":"info","timestamp":"2025-05-22T12:50:08.149Z","logger":"essentialcontactscontact-controller","msg":"starting reconcile","resource":{"name":"svanwijkmydomain","namespace":"sybren2sbx1"}}
{"severity":"info","timestamp":"2025-05-22T12:50:08.366Z","logger":"essentialcontactscontact-controller","msg":"underlying resource already up to date","resource":{"name":"svanwijkmydomain","namespace":"sybren2sbx1"}}
{"severity":"info","timestamp":"2025-05-22T12:50:08.390Z","logger":"essentialcontactscontact-controller","msg":"successfully finished reconcile","resource":{"name":"svanwijkmydomain","namespace":"sybren2sbx1"},"time to next reconciliation":"14m9.327700632s"}
```

When create the same resource with the direct controller annotation:

```
apiVersion: essentialcontacts.cnrm.cloud.google.com/v1alpha1
kind: EssentialContactsContact
metadata:
metadata:
  name: svanwijkmydomain
  namespace: sybren2sbx1
spec:
  email: svanwijk@mydomain.com
  languageTag: en
  notificationCategorySubscriptions:
  - ALL
  parent: projects/my-project-name-5c1
```

The controller failed to create the resource:

```
{"severity":"info","timestamp":"2025-05-22T12:51:56.261Z","msg":"Running reconcile","controller":"essentialcontactscontact-controller","controllerGroup":"essentialcontacts.cnrm.cloud.google.com","controllerKind":"EssentialContactsContact","EssentialContactsContact":{"name":"svanwijkmydomain","namespace":"sybren2sbx1"},"namespace":"sybren2sbx1","name":"svanwijkmydomain","reconcileID":"dd994283-232e-43db-9cbd-9b7f1a9b1e03","resource":{"name":"svanwijkmydomain","namespace":"sybren2sbx1"}}
{"severity":"error","timestamp":"2025-05-22T12:51:56.276Z","msg":"Reconciler error","controller":"essentialcontactscontact-controller","controllerGroup":"essentialcontacts.cnrm.cloud.google.com","controllerKind":"EssentialContactsContact","EssentialContactsContact":{"name":"svanwijkmydomain","namespace":"sybren2sbx1"},"namespace":"sybren2sbx1","name":"svanwijkmydomain","reconcileID":"dd994283-232e-43db-9cbd-9b7f1a9b1e03","error":"Update call failed: cannot resolve parent for contact"}

```

The resource shows:

```
status:
  conditions:
  - lastTransitionTime: "2025-05-22T12:51:56Z"
    message: 'Update call failed: cannot resolve parent for contact'
    reason: UpdateFailed
    status: "False"
    type: Ready
  observedGeneration: 1
```

### Kubernetes Cluster Version

v1.32.2-gke.118200

### Config Connector Version

1.131.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

Steps to reproduce, see above

### YAML snippets

```YAML

```
