### ISSUE TITLE
Add projectRef destination type to LoggingLogSink

### ISSUE THREAD

**Issue by rolandkool** [GoogleCloudPlatform/k8s-config-connector#4715]
### Checklist

- [x] I did not find a related open enhancement request.
- [x] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [x] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

According to the [Google documentation](https://cloud.google.com/logging/docs/routing/overview#:~:text=destinations%20are%20supported%3A-,Google%20Cloud%20project,-Select%20this%20destination) a logsink destination can be just a project.
The current `LoggingLogSink` resource does not support this destination, it only supports Topics, Buckets, Logbuckets and BQ datasets.

### Additional information

The feature could be supported like this:

```
spec:
  folderRef:
    name: myfolder
  destination:
    projectRef:
      external: logging.googleapis.com/projects/mylogproject
  filter: '....'
```
