### ISSUE TITLE
Automatically update the serial number in the SOA record

### ISSUE THREAD

**Issue by ryanbenchsci** [GoogleCloudPlatform/k8s-config-connector#503]
**Describe the feature or resource**
Currently, when the `DNSRecordSet`s in a `DNSManagedZone` are changed, the serial number in the SOA record is not automatically updated. Therefore, it must currently be manually updated to ensure the changes propagate to all parts of the internet.

While this currently doesn't happen in the GCP UI either, there is some precedent for doing this in `gcloud dns record-sets transaction start`: the initial transaction file contains an update to the serial number in the SOA record.

For example, for BenchSci's sandbox zone, after running `gcloud dns record-sets transaction start` on it,
```
cat transaction.yaml
```
outputs
```
---
additions:
- kind: dns#resourceRecordSet
  name: sandbox.benchsci.com.
  rrdatas:
  - ns-cloud-d1.googledomains.com. cloud-dns-hostmaster.google.com. 2 21600 3600 259200
    300
  ttl: 21600
  type: SOA
deletions:
- kind: dns#resourceRecordSet
  name: sandbox.benchsci.com.
  rrdatas:
  - ns-cloud-d1.googledomains.com. cloud-dns-hostmaster.google.com. 1 21600 3600 259200
    300
  ttl: 21600
  type: SOA
```

**Importance**
The current workaround here is to manually capture the SOA record in KCC and update it whenever a change is made in the `DNSRecordSet`s. Not having to do this would be nice to have.
