### ISSUE TITLE
Cannot reference to a ComputeSSLCertificate from a different project

### ISSUE THREAD

**Issue by maqiuyujoyce** [GoogleCloudPlatform/k8s-config-connector#505]
## Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

According to @snuggie12 in [this comment](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/107#issuecomment-876843046):

> One caveat trying to use a GKE managed cert is that AFAICT you can only use the project of the k8s cluster. If I'm wrong, I'd love to hear how to do it.

> Error when setting up the proxy:

>    message: 'Update call failed: error applying desired state: summary: Error creating
>      TargetHttpsProxy: googleapi: Error 400: Invalid value for field ''resource.sslCertificates[0]'':
>      ''projects/<my_project>/global/sslCertificates/<cert_name>''.
>      Cross project referencing is not allowed for this resource., invalid, detail: '

## Additional Diagnostic Information

I was able to produce the issue.

### Kubernetes Cluster Version

v1.19.9-gke.1900
### Config Connector Version

1.55.0
### Config Connector Mode

cluster
### Steps to reproduce the issue

Apply the following yaml snippet will cause the issue described above in ComputeTargetHTTPSProxy.

### YAML snippets

```yaml
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeTargetHTTPSProxy
metadata:
  name: computetargethttpsproxy
spec:
  description: "test description"
  urlMapRef:
    name: computeurlmap
  sslCertificates:
    - name: computesslcertificate
  quicOverride: DISABLE
  location: global
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeHealthCheck
metadata:
  name: computehealthcheck
spec:
  checkIntervalSec: 10
  httpHealthCheck:
    port: 80
  location: global
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendService
metadata:
  name: computebackendservice
spec:
  healthChecks:
    - healthCheckRef:
        name: computehealthcheck
  location: global
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeURLMap
metadata:
  name: computeurlmap
spec:
  defaultService:
    backendServiceRef:
      name: computebackendservice
  location: global
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSSLCertificate
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: [ANOTHER_PROJECT]
  name: computesslcertificate
spec:
  location: global
  certificate:
    valueFrom:
      secretKeyRef:
        name: [SECRET_NAME]
        key: [CERTIFICATE]
  privateKey:
    valueFrom:
      secretKeyRef:
        name: [SECRET_NAME]
        key: [PRIVATE_KEY]
```
