### ISSUE TITLE
ComputeDisk fails to be created/updated successfully due to "immutable field(s): [interface]"

### ISSUE THREAD

**Issue by dinvlad** [GoogleCloudPlatform/k8s-config-connector#521]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

`ComputeDisk` resources fail to be created/updated properly, due to `Update call failed: cannot make changes to immutable field(s): [interface]`.

### Kubernetes Cluster Version

```
Client Version: v1.21.2
Server Version: v1.20.8-gke.900
```

### Config Connector Version

`1.52.0`

### Config Connector Mode

`namespaced`

## Log Output

```
cnrm-controller-manager-xxx-0 manager {"severity":"error","logger":"controller-runtime.manager.controller.computedisk-controller","msg":"Reconciler error","reconciler group":"compute.cnrm.cloud.google.com","reconciler kind":"ComputeDisk","name":"<disk>","namespace":"<namespace>","error":"Update call failed: cannot make changes to immutable field(s): [interface]"}
```

### Steps to reproduce the issue

1. Apply a `ComputeDisk` template as below (either from scratch or for an existing resource)
2. Observe that the resource never becomes ready:
    ```
    kubectl wait --for condition=Ready ComputeDisk <disk> -n <namespace> --timeout 60s
    ```
3. Check the status of the resource:
    ```
    # kubectl get computedisk -n <namespace> <disk> -o jsonpath='{.status}'
    {"conditions":[{"lastTransitionTime":"2021-07-30T15:20:37Z","message":"Update call failed: cannot make changes to 
    immutable field(s): [interface]","reason":"UpdateFailed","status":"False","type":"Ready"}],"observedGeneration":1}
    ```

### YAML snippets

```yaml
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: <disk>
  namespace: <namespace>
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
spec:
  location: <region>
  replicaZones:
  - https://www.googleapis.com/compute/v1/projects/<project>/zones/<zone1>
  - https://www.googleapis.com/compute/v1/projects/<project>/zones/<zone2>
  resourcePolicies:
  - name: <snapshot-policy>
    namespace: <snapshot-policy-namespace>
  size: 200
```

**Comment by toumorokoshi** [comment]
Hello! Thanks for filing an issue, and noted about the internal issue as well.

I've attempted to repro the issue with KCC 1.52, and cannot reproduce the issue. I tried the following conditions:

- creating a new resource
- applying and matching an existing resource (several times deleting the manifest in between by abandoning the resource).

The only time I was able to get the immutable field error was by attempting to change the interface type, which returned an error for on apply (from a webhook validation) instead.

The error string you mentioned:

> cannot make changes to immutable field

Only occurs when an attempt to apply the state results in modifying an immutable field, and never occurs on a create call. If this is happening on a new resource, it implies that the initial creation of the resource worked, but a subsequent reconcile detected drift and is attempting to perform an immutable change on the resource.

A few questions that may help:

1. What is the state of the underlying resource when you run into that error? what is the type of interface? (I had a bit of trouble finding that in the UI, so I had to click on "equivalent REST API" to find the value).
2. What does `kubectl get -o yaml` on the resource return? Config Connector populates fields in the spec with the values that it read from the GCP API, so if the value was configured to a non-default, it should be reflected in the spec.

Also here is the spec that I used (project redacted).

```
apiVersion: v1
kind: Namespace
metadata:
  name: gh-521
  annotations:
    "cnrm.cloud.google.com/project-id": <project>
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeDisk
metadata:
  name: gh-521
  namespace: gh-521
  annotations:
      cnrm.cloud.google.com/deletion-policy: abandon
spec:
  projectRef:
    external: <project>
  location: us-central1
  replicaZones:
  - https://www.googleapis.com/compute/v1/projects/<project>/zones/us-central1-a
  - https://www.googleapis.com/compute/v1/projects/<project>/zones/us-central1-f
  resourcePolicies:
  - name: gh-521
    namespace: gh-521
  size: 200
  interface: SCSI
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeResourcePolicy
metadata:
  name: gh-521
  namespace: gh-521
  annotations:
    "cnrm.cloud.google.com/deletion-policy": abandon
    "cnrm.cloud.google.com/project-id": <project>
spec:
  region: us-central1
  snapshotSchedulePolicy:
    schedule:
      weeklySchedule:
        dayOfWeeks:
        - startTime: "08:00"
          day: MONDAY
        - startTime: "15:00"
          day: WEDNESDAY
        - startTime: "23:00"
          day: FRIDAY
    retentionPolicy:
      maxRetentionDays: 12
    snapshotProperties:
      storageLocations:
      - us
      guestFlush: false
      labels:
        autodeleted: "false"
        interval: "weekly"
```
