### ISSUE TITLE
How to get ipAddress of SQLInstance to be used for rrdatas in DNSRecordSet 

### ISSUE THREAD

**Issue by Nosmoht** [GoogleCloudPlatform/k8s-config-connector#528]
Hi all,

i', currently moving our code from Terraform to Helm Config Connector charts. In Terraform i can use the output of a module , like the `privateIPAddress` of a Cloud SQL Instance, as input for another module, like DNSRecordSet. 

How can i achieve the same with Config Connector?

Use Case:
- Create a Cloud SQL instance
- Use the privateIPAddress of Cloud SQL instance for DNSRecordSet or K8S endpoint

It would be great to have something like a general object reference like this in all objects available
```yaml
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: dnsrecordset-sample-a
spec:
  name: "www.example.com."
  type: "A"
  ttl: 300
  managedZoneRef:
    name: dnsrecordset-dep-a
  rrdatas:
    - refResource:
         apiVersion: sql.cnrm.cloud.google.com/v1beta1
         kind: SQLInstance
         name: my-sql-instance
         namespace: somewhere
         status: privateIpAddress
```

Thanks
