### ISSUE TITLE
Clearer Error Message when Attaching a Service Project without GCE API Enabled

### ISSUE THREAD

**Issue by tylerreidwaze** [GoogleCloudPlatform/k8s-config-connector#529]
## Checklist

- [ x] I did not find a related open issue.
- [ x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
 
## Bug Description

When attaching a project using `ComputeSharedVPCServiceProject`, I received the following error

```
  Warning  UpdateFailed  4s (x8 over 4m10s)  computesharedvpcserviceproject-controller  Update call failed: error applying desired state: summary: googleapi: Error 404: The resource 'projects/tylerreid-kpt-test6' was not found, notFound, detail:
```

The issue ended up being that the GCE API was not enabled.  This is pretty low priority, but I would hope to receive a clearer error message.  Can we add something to detect if the API is enabled before applying?

### Kubernetes Cluster Version

```
Client Version: v1.20.7
Server Version: v1.20.8-gke.900
```

### Config Connector Version
```
> kubectl get ns cnrm-system -o jsonpath='{.metadata.annotations.cnrm\.cloud\.google\.com/version}'
1.58.0%     
```

### Config Connector Mode

No output when I ran the command

## Log Output

```
Update call failed: error applying desired state: summary: googleapi: Error 404: The resource 'projects/tylerreid-kpt-test6' was not found, notFound, detail:
```

### Steps to reproduce the issue
Apply the below YAMLs

### YAML snippets
```
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/auto-create-network: "true"
  name: tylerreid-kpt-host-project2 # {"$kpt-set":"project-name"}
  namespace: config-control
spec:
  billingAccountRef:
    external: REDACTED
  folderRef:
    external: REDACTED
  name: tylerreid-kpt-host-project2 # {"$kpt-set":"project-name"}
  resourceID: tylerreid-kpt-host-project2 # {"$kpt-set":"project-name"}
-----
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSharedVPCHostProject
metadata: # kpt-merge: /computesharedvpcserviceproject-NEW_PROJECT_NAME
  annotations:
    cnrm.cloud.google.com/project-id: tylerreid-kpt-host-project2 # kpt-set: ${host-project}
  name: computesharedvpcserviceproject-tylerreid-kpt-host-project2 # kpt-set: computesharedvpcserviceproject-${project-name}
  namespace: config-control
------
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/auto-create-network: "true"
  name: tylerreid-kpt-test6 # {"$kpt-set":"project-name"}
  namespace: config-control
spec:
  billingAccountRef:
    external: REDACTED
  folderRef:
    external: REDACTED
  name: tylerreid-kpt-test6 # {"$kpt-set":"project-name"}
  resourceID: tylerreid-kpt-test6 # {"$kpt-set":"project-name"}
-------
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSharedVPCServiceProject
metadata: # kpt-merge: /computesharedvpcserviceproject-NEW_PROJECT_NAME
  annotations:
    cnrm.cloud.google.com/project-id: tylerreid-kpt-host-project2 # kpt-set: ${host-project}
  name: computesharedvpcserviceproject-tylerreid-kpt-test6 # kpt-set: computesharedvpcserviceproject-${project-name}
  namespace: config-control
spec:
  projectRef:
    name: tylerreid-kpt-test6 # kpt-set: ${project-name}
    namespace: config-control


```
