### ISSUE TITLE
reference DNSManagedZone asdasd is not ready

### ISSUE THREAD

**Issue by ni-ogrund** [GoogleCloudPlatform/k8s-config-connector#537]
Hi,

I need help understanding DNSManagedZone. It seems like it's updating itself every 10th minute. This leads to that my DNSRecordSet's sends out warnings:

```
reference DNSManagedZone asdasd is not ready
```

This makes my monitoring very noisy:

<img width="1166" alt="Screenshot 2021-08-24 at 09 50 49" src="https://user-images.githubusercontent.com/66365380/130578346-7c3baa81-94fb-4ac4-bb27-c9179606bad0.png">

Why is this happening?

Thank you for all the help!

**Comment by xiaobaitusi** [comment]
Hi @ni-ogrund,

Can you provide more information around DNSManagedZone updating itself? 

- Logs for one particular example resource will be helpful.  Here is a Cloud logging [query](https://cloud.google.com/config-connector/docs/troubleshooting) for your reference.
- Can you clarify if there are mutating requests to the underlying API?
- Can you check if your resources have [label leaser](https://cloud.google.com/config-connector/docs/concepts/managing-conflicts#modifying_conflict_prevention) on, turn if off to avoid the API calls for releasing the leases.

**Comment by travisrandolph-bestbuy** [comment]
@caieo We are also seeing this behavior. Is there any way to have the resource not update every ten minutes?

**Comment by ni-ogrund** [comment]
Sorry for not writing back.

This is the reply I got from our certified google support:
_"The message `creating/updating underlying resource` from `dnsmanagedzone-controller` contains a bad wording.
In fact, it might be syncing or creating or updating. In other words it's just a reconciliation loop iteration, as we know.
He agreed that it's bad, and will be improved on the Google side to provide clarity.

Different engineers, different code, different log messages, bad wording. Will be improved in the future.
The warning message shouldn't be worrying in this case."_

In the end I filtered out the affected messages with `LoggingLogExclusion` to reduce the noise.

**Comment by travisrandolph-bestbuy** [comment]
@ni-ogrund @caieo  We see the KCC resource going into an updating status, and then the Activity logs show that the DNSManagedZones are being updated. Is there a way to suppress the noise if nothing is actually changing?

**Comment by travisrandolph-bestbuy** [comment]
@caieo Here is an example of the DNS Managed Zone patch in the logs. I recently updated our configs to use upper case for 'VISIBILITY'. This didn't resolve the issue of the DNS Managed Zone trying to patch every ten minutes.

```
response: {
@type: "type.googleapis.com/cloud.dns.api.ManagedZonesPatchResponse"
managedZone: {
cloudLoggingConfig: {
}
creationTime: "2021-03-16T13:46:45.471Z"
description: "{{REDACTED}}"
dnsName: "cloudproxy.app."
fingerprint: "{{REDACTED}}"
id: "{{REDACTED}}"
labels: {
cnrm-lease-expiration: "1634310608"
cnrm-lease-holder-id: "{{REDACTED}}"
managed-by-cnrm: "true"
}
name: "private-cloudproxy-app"
nameServers: [
0: "ns-gcp-private.googledomains.com."
]
privateVisibilityConfig: {
networks: [
0: {
networkUrl: "https://www.googleapis.com/compute/v1/projects/{{REDACTED}}/global/networks/{{REDACTED}}"
}]}
rrsetCount: 4
visibility: "PRIVATE"
}
operation: {
id: "{{REDACTED}}"
startTime: "2022-01-24T18:10:29.201Z"
status: "DONE"
type: "UPDATE"
user: "{{REDACTED}}"
zoneContext: {
newValue: {
cloudLoggingConfig: {
}
creationTime: "2021-03-16T13:46:45.471Z"
description: "{{REDACTED}}"
dnsName: "cloudproxy.app."
fingerprint: "{{REDACTED}}"
id: "{{REDACTED}}"
labels: {
cnrm-lease-expiration: "1634310608"
cnrm-lease-holder-id: "{{REDACTED}}"
managed-by-cnrm: "true"
}
name: "private-cloudproxy-app"
nameServers: [
0: "ns-gcp-private.googledomains.com."
]
privateVisibilityConfig: {
networks: [
0: {
networkUrl: "https://www.googleapis.com/compute/v1/projects/{{REDACTED}}/global/networks/{{REDACTED}}"
}]}
rrsetCount: 4
visibility: "PRIVATE"
}
oldValue: {
cloudLoggingConfig: {
}
creationTime: "2021-03-16T13:46:45.471Z"
description: "Private zone for Google private access for the cloudproxy.app top level domain"
dnsName: "cloudproxy.app."
fingerprint: "25a2012ab907a0de0000017e8d433398"
id: "2711731208634999006"
labels: {
cnrm-lease-expiration: "1634310608"
cnrm-lease-holder-id: "c18bdf6uvgs6g7knafb0"
managed-by-cnrm: "true"
}
name: "private-cloudproxy-app"
nameServers: [
0: "ns-gcp-private.googledomains.com."
]
privateVisibilityConfig: {
networks: [
0: {
networkUrl: "https://www.googleapis.com/compute/v1/projects/{{REDACTED}}/global/networks/{{REDACTED}}"
}]}
rrsetCount: 4
visibility: "PRIVATE"
}}}}
serviceName: "dns.googleapis.com"
`

**Comment by caieo** [comment]
@travisrandolph-bestbuy, unfortunately, there's no way to reduce/stop the 10-minute reconcile events. However, the fact that the resource is going into an updating state indicates that something might actually be updating each time. 
* Can you check the DNSManagedZone before and after an update to see what/if anything updates? 
* (From Zeya's comment above) Can you check if your resources have [label leaser](https://cloud.google.com/config-connector/docs/concepts/managing-conflicts#modifying_conflict_prevention) on, turn if off to avoid the API calls for releasing the leases.
* Are you using any external tools to manage this resource? Historically, we've seen GitOps tools unintentionally causing diffs asa well for some resources.

**Comment by travisrandolph-bestbuy** [comment]
@caieo It looks like the DNSManagedZone has a fingerprint that is changing. We aren't using label leaser and aren't using any other tooling to manage the resource.

**Comment by jcanseco** [comment]
Hi @travisrandolph-bestbuy; taking a look at the issue now.

First: I notice from your screenshot that the resource has `cnrm-lease-*` labels. Can you please double check your KCC resource's state (i.e. _not_ the YAML file, but the output of `kubectl get -o yaml`) and verify that it does _not_ have annotation `cnrm.cloud.google.com/management-conflict-prevention-policy: resource`?

Second: Can you try [this troubleshooting guide](https://cloud.google.com/config-connector/docs/troubleshooting#resource_keeps_updating_every_5-15_mins)? You mentioned you upper-cased your `visibility` values -- this is indeed potentially one example of an unintended diff here. There may be others; we should compare the K8s resource state against the GCP resource state by getting the GCP resource state from the API directly. The guide explains how to do this.

Third: Can you share your resource YAML (i.e. the file) and the K8s resource state (i.e. the output of `kubectl get -o yaml`) so we can try to reproduce and try the above strategy on our end?

**Comment by jcanseco** [comment]
Aside: I don't believe the fingerprint has anything to do with the issue here since KCC does not interact with the fingerprint directly.

The fingerprint probably just changes every time the GCP resource is updated, so the fact that the fingerprint _is_ changing implies that KCC _is_ updating the resource -- we just don't know why at this point.

**Comment by travisrandolph-bestbuy** [comment]
@jcanseco Below is the DNSManagedZone output, management-conflict-prevention-policy is set to none. As for the visibility value we have change it to lower case to match. One thing I see is that the private visibility config doesn't match exactly because we are using internal resources. I've added the differences below as well. Thank you.
```
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
```
```
KCC
privateVisibilityConfig:
  networks:
  - networkRef:
      name: {{REDACTED}}

CLI output
privateVisibilityConfig:
  kind: dns#managedZonePrivateVisibilityConfig
  networks:
  - kind: dns#managedZonePrivateVisibilityConfigNetwork
    networkUrl: https://www.googleapis.com/compute/v1/projects/{{REDACTED}}/global/networks/{{REDACTED}}
```

**Comment by jcanseco** [comment]
Ok gotcha thank you -- can you share us your YAMLs then so we can try to reproduce the issue?

**Comment by travisrandolph-bestbuy** [comment]
Here you go.

```
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: private-source-developers-google-com
  namespace: {{REDACTED}}
spec:
  description: "Private zone for Google private access for the source.developers.google.com domain"
  dnsName: "source.developers.google.com."
  visibility: private
  privateVisibilityConfig:
    networks:
      - networkRef:
          name: {{REDACTED}}
```
