### ISSUE TITLE
Support for Google Compute Backend Bucket Signed URL Key

### ISSUE THREAD

**Issue by zsgilber** [GoogleCloudPlatform/k8s-config-connector#545]
**Describe the feature or resource**

We would like to be able to provision backend buckets that are restricted to signed URLs. Currently, a backend bucket provisioned via the `ComputeBackendBucket` resource will be exposed publicly. There is currently a terraform resource for this: https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_backend_bucket_signed_url_key

**Importance**

This not a blocker, but is a pain point. We have to manually add the signed url key whenever we want to add a new backend bucket that we don't want to expose publicly.

**Comment by maqiuyujoyce** [comment]
Hi @zsgilber , thank you for the request! We've added it to the list of resources we're looking into and will let you know when we have more information.

**Comment by maqiuyujoyce** [comment]
Hi @zsgilber , in your use case, do you want to manage the signed URL keys in the non-authoritative manner with a separate resource (i.e. like what Terraform does)?

**Comment by zsgilber** [comment]
Hi @maqiuyujoyce, as long as the key can be added to the bucket through `config-connector`, that would work for us. Our use case is to automate Cloud CDN backend bucket creation for buckets where we want to use a signed URL or cookie to restrict access.

**Comment by maqiuyujoyce** [comment]
Thanks for sharing your use case, @zsgilber ! Then I assume it also works for you if the list of signed URL keys (names and values) is maintained in the `ComputeBackendBucket` resource like below, right? To clarify, we haven't determined the UX for the signed URL key yet, but just want to collect some information.

```
  apiVersion: compute.cnrm.cloud.google.com/v1beta1
  kind: ComputeBackendBucket
  metadata:
    name: test
  spec:
    ...
    cdnPolicy:
      signedUrlKeys:
        - keyName: key-1
          keyValue: test-url-1
        - keyName: key-2
          keyValue: test-url-2
    ...
```

**Comment by zsgilber** [comment]
Yes that would definitely work for us! As far as I understand the keys don't have any use outside of the backend bucket or service they are attached to, so managing them with those resources makes sense to me.

**Comment by maqiuyujoyce** [comment]
Thanks for the confirmation, @zsgilber ! We'll take it into consideration when we look into this feature.

**Comment by ymmt2005** [comment]
Hello.

For us, it would be nice if we could specify the key value with the name of a Secret Manager secret.

**Comment by Rndmbash** [comment]
Hello,

Today we encountered lack of this feature as we started to utilize KCC in our deployments.
We like the proposition from above where it is managed within `ComputeBackendBucket` as adding a key is a method (`addSignedUrlKey`) on this API Resource (`backendBuckets`). To stay consistent with other objects that manage secrets, I'd suggest the following approach:
```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendBucket
metadata:
  name: test
spec:
  ...
  cdnPolicy:
    signedUrlKeys:
      - keyName: key-1
        valueFrom:
            secretKeyRef:
                key: string
                name: string
      - keyName: key-2
        valueFrom:
            secretKeyRef:
                key: string
                name: string
```
where `secretKeyRef.name` is a name of the k8s secret to extract a value from, `secretKeyRef.key` is a key that identifies the value to be extracted, and the value within k8s secret is a 128-bit, RFC 4648 Section 5 base64url encoded.

We are really looking forward to have this feature implemented to official support.
