### ISSUE TITLE
CloudSQL Private IP instance support (ServiceNetworkingConnection)

### ISSUE THREAD

**Issue by nrobert13** [GoogleCloudPlatform/k8s-config-connector#55]
would be nice to be able to customize the Instance, like:
- connectivity type ( Private/ Public IP)
- associated networking ( Private IP )
- authorized networks ( Public IP )

**Comment by AlexBulankou** [comment]
@nrobert13 , thanks for reporting ti! It will be possible once Config Connector supports ServiceNetworkingConnection resource, similar to Terraform's [google_service_networking_connection](https://www.terraform.io/docs/providers/google/r/service_networking_connection.html) . Then you should be able to configure private IP instance, [similar how you can do with TF](https://www.terraform.io/docs/providers/google/r/sql_database_instance.html#private-ip-instance).
Will that address your scenario?
Is not being able to configure private IP instance currently blocking for you?

**Comment by nrobert13** [comment]
Hi Alex,

we were able to create an SQL instance with both the Public/Private IP connectivity and configure associated networks, the only thing missing is the authorized networks.
Used this manifest:
```
---
apiVersion: sql.cnrm.cloud.google.com/v1alpha3
kind: SQLInstance
metadata:
  name: inst2912
  namespace: test
spec:
  databaseVersion: POSTGRES_9_6
  region: europe-west1
  settings:
    tier: db-f1-micro
    ipConfiguration:
      privateNetwork: "projects/test/global/networks/cluster-2-test-network"
      ipv4Enabled: true
```

not sure though if this is planned/expected behavior of the controller or just accidental, as the only thing what we specify is the `privateNetwork` and still the Public IP is getting configured on the resource.
