### ISSUE TITLE
How to Define a KMSRing?

### ISSUE THREAD

**Issue by PatrickChenSe** [GoogleCloudPlatform/k8s-config-connector#555]
We followed the example in the [doc](https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iampolicymember#kms_policy_member_with_condition) and tried to create KMSRing through YAML like below, but failed. 
```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: test-kmsring-iampartialpolicy
  namespace: test-project
spec:
  bindings:
    - members:
        - member: serviceAccount:testsa@test-project.iam.gserviceaccount.com
      role: roles/cloudkms.admin
  resourceRef:
    apiVersion: kms.cnrm.cloud.google.com/v1beta1
    kind: KMSKeyRing
    name: test
---
apiVersion: kms.cnrm.cloud.google.com/v1beta1
kind: KMSKeyRing
metadata:
  name: test
  namespace: test-project
spec:
  location: global
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: testsa
  namespace: test-project
```
The error message is:
```
googleapi: Error 403: Permission 'cloudkms.keyRings.get' denied on resource 'projects/zhec-test/locations/global/keyRings/test' (or it may not exist)
```

This succeeds after granting the SA `cloudkms.admin` role manually in the console. 

What's the right way to do this?
