### ISSUE TITLE
Actuating a ResourceManagerPolicy for a project seems to apply to the organization level

### ISSUE THREAD

**Issue by adamdoes** [GoogleCloudPlatform/k8s-config-connector#557]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [x] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

Actuating a `ResourceManagerPolicy` at the project level seems to apply it to the organization level.

### Kubernetes Cluster Version

Client Version: v1.19.4
Server Version: v1.20.9-gke.701

### Config Connector Version

1.61.0

### Config Connector Mode

`kubectl get ConfigConnector "configconnector.core.cnrm.cloud.google.com" -o=jsonpath="{@.spec.mode}"` produced no output.

## Log Output

Didn't see anything in relevant logs; happy to fetch anything requested.

### Steps to reproduce the issue

1. Disable the `uniformBucketLevelAccess` policy at the organization level via the Google Cloud Console (replace the query parameter in the URL): [https://console.cloud.google.com//iam-admin/orgpolicies/storage-uniformBucketLevelAccess?organizationId=YOUR_ORG_ID_HERE](//intentionallydisablingclicking)
1. Download the three files shown in the YAML snippets at the bottom of this issue.
1. Modify `setters.yaml`; change `$DEFAULT_PROJECT` to a project ID that you have access to.
1. Run these commands (EDIT (Mon 09/27/2021 - 02:47 PM): see [this comment](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/557#issuecomment-928318839) for the non-`kpt` version of these instructions):
```
kpt fn render
kpt live init
kpt live apply
```

At this point, if you go to the Google Cloud Console link from the first step, you'll see that `constraints/storage.uniformBucketLevelAccess` is enforced for the whole organization, not just for the project.

EDIT (Fri 09/24/2021 - 05:09 PM): there are some oddities here that I can't quite figure out. This bug repro'd when I had the project inherit its policy value from the organization. I then customized the project's policy to explicitly have an "Enforcement: off" rule, and now KCC will only enable the constraint on `kpt live destroy`, and then it's only on the organization, not on the project.

### YAML snippets

Note: `policy.yaml` below was modified from [these instructions](https://cloud.google.com/config-connector/docs/reference/resource-docs/resourcemanager/resourcemanagerpolicy#organization_policy_for_project).

```yaml
# Kptfile
apiVersion: kpt.dev/v1
kind: Kptfile
metadata:
  name: uniform-bucket-level-access
  annotations:
    blueprints.cloud.google.com/title: Enforce uniform bucket-level access
info:
  description: A blueprint to enforce the uniformBucketLevelAccess org policy at the project level
pipeline:
  mutators:
    - image: gcr.io/kpt-fn/apply-setters:v0.1
      configPath: setters.yaml




# policy.yaml
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: blueprints-project-bucket-policy # kpt-set: ${project-id}-${name}
spec:
  projectRef:
    name: blueprints-project # kpt-set: ${project-id}
  constraint: "constraints/storage.uniformBucketLevelAccess"
  booleanPolicy:
    enforced: true




# setters.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: setters
data:
  name: bucket-policy
  project-id: $DEFAULT_PROJECT
```

**Comment by toumorokoshi** [comment]
Hi @adamdoes! Thanks for the bug report.

To simplify things a bit: can you instead provide an example just using kubectl, and the final object yaml?

kpt is a tool to render configuration, so the most relevant part for Config Connector to troubleshoot is the final yaml.

In the meantime, I'll try setting a constraint at the project level and see what comes of it.

**Comment by adamdoes** [comment]
> can you instead provide an example just using kubectl, and the final object yaml?

Sure, and sorry about that! Here are the updated repro steps solely using `kubectl`:

1. Save this as `policy.yaml`:

```yaml
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: ResourceManagerPolicy
metadata:
  name: your-project-name-bucket-policy
spec:
  projectRef:
    name: your-project-name
  constraint: "constraints/storage.uniformBucketLevelAccess"
  booleanPolicy:
    enforced: true
```

2. Replace `your-project-name` with a project that you control.
3. Apply to your cluster: `kubectl apply -f ./policy.yaml`

In testing this now, I ensured that my organization had a starting policy state of "Customize" → "Enforcement" → "Off", and after doing `kubectl apply` followed by `kubectl delete`, the organization-level policy was enabled.

(I originally filed the bug because I witnessed this happening on _apply_, not _delete_, but that was several business hours ago and I can't seem to repro it happening on apply any longer)
