### ISSUE TITLE
SQLInstance with failoverTarget doesn't reconcile

### ISSUE THREAD

**Issue by robertomlsoares** [GoogleCloudPlatform/k8s-config-connector#560]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

I'm trying to define a `SQLInstance` as a read replica and target failover. When I set the field `spec.replicaConfiguration.failoverTarget` to `true`, I get the following error from the reconciler:

```
'Update call failed: error applying desired state: summary: Error, failed
      to create instance sqlinstance-sample-replica: googleapi: Error 400: The incoming
      request contained invalid data., invalidRequest, detail: '
```

Removing that field makes the object reconcile successfully.

### Kubernetes Cluster Version

Client Version: v1.21.3
Server Version: v1.20.9-gke.1001

### Config Connector Version

1.58.0

### Config Connector Mode

Manual installation.

### Steps to reproduce the issue

Apply the YAMLs below with `kubectl apply` on a specific namespace, wait a few minutes for Config Connector to try to reconcile them, and then `kubectl describe` the replica (`sqlinstance-sample-replica`) to see the error message.

### YAML snippets

```yaml
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: delete
  name: sqlinstance-sample-primary
spec:
  databaseVersion: POSTGRES_13
  region: europe-west1
  settings:
    tier: db-custom-1-3840
    availabilityType: REGIONAL
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: delete
  name: sqlinstance-sample-replica
spec:
  databaseVersion: POSTGRES_13
  masterInstanceRef:
    external: sqlinstance-sample-primary
  region: europe-west1
  replicaConfiguration:
    failoverTarget: true
  settings:
    tier: db-custom-1-3840
    availabilityType: ZONAL
```
