### ISSUE TITLE
Allow to use a kubernetes secret for Redis/ authString

### ISSUE THREAD

**Issue by gdamjan** [GoogleCloudPlatform/k8s-config-connector#562]
**Describe the feature or resource**

Currently the only way to specify the authentication string for a RedisInstance it to use the plain-text `authString` in the resource spec. Which means the "password" is:
* not reusable for other resources/pods/services
* is visible in plain-text to whoever has access to the resource data

**Importance**

It's a pain point to have the auth string available in plaintext in the RedisInstance  resource.

**Suggestion**

Implement `authStringFrom` field that can import the password from a secret like for ex `SqlUser`.

I guess one way it can look like would be:
```
  authStringFrom:
      secretKeyRef:
        name: redis-secret-1  # Name of the Secret object to extract a value from
        key: password   # Key that identifies the value to be extracted
```
