### ISSUE TITLE
Issue when trying to acquire GKE Cluster

### ISSUE THREAD

**Issue by travisrandolph-bestbuy** [GoogleCloudPlatform/k8s-config-connector#568]
## Bug Description

When trying to acquire a GKE cluster that has already been created I'm seeing the error below. I'm not specifying a node version, so I'm not sure why it's complaining about it.

```bash
Name:         {{REDACTED}}
Annotations:  cnrm.cloud.google.com/management-conflict-prevention-policy: none
              cnrm.cloud.google.com/project-id: {{REDACTED}}
              cnrm.cloud.google.com/remove-default-node-pool: true
              cnrm.cloud.google.com/state-into-spec: merge
API Version:  container.cnrm.cloud.google.com/v1beta1
Kind:         ContainerCluster
Metadata:
Spec:
  Addons Config:
    Http Load Balancing:
      Disabled:  false
  Database Encryption:
    Key Name:                   {{REDACTED}}
    State:                      ENCRYPTED
  Enable Binary Authorization:  true
  Enable Shielded Nodes:        true
  Initial Node Count:           1
  Ip Allocation Policy:
    clusterIpv4CidrBlock:          {{REDACTED}}
    Cluster Secondary Range Name:   {{REDACTED}}
    servicesIpv4CidrBlock:          {{REDACTED}}
    Services Secondary Range Name:  {{REDACTED}}
  Location:                         us-central1
  Master Authorized Networks Config:
    Cidr Blocks:
      Cidr Block:  {{REDACTED}}
  Network Ref:
    Name:  {{REDACTED}}
  Node Config:
    Image Type:    COS
    Machine Type:  n1-standard-8
    Metadata:
      Block - Project - Ssh - Keys:  true
      Disable - Legacy - Endpoints:  true
    Oauth Scopes:
      https://www.googleapis.com/auth/cloud-platform
    Shielded Instance Config:
      Enable Integrity Monitoring:  true
      Enable Secure Boot:           true
    Tags:
      {{REDACTED}}
  Node Locations:
    us-central1-b
    us-central1-c
  Notification Config:
    Pubsub:
      Enabled:  true
      Topic Ref:
        Name:  gke-notification
  Private Cluster Config:
    Enable Private Endpoint:  false
    Enable Private Nodes:     true
    masterIpv4CidrBlock:      {{REDACTED}}
  Release Channel:
    Channel:  stable
  Subnetwork Ref:
    Name:  {{REDACTED}}
  Vertical Pod Autoscaling:
    Enabled:  true
  Workload Identity Config:
    Identity Namespace:  {{REDACTED}}
Status:
  Conditions:
    Last Transition Time:  2021-11-01T15:10:03Z
    Message:               Update call failed: error calculating diff: 1 error occurred:
                           * node_version can only be specified if remove_default_node_pool is not true


    Reason:             UpdateFailed
    Status:             False
    Type:               Ready
  Observed Generation:  1
Events:
  Type     Reason        Age               From                         Message
  ----     ------        ----              ----                         -------
  Warning  UpdateFailed  8s (x3 over 11s)  containercluster-controller  Update call failed: error calculating diff: 1 error occurred:
           * node_version can only be specified if remove_default_node_pool is not true
```

### Kubernetes Cluster Version

Client Version: v1.19.2
Server Version: v1.20.10-gke.301

### Config Connector Version

1.60.0

### Config Connector Mode

namespaced

### YAML
```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
  name: {{REDACTED}}
spec:
  location: us-central1
  nodeLocations:
  - us-central1-b
  - us-central1-c
  initialNodeCount: 1
  releaseChannel:
      channel: stable
  notificationConfig:
    pubsub:
      enabled: true
      topicRef:
        name: gke-notification
  enableBinaryAuthorization: true
  verticalPodAutoscaling:
    enabled: true
  networkRef:
    name: {{REDACTED}}
  subnetworkRef:
    name: {{REDACTED}}
  addonsConfig:
    httpLoadBalancing:
      disabled: false
  masterAuthorizedNetworksConfig:
    cidrBlocks:
    - cidrBlock: {{REDACTED}}
  privateClusterConfig:
    enablePrivateEndpoint: false
    enablePrivateNodes: true
    masterIpv4CidrBlock: {{REDACTED}}
  ipAllocationPolicy:
    clusterIpv4CidrBlock: {{REDACTED}}
    clusterSecondaryRangeName: gke-pods
    servicesIpv4CidrBlock: {{REDACTED}}
    servicesSecondaryRangeName: gke-services
  databaseEncryption:
    state: ENCRYPTED
    keyName: {{REDACTED}}
  enableShieldedNodes: true
  workloadIdentityConfig:
    identityNamespace: {{REDACTED}}
  nodeConfig:
    imageType: COS
    metadata:
      disable-legacy-endpoints: "true"
      block-project-ssh-keys: "true"
    oauthScopes:
    - https://www.googleapis.com/auth/cloud-platform
    shieldedInstanceConfig:
      enableSecureBoot: true
      enableIntegrityMonitoring: true
    machineType: n1-standard-8
    tags:
    - {{REDACTED}}
```
