### ISSUE TITLE
ComputeFirewall constantly updating if spec.enableLogging is specified

### ISSUE THREAD

**Issue by jcanseco** [GoogleCloudPlatform/k8s-config-connector#570]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

`ComputeFirewall` resources constantly go into `Updating` if `spec.enableLogging` is specified (regardless if the value is `true` or `false`).

### Kubernetes Cluster Version

```
Client Version: v1.22.3
Server Version: v1.20.10-gke.1600
```
### Config Connector Version

1.60.0

### Config Connector Mode

cluster

### Steps to reproduce the issue

1. Apply the YAML below.
2. Notice how the resource updates every ~10 minutes.

### YAML snippets

```yaml
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewall
metadata:
  name: my-computefirewall
spec:
  allow:
    - protocol: tcp
      ports: ["80"]
  networkRef:
    external: projects/<project>/global/networks/default
  enableLogging: true
```
