### ISSUE TITLE
ContainerCluster: Update call failed: cannot make changes to immutable field(s) (Autopilot)

### ISSUE THREAD

**Issue by flunderpero** [GoogleCloudPlatform/k8s-config-connector#576]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

I create an Autopilot Cluster like this:
```
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: beta
spec:
  enableAutopilot: true
  location: europe-west1
  releaseChannel:
    channel: REGULAR
  minMasterVersion: 1.21.5-gke.1302

```

Everything is fine, but after a while, the resource moves to status `UpdateFailed` with the message: 
```Update call failed: cannot make changes to immutable field(s): [nodeConfig.0.Taint.0.Value nodeConfig.0.Taint.# nodeConfig.0.Taint.0.Effect nodeConfig.0.Taint.0.Key]```.

As you can see, I did not specify any taints. I use Spot-VMs and as a result, the nodes receive a taint during runtime. But that's nothing I could specify here because it relies purely on the actual pods/deployments running in the cluster.

I upgraded ConfigConnector to the latest version, but the problem still exists.

### Kubernetes Cluster Version

Client Version: v1.20.8-dispatcher
Server Version: v1.20.10-gke.1600

### Config Connector Version
1.67.0

### Config Connector Mode

cluster

## Steps to Reproduce

See above.
