### ISSUE TITLE
Ability to set up workload identity with the workload identity pool

### ISSUE THREAD

**Issue by jacek-jablonski** [GoogleCloudPlatform/k8s-config-connector#583]
Hi,
it seems it is currently not possible to set up workload identity with workload identity pool. I am trying to do it like that:

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: wip
  annotations:
    cnrm.cloud.google.com/project-id: xxx
spec:
  member: principalSet://iam.googleapis.com/projects/123/locations/global/workloadIdentityPools/github-actions-identity-pool/attribute.repository_owner/xxx
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: github-actions@xxx.iam.gserviceaccount.com
```

Unfortunately it doesn't validate, error shows:
```
spec.member in body should match '^(user|serviceAccount|group|domain|projectEditor|projectOwner|projectViewer):.+|allUsers|allAuthenticatedUsers$
```

Am I missing something, or this is not yet supported?
