### ISSUE TITLE
Should projectRef be a required field?

### ISSUE THREAD

**Issue by erikjoh** [GoogleCloudPlatform/k8s-config-connector#604]
I've noticed that several resources now require the `projectRef` field.

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/a4b666780e2507e9c94f9457ea65e1272c063961/crds/networkservices_v1beta1_networkservicesmesh.yaml#L128-L130

Whereas there are some resources that have but don't require the `projectRef` field.

https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/a4b666780e2507e9c94f9457ea65e1272c063961/crds/bigquery_v1beta1_bigquerydataset.yaml#L238-L239

Based on the discussion about `projectRef` in #349 , shouldn't the `projectRef` field be optional?
Since we have namespace level annotations for project I don't really see why it would be required in *all* cases.

For example now we *must* do:

```yaml
apiVersion: networkservices.cnrm.cloud.google.com/v1beta1
kind: NetworkServicesMesh
metadata:
  name: mesh
  namespace: <project> # namespace that is annotated 'cnrm.cloud.google.com/project-id: <project>'
spec:
  location: global
  projectRef:
    external: projects/<project>
```

to not get a validation error (`spec.projectRef: Required value`).

Instead it would be nice to just have to do:

```yaml
apiVersion: networkservices.cnrm.cloud.google.com/v1beta1
kind: NetworkServicesMesh
metadata:
  name: mesh
  namespace: <project> # namespace that is annotated 'cnrm.cloud.google.com/project-id: <project>'
spec:
  location: global
```

And let the field default based on the namespace annotation.
