### ISSUE TITLE
Failure in creating cloudbuild trigger with pubsub config

### ISSUE THREAD

**Issue by avinash-getmega** [GoogleCloudPlatform/k8s-config-connector#605]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)

## Bug Description

I'm creating a cloud build trigger which uses pubsub topic for triggering. When I apply the cloudbuild config, it prints the following error
`Update call failed: error applying desired state: summary: Error creating Trigger: googleapi: Error 400: Invalid resource name given (name=sample-cloudbuild-shceduler). Refer to https://cloud.google.com/pubsub/docs/admin#resource_names for more information.`

Though the pub sub topic with same name is already create. Adding 

### Kubernetes Cluster Version

Client Version: v1.21.3
Server Version: v1.21.5-gke.1302

### Config Connector Version

1.63.0

### Config Connector Mode

namespaced

## Steps to Reproduce

apply the following yamls

### YAML snippets

```
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  name: sample-cloudbuild-shceduler
spec:
  description: sample-cloudbuild-shceduler
  disabled: true
  filename: build_file.yaml
  ignoredFiles:
  - '**/*.md'
  includedFiles:
  - src/**
  pubsubConfig:
    topicRef:
      name: sample-cloudbuild-shceduler
  substitutions:
    _SERVICE_NAME: service-name
```

```
apiVersion: cloudscheduler.cnrm.cloud.google.com/v1beta1
kind: CloudSchedulerJob
metadata:
  name: sample-cloudbuild-shceduler
spec:
  description: sample-cloudbuild-shceduler
  location: asia-south1
  pubsubTarget:
    data: dGVzdCBtZXNzYWdlCg==
    topicRef:
      name: sample-cloudbuild-shceduler
  schedule: 30 01 * * *
  timeZone: Asia/Kolkata
```

```
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: sample-cloudbuild-shceduler
```
