### ISSUE TITLE
Cluster gets stuck in UpdateFailed when GKE Dataplane V2 is enabled

### ISSUE THREAD

**Issue by jetersen** [GoogleCloudPlatform/k8s-config-connector#616]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

After cluster creation with the following yaml below. ConfigConnector is trying to update the object after the cluster has successfully deployed and seems to throw the same condition I experienced when `networkPolicy` was enabled and trying to enable Dataplane V2.

### Kubernetes Cluster Version

v1.22.4-gke.1501

### Config Connector Version

1.67.0

### Config Connector Mode

cluster

## Log Output

```yaml
status:
  conditions:
    - lastTransitionTime: '2022-02-24T22:49:22Z'
      message: >-
        Update call failed: error applying desired state: summary: googleapi:
        Error 400: Enabling NetworkPolicy for clusters with
        DatapathProvider=ADVANCED_DATAPATH is not allowed., badRequest
      reason: UpdateFailed
      status: 'False'
      type: Ready
```

Making it impossible to spin up ContainerNodePools:
```yaml
  conditions:
    - lastTransitionTime: '2022-02-24T22:35:52Z'
      message: >-
        reference ContainerCluster gcp-resources/worker1 is not
        ready
      reason: DependencyNotReady
      status: 'False'
      type: Ready
```

### Steps to reproduce the issue

- replace project-id accordingly
- apply yaml and see the config connector gets into a race condition

```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: worker1
  annotations:
    cnrm.cloud.google.com/project-id: company-project-id
    cnrm.cloud.google.com/remove-default-node-pool: "true"
  labels:
    availability: high
    target-audience: production
spec:
  description: A large regional VPC-native cluster set up with special networking considerations.
  location: europe-west4
  initialNodeCount: 1
  defaultMaxPodsPerNode: 16
  nodeLocations:
    - europe-west4-a
    - europe-west4-b
    - europe-west4-c
  workloadIdentityConfig:
    workloadPool: company-project-id.svc.id.goog
  networkingMode: VPC_NATIVE
  networkRef:
    name: worker1-network
  subnetworkRef:
    name: worker1-network
  ipAllocationPolicy:
    servicesSecondaryRangeName: servicesrange
    clusterSecondaryRangeName: clusterrange
  clusterAutoscaling:
    enabled: true
    autoscalingProfile: BALANCED
    resourceLimits:
    - resourceType: cpu
      maximum: 100
      minimum: 10
    - resourceType: memory
      maximum: 1000
      minimum: 100
  maintenancePolicy:
    dailyMaintenanceWindow:
      startTime: 00:00
  releaseChannel:
    channel: STABLE
  notificationConfig:
    pubsub:
      enabled: true
      topicRef:
        name: cluster-notifications
  enableBinaryAuthorization: false
  enableIntranodeVisibility: true
  enableShieldedNodes: true
  enableL4IlbSubsetting: true
  authenticatorGroupsConfig:
    securityGroup: gke-security-groups@company.com
  datapathProvider: ADVANCED_DATAPATH # Dataplane v2
  addonsConfig:
    networkPolicyConfig:
      disabled: false
    dnsCacheConfig:
      enabled: true
    configConnectorConfig:
      enabled: true
    gcePersistentDiskCsiDriverConfig:
      enabled: true
  networkPolicy:
    enabled: false # using Dataplane v2 which provides network policy
  podSecurityPolicyConfig:
    enabled: true
  verticalPodAutoscaling:
    enabled: false
  loggingConfig:
    enableComponents:
      - "SYSTEM_COMPONENTS"
      - "WORKLOADS"
  monitoringConfig:
    enableComponents:
      - "SYSTEM_COMPONENTS"
      - "WORKLOADS"
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: preemptible-pool1
  annotations:
    cnrm.cloud.google.com/project-id: company-project-id
spec:
  location: europe-west4
  autoscaling:
    minNodeCount: 0
    maxNodeCount: 3
  nodeConfig:
    machineType: n2d-standard-2
    diskSizeGb: 100
    diskType: pd-balanced
    imageType: COS_CONTAINERD
    preemptible: true
    oauthScopes:
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
      - https://www.googleapis.com/auth/devstorage.read_only
      - https://www.googleapis.com/auth/servicecontrol
      - https://www.googleapis.com/auth/service.management.readonly
      - https://www.googleapis.com/auth/trace.append
    metadata:
      disable-legacy-endpoints: "true"
  management:
    autoRepair: true
    autoUpgrade: true
  nodeLocations:
    - europe-west4-a
    - europe-west4-b
    - europe-west4-c
  clusterRef:
    name: worker1
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: worker1-network
  annotations:
    cnrm.cloud.google.com/project-id: company-project-id
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: false
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  name: worker1-network
  annotations:
    cnrm.cloud.google.com/project-id: company-project-id
spec:
  ipCidrRange: 10.2.0.0/16
  region: europe-west4
  networkRef:
    name: worker1-network
  secondaryIpRange:
  - rangeName: servicesrange
    ipCidrRange: 10.3.0.0/16
  - rangeName: clusterrange
    ipCidrRange: 10.4.0.0/16
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: cluster-notifications
  annotations:
    cnrm.cloud.google.com/project-id: company-project-id
```

_Originally posted by @jetersen in https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/217#issuecomment-1050341629_

**Comment by jetersen** [comment]
Tried redeploying the state but goes into the same condition where it get's stuck on NetworkPolicy check

**Comment by jetersen** [comment]
@diviner524 could this be labelled as a bug :) Did not go through the new issue submission 😅

**Comment by xiaobaitusi** [comment]
Re: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/217#issuecomment-1050341629

Hi @jetersen, can you try the following yaml snippet without `networkPolicy` specified?
Looking at the GKE [documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/dataplane-v2#create-cluster), GKE Dataplane V2 comes with [Kubernetes network policy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) enforcement built-in. If You don't need to explicitly enable or disable network policy enforcement in a cluster that uses GKE Dataplane V2.


```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  labels:
    availability: dev
    target-audience: development
  name: containercluster-sample-dataplanev2
spec:
  description: A dataplanev2 cluster.
  location: us-central1-a
  initialNodeCount: 1
  releaseChannel:
    channel: REGULAR
  datapathProvider: ADVANCED_DATAPATH # Dataplane v2
  networkingMode: VPC_NATIVE
  networkRef:
    name: containercluster-dep-dataplanev2
  subnetworkRef:
    name: containercluster-dep-dataplanev2
  ipAllocationPolicy:
    servicesSecondaryRangeName: servicesrange
    clusterSecondaryRangeName: clusterrange
  workloadIdentityConfig:
    # Replace ${PROJECT_ID?} with your project ID.
    workloadPool: "${PROJECT_ID?}.svc.id.goog"
```
