### ISSUE TITLE
add loggingBucket to destination for LoggingLogSink

### ISSUE THREAD

**Issue by obito** [GoogleCloudPlatform/k8s-config-connector#617]
**Describe the feature or resource**

Add loggingBucketRef to the destination spec, so we can point a Google Logging Bucket with a sink instead of a Storage Bucket.

Something like that:

```yaml
apiVersion: logging.cnrm.cloud.google.com/v1beta1
kind: LoggingLogBucket
metadata:
  name: logbucket-sample
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
spec:
  projectRef:
    # Replace ${PROJECT_ID?} with your project ID
    external: "project/test"
  location: "global"
  description: "A sample log bucket"
  locked: false
  retentionDays: 30
```

```yaml
  apiVersion: logging.cnrm.cloud.google.com/v1beta1
  kind: LoggingLogSink
  metadata:
    name: logginglogsink-sample
  spec:
    projectRef:
      # Replace ${PROJECT_ID?} with your project ID
      external: "test"
    destination:
      loggingLogRef:
        name: logbucket-sample
    filter: resource.type="bigquery_project"
```
**Importance**

Blocker, we need it ASAP. It's very useful for many reasons and I don't see why it's not supported yet, when the Storage Bucket is supported with a Logging Sink.
