### ISSUE TITLE
ContainerNodePool stuck in UpdateFailed status

### ISSUE THREAD

**Issue by mariadb-MarinKoynov** [GoogleCloudPlatform/k8s-config-connector#623]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

When I try to create a `ContainerNodePool` object in Kubernetes, the resource gets created in the cloud and can be used, but the Kubernetes object's status is stuck in `UpdateFailed`, and the controller logs keep spamming reconciliation errors of "RESOURCE - already exists"

### Kubernetes Cluster Version

`Client Version: v1.23.4`
`Server Version: v1.21.6-gke.1500`

### Config Connector Version

`1.67.0`

### Config Connector Mode

`namespaced`

## Log Output

```text
{"severity":"info","timestamp":"2022-03-03T11:45:32.001Z","logger":"containernodepool-controller","msg":"starting reconcile","resource":{"namespace":"cnrm-system","name":"my-server-pool"}}
{"severity":"info","timestamp":"2022-03-03T11:45:32.125Z","logger":"containernodepool-controller","msg":"creating/updating underlying resource","resource":{"namespace":"cnrm-system","name":"my-server-pool"}}
{"severity":"info","timestamp":"2022-03-03T11:46:03.856Z","logger":"containernodepool-controller","msg":"successfully finished reconcile","resource":{"namespace":"cnrm-system","name":"my-server-pool"},"time to next reconciliation":"8m48.873932865s"}
{"severity":"info","timestamp":"2022-03-03T11:46:03.857Z","logger":"containernodepool-controller","msg":"starting reconcile","resource":{"namespace":"cnrm-system","name":"my-server-pool"}}
{"severity":"info","timestamp":"2022-03-03T11:46:03.950Z","logger":"containernodepool-controller","msg":"creating/updating underlying resource","resource":{"namespace":"cnrm-system","name":"my-server-pool"}}
{"severity":"error","timestamp":"2022-03-03T11:46:04.040Z","logger":"controller.containernodepool-controller","msg":"Reconciler error","reconciler group":"container.cnrm.cloud.google.com","reconciler kind":"ContainerNodePool","name":"my-server-pool","namespace":"cnrm-system","error":"Update call failed: error applying desired state: summary: resource - projects/${PROJECT_ID?}/locations/us-central1/clusters/${CLUSTER_ID}/nodePools/my-server-pool - already exists"}
{"severity":"info","timestamp":"2022-03-03T11:46:06.041Z","logger":"containernodepool-controller","msg":"starting reconcile","resource":{"namespace":"cnrm-system","name":"my-server-pool"}}
{"severity":"info","timestamp":"2022-03-03T11:46:06.107Z","logger":"containernodepool-controller","msg":"creating/updating underlying resource","resource":{"namespace":"cnrm-system","name":"my-server-pool"}}
{"severity":"error","timestamp":"2022-03-03T11:46:06.182Z","logger":"controller.containernodepool-controller","msg":"Reconciler error","reconciler group":"container.cnrm.cloud.google.com","reconciler kind":"ContainerNodePool","name":"my-server-pool","namespace":"cnrm-system","error":"Update call failed: error applying desired state: summary: resource - projects/${PROJECT_ID?}/locations/us-central1/clusters/${CLUSTER_ID}/nodePools/my-server-pool - already exists"}
{"severity":"info","timestamp":"2022-03-03T11:46:10.183Z","logger":"containernodepool-controller","msg":"starting reconcile","resource":{"namespace":"cnrm-system","name":"my-server-pool"}}
{"severity":"info","timestamp":"2022-03-03T11:46:10.258Z","logger":"containernodepool-controller","msg":"creating/updating underlying resource","resource":{"namespace":"cnrm-system","name":"my-server-pool"}}
{"severity":"error","timestamp":"2022-03-03T11:46:10.316Z","logger":"controller.containernodepool-controller","msg":"Reconciler error","reconciler group":"container.cnrm.cloud.google.com","reconciler kind":"ContainerNodePool","name":"supernewaaa-server","namespace":"cnrm-system","error":"Update call failed: error applying desired state: summary: resource - projects/${PROJECT_ID}/locations/us-central1/clusters/${CLUSTER_ID}/nodePools/my-server-pool - already exists"}
```

The error keep spamming the logs forever.

### Steps to reproduce the issue

1. Create a new cluster with the `ConfigConnector` add-on enabled (it's namespaced by default it seems like). 
2. Create a `ConfigConnectorContext`, following the [guide](https://cloud.google.com/config-connector/docs/how-to/advanced-install#creating_an_identity).
3. Create a `ContainerNodePool` with an external cluster ref (yaml in the next section).

### Additional steps taken

After the `ContainerNodePool` gets stuck in `READY: false` and `STATUS : UpdateFailed` the following steps were taken:
1. Deleting the Kubernetes resource, the cloud resource does not get deleted.
2. Deleting the Kubernetes resource and recreating it, the status doesn't change.
3. Deleting the cloud resource. The `containernodepool-controller` recreates it successfully, but the Kubernetes resource gets stuck, just as before.

### YAML snippets

```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: my-server-pool
  namespace: cnrm-system
  annotations:
    cnrm.cloud.google.com/force-destroy: "true"
    cnrm.cloud.google.com/deletion-policy: "delete"
    cnrm.cloud.google.com/delete-contents-on-destroy: "true"
spec:
  location: us-central1
  initialNodeCount: 0
  autoscaling:
    minNodeCount: 0
    maxNodeCount: 40
  nodeConfig:
    diskSizeGb: 64
    minCpuPlatform: "Intel Cascade Lake"
    machineType: n2-standard-4
    diskType: pd-ssd
    imageType: cos
    oauthScopes:
    - "https://www.googleapis.com/auth/logging.write"
    - "https://www.googleapis.com/auth/monitoring"
    - "https://www.googleapis.com/auth/trace.append"
    - "https://www.googleapis.com/auth/servicecontrol"
    - "https://www.googleapis.com/auth/service.management.readonly"
    - "https://www.googleapis.com/auth/devstorage.read_only"
    labels:
      labelkeyone: labelvalueone
      labelkeytwo: labelvaluetwo
      labelkeythree: labelvaluethree
    taint:
    - effect: NO_SCHEDULE
      key: labelkeyone
      value: labelvalueone
    - effect: NO_SCHEDULE
      key: labelkeytwo
      value: labelvaluetwo
    - effect: NO_SCHEDULE
      key: labelkeythree
      value: labelvaluethree
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    external: projects/${PROJECT_ID?}/locations/us-central1/clusters/${CLUSTER_ID?}
```
