### ISSUE TITLE
LoggingSink Permission Issue

### ISSUE THREAD

**Issue by cartyc** [GoogleCloudPlatform/k8s-config-connector#628]
## Checklist

- [x ] I did not find a related open issue.
- [ x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

When provisioning a LoggingLogSink for BigQuery/PubSub/Bucket services are provisioned within GCP and have an up to date status in the Config Control Cluster but no logs are delivered to the destinations. When creating the services through the GCP Console the services behave as expected.

I was able to resolve the issue manually by adding the loggingsink's Writer identity to the associated BigQuery instance within the BQ Console. I tried this after looking at the logsink trouble shooting logs and finding permission errors on the target resource.

My assumption is there is a permission missing somewhere but I am unsure if this is on the KCC end or the user side of things.

### Kubernetes Cluster Version
Config Controller v1.21.9-gke.1002

### Config Connector Version
1.75.0

## Log Output
Logs report everything is healthy in Config Controller and either no logs are found when troubleshooting the logsink or it reports a permission issue. Right now no errors are being reported in Cloud Logs.

### YAML snippets

```yaml
---
apiVersion: logging.cnrm.cloud.google.com/v1beta1
kind: LoggingLogSink
metadata:
  name: logginglogsink-bq
spec:
  projectRef:
    external: project-id
  destination:
    bigQueryDatasetRef:
      name: logginglogsinkdepfolder
  filter: logName:"cloudaudit.googleapis.com"
---
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  annotations:
    cnrm.cloud.google.com/delete-contents-on-destroy: "true"
  name: logginglogsinkdepfolder
```

**Comment by jcanseco** [comment]
> My assumption is there is a permission missing somewhere but I am unsure if this is on the KCC end or the user side of things.

Yes I think your assessment is correct; and the permission should be added by the user as KCC does not have GCP permissions by itself.

> I was able to resolve the issue manually by adding the loggingsink's Writer identity to the associated BigQuery instance within the BQ Console

If you want to do this on KCC, you'll want to grant the `LoggingLogSink`'s identity Writer Identity role on the `BigQueryDataset` using `spec.access` field.

Unfortunately this is hard to do with KCC by itself today, but if you're using kpt, you can leverage kpt's apply-time-mutating to copy over `LoggingLogSink`'s identity to `BigQueryDataset`'s `spec.access`.

Let us know if you'd like more clarification.

**Comment by cartyc** [comment]
In case anyone else stumbles upon this here's what I did. I tried to append to the `BigQueryDataset` but got into a chicken and egg situation where the `LoggingLogSink` wouldn't come up because it needs the `BigQueryDataset` to be live and it was waiting for the `LoggingLogSink` to become healthy to grab the Writer Identity.

I created an IAM Binding for the Project that adds the Writer Identity as a BQ Admin and with that in place things work as expected.
```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata: # kpt-merge: config-control/bq-audit-data-viewer
  name: bq-sink-writer
  namespace: config-control
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-pkg-fn-live'
    config.kubernetes.io/apply-time-mutation: |
      - sourceRef:
          apiVersion: logging.cnrm.cloud.google.com/v1beta1
          kind: LoggingLogSink
          name: bigquery-logsink
        sourcePath: $.status.writerIdentity
        targetPath: $.spec.member
        token: ${logging-writerIdentity}
spec:
  member: ${logging-writerIdentity} 
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: my-awesome-project
  role: roles/bigquery.admin    
 ```
