### ISSUE TITLE
Modifiable `ConfigConnector` resource with GKE addon

### ISSUE THREAD

**Issue by djfinnoy** [GoogleCloudPlatform/k8s-config-connector#632]
**Describe the feature or resource**

When installing ConfigConnector via the GKE addon, the `ConfigConnector` CRD is automatically created in the `cnrm-system`.
I'm guessing that most users will need to modify this resource in order to use ConfigConnector.

Eg:

```
      apiVersion: core.cnrm.cloud.google.com/v1beta1
      kind: ConfigConnector
      metadata:
        name: configconnector.core.cnrm.cloud.google.com
        namespace: cnrm-system
        annotations:
          created-by: Terraform
          created-with: github.com/org/cloud-setup
      spec:
        mode: cluster
        googleServiceAccount: some-gsa@some-project.iam.gserviceaccount.com

```

It would be amazing if we could specify what this resource should look like directly in the GKE addon config; it would save Terraform users the trouble of dealing with last mile configuration of their ConfigConnector setup.

We use Terraform, so here is how I would like to handle the `ConfigConnector` resource:

```
resource "google_container_cluster" "my_cluster" {
  ...
    config_connector_config {
      enabled = true

      # These config options do not exist:
      mode = "cluster"
      googleServiceAccount = "some-gsa@some-project.iam.gserviceaccount.com"
      annotations = {
        created-by = "Terraform"
        created-with = "github.com/org/cloud-setup"
      }
    }
}
```
Another, slightly less desireable solution, would be an option to not create the default `ConfigConnector` resource, this would make it easier to create the resource with Helm:
```
resource "google_container_cluster" "my_cluster" {
  ...
    config_connector_config {
      enabled = true

      # This config option does not exist:
      create_config = false
    }
}
```

**Importance**

Nice to have.

Saves us the trouble of using the kubernetes provider. Helm provider currently doesn't work because Helm can't inherit the pre-existing `ConfigConnector` resource.
