### ISSUE TITLE
Have permission/grants of a SQLUser configurable

### ISSUE THREAD

**Issue by RonaldFindling** [GoogleCloudPlatform/k8s-config-connector#641]
## Describe the feature or resource
It would be great to be able to configure the permissions/grants of a SQLUser directly - somehow in the idea of the following 

```yaml
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLUser
metadata:
  name: cats
spec:
  resourceID: cats
  instanceRef:
    external: mysql-cats
  host: "%"
  grants: "SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `cats`.*"
  password:
    valueFrom:
      secretKeyRef:
        name: cats-pw
        key: password
```

## Importance
Atm we need to work around this by building external tooling.

## Links
Related issue limit the Databases for which the permission grant happens see https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/134
