### ISSUE TITLE
[documentation bug] PubsubSubscription without expirationPolicy.ttl expires in 31 days

### ISSUE THREAD

**Issue by slaise** [GoogleCloudPlatform/k8s-config-connector#643]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description

Create a PubSubSubscription without explicitly setting `expirationPolicy`, the resource expires in 31 days. 
```yaml
apiVersion: "pubsub.cnrm.cloud.google.com/v1beta1"
kind: "PubSubSubscription"
metadata:
  name: "test"
  namespace: "test"
spec:
  ackDeadlineSeconds: 10
  messageRetentionDuration: "604800s"
  resourceID: "test"
  topicRef:
    external: "projects/test/topics/test"
```

But the documentation is conflicting in two sections, the one from the `expirationPolicy` field matches the behavior
>  If expirationPolicy is not set, a default policy with ttl of 31 days will be used

But also mentions the opposite thing in `expirationPolicy.ttl` field

> The resource expires if it is not active for a period of ttl. If ttl is not set, the associated resource never expires. 

Can you please fix the doc, thanks!
