### ISSUE TITLE
Support only install partial CRDs

### ISSUE THREAD

**Issue by liubog2008** [GoogleCloudPlatform/k8s-config-connector#650]
## Checklist

- [x] I did not find a related open enhancement request.
- [x] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [x] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Describe the feature or resource

There are too many CRDs which are not needed for me. I hope to uninstall some CRDs to avoid k8s discovery throttling.

**Comment by maqiuyujoyce** [comment]
Hi @liubog2008 , thank you for your feedback!

> I hope to uninstall some CRDs to avoid k8s discovery throttling.

Could you elaborate a bit about "K8s discovery throttling"? What issue(s) have you encountered? Would be great if you can share more details.

Also is this enhancement feature a blocker, a friction point, or a nice-to-have to your project?

**Comment by liubog2008** [comment]
nice-to-have

See https://github.com/kubernetes/kubernetes/pull/105520

And too many CRDs lead to many problems.

Maybe this issue in crossplane is helpful for you. https://github.com/crossplane/crossplane/issues/2649

**Comment by mbzomowski** [comment]
Hi @liubog2008, thanks for the suggestion - we'll look into adding this feature.

**Comment by DoctahPopp871** [comment]
This issue makes it hard to use kubectl to interact with GKE clusters that have ConfigConnector enabled. If you could choose the APIs and corresponding CRDs you needed ahead of time, it would dramatically reduce the CRD count, and help mitigate this kubectl bug. Thanks!

**Comment by maqiuyujoyce** [comment]
Hi folks,

We're looking into the options to support CRD partial installation and we'd like your input! Here are some details:

### Option I: New field `crdSelector` in the ConfigConnector kind
For example, you can install all the CRDs containing v1alpha1 version:
```
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  mode: cluster
  googleServiceAccount: "${GSA?}@${PROJECT_ID?}.iam.gserviceaccount.com"
  crdSelector:
    services:
      - all  # Specify the services in the format of the API group to select certain services.
    versions:
      - v1alpha1
```
Or, you can install CRDs based on the kinds you've selected:
```
apiVersion: core.cnrm.cloud.google.com/v1beta1
kind: ConfigConnector
metadata:
  name: configconnector.core.cnrm.cloud.google.com
spec:
  mode: cluster
  googleServiceAccount: "${GSA?}@${PROJECT_ID?}.iam.gserviceaccount.com"
  crdSelector:
    kinds:  # Used mutually exclusive with `services` + `versions` combination.
      - containerclusters.container.cnrm.cloud.google.com
      - iamserviceaccounts.iam.cnrm.cloud.google.com
      - kmskeyrings.kms.cnrm.cloud.google.com
      - kmscryptokeys.kms.cnrm.cloud.google.com
```

### Option II: New kind(s) to manage CRD selection
For example, you can install all the CRDs containing v1alpha1 version under PubSubLite using the `CRDGroupSelector` CR:
```
apiVersion: customize.cnrm.cloud.google.com/v1alpha1
kind: CRDGroupSelector
metadata:
  name: pubsublite.cnrm.cloud.google.com
spec:
  versions:
    - v1alpha1
```
Or, you can install CRDs based on the kinds you've selected like below:
```
apiVersion: customize.cnrm.cloud.google.com/v1alpha1
kind: CRDGroupSelector
metadata:
  name: pubsublite.cnrm.cloud.google.com
spec:
  kinds:
    - PubSubLiteReservation
    - PubSubLiteTopic
```

In addition, there could be a specific `CRDVersionSelector` CRD for bulk selection by version. E.g. the following CR means that all the v1alpha1 CRDs should be installed:
```
apiVersion: customize.cnrm.cloud.google.com/v1alpha1
kind: CRDVersionSelector
metadata:
  name: v1alpha1
```

### Option III: New field `crdVersions` + New kind `CRDGroupSelector`
This is a combination of Option I and Option II. Based on the different use case (managing CRD selection by groups or by versions), different options are provided.
