### ISSUE TITLE
GKE - Error 400: Node_pool_id must be specified.

### ISSUE THREAD

**Issue by travisrandolph-bestbuy** [GoogleCloudPlatform/k8s-config-connector#653]
## Bug Description
We have roughly 10 clusters showing the error below. I believe the issue stems from users manually deleting the cluster from the console. The KCC resources aren't removed and the cluster is rebuilt on the next reconciliation. I tried to abandon and delete the resources from KCC and then re-acquire them. The error still persisted after acquisition.

## Additional Diagnostic Information
```
status:
  conditions:
  - lastTransitionTime: "2022-03-16T21:29:03Z"
    message: 'Update call failed: error applying desired state: summary: googleapi:
      Error 400: Node_pool_id must be specified., badRequest'
    reason: UpdateFailed
    status: "False"
```

### Config Connector Version
1.76.0

### Config Connector Mode
namespaced

**Comment by maqiuyujoyce** [comment]
Hi @travisrandolph-bestbuy , thanks for reporting the issue.

I tried to reproduce it using the following resource YAML and steps, but the cluster was recreated successfully without any issue:

```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: test-1
  namespace: test
spec:
  location: us-central1-a
  initialNodeCount: 1
```
1. Installed Config Connector 1.76.0 in the namespaced mode.
2. Created the GKE cluster using the snippet above via Config Connector.
3. Deleted the GKE cluster via Cloud Console.
4. Waited for the drift correction of ContainerCluster resource.

Could you provide more details about your scenario? Would be great if you can provide the yaml snippet that will result in the "node_pool_id must be specified" issue.

> The KCC resources aren't removed and the cluster is rebuilt on the next reconciliation.

What's the status of the cluster (the GCP resource) after rebuild? Is there a similar error in the resource status/command output when you run `gcloud container clusters describe`?

> I tried to abandon and delete the resources from KCC and then re-acquire them.

Did you acquire the resource using the same YAML? Have you tried to acquire the cluster using the YAML [exported by the config-connector tool](https://cloud.google.com/config-connector/docs/how-to/import-export/export)?

**Comment by travisrandolph-bestbuy** [comment]
>Would be great if you can provide the yaml snippet that will result in the "node_pool_id must be specified" issue.
```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "true"
  name: {{ REDACTED }}
spec:
  location: us-central1
  nodeLocations:
  - us-central1-b
  - us-central1-c
  initialNodeCount: 1
  releaseChannel:
      channel: STABLE
  notificationConfig:
    pubsub:
      enabled: true
      topicRef:
        name: {{ REDACTED }}
  maintenancePolicy:
    recurringWindow:
      endTime: 2099-01-01T23:00:00Z
      recurrence: FREQ=WEEKLY;BYDAY=MO,TU,WE,TH,FR
      startTime: 2021-01-01T15:00:00Z
  enableBinaryAuthorization: true
  verticalPodAutoscaling:
    enabled: true
  networkRef:
    name: {{ REDACTED }}
  subnetworkRef:
    name: {{ REDACTED }}
  addonsConfig:
    httpLoadBalancing:
      disabled: false
  masterAuthorizedNetworksConfig:
    cidrBlocks:
    - cidrBlock: {{ REDACTED }}
  privateClusterConfig:
    enablePrivateEndpoint: true
    enablePrivateNodes: true
    masterIpv4CidrBlock: {{ REDACTED }}
  ipAllocationPolicy:
    clusterIpv4CidrBlock: {{ REDACTED }}
    clusterSecondaryRangeName: {{ REDACTED }}
    servicesIpv4CidrBlock: {{ REDACTED }}
    servicesSecondaryRangeName: {{ REDACTED }}
  databaseEncryption:
    state: ENCRYPTED
    keyName: projects/{{ REDACTED }}/locations/us-central1/keyRings/{{ REDACTED }}/cryptoKeys/{{ REDACTED }}
  enableShieldedNodes: true
  workloadIdentityConfig:
    identityNamespace: {{ REDACTED }}.svc.id.goog
  nodeConfig:
    imageType: COS
    metadata:
      disable-legacy-endpoints: "true"
      block-project-ssh-keys: "true"
    oauthScopes:
    - https://www.googleapis.com/auth/cloud-platform
    shieldedInstanceConfig:
      enableSecureBoot: true
      enableIntegrityMonitoring: true
    tags:
    - {{ REDACTED }}
---
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  name: {{ REDACTED }}
spec:
  location: us-central1
  nodeLocations:
  - us-central1-a
  - us-central1-b
  - us-central1-c
  initialNodeCount: 1
  autoscaling:
    minNodeCount: 1
    maxNodeCount: 10
  nodeConfig:
    serviceAccountRef:
      name: {{ REDACTED }}
    imageType: COS_CONTAINERD
    machineType: n2-standard-2
    tags:
      - {{ REDACTED }}
    preemptible: false
    oauthScopes:
      - https://www.googleapis.com/auth/cloud-platform
    metadata:
      disable-legacy-endpoints: "true"
      block-project-ssh-keys: "true"
    shieldedInstanceConfig:
        enableSecureBoot: true
        enableIntegrityMonitoring: true
  management:
    autoRepair: true
    autoUpgrade: true
  clusterRef:
    name: {{ REDACTED }}
```
>What's the status of the cluster (the GCP resource) after rebuild? Is there a similar error in the resource status/command output when you run gcloud container clusters describe?

The status of the cluster is "RUNNING".
>Did you acquire the resource using the same YAML? Have you tried to acquire the cluster using the YAML [exported by the config-connector tool](https://cloud.google.com/config-connector/docs/how-to/import-export/export)?

We are just using the same YAML that we originally used to deploy the cluster.
