### ISSUE TITLE
Dataproc cluster Update Failed

### ISSUE THREAD

**Issue by sbihun** [GoogleCloudPlatform/k8s-config-connector#661]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Status:  
  Conditions:  
    Last Transition Time:  2022-05-18T08:51:03Z
    Message:               Update call failed: error applying desired state: infeasible update: ({true <nil>}) would require recreation
    Reason:                UpdateFailed
    Status:                False
    Type:                  Ready

### Additional Diagnostic Information

I tried to deploy the Dataproc cluster
GKE cluster: 
1. Workload Identity: Enabled
2. Config Connector: Enabled
Also, I updated Kubernetes Cluster to the latest versions and Config Connector, but it didn't help me.
### Kubernetes Cluster Version

1.20.15-gke.6000

### Config Connector Version

1.69.0

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

Every deployed Dataproc cluster got a warning.

### YAML snippets

```YAML
apiVersion: dataproc.cnrm.cloud.google.com/v1beta1
kind: DataprocCluster
metadata:
  name: dataproccluster-sample
  namespace: config-connector-system
  annotations:
    cnrm.cloud.google.com/project-id: <project_id>
    cnrm.cloud.google.com/management-conflict-prevention-policy: "none"
spec:
  location: "<gcp_region>"
  config:
    masterConfig:
      diskConfig:
        bootDiskSizeGb: 30
        bootDiskType: pd-standard
      machineType: "n2-standard-2"
      numInstances: 1
    workerConfig:
      numInstances: 2
      machineType: "n2-standard-2"
      diskConfig:
        bootDiskSizeGb: 30
        numLocalSsds: 1
    softwareConfig:
      imageVersion: "2.0-debian10"
      properties:
        "core:hadoop.security.groups.cache.secs": "250"
        "mapred:mapred.tasktracker.map.tasks.maximum": "2"
        "mapred:mapreduce.map.sort.spill.percent": "0.90"
        "mapred:mapreduce.tasktracker.reduce.tasks.maximum": "5"
    gceClusterConfig:
      tags:
      - "foo"
    initializationActions:
    - executableFile: "gs://dataproc-initialization-actions/stackdriver/stackdriver.sh"
      executionTimeout: "500s"
```
