### ISSUE TITLE
GCP DNSManagedZone uses the wrong GCP project

### ISSUE THREAD

**Issue by esn89** [GoogleCloudPlatform/k8s-config-connector#662]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

DNSManagedZone is trying to make a DNSPeering from the wrong GCP project.  It uses the project name of the Kubernetes namespace.

### Additional Diagnostic Information

Using this manifest:

```
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: dns-peer
spec:
  description: "DNS Peering"
  dnsName: "peer.com."
  visibility: private
  privateVisibilityConfig:
    networks:
      - networkRef:
          external: "projects/sourceVPC/global/networks/internal"
  peeringConfig:
    targetNetwork:
      networkRef:
        external: "https://www.googleapis.com/compute/v1/projects/destinationVPC/global/networks/internal"
```

It returns an error like this when I do `kubectl describe`

```
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.Help",
    "links": [
      {
        "description": "Google developer console API key",
        "url": "https://console.developers.google.com/project/default/apiui/credential"
      }
    ]
  },
  {
    "@type": "type.googleapis.com/google.rpc.ErrorInfo",
    "domain": "googleapis.com",
    "metadata": {
      "consumer": "projects/default",
      "service": "dns.googleapis.com"
    },
    "reason": "CONSUMER_INVALID"
  }
]
, forbidden
```

and:

```
Events:
  Type     Reason        Age                 From                       Message
  ----     ------        ----                ----                       -------
  Warning  UpdateFailed  47s (x3 over 108s)  dnsmanagedzone-controller  Update call failed: error fetching live state: error reading underlying resource: summary: Error when reading or editing DNSManagedZone "projects/default/managedZones/dns-peer": googleapi: Error 403: Permission denied on resource project default.
 ```
 
 I tried changing the namespace of the manifest to be deployed in, to, "test".  However, it was the same error, simply that now it complains about "projects/test" have permission issues.

### Kubernetes Cluster Version

1.21.10-gke.2000 

### Config Connector Version

1.65.0

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

Apply that yaml from below

### YAML snippets

```YAML
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: dns-peer
spec:
  description: "DNS Peering"
  dnsName: "peer.com."
  visibility: private
  privateVisibilityConfig:
    networks:
      - networkRef:
          external: "projects/sourceVPC/global/networks/internal"
  peeringConfig:
    targetNetwork:
      networkRef:
        external: "https://www.googleapis.com/compute/v1/projects/destinationVPC/global/networks/internal"
```

**Comment by diviner524** [comment]
@esn89 Could you try adding `cnrm.cloud.google.com/project-id` annotation to the resource YAML?
```YAML
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: YOUR_GCP_PROJECT_ID
  name: dns-peer
spec:
  description: "DNS Peering"
  dnsName: "peer.com."
  visibility: private
  privateVisibilityConfig:
    networks:
      - networkRef:
          external: "projects/sourceVPC/global/networks/internal"
  peeringConfig:
    targetNetwork:
      networkRef:
        external: "https://www.googleapis.com/compute/v1/projects/destinationVPC/global/networks/internal"
```

https://cloud.google.com/config-connector/docs/reference/resource-docs/dns/dnsmanagedzone
