### ISSUE TITLE
LoggingLogSink uniqueWriterIdentity not working as expected (documented)

### ISSUE THREAD

**Issue by reikje** [GoogleCloudPlatform/k8s-config-connector#676]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

We are running the following definition:

```
apiVersion: logging.cnrm.cloud.google.com/v1beta1
kind: LoggingLogSink
metadata:
  name: settlement-processor-service-log-sink
  namespace: "settlement-processor-abcd"
spec:
  projectRef:
    external: "settlement-processor-abcd"
  destination:
    storageBucketRef:
      name: "settlement-processor-service-logs"
  filter: logName =~ "projects\/settlement-processor-abcd\/logs\/sp\.[a-z]+\.settlement-processor"
```

Documentation on the `uniqueWriteIdentity` (which we didn't set):

> Immutable. Whether or not to create a unique identity associated with this sink. If false (the default), then the writer_identity used is serviceAccount:cloud-logs@system.gserviceaccount.com. If true, then a unique service account is created and used for this sink. If you wish to publish logs across projects, you must set unique_writer_identity to true.

Yet the Log Sink is created using the following writer identity:
`serviceAccount:p43863790579-159108@gcp-sa-logging.iam.gserviceaccount.com` instead of `serviceAccount:cloud-logs@system.gserviceaccount.com`

### Additional Diagnostic Information

The Log Sink should run using `serviceAccount:cloud-logs@system.gserviceaccount.com` if `false` is the default for the `uniqueWriteIdentity` attribute.

### Kubernetes Cluster Version

Client Version: v1.22.1 Server Version: v1.21.11-gke.900

### Config Connector Version

1.71.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

Create the log sink resource using a similar definition to the one above.

### YAML snippets

```YAML
apiVersion: logging.cnrm.cloud.google.com/v1beta1
kind: LoggingLogSink
metadata:
  name: settlement-processor-service-log-sink
  namespace: "settlement-processor-abcd"
spec:
  projectRef:
    external: "settlement-processor-abcd"
  destination:
    storageBucketRef:
      name: "settlement-processor-service-logs"
  filter: logName =~ "projects\/settlement-processor-abcd\/logs\/sp\.[a-z]+\.settlement-processor"
```
