### ISSUE TITLE
unable to provision regional managed proxy

### ISSUE THREAD

**Issue by lienegotliba** [GoogleCloudPlatform/k8s-config-connector#678]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

When trying to provision subnetwork with purpose "REGIONAL_MANAGED_PROXY" an error is returned "Invalid field set in subnetwork with purpose REGIONAL_MANAGED_PROXY"

### Additional Diagnostic Information

similar issues have been reported on cloud foundation fabric
https://github.com/GoogleCloudPlatform/cloud-foundation-fabric/issues/633

### Kubernetes Cluster Version

v1.21.12-gke.1500

### Config Connector Version

1.69.0

### Config Connector Mode

cluster mode

### Log Output

Update call failed: error applying desired state: summary: Error creating Subnetwork: googleapi: Error 400: Invalid value for field 'resource.logConfig': '{ "enable": false}'. Invalid field set in subnetwork with purpose REGIONAL_MANAGED_PROXY., invalid

### Steps to reproduce the issue

attempt to create subnetwork with purpose REGIONAL_MANAGED_PROXY, receive error "Invalid field set in subnetwork with purpose REGIONAL_MANAGED_PROXY"

### YAML snippets

```YAML
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSubnetwork
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: <project-id>
  name: proxy-only-subnet
spec:
  description: regional managed proxy for cluster loadbalancing
  ipCidrRange: 10.129.0.0/23
  networkRef:
    external: <network-self-link>
  purpose: REGIONAL_MANAGED_PROXY
  region: us-east4
  role: ACTIVE
```
