### ISSUE TITLE
GCP resources created by KCC does not allow for dynamic fields

### ISSUE THREAD

**Issue by klaraward** [GoogleCloudPlatform/k8s-config-connector#68]
Use case: Use KCC to create GCP resources used as Traffic Director configuration

1. We create GCP resources using KCC 
- healthcheck
- backend service
- urlmap
....

2. We annotate k8s service object with `cloud.google.com/neg` and `anthos.cft.dev/autoneg` which will respectively create NEGs, and add them to the backend service.

3.  These NEGs are removed from the backend service by the KCC controller, which is not the desired behavior for us.

Tried to workaround by
- create healtcheck with KCC
- create backend service with gcloud command
- create urlmap and other resources with KCC

This makes us run into issue #66, that we can't create the resources referring to the backend service. 
We tried to workaround this by first creating the backend service with gcloud and then creating the KCC resource for it, this allows for creating the urlmaps etc, but then we run into the same problem we started with, KCC deletes the NEGs from the backend service.

Would it be possible to annotate the KCC resources with some GCP resource fields that KCC will not touch?

**Comment by spew** [comment]
Hi @klaraward, what does NEG stand for?

**Comment by klaraward** [comment]
@spew 
NEG = Network Endpoint Group, one of the types of “Backends” you can add to a Backend Service (other is MIG = Managed Instance Group)

**Comment by caieo** [comment]
Hi @klaraward , sorry to hear that KCC keeps removing the NEGs from the backend service. Do you think you can paste the YAML for your backend service?  

Re: annotate so that KCC will not touch some GCP resource fields: We don't have anything like this currently and I don't believe we have any current plans for a feature like this. It's possible that you've encountered a bug with the way KCC is handling backend services. We will go through your use case and try to fix it as soon as possible!

**Comment by klaraward** [comment]
backend service yaml:
```
apiVersion: compute.cnrm.cloud.google.com/v1alpha3
kind: ComputeBackendService
metadata:
  name: concat-backendservice
  namespace: fabric-rnd
spec:
  healthCheckRef:
    name: concat-healthcheck
  location: global
  loadBalancingScheme: INTERNAL_SELF_MANAGED
```

**Comment by caieo** [comment]
@klaraward , thanks for the detailed YAMLs (and in #66 ). Can you help me understand what you mean by this step: "2. We annotate k8s service object with cloud.google.com/neg and anthos.cft.dev/autoneg which will respectively create NEGs, and add them to the backend service"? How are you annotating the NEGs into the k8s object? Are you adding it directly to the YAML or editing it on the command line?

**Comment by klaraward** [comment]
@caieo 
This is how we create our k8s service:
```
apiVersion: v1
kind: Service
metadata:
  name: concat
  namespace: concat-ns
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"5990":{}, "8080":{}}}'
    anthos.cft.dev/autoneg: '{"name":"concat-backendservice", "max_rate_per_endpoint":1000}'
...
```

**Comment by caieo** [comment]
@klaraward , I marked this issue as an enhancement that is important for us to address within the coming months. We will definitely run into similar scenarios like yours based on the breadth of unique resources es that we deal with. Thank you again for giving us enough context to understand/repro your scenario and we will post updates in this thread!

**Comment by spew** [comment]
We are planning to support Server Side apply which should make it possible for customers of KCC to specify values for fields they want to manage. For fields they do not specify, KCC will allow "GCP" to be the source of truth. With that information, KCC will be able to sync the state of the BackendService into the API server and know to NOT overwrite the NEG list.

https://kubernetes.io/docs/reference/using-api/api-concepts/#server-side-apply

**Comment by AlexBulankou** [comment]
> We are planning to support Server Side apply which should make it possible for customers of KCC to specify values for fields they want to manage.

CC @soellman, this should enable the scenario of using KCC with your `autoneg`controller.

**Comment by mikelnrd** [comment]
Hi. I am hitting this issue too.

I have a different idea for a solution however (let me know what you think):

Currently the name of the NEG (Network Endpoint Group) that is created automatically when you define a Service is based on the service's name and port and ends with a random string - so isn't knowable in advance - which makes configuration as code difficult.

Image instead that you could configure the name of the NEG in the Service yaml. For example: `"name": "my-neg"`. 

```yaml
apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-project
  annotations:
    cloud.google.com/neg: '{"exposed_ports":{"5990":{}, "8080":{}}, "name": "my-neg"}'
```
With this approach, you could configure a `BackendService` backed by NEGs running in one or more GKE clusters **without** using the anthos autoneg controller. 

You would instead define a `ComputeBackendService` and `ComputeNetworkEndpointGroup` using KCC as follows:

```yaml
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendService
metadata:
  name: my-backend-service
  namespace: my-project
spec:
  affinityCookieTtlSec: 0
  backend:
    - balancingMode: RATE
      capacityScaler: 1.0
      maxRatePerEndpoint: 1000.0
      group:
        networkEndpointGroupRef:
          name: my-neg # reference the NEG defined below
    # optionally add other backends here, eg from another zone in the cluster, or even from another GKE cluster

---

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetworkEndpointGroup
metadata:
  name: my-neg # this matches the name defined in the Service annotation above
  namespace: my-project
spec:
  networkEndpointType: GCE_VM_IP_PORT
  networkRef:
    ...
  subnetworkRef:
    ...
  location: ...
```

This would I imagine need to be filed as an feature request against the GCE Ingress repo.
