### ISSUE TITLE
RHEL images on an instance result in Update call failed: cannot make changes to immutable field(s): [bootDisk.0.InitializeParams.0.Image] error

### ISSUE THREAD

**Issue by dfellmeth-google** [GoogleCloudPlatform/k8s-config-connector#682]
A simple ComputeInstance yaml with all rhel-sap-cloud images I have tested result in the same error after `kubectl apply -f instance.yaml` from `kubectl describe computeinstances`:
```
  Warning  UpdateFailed  3s (x3 over 9s)  computeinstance-controller  Update call failed: cannot make changes to immutable field(s): [bootDisk.0.InitializeParams.0.Image]
```

```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeInstance
metadata:
  name: image-bug
spec:
  machineType: n1-highmem-32
  zone: us-central1-a
  bootDisk:
    initializeParams:
      type: pd-balanced
      size: 50
      sourceImageRef:
        external: rhel-sap-cloud/rhel-8-4-sap-ha
  networkInterface:
  - networkRef:
      external: default
```
