### ISSUE TITLE
Can't use external reference to bind a IAMPartialPolicy to project

### ISSUE THREAD

**Issue by hsuabina** [GoogleCloudPlatform/k8s-config-connector#684]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Hi,

I'm trying to add a IAMPartialPolicy for the role Big Query Job User (`bigquery/jobUser`) to an existing service account (managed by KCC).

Please check the objects I'm using in the snippets section.

When applying the Partial Policy, I'm getting this error:

```
Update call failed: error getting resource config for referenced resource: failed to load ServiceMapping for GroupVersionKind /, Kind=Project: unable to get service mapping: no mapping with name '' found
```

Notes:
* Checking other existing issues, this error has been mentioned when using a wrong 'external' syntax to refer to an object. I've checked the 'Project' external syntax and it should be `projects/{project_id}` which is the one I'm using.
* The service account bound to the namespace/project the objects are being added to has Owner permissions for that same project

Thanks in advance!

### Additional Diagnostic Information

I've tested elevating the service account bound to KCC for the project in question to have 'Organization Admin' (roles/resourcemanager.organizationAdmin) because I suspected maybe the service account might need the `resourcemanager.projects.get` or `resourcemanager.projects.list` permissions to find the project, but it didn't help.

### Kubernetes Cluster Version

1.24.1 (v1.24.1-gke.1800)

### Config Connector Version

1.71.0

### Config Connector Mode

namespaced mode (default)

### Log Output

Extract when describing the IAMPartialPolicy object:

status:
    conditions:
    - lastTransitionTime: "2022-07-16T09:58:42Z"
      message: 'Update call failed: error getting resource config for referenced resource:
        failed to load ServiceMapping for GroupVersionKind /, Kind=Project: unable
        to get service mapping: no mapping with name '''' found'
      reason: UpdateFailed
      status: "False"
      type: Ready
    observedGeneration: 1

### Steps to reproduce the issue

1) Apply IAMServiceAccount object described above. 
2) Apply IAMPartialPolicy object described above.
3) Describe IAMPartialPolicy object created

### YAML snippets

```YAML
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: gsa-name
  namespace: XXX
spec:
  displayName: Client BQ access
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: client-bq-jobuser-usa-data-iampolicymember
  namespace: XXX
spec:
  bindings:
  - members:
    - member: serviceAccount:gsa-name@XXX.iam.gserviceaccount.com
    role: roles/bigquery.jobUser
  resourceRef:
    external: 'projects/XXX'
    kind: Project
```
