### ISSUE TITLE
CC should not delete underlying ComputeSharedVPCServiceProject when 1 of 2 identical ComputeSharedVPCServiceProject exist with different names

### ISSUE THREAD

**Issue by wleese** [GoogleCloudPlatform/k8s-config-connector#687]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Creating 2 identical ComputeSharedVPCServiceProject's with different names and then deleting 1 of them, results in the underlying resource being deleted initially, only to be recreating during reconciliation.

I was somewhat surprised by this behavior. I was hoping Config Connector would understand it would be deleting something that would be recreated during reconciliation.

### Additional Diagnostic Information

None

### Kubernetes Cluster Version

v1.22.8-gke.202

### Config Connector Version

1.89.0

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

Apply these resources using kubectl:
```
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSharedVPCServiceProject
metadata:
  name: shared-vpn-cloudsql-cloudsql0 
  namespace: plgr-infra-stg-wl003 
spec:
  projectRef:
    name: plgr-stg-myapp1-abc
    namespace: myapp1 
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSharedVPCServiceProject
metadata:
  name: shared-vpn-cloudsql-cloudsql1
  namespace: plgr-infra-stg-wl003 
spec:
  projectRef:
    name: plgr-stg-myapp1-abc
    namespace: myapp1 
```

I remove 1 of the 2 and see what happens

```
➜  k rm computesharedvpcserviceproject.compute.cnrm.cloud.google.com -n plgr-infra-stg-wl003 shared-vpn-cloudsql-cloudsql

➜  gcloud compute shared-vpc list-associated-resources plgr-infra-stg-wl003
RESOURCE_ID          RESOURCE_TYPE
plgr-stg-myapp1-abc  PROJEC
T
➜  gcloud compute shared-vpc list-associated-resources plgr-infra-stg-wl003
Listed 0 items.

# much later..
➜  gcloud compute shared-vpc list-associated-resources plgr-infra-stg-wl003
RESOURCE_ID          RESOURCE_TYPE
plgr-stg-myapp1-abc  PROJECT
```

### YAML snippets

```YAML
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSharedVPCServiceProject
metadata:
  name: shared-vpn-cloudsql-cloudsql0 
  namespace: plgr-infra-stg-wl003 
spec:
  projectRef:
    name: plgr-stg-myapp1-abc
    namespace: myapp1 
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeSharedVPCServiceProject
metadata:
  name: shared-vpn-cloudsql-cloudsql1
  namespace: plgr-infra-stg-wl003 
spec:
  projectRef:
    name: plgr-stg-myapp1-abc
    namespace: myapp1
```
