### ISSUE TITLE
FilestoreInstance does not work with Shared VPC

### ISSUE THREAD

**Issue by jnodorp-jaconi** [GoogleCloudPlatform/k8s-config-connector#691]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Using FilestoreInstance with a shared VPC results in the following error:

```
Update call failed: error applying desired state: googleapi: Error 400: network project is: my-network-project, mismatch with instance project with project_id: my-main-project and project_number: xxxxxxxxxxxx.
```

### Additional Diagnostic Information

I assume this is due to the `connectMode` missing from the CRD. Connect mode defaults to `DIRECT_PEERING` but should be `PRIVATE_SERVICE_ACCESS` in this case.

### Kubernetes Cluster Version

v1.22.8-gke.202

### Config Connector Version

1.90.0

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

1. Apply the supplied YAML.
2. Run `kubectl describe filestoreinstance nfs` to see the error.

### YAML snippets

```YAML
apiVersion: filestore.cnrm.cloud.google.com/v1beta1
kind: FilestoreInstance
metadata:
  name: nfs
spec:
  fileShares:
    - capacityGb: 1024
      name: my-share
      nfsExportOptions:
        - squashMode: ROOT_SQUASH
  location: europe-west3-c
  networks:
    - networkRef:
        external: projects/my-network-project/global/networks/my-shared-network
      connectMode: PRIVATE_SERVICE_ACCESS
  projectRef:
    external: projects/my-main-project
  tier: BASIC_HDD
```
