### ISSUE TITLE
PubSubSchema attributes optional on CRD, required by API

### ISSUE THREAD

**Issue by npitts0811** [GoogleCloudPlatform/k8s-config-connector#697]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

While working with the newly added support for PubSubSchema, I discovered the following:
* the 'type' attribute is defined as optional, however the resource fails to deploy unless specified (API error)
* the 'type' attribute is listed as having a default value of 'TYPE_UNSPECIFIED', however the resource fails to deploy unless specified (API error)
* the 'definition' attribute is defined as optional, however the resource fails to deploy unless specified (API error)

### Additional Diagnostic Information

na

### Kubernetes Cluster Version

v1.22.10-gke.600

### Config Connector Version

1.90.0

### Config Connector Mode

namespaced mode (default)

### Log Output

type not defined:
Update call failed: error applying desired state: summary: Error creating Schema: googleapi: Error 400: The schema's type must be specified.

type set to TYPE_UNSPECIFIED:
Update call failed: error applying desired state: summary: Error creating Schema: googleapi: Error 400: The schema's type must be specified.

definition not defined:
Update call failed: error applying desired state: summary: Error creating Schema: googleapi: Error 400: Invalid schema definition: Could not parse schema.

### Steps to reproduce the issue

noted in description

### YAML snippets

```YAML
# type attribute not defined
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSchema
metadata:
  name: pubsubsubschema-sample
spec:
  definition: "syntax = \"proto3\";\nmessage Results {\nstring message_request = 1;\nstring message_response = 2;\nstring timestamp_request = 3;\nstring timestamp_response = 4;\n}"
  projectRef:
    external: project
# type value set to TYPE_UNSPECIFIED
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSchema
metadata:
  name: pubsubsubschema-sample1
spec:
  type: TYPE_UNSPECIFIED
  definition: "syntax = \"proto3\";\nmessage Results {\nstring message_request = 1;\nstring message_response = 2;\nstring timestamp_request = 3;\nstring timestamp_response = 4;\n}"
  projectRef:
    external: project
# definition attribute not defined
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSchema
metadata:
  name: pubsubsubschema-sample2
spec:
  type: PROTOCOL_BUFFER
  projectRef:
    external: project
```
