### ISSUE TITLE
Failed to Create ContainerCluster with cluster_telemetry and logging_service

### ISSUE THREAD

**Issue by PatrickChenSe** [GoogleCloudPlatform/k8s-config-connector#699]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

We tried to create `ContainerCluster` with KCC, but failed with the below error:
```
 error applying desired state: summary: googleapi: Error 400: Cannot specify cluster_telemetry together with logging_service., badRequest
```

It is not clear from the Google [documentation](https://cloud.google.com/config-connector/docs/reference/resource-docs/container/containercluster) that such an issue should have been expected to occur.

All the fields impacted by this issue are: `cluster_telemetry`, `logging_service`, and `monitoring_service`. 

**The creation works only if we delete all three fields and let it set to be the default value**

### Additional Diagnostic Information

No

### Kubernetes Cluster Version

1.21

### Config Connector Version

1.71

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

Create a `ContainerCluster` with `clusterTelemetry`, `loggingService`, and `monitoringService` fields, and all three fields use the default values. 

### YAML snippets

```YAML
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
 name: euw1-test
 namespace: xxxxxx
spec:
 addonsConfig:
   gcePersistentDiskCsiDriverConfig:
     enabled: true
   horizontalPodAutoscaling:
     disabled: false
   httpLoadBalancing:
     disabled: false
   networkPolicyConfig:
     disabled: false
 clusterAutoscaling:
   autoscalingProfile: BALANCED
   enabled: false
 clusterIpv4Cidr: 10.0.00.00/16
 clusterTelemetry:
   type: ENABLED
 databaseEncryption:
   state: DECRYPTED
 defaultMaxPodsPerNode: 110
 defaultSnatStatus:
   disabled: false
 initialNodeCount: 1
 ipAllocationPolicy:
   clusterIpv4CidrBlock: 10.0.0.0/16
   clusterSecondaryRangeName: xpn-euw1-xxxx
   servicesIpv4CidrBlock: 10.0.0.0/21
   servicesSecondaryRangeName: xpn-euw1-xxxx
 location: europe-west1
 loggingService: logging.googleapis.com/kubernetes
 masterAuth:
   clientCertificateConfig:
     issueClientCertificate: false
   clusterCaCertificate: xxx
 monitoringService: monitoring.googleapis.com/kubernetes
 networkPolicy:
   enabled: true
   provider: CALICO
 networkRef:
   external: projects/xpn-xxx/global/networks/xpn-xxx
 networkingMode: VPC_NATIVE
 nodeConfig:
   diskSizeGb: 100
   diskType: pd-ssd
   imageType: COS_CONTAINERD
   linuxNodeConfig:
     sysctls:
       net.core.rmem_max: "26214400"
   machineType: e2-standard-2
   metadata:
     disable-legacy-endpoints: "true"
   oauthScopes:
   - https://www.googleapis.com/auth/cloud-platform
   - https://www.googleapis.com/auth/userinfo.email
   serviceAccountRef:
     external: xxxreator@xxxx.iam.gserviceaccount.com
   shieldedInstanceConfig:
     enableIntegrityMonitoring: true
   workloadMetadataConfig:
     nodeMetadata: GKE_METADATA_SERVER
 nodeLocations:
 - europe-west1-b
 - europe-west1-c
 - europe-west1-d
 releaseChannel:
   channel: RAPID
 subnetworkRef:
   external: projects/xpn-xxx/regions/europe-west1/subnetworks/xpn-euw1-xxx
 verticalPodAutoscaling:
   enabled: true
 workloadIdentityConfig:
   identityNamespace: xxxx.svc.id.goog
```
