### ISSUE TITLE
IAMPolicyMember for roles/dns.admin

### ISSUE THREAD

**Issue by infa-pavakuma** [GoogleCloudPlatform/k8s-config-connector#702]
### Describe your question

``` 
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: ext-dns-binding
  annotations:
    cnrm.cloud.google.com/project-id: "test"
spec:
  member: serviceAccount:external-dns-sa@test.iam.gserviceaccount.com
  role: roles/dns.admin
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: mysten-sui
```
I would like to Bind the SA to the role dns.admin. Is this possible through config connector?
