### ISSUE TITLE
Append Workload Identity using Config connector

### ISSUE THREAD

**Issue by infa-pavakuma** [GoogleCloudPlatform/k8s-config-connector#705]
### Describe your question

I am initially creating an IAMPolicy with some bindings 
```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicy
metadata:
  name: storage-admin-policy
  namespace: cnrm-system
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    cnrm.cloud.google.com/project-id: "mysten-sui"
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: storage-admin
    namespace: cnrm-system
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - serviceAccount:mysten-sui.svc.id.goog[monitoring/thanos-compactor] 
```
But I would want to append some new entries of workloadIdentityUser, for which I was using 
```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: ax001-sa-policy
  namespace: ax001
spec:
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: storage-admin
    namespace: cnrm-system
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - member: serviceAccount:mysten-sui.svc.id.goog[ax001/ax001-prometheus]
```
But it seems like the entries are not being appended, instead, they are being overridden. Is there any way that I can append rather than overriding?

**Comment by infa-pavakuma** [comment]
Any updates?

**Comment by diviner524** [comment]
@infa-pavakuma, there are different options to achieve what you desired:

1. Have one YAML/K8s resource as the single source of truth for all IAM policies of this IAMServiceAccount. This means instead of creating a new `IAMPartialPolicy`, you update the first `IAMPolicy` resource (or it's YAML in Git repo if you are using GitOps model) to include the change you want to introduce.
2. Always use `IAMPartialPolicy`. In this case if the two resources you created are all of type `IAMPartialPolicy`, then their members list will be merged as the actual IAM Policy of the resource, so the append purpose should be achieved.
3. Always use `IAMPolicyMember`. You may choose this option if every IAM resource you plan to add is only for one single member + one single role, because  `IAMPolicyMember` does not support a bindings list. If you are expecting a lot of bindings with many roles/members, this option is not recommended because it increases the number of K8s resources you need to manage and also increases the underlying API traffic against GCP IAM which might result in quota issues.


P.S. I noticed you are creating IAMServiceAccount under namespace `cnrm-system`. This is not recommended as `cnrm-system` is supposed to be used for Config Connector's core components only, and Config Connector users should avoid making changes to this namespace directly. Please consider using some other namespaces.

**Comment by infa-pavakuma** [comment]
Thanks, @diviner524. I did try using IAMPartialPolicy. In my GKE Cluster, I have 14 Iampartialpolicies, But in the Permissions section of the GCP SA, I only find 4. And the Pods that are expecting this Binding to be present enter Crash Loop Backoff state

**Comment by infa-pavakuma** [comment]
For example. See this exception. The same pod was able to upload to GCS Bucket an hour ago, now all of a sudden it shows
Logs
![image](https://user-images.githubusercontent.com/54094196/190887569-9b008589-73e9-4d03-af61-11b16ea18bc6.png)
IAMPartialBinding
![image](https://user-images.githubusercontent.com/54094196/190887598-ba47461f-cd7c-4224-a2ad-b50597f6e84b.png)
And the K8s SA is also annotated 
![image](https://user-images.githubusercontent.com/54094196/190887620-3a437958-0385-4b0f-a066-d5966d871b75.png)

**Comment by cloudpaldev** [comment]
+1 Even I see am observing the same behaviour. We are not sure if config connector is Production ready. Should we switch to any other solution?

**Comment by cloudpaldev** [comment]
May be we should consider using tools like cross plane?

**Comment by diviner524** [comment]
@infa-pavakuma Are you able to further isolate the problem? For example can you find the required IAM Policy from GCP Console.

Is it because the IAMPartialPolicy K8s resource was not able to actuate required IAM Policy in GCP?
Or the required IAM Policy was created successfully and can be found in GCP console, but it was not working as expected?

**Comment by infa-pavakuma** [comment]
Hi @diviner524, Nope the policy is being overridden by the most recent one that is being created. So all the ones that are being created earlier are not working

**Comment by diviner524** [comment]
@infa-pavakuma Thanks for confirming! Note that overridden is expected behavior if you are using both IAMPolicy and IAMPartialPolicy for the same resource.  

I assume you have already removed IAMPolicy and the issue can be reproduced using just IAMPartialPolicy?

Could you please provide us with sample YAMLs and reproduce steps so we can further investigate the issue? If possible please also update the original bug description.

**Comment by infa-pavakuma** [comment]
@diviner524 Yes you are correct, I am using a combination of IAMPolicy and IAMPartialPolicy

**Comment by infa-pavakuma** [comment]
@diviner524 So can I just use multiple IAMPartialPolicy instead of using IAMPolicy?

**Comment by diviner524** [comment]
@infa-pavakuma, IAMPolicy should not be used together with IAMPartialPolicy, as overridden will happen. See also the warning in IAMPolicy resource reference page:

"Warning: IAMPolicy should not be used in conjunction with IAMPolicyMember, IAMAuditConfig, and IAMPartialPolicy for the same resource."

https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iampolicy

**Comment by ldanielmadariaga** [comment]
This item has been open for >12 months. As part of scheduled repository maintenance, this Issue/PR will be closed. If this is still a critical ask, please re-open and work with your Google Cloud Account team to prioritize it with GCP KCC Product Management.

**Comment by bygui86** [comment]
Actually we found a sort of workaround using `IAMPartialPolicy` + `IAMPolicyMember`
and is not that bad ;)

```yaml
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: my-gcp-service-account
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    external: projects/my-gcp-project
    kind: Project
  bindings:
    - role: roles/iam.workloadIdentityUser
      members:
        - member: &sa serviceAccount:my-gcp-service-account@my-gcp-project.iam.gserviceaccount.com
    - role: roles/storage.objectUser
      members:
        - member: *sa
      condition:
        title: GCS bucket my-gcs-bucket
        expression: resource.name.startsWith("projects/_/buckets/my-gcs-bucket")

---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: my-gcp-service-account
spec:
  member: serviceAccount:my-gcp-project.svc.id.goog[my-k8s-namespace/my-k8s-service-account]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    kind: IAMServiceAccount
    name: my-gcp-service-account
```

Hope this is helpful
Cheers
