### ISSUE TITLE
SQLUser being "recreated" every few minutes

### ISSUE THREAD

**Issue by syphernl** [GoogleCloudPlatform/k8s-config-connector#706]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Related to #153 

Our `SQLUser` is being "re-created" (at least according to the docs) every few minutes:

![image](https://user-images.githubusercontent.com/639906/189903863-438fad79-2776-4101-a17f-19e209515226.png)

### Additional Diagnostic Information

Kubectl events show the following:

```shell
example      0s          Normal    Updating            sqluser/app-prod-db-user                          Update in progress
example      0s          Normal    UpToDate           sqluser/app-prod-db-user                           The resource is up to date
```

We have looked at the "Resource keeps updating every 5-15 mins" section in the docs but there is no `get` method for the SQL User so we cannot get its state from Google. 
This is probably also why this user is being "recreated" all the time?

### Kubernetes Cluster Version

v1.23.8-gke.1900

### Config Connector Version

1.93.0

### Config Connector Mode

namespaced mode (default)

### Log Output

{"severity":"info","timestamp":"2022-09-13T12:49:08.677Z","logger":"sqluser-controller","msg":"starting reconcile","resource":{"namespace":"example","name":"app-prod-db-user"}}
{"severity":"info","timestamp":"2022-09-13T12:49:09.006Z","logger":"sqluser-controller","msg":"creating/updating underlying resource","resource":{"namespace":"example","name":"app-prod-db-user"}}
{"severity":"info","timestamp":"2022-09-13T12:49:09.821Z","logger":"sqluser-controller","msg":"successfully finished reconcile","resource":{"namespace":"example","name":"app-prod-db-user"},"time to next reconciliation":"13m45.706017195s"}

### Steps to reproduce the issue

- Create `SQLUser`
- See that it will be "created" (according to GCP Console) or "updated" (according to kubectl) every few minutes.

### YAML snippets

```YAML
---
    apiVersion: sql.cnrm.cloud.google.com/v1beta1
    kind: SQLUser
    metadata:
        annotations:
            cnrm.cloud.google.com/project-id: app-prod
            cnrm.cloud.google.com/deletion-policy: abandon
        name: app-prod-db-user
        namespace: example
    spec:
        host: '%'
        resourceID: example_prod
        password:
            valueFrom:
                secretKeyRef:
                    key: password
                    name: example-postgres-secret
        instanceRef:
            name: app-prod-db
            namespace: example
```
