### ISSUE TITLE
Secret Versions constantly being created

### ISSUE THREAD

**Issue by kaldvelski** [GoogleCloudPlatform/k8s-config-connector#711]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

I'm using the config connector to create a Secret Manager and associated secret data. However, I'm finding although it gets created the connector is creating new versions of the secret every 2 minutes.

The controller log shows messages such as `Error reading SecretVersion: googleapi: Error 403: Permission 'secretmanager.versions.access' denied for resource 'projects/1234/secrets/my-secrets/versions/20' (or it may not exist).`

And then a few minutes later it's looking for version 21, then 22 etc. but each time a new version is actually created.

My config connector account has full Editor access to I don't think it's permissions based but rather the later message about the version not being found.

### Additional Diagnostic Information

n/a

### Kubernetes Cluster Version

Client Version: v1.22.0 Server Version: v1.21.14-gke.2700

### Config Connector Version

1.89.0

### Config Connector Mode

cluster mode

### Log Output

`{`
  `    "severity":"error",`
`  "timestamp":"2022-09-21T10:57:49.049Z",`
`  "logger":"controller.secretmanagersecretversion-controller",`
`  "msg":"Reconciler error",`
`  "reconciler group":"secretmanager.cnrm.cloud.google.com",`
`  "reconciler kind":"SecretManagerSecretVersion",`
`  "name":"my-secret-data",`
`  "namespace":"my-namespace",`
`  "error":"Update call failed: error applying desired state: summary: Error reading SecretVersion: googleapi: Error 403: Permission 
 'secretmanager.versions.access' denied for resource 'projects/1234/secrets/my-secrets/versions/20' (or it may not exist)."`
`}`

### Steps to reproduce the issue

I'm using Helm and Helmfile to deploy the templates - see below

### YAML snippets

```YAML
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecret
metadata:
  name: my-secrets
  labels:
    replication-type: user-managed
spec:
  replication:
    userManaged:
      replicas:
        - location: europe-west2
---
apiVersion: secretmanager.cnrm.cloud.google.com/v1beta1
kind: SecretManagerSecretVersion
metadata:
  name: my-secret-data
spec:
  enabled: true
  secretRef:
    name: my-secrets
  secretData:
    value: |
      secrets: 
         key: value
```
