### ISSUE TITLE
Unable to manage SQLInstance replicas

### ISSUE THREAD

**Issue by fsommar** [GoogleCloudPlatform/k8s-config-connector#714]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Hi,

We've noticed an issue that was introduced with the addition of the `sqlServerAuditConfig` field for SQLInstances. This affects instances that aren't SQL Server too, including both MySQL and PostgreSQL. In short, it's no longer possible to manage SQLInstance replicas as they end up in a perpetual `Updating` state. There are no errors exposed on the resource, but logs (see relevant section) emits an error.

### Additional Diagnostic Information

We used to run 1.84 and didn't have any issues with SQLInstance replicas with that version.

### Kubernetes Cluster Version

v1.21.14

### Config Connector Version

1.94

### Config Connector Mode

namespaced mode (default)

### Log Output

{
  "severity": "error",
  "timestamp": "2022-09-27T15:09:53.911Z",
  "logger": "controller.sqlinstance-controller",
  "msg": "Reconciler error",
  "reconciler group": "sql.cnrm.cloud.google.com",
  "reconciler kind": "SQLInstance",
  "name": "my-instance-replica",
  "namespace": "$PROJECT",
  "error": "error with update call to API server: SQLInstance.sql.cnrm.cloud.google.com \"my-instance-replica\" is invalid: spec.settings.sqlServerAuditConfig.bucketRef: Required value"
}

### Steps to reproduce the issue

To replicate, first create a regular SQLInstance. Note that non-replicas still work properly.

```
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: my-instance
  namespace: $PROJECT
spec:
  databaseVersion: POSTGRES_14
  region: europe-west1
  settings:
    tier: db-custom-1-3840
    diskAutoresize: true
    diskType: PD_SSD
    availabilityType: REGIONAL
```

Once that's successfully created, go into the Cloud Console and create a read replica with the default values.

Once the replica is created, let's use the `config-connector` CLI to import it.

```
config-connector export //sqladmin.googleapis.com/projects/$PROJECT/instances/my-instance-replica > replica.yaml
```

Note that the output includes `sqlServerAuditConfig` with zero values.

```
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: $PROJECT
  labels:
    managed-by-cnrm: "true"
  name: my-instance-replica
spec:
  databaseVersion: POSTGRES_14
  masterInstanceRef:
    external: my-instance
  region: europe-west1
  resourceID: my-instance-replica
  settings:
    activationPolicy: ALWAYS
    availabilityType: ZONAL
    backupConfiguration:
      backupRetentionSettings:
        retainedBackups: 7
        retentionUnit: COUNT
      startTime: "23:00"
      transactionLogRetentionDays: 7
    diskAutoresize: true
    diskAutoresizeLimit: 0
    diskSize: 10
    diskType: PD_SSD
    ipConfiguration:
      ipv4Enabled: true
    locationPreference:
      zone: europe-west1-b
    pricingPlan: PER_USE
    sqlServerAuditConfig:
      retentionInterval: 0s
      uploadInterval: 0s
    tier: db-custom-1-3840
```

Applying that resource (after changing it to use the $PROJECT namespace) results in:

```
error: error validating "replica.yaml": error validating data: ValidationError(SQLInstance.spec.settings.sqlServerAuditConfig): missing required field "bucketRef" in com.google.cloud.cnrm.sql.v1beta1.SQLInstance.spec.settings.sqlServerAuditConfig; if you choose to ignore these errors, turn validation off with --validate=false
```

Removing `sqlServerAuditConfig` and applying the resource works. But then it ends up in its perpetual `Updating` state:

```
❯ kubectl -n$PROJECT get sqlinstance my-instance-replica
NAME                  AGE   READY   STATUS     STATUS AGE
my-instance-replica   14m   False   Updating   14m

❯ kubectl -n$PROJECT get sqlinstance my-instance-replica -oyaml | yq '.status.conditions'
- lastTransitionTime: "2022-09-27T15:07:25Z"
  message: Update in progress
  reason: Updating
  status: "False"
  type: Ready
```
