### ISSUE TITLE
How do I reference outputs?

### ISSUE THREAD

**Issue by OperationalFallacy** [GoogleCloudPlatform/k8s-config-connector#715]
### Describe your question

Hi,

I could not figure out how to reference the outputs between resources.

For example, schema for IAMServiceAccount

```
conditions:
- lastTransitionTime: string
  message: string
  reason: string
  status: string
  type: string
email: string
name: string
observedGeneration: integer
uniqueId: string 
```

Is there a way to reference email string of service account in other resources?

For example, in the run service https://cloud.google.com/config-connector/docs/reference/resource-docs/run/runservice
there is `template.serviceAccountRef.external`

```
spec:
  launchStage: "GA"
  location: "us-central1" # kpt-set: region
  projectRef:
    external: ref # kpt-set: projects/${project-id}
  template:
    serviceAccountRef:
      external: ???
```

Thanks!
