### ISSUE TITLE
Support referencing IP from to be created GKE Ingress LoadBalancer

### ISSUE THREAD

**Issue by max-frank** [GoogleCloudPlatform/k8s-config-connector#716]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Similar to how support for referencing ComputeAddresses in DnsRecordSet is being/has been added (https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/101), it would be useful do be able to do the same for GKE Ingress LoadBalancers helping to bridge the gap between GKE and GCP resources 

e.g.,

```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ir
  namespace: {{ .Release.Namespace }}
  annotations:
    "networking.gke.io/managed-certificates": "{{ .Release.Name }}-cert"
spec:
  defaultBackend:
    service:
      name: {{ .Release.Name }}-platform-proxy
      port:
        name: opencti
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: dnsrecordset-sample-computeaddressreference
spec:
  name: "www.compute-address-reference-example.com."
  type: A
  ttl: 300
  managedZoneRef:
    name: dnsrecordset-dep-computeaddressreference
  rrdatasRefs:
    - name: dnsrecordset-dep-computeaddressreference
      kind: ComputeAddress
```

The information needed for this would be in the following JSON path of the Ingress resource

```
$.status.loadBalancer.ingress[0].ip
```

**Comment by maqiuyujoyce** [comment]
Hi @max-frank , thank you for the feedback! Just to confirm, you are suggesting that under `spec.rrdatasRefs` field in DNSRecordSet, users can reference a GKE Ingress LoadBalancer like below, right?

```
  rrdatasRefs:
    - apiVersion: networking.k8s.io/v1
      kind: Ingress
      name: ingress-name
      namespace: ns-name
      ... # Other fields for resource identification
```

It looks like that `status.loadBalancer.ingress` is a list, so in your use case, do you expect ip values for all ingresses in the list to be added? Or what's the UX do you expect this reference to be like?

Also, have you filed a ticket with GCP support? Just want to get some clarification as I saw that you checked the box for `If this request is time-sensitive, I have submitted a corresponding issue with GCP support.` but I didn't really find any internal ticket.
