### ISSUE TITLE
Error when creating CloudFunctionFunction

### ISSUE THREAD

**Issue by sthomson-wyn** [GoogleCloudPlatform/k8s-config-connector#718]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

When creating a CloudFunctionFunction, after successful creation, update fails with

```
Update call failed: error applying desired state: diffs exist after apply: [Field SourceRepository: got {empty:false,Url:"https://source.developers.google.com/projects/my-proj/repos/my-repo/moveable-aliases/master/paths/my-path",DeployedUrl:"https://source.developers.google.com/projects/my-proj/repos/my-repo/revisions/my-revision/paths/my-path"}, want {empty:false,Url:""https://source.developers.google.com/projects/my-proj/repos/my-repo/moveable-aliases/master/paths/my-path",DeployedUrl:nil}]
```

The resource is still created successfully initially

### Additional Diagnostic Information

n/a

### Kubernetes Cluster Version

v1.21.14-gke.700

### Config Connector Version

1.93.0

### Config Connector Mode

cluster mode

### Log Output

Update call failed: error applying desired state: diffs exist after apply: [Field SourceRepository: got {empty:false,Url:"https://source.developers.google.com/projects/my-proj/repos/my-repo/moveable-aliases/master/paths/my-path",DeployedUrl:"https://source.developers.google.com/projects/my-proj/repos/my-repo/revisions/my-revision/paths/my-path"}, want {empty:false,Url:""https://source.developers.google.com/projects/my-proj/repos/my-repo/moveable-aliases/master/paths/my-path",DeployedUrl:nil}]

### Steps to reproduce the issue

Create a CloudFunctionsFunction with a sourceRepository

### YAML snippets

```YAML
apiVersion: cloudfunctions.cnrm.cloud.google.com/v1beta1
kind: CloudFunctionsFunction
metadata:
  name: cluster-update-notification
spec:
  projectRef:
    name: proj
  region: "us-central1"
  runtime: "python37"
  availableMemoryMb: 256
  sourceRepository:
    url: "https://source.developers.google.com/projects/my-proj/repos/my-repo/moveable-aliases/master/paths/my-path"
  timeout: "60s"
  entryPoint: "main"
  eventTrigger:
    eventType: "providers/cloud.pubsub/eventTypes/topic.publish"
    resourceRef:
      name: "cluster-notification"
      kind: "PubSubTopic"
    failurePolicy: true
    service: "pubsub.googleapis.com"
```
