### ISSUE TITLE
Referencing existing secret in RunService

### ISSUE THREAD

**Issue by knowhoper** [GoogleCloudPlatform/k8s-config-connector#719]
### Describe your question

I would like to reference an existing secret in a different project from a RunService. I am unsure as to whether i need to create CC resources for the secret itself - I can't change the values of the existing secret, i just need to use it. 

The following YAML

```YAML
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: products-api-config-connector
  namespace: products-api
spec:
  ingress: "INGRESS_TRAFFIC_ALL"
  launchStage: "GA"
  location: "australia-southeast1"
  projectRef:
    external: projects/acme-development
  template:
    containers:
      - image: "australia-southeast1-docker.pkg.dev/acme-dev-tooling-project/docker-registry/cc-products-api:stg-v1.2.9"
        name:  products-api-config-connector
        ports:
          - name: http1
            containerPort: 5000
        env:
          - name: LOG_LEVEL
            value: INFO
          - name: client_id
            valueSource:
              secretKeyRef:
                secretRef:
                  external:  "projects/acme-dev-tooling-project/secrets/clientId"
                  namespace: products-api
              versionRef:
                  external: "latest"
                  namespace: products-api
                  
 ```
                  
  Yields:
  
  * <nil>: Invalid value: "": "spec.template.containers.env.valueSource.secretKeyRef.secretRef" must validate one and only one schema (oneOf). Found none valid
* <nil>: Invalid value: "": "spec.template.containers.env.valueSource.secretKeyRef.secretRef" must not validate the schema (not)

Is what i am attempting supported?
