### ISSUE TITLE
Incorrect project mapping when using secrets in CloudRun

### ISSUE THREAD

**Issue by knowhoper** [GoogleCloudPlatform/k8s-config-connector#720]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

the following CR YAML:

```YAML
        - name: ct_client_id
          valueFrom:
            secretKeyRef:
              key: latest
              name: cc-products-api_stg_clientId
        - name: ct_secret
          valueFrom:
            secretKeyRef:
              key: latest
              name: cc-products-api_stg_secret

```

This is not looking in the correct project for the secret and is causing issues. 

### Additional Diagnostic Information

I get the following errors - they are pointing to the wrong project:

spec.template.spec.containers[0].env[6].value_from.secret_key_ref.name: Permission denied on secret: projects/98080923809/secrets/cc-products-api_stg_clientId/versions/latest for Revision service account svc-cc-products-api@acme-development.iam.gserviceaccount.com. The service account used must be granted the 'Secret Manager Secret Accessor' role (roles/secretmanager.secretAccessor) at the secret, project or higher level. 

spec.template.spec.containers[0].env[7].value_from.secret_key_ref.name: Permission denied on secret: projects/98080923809/secrets/cc-products-api_stg_secret/versions/latest for Revision service account svc-cc-products-api@acme-development.iam.gserviceaccount.com. The service account used must be granted the 'Secret Manager Secret Accessor' role (roles/secretmanager.secretAccessor) at the secret, project or higher level.

### Kubernetes Cluster Version

v1.23.8-gke.1900

### Config Connector Version

1.82.0

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

Try to reference a secret contained in an external GSM to the project the current CR instance is in.
