### ISSUE TITLE
BillingBudgetsBudget amount.lastPeriodAmount is unusable

### ISSUE THREAD

**Issue by martinbeck-bestbuy** [GoogleCloudPlatform/k8s-config-connector#723]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

When attempting to create a BillingBudgetsBudget with amount.lastPeriodAmount the resource gets created but remains in an error state. There appears to be an issue with lastPeriodAmount as there has been no success with being able to deploy a BillingBudgetsBudget resource correctly using this attribute.

### Additional Diagnostic Information

To ensure the rest of our configuration is good in the YAML we've deployed with amount.specifiedAmount instead and the resource becomes healthy. This points to amount.lastPeriodAmount being the failure point.

After reaching out to Google support to figure out if perhaps there is an issue with the input we are using they gave us back the same input we were using which was:
lastPeriodAmount: {} 
When attempting to use an empty object in lastPeriodAmount it would still fail. We used a boolean true, that would fail. Attempted to set values similar to specifiedAmount this fails too. It appears the only way to create a Budget & Alert with lastPeriodAmount is manually within the GCP console.

We are unsure if perhaps there is another input that is desired but not documented, or if the CRD is just broken to start with.

### Kubernetes Cluster Version

v1.20.0

### Config Connector Version

1.95.0

### Config Connector Mode

namespaced mode (default)

### Log Output

Warning  UpdateFailed  21s (x4 over 35s)  billingbudgetsbudget-controller  Update call failed: error applying desired state: googleapi: Error 400: Request contains an invalid argument.

### Steps to reproduce the issue

1. Utilize the YAML below
2. Deploy the resource at org level budget&alerts.

### YAML snippets

```YAML
apiVersion: billingbudgets.cnrm.cloud.google.com/v1beta1
kind: BillingBudgetsBudget
metadata:
  name: lastperiodamount-test
  namespace: org-resource-mgmt
  annotations:
    cnrm.cloud.google.com/deletion-policy: “abandon”
spec:
  billingAccountRef:
    external: < REDACTED >
  budgetFilter:
    calendarPeriod: “MONTH”
    projects:
      - external: ‘projects/bbyus-cplat-discovery-rn-s63’
  amount:
    lastPeriodAmount: {}
```
