### ISSUE TITLE
More granular support for dealing with AccessContextManagerServicePerimeter resources

### ISSUE THREAD

**Issue by wmuizelaar** [GoogleCloudPlatform/k8s-config-connector#727]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

**Introduction** 

We use the functionality of VPC Service Controls heavily within our Google Cloud Organization and setup, most, if not all, of the available APIs are protected with this toolset. 

Our Cloud-setup is split up into multiple “environments”, like a production environment, a non-production environment, and some corner cases. Every environment has its own perimeter, and all of the projects that we create are programmatically added to the perimeter from our internal (bespoke) provisioning tool. Currently we rely on the Gcloud SDK for that (`gcloud access-context-manager perimeters update <perimeter> --policy <policy> --add-resources=”projects/<projectnumber>”`), but not too long ago this functionality was also made available in the Terraform provider (https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/access_context_manager_service_perimeter_resource). 

We also have some bridges to bridge different environments and perimeters, and projects might need to be added to one or more bridges as well. 

Furthermore, we also have a lot of Ingress and Egress Policies on our perimeters, which we currently also manage individually, so we can combine programmatically generated rules with statically defined rules.  
 

We are migrating our setup towards using Config Connector (KCC) in combination with tools like `kpt`, instead of relying on a lot of bespoke tooling. To be able to migrate our VPC SC functionality, we would like to request a split up of different VPC SC related resources, as the current single existing resource (https://cloud.google.com/config-connector/docs/reference/resource-docs/accesscontextmanager/accesscontextmanagerserviceperimeter) to manage all of this in 1 (very large) resource does not fit our dynamic environment where we want to be able to add / remove resources and rules on perimeters individually, and not having to adjust the 1 single file every time we need this. 

 Therefore we’d like to propose the following resources: 

 **AccessContextManagerServicePerimeterBase**

The resource that creates the basics of the perimeter, excluding the Ingress/Egress rules and the resources. 

It would have the following schema: 

```
spec: 
  accessPolicyRef: 
    external: string 
    name: string 
    namespace: string 
  description: string 
  perimeterType: string 
  resourceID: string 
  accessLevels: 
  - external: string 
    name: string 
    namespace: string 
  restrictedServices: 
  - string 
  vpcAccessibleServices: 
    allowedServices: 
    - string 
    enableRestriction: boolean 
status: 
  accessLevels: 
  - external: string 
    name: string 
    namespace: string 
  restrictedServices: 
  - string 
  vpcAccessibleServices: 
    allowedServices: 
    - string 
    enableRestriction: boolean 
  title: string 
  useExplicitDryRunSpec: boolean
  conditions:
  - lastTransitionTime: string
    message: string
    reason: string
    status: string
    type: string 
```

**AccessContextManagerServicePerimeterResource** 

The resource that defines the existence of a single resource in a specific perimeter. 

It would have the following schema: 

```
spec: 
  resourceID: string 
  perimeterBaseRef: # this would point to the above PerimeterBase 
      external: string 
      name: string 
      namespace: string 
  resource: 
    projectRef: 
      external: string 
      name: string 
      namespace: string 
status:
  conditions: 
  - lastTransitionTime: string
    message: string
    reason: string
    status: string
    type: string
```
 
**AccessContextManagerServicePerimeterEgressPolicy** 

The resource that defines the existence of a single Egress Policy in a specific perimeter. 

It would have the following schema: 
```
spec: 
  resourceID: string
  perimeterBaseRef: # this would point to the above PerimeterBase 
      external: string 
      name: string 
      namespace: string 
  egressFrom: 
    identities: 
    - serviceAccountRef: 
        external: string 
        name: string 
        namespace: string 
      user: string 
    identityType: string 
  egressTo: 
    externalResources: 
    - string 
    operations: 
    - methodSelectors: 
      - method: string 
        permission: string 
      serviceName: string 
    resources: 
    - projectRef: 
        external: string 
        name: string 
        namespace: string 
status:
  conditions: 
  - lastTransitionTime: string
    message: string
    reason: string
    status: string
    type: string
```

**AccessContextManagerServicePerimeterIngressPolicy** 

The resource that defines the existence of a single Ingress Policy in a specific perimeter. 

It would have the following schema: 
```
spec: 
  resourceID: string
  perimeterBaseRef: # this would point to the above PerimeterBase 
      external: string 
      name: string 
      namespace: string 
  ingressFrom: 
    identities: 
    - serviceAccountRef: 
        external: string 
        name: string 
        namespace: string 
      user: string 
    identityType: string 
  ingressTo: 
    externalResources: 
    - string 
    operations: 
    - methodSelectors: 
      - method: string 
        permission: string 
      serviceName: string 
    resources: 
    - projectRef: 
        external: string 
        name: string 
        namespace: string 
status:
  conditions: 
  - lastTransitionTime: string
    message: string
    reason: string
    status: string
    type: string
```
 
The Config Connector controller would then do all the interactions with the actual accescontextmanager API and patch the perimeter based on the individual resources that it sees. It needs to be indicated clearly in the documentation that one should use either this (set of) resources, OR the existing one, just like the `IAMPolicy` and `IAMPolicyMember` resources are mutually exclusive. This proposal tries to follow the same pattern.

### Additional information

https://cloud.google.com/access-context-manager/docs/reference/rest/v1/accessPolicies.servicePerimeters - the code would need to use the `patch` operation here to modify the perimeter based on the intent of the user.

### Importance

This is becoming a blocker for us soon - currently we can workaround this by using manually crafted gcloud commands, but that doesn't scale very well.
