### ISSUE TITLE
storageTarget unsupported in BigtableInstance CRD

### ISSUE THREAD

**Issue by travisrandolph-bestbuy** [GoogleCloudPlatform/k8s-config-connector#729]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

It appears that storageTarget isn't actually a supported field for cluster autoscaling config. When we try to add the storageTarget configuration we are seeing an error that states it's an unknown field.

<img width="880" alt="image" src="https://user-images.githubusercontent.com/75803296/198701542-b762d298-1330-4b11-8313-57948d59522f.png">

### Additional Diagnostic Information

`error: error validating "test.yaml": error validating data: ValidationError(BigtableInstance.spec.cluster[0].autoscalingConfig): unknown field "storageTarget" in com.google.cloud.cnrm.bigtable.v1beta1.BigtableInstance.spec.cluster.autoscalingConfig; if you choose to ignore these errors, turn validation off with --validate=false`

### Kubernetes Cluster Version

v1.22.12-gke.2300

### Config Connector Version

1.95.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

Deploy the YAML snippet below.

### YAML snippets

```YAML
apiVersion: bigtable.cnrm.cloud.google.com/v1beta1
kind: BigtableInstance
metadata:
  name: bigtable-test
spec:
  displayName: BigtableAuto
  instanceType: PRODUCTION
  resourceID: bigtable-test
  cluster:
  - clusterId: test-cluster
    zone: us-central1-a
    autoscalingConfig:
      cpuTarget: 25
      maxNodes: 10
      minNodes: 1
      storageTarget: 3000
```
