### ISSUE TITLE
How do I connect SQLInstance to RunService?

### ISSUE THREAD

**Issue by jtcressy** [GoogleCloudPlatform/k8s-config-connector#736]
### Describe your question

I can't find any examples on this use case in the documentation, so I've tried to use the fields in `spec` as-is:
```yaml
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: server
spec:
  template:
    ...
    volumes:
    - name: sql
      cloudSqlInstance:
        instances:
        - name: db
```
And I have a `SQLInstance` named `db` in the same namespace as this `RunService`
however i'm getting this error in the `status` field of the `RunService` after applying the resources:
```
status:
  conditions:
    - lastTransitionTime: '2022-11-11T19:57:44Z'
      message: >-
        Update call failed: error fetching live state: error converting to lite
        state: error converting list item: error resolving reference field
        instances: error resolving target field value for referenced resource
        my-namespace/db with GroupVersionKind
        sql.cnrm.cloud.google.com/v1beta1, Kind=SQLInstance: couldn't resolve
        the value for target field instanceName from the referenced resource
        my-namespace/db
      reason: UpdateFailed
      status: 'False'
      type: Ready
  observedGeneration: 3
```

Further, how can I expose the connection string for the SQLInstance once I do get this working? Documentation requires I expose it as an environment variable in the container spec, but the only way to insert the value is either directly in hard-coded yaml or by referencing a GCP Secret Manager secret version. At this rate I have no idea how i'm going to export the connection string to GCPSM.

Oh also there's an annotation of `run.googleapis.com/cloudsql-instances` that seems to be required with the connection string so now I need to find a way of modifying the RunService's spec after apply, and that just does not work well with any GitOps tooling.
