### ISSUE TITLE
ComputeRegionNetworkEndpointGroup not found in the CRDs

### ISSUE THREAD

**Issue by SabySen** [GoogleCloudPlatform/k8s-config-connector#738]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Trying to install the CRD ComputeRegionNetworkEndpointGroup and it complains that there are no CRDs with the name "ComputeRegionNetworkEndpointGroup" in the "compute.cnrm.cloud.google.com". Hence we are unable to create one.
here is the spec referred to 
```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRegionNetworkEndpointGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
    cnrm.cloud.google.com/project-id: gcp-project-test1
  labels:
    app.kubernetes.io/instance: glb-related
  name: my-sample-cloud-run-neg
  namespace: cc-resources
spec:
  cloudRun:
    serviceRef:
      external: my-sample-cloud-run
  description: >-
    neg for cloud run for the testing
    if it works
  networkEndpointType: SERVERLESS
  region: us-east4

```

Error was
```
ComputeRegionNetworkEndpointGroup.compute.cnrm.cloud.google.com "" not found
```

### Additional Diagnostic Information

the documentation mentions it is present ..
https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computeregionnetworkendpointgroup

### Kubernetes Cluster Version

 v1.25.4

### Config Connector Version

1.69.0

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

1. create a cloud run service
2. install the spec given and you will get the error

### YAML snippets

```YAML
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRegionNetworkEndpointGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '-5'
    cnrm.cloud.google.com/project-id: gcp-project-test1
  labels:
    app.kubernetes.io/instance: glb-related
  name: my-sample-cloud-run-neg
  namespace: cc-resources
spec:
  cloudRun:
    serviceRef:
      external: my-sample-cloud-run
  description: >-
    neg for cloud run for the testing
    if it works
  networkEndpointType: SERVERLESS
  region: us-east4
```
