### ISSUE TITLE
ComputeRouterNAT and drainNatIps

### ISSUE THREAD

**Issue by mikesharpton-bestbuy** [GoogleCloudPlatform/k8s-config-connector#749]
### Describe your question

I am working with the yaml below to create a Cloud NAT.  I have the router, route, IP's etc all configured and working.  Below is my yaml.

```
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: cloud-nat
spec:
  region: us-central1
  routerRef:
    name: computerouter-cloudnat
  natIpAllocateOption: MANUAL_ONLY
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_PRIMARY_IP_RANGES
  natIps:
  - name: cloud-nat-ip01
  - name: cloud-nat-ip02
  tcpEstablishedIdleTimeoutSec: 1200
  tcpTransitoryIdleTimeoutSec: 30
  udpIdleTimeoutSec: 30
  icmpIdleTimeoutSec: 30
  logConfig:
    enable: true
    filter: ALL
  minPortsPerVm: 32
  maxPortsPerVm: 256
  enableDynamicPortAllocation: true
  enableEndpointIndependentMapping: false
  # Need to be able to support setting draining on Cloud NAT IP's
  # You have to unset/remove the IP you plan to drain above, then configure it to drain
  # Once drained, all you should need to do is remove the drainNatIps below, but this does not delete the IP from the Cloud NAT.
  # drainNatIps:
  #   - name: cloud-nat-ip01
```

I am trying to place an IP into a draining state and then eventually remove the IP from the NAT configuration entirely.  This may or may not be how this works.

I attempted to add the elements below to get the IP to start draining the IP from above.

```
drainNatIps:
    - name: cloud-nat-ip01
```

I did not remove the ip that I want to drain from the natIps section.  I am presented with this error when I do this.
`Warning  UpdateFailed  25s (x9 over 6m32s)  computerouternat-controller  Update call failed: error calculating diff: drain_nat_ip "cloud-nat-ip01" cannot be drained if still set in nat_ips [cloud-nat-ip02 cloud-nat-ip01]`

OK, so we need to remove the IP from the natIps section and add the drainNatIps section.  I do this, and the IP shows as draining.  This is good.

This is the yaml I applied.
```
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: cloud-nat
spec:
  region: us-central1
  routerRef:
    name: computerouter-cloudnat
  natIpAllocateOption: MANUAL_ONLY
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_PRIMARY_IP_RANGES
  natIps:
  # - name: cloud-nat-ip01
  - name: cloud-nat-ip02
  tcpEstablishedIdleTimeoutSec: 1200
  tcpTransitoryIdleTimeoutSec: 30
  udpIdleTimeoutSec: 30
  icmpIdleTimeoutSec: 30
  logConfig:
    enable: true
    filter: ALL
  minPortsPerVm: 32
  maxPortsPerVm: 256
  enableDynamicPortAllocation: true
  enableEndpointIndependentMapping: false
  # Need to be able to support setting draining on Cloud NAT IP's
  # You have to unset/remove the IP you plan to drain above, then configure it to drain
  # Once drained, all you should need to do is remove the drainNatIps below, but this does not delete the IP from the Cloud NAT.
  drainNatIps:
    - name: cloud-nat-ip01
```
   
Once this IP is drained, I would want to completely remove the IP from this Cloud NAT.  I would assume to remove the last part (drainNatIps) that references the drained IP would be what we need to do.  

When I remove the drained IP (all references to this IP are now gone), the IP is not deleted. It remains in draining and is not deleted from the configuration.  This may be the way Cloud NAT intends this to be, but it seems odd I can remove an IP without draining it.  Connections would be severed immediately. When I try to drain, I can get the IP to drain, but I cannot delete it from the configuration via Config Connector.  It is also possible, I have missed something obvious.

I can also see that the reference for the draining IP changes from the CC name to the external ref.  Why it does this I do not know.

```
Spec:
  Drain Nat Ips:
    External:                           https://www.googleapis.com/compute/v1/projects/project/regions/us-central1/addresses/cloud-nat-ip01
  Enable Dynamic Port Allocation:       true
  Enable Endpoint Independent Mapping:  false
  Icmp Idle Timeout Sec:                30
  Log Config:
    Enable:                true
    Filter:                ALL
  Max Ports Per Vm:        256
  Min Ports Per Vm:        32
  Nat Ip Allocate Option:  MANUAL_ONLY
  Nat Ips:
    Name:       cloud-nat-ip02
  Region:       us-central1
  Resource ID:  cloud-nat
  Router Ref:
    Name:                              computerouter-cloudnat
  Source Subnetwork Ip Ranges To Nat:  ALL_SUBNETWORKS_ALL_PRIMARY_IP_RANGES
  Tcp Established Idle Timeout Sec:    1200
  Tcp Transitory Idle Timeout Sec:     30
  Udp Idle Timeout Sec:                30
```

We are on v1.96.0 of Config Connector.

**Comment by maqiuyujoyce** [comment]
Hi @mikesharpton-bestbuy , thank you for reporting the issue with all the details!

> When I remove the drained IP (all references to this IP are now gone), the IP is not deleted.

IIUC, you tried to remove the drained IP from the ComputeRouterNAT configuration by removing the entire `drainNatIps` field like below, right?
```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
  name: cloud-nat
spec:
  region: us-central1
  routerRef:
    name: computerouter-cloudnat
  natIpAllocateOption: MANUAL_ONLY
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_PRIMARY_IP_RANGES
  natIps:
  # - name: cloud-nat-ip01
  - name: cloud-nat-ip02
  tcpEstablishedIdleTimeoutSec: 1200
  tcpTransitoryIdleTimeoutSec: 30
  udpIdleTimeoutSec: 30
  icmpIdleTimeoutSec: 30
  logConfig:
    enable: true
    filter: ALL
  minPortsPerVm: 32
  maxPortsPerVm: 256
  enableDynamicPortAllocation: true
  enableEndpointIndependentMapping: false
  # Need to be able to support setting draining on Cloud NAT IP's
  # You have to unset/remove the IP you plan to drain above, then configure it to drain
  # Once drained, all you should need to do is remove the drainNatIps below, but this does not delete the IP from the Cloud NAT.
#  drainNatIps:
#    - name: cloud-nat-ip01
```

In Config Connector, removing a previously configured field means "unmanaging the field", i.e. "I don't want to use Config Connector to manage the field any more". That's why the drained IP was not removed. If you want to remove the drained IP when it's the only item in the list, you'll need to set the list to empty. Please find the instructions here: https://cloud.google.com/config-connector/docs/troubleshooting#unable_to_remove_fields_from_resource_spec.
