### ISSUE TITLE
containerCluster status shows error related to NodeConfig.

### ISSUE THREAD

**Issue by droot** [GoogleCloudPlatform/k8s-config-connector#753]
### Describe your question

I launched a GKE cluster by applying following yaml.

```yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: dev-1
  namespace: config-control
spec:
  description: Development demo cluster for Bank of Anthos deployment
  enableAutopilot: true
  location: us-west1
```

I queried the the clusterstatus and it became ready after a while. After sometime, the status showing following conditions:

{"lastTransitionTime":"2022-12-15T03:37:03Z","message":"Update call failed: cannot make changes to immutable field(s): [nodeConfig.0.Spot nodeConfig.0.OauthScopes.# nodeConfig.0.WorkloadMetadataConfig.# nodeConfig.0.GuestAccelerator.# nodeConfig.0.Metadata.% nodeConfig.0.OauthScopes.316356861 nodeConfig.0.ShieldedInstanceConfig.# nodeConfig.0.OauthScopes.172152165 nodeConfig.0.OauthScopes.3663490875 nodeConfig.# nodeConfig.0.OauthScopes.3859019814 nodeConfig.0.OauthScopes.1632638332 nodeConfig.0.OauthScopes.1277378754 nodeConfig.0.Preemptible]; please refer to our troubleshooting doc: https://cloud.google.com/config-connector/docs/troubleshooting","reason":"UpdateFailed","status":"False","type":"Ready"}}

I am using some code that uses `connectorContext` to talk to it programmatically. Though, I am able to establish client connection to the cluster and query resources nicely. I was planning to filter clusters that are only READY, but ran into this failed condition.
