### ISSUE TITLE
ComputeForwardingRule - serviceDirectoryRegistrations doesn't support region

### ISSUE THREAD

**Issue by davelanglois-ssc** [GoogleCloudPlatform/k8s-config-connector#754]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

I'm trying to implement this [procedure ](https://cloud.google.com/vpc/docs/configure-private-service-connect-apis). When you get to this [section](https://cloud.google.com/vpc/docs/configure-private-service-connect-apis#create-endpoint),  at the ForwardingRule step, I have to be able to specify the region in the serviceDirectoryRegistrations. If I don't specify it, the servicedirectorynamespace gets created in the us-central1 region. The config connector [resource](https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computeforwardingrule) schema doesn't support the region whereas, the compute API does support it.

### Additional Diagnostic Information

none

### Kubernetes Cluster Version

Client Version: v1.23.1 Server Version: v1.23.12-gke.1600

### Config Connector Version

1.97.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

none

### YAML snippets

```YAML
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: thisisatestproject3-apis-private-ip
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: thisisatestproject3
spec:
  resourceID: xx-m-apis-private-ip
  address: 10.255.255.254
  addressType: INTERNAL
  location: global
  networkRef:
    name: thisisatestproject3-vpc1
  purpose: PRIVATE_SERVICE_CONNECT
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeForwardingRule
metadata:
  name: thisisatestproject3-endpoint1
  namespace: networking
  annotations:
    cnrm.cloud.google.com/project-id: thisisatestproject3
spec:
  resourceID: endpoint1
  ipAddress:
    addressRef:
      name: thisisatestproject3-apis-private-ip
  location: global
  # serviceDirectoryRegistrations:
  # - namespace: thisisatestproject3-servicedirectorynamespace
  #   service: xx-m-endpoint1
  networkRef:
    name: thisisatestproject3-vpc1
  target:
    targetHTTPProxyRef:
      external: all-apis
  loadBalancingScheme: ""
```
