### ISSUE TITLE
Unable to deploy IAMPolicyMember on GCP due to required resourceRef.name

### ISSUE THREAD

**Issue by andymakesapps** [GoogleCloudPlatform/k8s-config-connector#756]
### Describe your question

I am trying to deploy a role for one of my service accounts via [IAMPolicyMember](https://cloud.google.com/config-connector/docs/reference/resource-docs/iam/iampolicymember) all whilst avoiding the use of the spec.resourceRef.external field.
In other words, instead of this:
```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-sample-projlevel
  namespace: my-namespace
spec:
  member: serviceAccount:iamserviceaccount-sample@my-project.iam.gserviceaccount.com
  role: roles/storage.admin
  resourceRef:
    kind: Project
    external: projects/my-project
```

I am running this:

```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-sample-projlevel
  namespace: my-namespace
  annotations:
    cnrm.cloud.google.com/project-id: my-project
spec:
  member: serviceAccount:iamserviceaccount-sample@my-project.iam.gserviceaccount.com
  role: roles/storage.admin
  resourceRef:
    kind: Project
```

However every time I run it I get the following error:
```
* <nil>: Invalid value: "": "spec.resourceRef" must validate one and only one schema (oneOf). Found none valid
* spec.resourceRef.name: Required value
```

And I am not sure where this is coming from, as I followed similar steps as before when it worked fine. My set up is a simple cluster with Config Connector enabled where the namespace my-namespace has been annotated to the project my-project.
