### ISSUE TITLE
IAMServiceAccount + CloudIdentityMembership race condition

### ISSUE THREAD

**Issue by ppawiggers** [GoogleCloudPlatform/k8s-config-connector#760]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

I use config connector to create a GCP Service Account and add it as a member to an existing Google Group, see YAML manifests below.

This works fine, the GSA is created and added to the existing Google group. However, when I delete a namespace with both config connector resources, the CloudIdentityMembership sometimes gives this error:

```
Delete call failed: error fetching live state: error reading underlying
      resource: googleapi: Error 403: Error(2028): Permission denied for resource
      groups/mygroup/memberships/123 (or it may not exist).
```

I think this is a race condition - if the IAMServiceAccount gets deleted, it's also removed as member of the group. If after that it tries to delete the membership, it fails because it's not a member of the group anymore.

As far as I can't tell, I can refer to the IAMServiceAccount object in the CloudIdentityMembership (which I usually can). That would probably solve it though.

### Additional Diagnostic Information

None

### Kubernetes Cluster Version

v1.23.13-gke.900

### Config Connector Version

1.82.0

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

1. Create the IAMServiceAccount manifest
2. Create a CloudIdentityMembership manifest to add the SA to a group
3. Remove the IAMServiceAccount, wait until GSA is deleted
4. Remove the CloudIdentityMembership, this will fail.

### YAML snippets

```YAML
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: sa
---
apiVersion: cloudidentity.cnrm.cloud.google.com/v1beta1
kind: CloudIdentityMembership
metadata:
  name: membership
spec:
  groupRef:
    external: groups/mygroup
  preferredMemberKey:
    id: sa@myproject.iam.gserviceaccount.com
  roles:
  - name: MEMBER
```

**Comment by maqiuyujoyce** [comment]
Hi @ppawiggers , thank you for reporting the issue.

Is the underlying Cloud Identity Membership resource (the GCP resource) gone after step#3 (in `Steps to reproduce the issue`), or is it still existent?
If the underlying GCP resource is already gone, then to delete the corresponding CloudIdentityMembership resource in Config Connector, you can set deletion policy to abandon, and abandon the resource. It'll be [steps#1-#3 in this troubleshooting section](https://cloud.google.com/config-connector/docs/troubleshooting#error_updating_the_immutable_fields_when_there_is_no_update).

Right now, Config Connector cannot handle deletion ordering properly. One alternative is to use the [`depends-on` annotation](https://kpt.dev/reference/annotations/depends-on/) in [kpt](https://github.com/GoogleContainerTools/kpt)/[ConfigSync](https://cloud.google.com/anthos-config-management/docs/config-sync-overview)/[Anthos Config Management](https://cloud.google.com/anthos-config-management/docs/overview) to work around the problem. Here is an [tutorial for the annotation](https://kpt.dev/book/06-deploying-packages/03-handling-dependencies).

**Comment by jb-metzger** [comment]
Hi @maqiuyujoyce, following up on your comment and responding on behalf of @ppawiggers.

The underlying Cloud Identity Membership isn't gone, So abandoning the resource isn't an option.
ConfigSync is also not an option as we use fluxcd. 

For now as a workaround our pipeline first deletes Cloud Identity Membership, waits for reconciliation and then deletes the IAM Service Account.

**Comment by jb-metzger** [comment]
@maqiuyujoyce Do you know if a long term fix is already planned where one could natively set "depends-on"-like values? I would assume that not only CloudIdentityMembership and IAMServiceaccount have this kind of dependency.

**Comment by Magic-Mayo** [comment]
We just ran into this issue and it would be great if this could be fixed upstream instead of having to implement our own solution.  In our case we wanted to fully delete the namespace but the `IAMServiceAccount` is deleted first and the  `CloudIdentityMembership` still exists in the namespace which holds up namespace deletion which then requires manual intervention for the moment.

**Comment by maqiuyujoyce** [comment]
@gemmahou I recall you worked on a similar issue. Do you happen to know some context about how we address deletion ordering now?

**Comment by gemmahou** [comment]
For this specific case as shown in the YAML:
```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: sa
---
apiVersion: cloudidentity.cnrm.cloud.google.com/v1beta1
kind: CloudIdentityMembership
metadata:
  name: membership
spec:
  groupRef:
    external: groups/mygroup
  preferredMemberKey:
    id: sa@myproject.iam.gserviceaccount.com
  roles:
  - name: MEMBER
```

The IAMServiceAccount is used as a string value in the `preferredMemberKey.id` field, not as a reference or dependency. So I'm afraid there's no way for us to determine the status of IAMServiceAccount during CloudIdentityMembership reconciliation
