### ISSUE TITLE
Ability to create BigQuery LoggingLogSink and grant it permissions simultaneously

### ISSUE THREAD

**Issue by LiptonB** [GoogleCloudPlatform/k8s-config-connector#761]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

When creating a LoggingLogSink that writes to BigQuery, one also needs to grant the sink's service account permission to write to the configured BigQuery dataset. To do this with config connector, I believe you currently need multiple steps:
- Create the BigQueryDataset and the LoggingLogSink
- Wait for both to be reconciled so you can get the `status.writerIdentity` from the LoggingLogSink
- Modify the BigQueryDataset to add the sink's service account to its `spec.access`

Alternatively, you can choose between two lower-security options:
- Grant the log sink access to the whole project using IAMPartialPolicy. This can be done all at once because the LoggingLogSink can be referenced with `memberFrom.logSinkRef` in the IAMPartialPolicy. However, you can not target a BigQueryDataset with an IAMPartialPolicy, and the `spec.access` on BigQueryDataset doesn't support `logSinkRef`.
- Set `uniqueWriterIdentity: false` on the LoggingLogSink so that the service account name can be predicted ahead of time (although this doesn't seem to work with folder or org-level log sinks).

### Importance

This is a (minor) pain point for us because we use config connector via gitops (Anthos Config Management) so it currently takes two PRs to deploy a log sink. Being able to use references to create all the resources and permissions in a single PR would reduce the friction of this process.

**Comment by LiptonB** [comment]
I suppose this is related to https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/256 in the sense that being able to reference BigQueryDatasets in IAMPolicyMember/IAMPartialPolicy is one way this could be solved. But I decided to made a separate issue because any solution that enabled us to create all the resources with a single config change would be fine for us.

**Comment by diviner524** [comment]
Thank you for filing the enhancement request @LiptonB!

The fundamental issue here is because the datasets REST resource in GCP does not support the `getIamPolicy` and `setIamPolicy` methods. This makes it difficult for us to integrate it with our IAM(Partial)Policy(Member) CRDs. We have experimented it with some workarounds which turns out to be problematic.

Since you mentioned you are using ACM, have you heard of the `apply-time-mutation` feature in Kpt?

https://kpt.dev/reference/annotations/apply-time-mutation/

If you are using Kpt + KCC, then this feature should be able to workaround your scenario. If you are using Config Sync, unfortunately you will need to wait until the same feature is implemented in Config Sync.

**Comment by cartyc** [comment]
@LiptonB bumped into this a while back and found that  the `IAMPartialPolicy`  resource has the ability to target logsinks which solved the problem for us.

Here's a slightly modified version of what we're using
```
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata: 
  name: bq-sink-writer
  namespace: config-control # kpt-set: ${namespace}
  annotations:
    config.kubernetes.io/depends-on: logging.cnrm.cloud.google.com/namespaces/config-control/LoggingLogSink/bigquery-logsink # kpt-set: logging.cnrm.cloud.google.com/namespaces/${namespace}/LoggingLogSink/bigquery-logsink
spec:
  resourceRef:
    kind: Project
    name: project-id # kpt-set: ${project-id}
  bindings:
    - role: roles/bigquery.dataOwner
      members:
        - memberFrom: 
            logSinkRef:
              name: bigquery-logsink
    ````
