### ISSUE TITLE
Enable the ability to do Private Service Connect Consumer to published services

### ISSUE THREAD

**Issue by snuggie12** [GoogleCloudPlatform/k8s-config-connector#763]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

According to TF docs a consumer can more or less be created by creating the following resources:
- ComputeForwardingRule
- ComputeAddress

The `ComputeForwardingRule` requires a new target type to hit the service attachment.

However, when you create a consumer using the console additional objects get created:
- ServiceDirectoryNamespace
- ServiceDirectoryEndpoint
- ServiceDirectoryService
- A private service connection? I'm not sure how to see the object using something like "rest equivalent", but it does have a `PSC Connection ID` so I presume it's an object of some sort.

Weirdly the service directory API doesn't need enabled to work, but I turned it on to see which objects were getting created.

I'm willing to try and create all these objects separately but at the very least I think the forwarding rule needs updated in order to talk to a service attachment.

### Additional information

https://cloud.google.com/vpc/docs/configure-private-service-connect-services#create-endpoint shows similar instructions to the terraform docs.

### Importance

We are currently testing this feature out so it's not a blocker since this can be created via other means, but using kcc is our preference with these things.

**Comment by snuggie12** [comment]
I also discovered that `ServiceDirectoryService` is missing the `type` field where you can say the service is a `PRIVATE_SERVICE_CONNECT`. Not sure if that creates the forwarding rule for you or not.

**Comment by jmisasa** [comment]
Hi, curious if there is any update on this? We ended up creating a PSC via other means as well, but using CC is as well our preference so just a quick ping to mention we'd be interested in this, thanks in advance!

**Comment by schmurfy** [comment]
I just found out that there is no way to create a forwarding rule pointing to a serviceAttachment (PSC), I really need it too :/

**Comment by diviner524** [comment]
@snuggie12 Are you asking the `target` field in `ComputeForwardingRule` to support `ComputeServiceAttachement`? 

Something like below?

```
spec:
  target:
    targetServiceAttachmentRef:
      external: "projects/destination-project/regions/us-east1/serviceAttachments/target-service
```

**Comment by Dineshvcetster** [comment]
yes @diviner524 , We too expect this behavior

**Comment by Dineshvcetster** [comment]
Also in the config connector docs, we could see only the below targets  and not for ServiceAttachmentRef

![image](https://github.com/GoogleCloudPlatform/k8s-config-connector/assets/129482901/e72ee09d-6543-4e45-99c6-299bb7beccc7)

**Comment by diviner524** [comment]
@Dineshvcetster: So ideally we want to add `targetServiceAttachmentRef` to support referencing a ComputeServiceAttachment resource.

Having said that, I believe we can use the `external` field of any other existing ref fields as a workaround, for example:

```
spec:
  target:
    targetTCPProxyRef:
      external: "projects/destination-project/regions/us-east1/serviceAttachments/target-service
```

On top of the workaround above, there are a few other known issues with this combination, @justinsb has a recent [fix](https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/944 ) for this scenario, which should be included in our next release (v1.111.0). I suggest you wait until the release is out and then apply the workaround above to see if it works.

**Comment by Dineshvcetster** [comment]
@diviner524, we tried with config connector v1.111.0 version but ended with below error

**Error creating ForwardingRule: googleapi: Error 400: Invalid value for field 'resource.IPAddress': ''. The URL is malformed., invalid**

I tried with addressType Internal, External and allowed psc to be global but still getting same issue.

Below Config i have used in my case.

```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeForwardingRule
metadata:
  labels:
    label-one: "value-one"
  name: computeforwardingrule-regional
  namespace: cnrm-gcp-infra
spec:
  description: "A regional forwarding rule"
  target:
    targetVPNGatewayRef:
      external: <serviceAttachmentURI>
  location: europe-west1
  ipProtocol: "ESP"
  ipAddress:
    addressRef:
      name: computeforwardingrule-dep-regional


---

apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: computeforwardingrule-dep-regional
  namespace: cnrm-gcp-infra
  labels:
    label-one: "value-one"
spec:
  description: IP Address for PSC Endpoint
  location: europe-west1
```
