### ISSUE TITLE
Cannot create Service Level Objective with basicSli of type availability

### ISSUE THREAD

**Issue by KaelBaldwin** [GoogleCloudPlatform/k8s-config-connector#764]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

When attempting to create a MonitoringServiceLevelObjective with `spec.serviceLevelObjective.basicSli.availability` set to `{}` The SLO fails to be created in Google Cloud and the following message is set on the `Ready` status condition of the created resource:

```
      message: 'Update call failed: error applying desired state: googleapi: Error
        400: Invalid SLO definition: Request was missing field ServiceLevelIndicator.type.'
      reason: UpdateFailed
      status: "False"
      type: Ready
```

I attempted to workaround this issue by setting `spec.serviceLevelObjective.basicSli.location` to `us-central`, which changed the error condition to:

```
      message: 'Update call failed: error applying desired state: googleapi: Error
        400: BasicSli cannot be empty'
      reason: UpdateFailed
      status: "False"
      type: Ready
```

### Additional Diagnostic Information

version: 1.82.0

### Kubernetes Cluster Version

v1.23.14-gke.401

### Config Connector Version

1.82.0

### Config Connector Mode

cluster mode

### Log Output

2023-01-31T17:55:24.770187214Z starting reconcile
2023-01-31T17:55:24.995285269Z creating/updating underlying resource
2023-01-31T17:55:25.232061257Z error applying desired stategoogleapi: Error 400: Invalid SLO definition: Request was missing field ServiceLevelIndicator.type.
2023-01-31T17:56:11.450205559Z starting reconcile
2023-01-31T17:56:11.605082952Z creating/updating underlying resource
2023-01-31T17:56:11.789139841Z error applying desired stategoogleapi: Error 400: BasicSli cannot be empty

### Steps to reproduce the issue

1. Create a MonitoringServiceLevelObjective resource similar to the one provided in the YamlSnippets below.
    - make sure to set a valid projectRef and serviceRef
    - make sure `spec.serviceLevelIndicator.basicSli.availability` is set to an empty object `{}`
2. Kubectl describe the created resource and note the error in the status section.

### YAML snippets

```YAML
apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringServiceLevelObjective
metadata:
  name: availability-slo
  namespace: default
spec:
  goal: .80
  projectRef:
    external: "projects/{PROJECT_NAME}"
  serviceRef:
    external: "projects/{PROJECT_NAME}/services/{SERVICE_NAME}"
  rollingPeriod: "2592000s"
  serviceLevelIndicator:
    basicSli:
      location:
        - "us-central1"
      availability: {}
```

**Comment by KaelBaldwin** [comment]
I'm guessing this is happening because the availability field has omitempty here: https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/575c41ffed57b541a96ab9c22bb20b55960ed4e2/pkg/clients/generated/apis/monitoring/v1beta1/monitoringservicelevelobjective_types.go#L74 when the field shouldn't actually be emitted if empty in this case.

**Comment by mskyrim** [comment]
I have the same issue I hope it could be fixed

**Comment by mskyrim** [comment]
Hello, 
so while waiting for a fixe on the availability basic, I would like to share with you the configuration to build an Availability SLO using a requestBased ServiceLevelIndicator instead of the basicSli that I have created it on our REST API.

```
apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringServiceLevelObjective
metadata:
  name:rest-api-availability-slo
spec:
  displayName: "SLO 99,9% of API availability"
  goal: 0.999
  calendarPeriod: DAY
  serviceLevelIndicator:
    requestBased:
      goodTotalRatio:
        goodServiceFilter: "metric.type=\"istio.io/service/client/request_count\" resource.type=\"istio_canonical_service\" resource.labels.project_id=\"$projectId\" metric.labels.destination_canonical_service_name=\ "$yourService\""
        badServiceFilter: "metric.type=\"istio.io/service/client/request_count\" resource.type=\"istio_canonical_service\" resource.labels.project_id=\"$projectId\" metric.labels.destination_canonical_service_name=\"$yourService\""
  projectRef:
    external: "projects/$project"
  serviceRef:
    external: "projects/$projectId/services/canonical-ist:proj-$projectId-platform-services-$yourService"
```

**Comment by mskyrim** [comment]
Hello, 

so while waiting for a fixe on the availability basic, I would like to share with you the configuration to build an Availability SLO using a requestBased ServiceLevelIndicator instead of the basicSli that I have created it on our REST API.

```
apiVersion: monitoring.cnrm.cloud.google.com/v1beta1
kind: MonitoringServiceLevelObjective
metadata:
  name:rest-api-availability-slo
spec:
  displayName: "SLO 99,9% of API availability"
  goal: 0.999
  calendarPeriod: DAY
  serviceLevelIndicator:
    requestBased:
      goodTotalRatio:
        goodServiceFilter: "metric.type=\"istio.io/service/client/request_count\" resource.type=\"istio_canonical_service\" resource.labels.project_id=\"$projectId\" metric.labels.destination_canonical_service_name=\ "$yourService\""
        badServiceFilter: "metric.type=\"istio.io/service/client/request_count\" resource.type=\"istio_canonical_service\" resource.labels.project_id=\"$projectId\" metric.labels.destination_canonical_service_name=\"$yourService\""
  projectRef:
    external: "projects/$project"
  serviceRef:
    external: "projects/$projectId/services/canonical-ist:proj-$projectId-platform-services-$yourService"
```
