### ISSUE TITLE
ConfigConnector BackendBucket CDN Not Updating when cacheMode = USE_ORIGIN_HEADERS

### ISSUE THREAD

**Issue by loganrobertclemons** [GoogleCloudPlatform/k8s-config-connector#784]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

This issue is made in conjunction with this GCP Support ticket: 43224166

### Description
DefaultTTL when cache mode is set to USE_ORIGIN_HEADERS is getting set as null by default and attempting to upgrade the resource does not work.

### Affected Resources
ComputeBackendBucket when cacheMode is set to USE_ORIGIN_HEADERS

### Current Configuration
```
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeBackendBucket
metadata:
  name: {name}
spec:
  bucketRef:
    name: {bucket}
  enableCdn: true
  cdnPolicy:
    cacheMode: "USE_ORIGIN_HEADERS"
    defaultTtl: null
    maxTtl: null
    clientTtl: null
  customResponseHeaders:
  - X-Content-Type-Options:nosniff
  - Referrer-Policy:strict-origin-when-cross-origin
  - Strict-Transport-Security:max-age=63072000; includeSubDomains
  - X-Frame-Options:SAMEORIGIN
---
```

We attempted to explicitly set these to null, and it still didn't work.
```
cdnPolicy:
    cacheMode: "USE_ORIGIN_HEADERS"
    defaultTtl: null
    maxTtl: null
    clientTtl: null
```

This is the error from attempting that:
```
message: 'Update call failed: error applying desired state: summary: Error creating
      BackendBucket: googleapi: Error 400: Invalid value for field ''resource.cdnPolicy.defaultTtl'':
      ''0''. default_ttl cannot be specified with USE_ORIGIN_HEADERS cache_mode.,
      invalid'
```

### Additional Diagnostic Information

Attempting to update it with the gcloud command does work - gcloud beta compute backend-services update [backend_name_here] --global --cache-mode=CACHE_ALL_STATIC.

### Kubernetes Cluster Version

1.22.16

### Config Connector Version

1.82.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

Update ComputeBackendBucket when cacheMode is set to USE_ORIGIN_HEADERS

**Comment by diviner524** [comment]
This specific Config Connector resource is built on top of Terraform, so I believe we are hitting one similar issue as Terraform users, which is mentioned here:

https://github.com/hashicorp/terraform-provider-google/issues/10622

It seems there is a proposed fix but the PR is still open.

**Comment by hsulipe** [comment]
This have a solution already? Noticed that the https://github.com/hashicorp/terraform-provider-google/issues/10622 PR is merged but I'm facing the same issue

*Spec*

```yaml
spec:
   bucketRef:
     name: *
   cdnPolicy:
     cacheMode: USE_ORIGIN_HEADERS
     defaultTtl: 300
   compressionMode: AUTOMATIC
   customResponseHeaders:
       - Cache-Control:no-cache, no-store, max-age=0, must-revalidate
   enableCdn: true
```

*Logs*

```
Warning  UpdateFailed  32s (x7 over 2m42s)  computebackendbucket-controller  Update call failed: error applying desired state: summary: Error updating BackendBucket "": googleapi: Error 400: Invalid value for field 'resource.cdnPolicy.defaultTtl': '0'. default_ttl cannot be specified with USE_ORIGIN_HEADERS cache_mode., invalid                                        
```
