### ISSUE TITLE
Enabling query insights for MySQL instances fails, disabling turns it off for manually enabled MySQL instances

### ISSUE THREAD

**Issue by taisph** [GoogleCloudPlatform/k8s-config-connector#788]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

I can manually enable query insights for MySQL instances but attempting to do so via the Config Connector SQLInstance immediately results in the status below. Oddly, disabling query insights will disable it in a manually enabled MySQL instance.

### Additional Diagnostic Information

```yaml
status:
  conditions:
    - lastTransitionTime: '2023-03-16T11:56:50Z'
      message: "Update call failed: error calculating diff: 1 error occurred:\n\t* query_insights_enabled is only available for Postgres now.\n\n"
      reason: UpdateFailed
      status: 'False'
      type: Ready
```

### Kubernetes Cluster Version

v1.23.16-gke.1100

### Config Connector Version

1.82.0

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

- Update a MySQL instance using Config Connector adding the insightsConfig setting. (Creating a new instance not tested)

### YAML snippets

```YAML
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: sqlinstance
spec:
  databaseVersion: MYSQL_5_7
  settings:
    insightsConfig:
      queryInsightsEnabled: true
```
