### ISSUE TITLE
Unable to enable binary logging on replica SQLInstance

### ISSUE THREAD

**Issue by chadkouse** [GoogleCloudPlatform/k8s-config-connector#792]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Trying to enable binary logging on a SQLInstance read replica I recieve the following error: 

> Update call failed: error applying desired state: summary: Error, failed to update instance settings for : googleapi: Error 400: Invalid request: Binary log must be disabled when backup is disabled or the instance must be a replica instance with a MySQL 5.7 or above version., invalid

The read replica is at MySQL version 5.7.39

### Additional Diagnostic Information

The instance was already created with backup configuration and binary logging disabled.  I was reading in some teraform docs that the instance needs to be created before it can be patched to enable binary logging.

### Kubernetes Cluster Version

v1.24.9-gke.3200

### Config Connector Version

1.89.0

### Config Connector Mode

cluster mode

### Log Output

Update call failed: error applying desired state: summary: Error, failed to update instance settings for : googleapi: Error 400: Invalid request: Binary log must be disabled when backup is disabled or the instance must be a replica instance with a MySQL 5.7 or above version., invalid

### Steps to reproduce the issue

Create two SQLInstance resources running MySQL 5.7 -- a master and a read replica.  Then try to enable binary logging on the read replica.

### YAML snippets

```YAML
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: testing-main
  annotations:
    cnrm.cloud.google.com/project-id: my-project-id
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  settings:
    activationPolicy: ALWAYS
    availabilityType: REGIONAL
    tier: db-custom-4-15360
    backupConfiguration:
      backupRetentionSettings:
        retainedBackups: 7
        retentionUnit: COUNT
      binaryLogEnabled: true
      enabled: true
      location: us
      startTime: "04:00"
      transactionLogRetentionDays: 7
    diskSize: 100
    diskType: PD_SSD
    ipConfiguration:
      ipv4Enabled: true
    locationPreference:
      zone: us-central1-b
    pricingPlan: PER_USE
---
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: testing-replica
  annotations:
    cnrm.cloud.google.com/project-id: my-project-id
spec:
  databaseVersion: MYSQL_5_7
  region: us-central1
  masterInstanceRef:
    name: testing-main
  replicaConfiguration:
    failoverTarget: false
    connectRetryInterval: 30
  settings:
    activationPolicy: ALWAYS
    availabilityType: REGIONAL
    tier: db-custom-2-7680
    backupConfiguration:
      binaryLogEnabled: true
    diskSize: 100
    diskType: PD_SSD
    ipConfiguration:
      ipv4Enabled: true
    locationPreference:
      zone: us-central1-a
    pricingPlan: PER_USE
    replicationType: SYNCHRONOUS
```
