### ISSUE TITLE
CloudBuildTrigger does not update as expected

### ISSUE THREAD

**Issue by npitts0811** [GoogleCloudPlatform/k8s-config-connector#796]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

When attempting to update a CloudBuildTrigger that's set to a SourceRepoRepository to a GitHub repository, the trigger resource enters an `UpdateFailed` state with the following error: `googleapi: Error 400: cannot set more than one trigger config`. If the Cloud Build trigger in the GCP console is then updated manually to point to the GitHub repo, the resource returns to an `UpToDate` state. 

This is also true in reverse: if a trigger is configured for a GitHub repo and is updated to point to a SourceRepoRepository, the trigger enters an `UpdatedFailed` state with the same error. Similarly, if the trigger is manually updated in the GCP console to point to the source repo, the trigger resource returns to an `UpToDate` state.

### Additional Diagnostic Information

n/a

### Kubernetes Cluster Version

v1.24.9-gke.3200

### Config Connector Version

1.101.0

### Config Connector Mode

namespaced mode (default)

### Log Output

n/a

### Steps to reproduce the issue

1. Create a CloudBuildTrigger pointing to a SourceRepoRepository
2. After validating the GH repo is connected, update the CloudBuildTrigger resource to point to a GitHub repository.
3. CloudBuildTrigger enters `UpdateFailed` state with the error: `googleapi: Error 400: cannot set more than one trigger config`
4. Navigate to the Cloud Build trigger in the GCP console and manually set the repository to the desired GitHub repo
5. The CloudBuildTrigger returns to `UpToDate` state.

### YAML snippets

```YAML
# Create a CloudBuildTrigger pointing to a SourceRepoRepository
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: merge
  name: my-trigger 
  namespace: example-ns
spec:
  filename: myapp/cloudbuild.json
  includedFiles:
  - myapp/**
  location: global
  triggerTemplate:
    branchName: ^main$
    repoRef:
      name: example-repo-csr

# Update the same CloudBuildTrigger to instead point to a GitHub repository
apiVersion: cloudbuild.cnrm.cloud.google.com/v1beta1
kind: CloudBuildTrigger
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/state-into-spec: merge
  name: my-trigger
  namespace: example-ns
spec:
  filename: myapp/cloudbuild.json
  github:
    name: example-repo-gh
    owner: example
    push:
      branch: ^main$
  includedFiles:
  - myapp/**
  location: global
```
