### ISSUE TITLE
VPC routing mode is not update to what it's set in KCC resource

### ISSUE THREAD

**Issue by dooman87** [GoogleCloudPlatform/k8s-config-connector#80]
Hi,

I created VPC using KCC using the manifest below:

```yaml
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  labels:
    environment: "conare"
    environment_type: "sandbox"
  name: test-vpc
spec:
  routingMode: GLOBAL
  autoCreateSubnetworks: true
```

VPC been created successfully. Then I went to GCP console and changed routing mode to "Regional". I did expect that KCC will sync it back to state and set to "Global", but it didn't happen. When I'm trying to reapply manifest then it says that nothing changed:

```
➜  resources git:(master) ✗ kubectl apply -n dmitry-kcc-sandbox  -f ./vpc.yaml
computenetwork.compute.cnrm.cloud.google.com/test-vpc unchanged
➜  resources git:(master) ✗
```

I thought that KCC will allow to eliminate "state drift" problem. 

Is it a bug or expected behaviour?
