### ISSUE TITLE
Subscription DLQ topic expect fully qualified name

### ISSUE THREAD

**Issue by naresh-gn** [GoogleCloudPlatform/k8s-config-connector#800]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

In PubsubSubcription  `deadLetterPolicy.deadLetterTopicRef.external` expects fully qualified name for the topic `projects/project-id/topics/topic-name` whereas in other places such as `topicRef.external` accepts just the resource name (need not be fully qualified)
`deadLetterPolicy.deadLetterTopicRef.external` should allow not fully qualified resource name

### Importance

need to provide project id while deploying to different projects

**Comment by diviner524** [comment]
@naresh-gn Could you please provide a sample YAML that can be used to reproduce this?

i.e. It shows `topicRef.external` accepts just the resource name.

Our current doc for `topicRef.external` is: "string of the format `projects/{{project}}/topics/{{value}}` "

https://cloud.google.com/config-connector/docs/reference/resource-docs/pubsub/pubsubsubscription#spec:~:text=to%20a%20PubSubTopic.-,topicRef.external,-Optional

**Comment by naresh-gn** [comment]
@diviner524 as you can see in below example `topicRef.external` accepts just the name even though the doc says the format should be `projects/<project id>/topics/<topic name>` but where as `deadLetterPolicy.deadLetterTopicRef.external` only accepts fully qualified name, if you use just topic name it error out with

```
Error creating Subscription: googleapi: Error 400: Invalid resource name given (dead_letter_topic=my-error-topic)
```

Having full name makes it difficult promoting code different projects. I understand if you try to use different project topic you need fully qualified name but if you are using topic that belongs in the same project then fully qualified name is not required. 

```
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  annotations:
    dummy: dummy-value
  name: browser-test-1
  namespace: test
spec:
  ackDeadlineSeconds: 300
  deadLetterPolicy:
    deadLetterTopicRef:
      external: projects/<project Id>/topics/my-error-topic
  messageRetentionDuration: 604800s
  resourceID: my-subscription
  retainAckedMessages: false
  topicRef:
    external: my-topic
```
