### ISSUE TITLE
Auth String in the RedisInstance KCC resource does not work 

### ISSUE THREAD

**Issue by psabhishekgoogle** [GoogleCloudPlatform/k8s-config-connector#802]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

when creating a redis instance through kcc with option AUTHstring set to a UUID , when authenabled is true , it randomly generates the UUID and does not pick the UUID passed through auth string , so the field value is not taken into consideration so can we remove it from doc

### Additional Diagnostic Information

we tested it in our environment faced similar behaviour as mentioned above

### Kubernetes Cluster Version

Client Version: v1.26.1 Kustomize Version: v4.5.7 Server Version: v1.24.10-gke.2300

### Config Connector Version

1.89.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

setting 
authEnabled: true
authString: UUIDgeneratedvalue

### YAML snippets

```YAML
apiVersion: redis.cnrm.cloud.google.com/v1beta1
kind: RedisInstance
metadata:
  namespace: memorystore
  labels:
    label-one: "value-one"
  name: redisinstance-sample
  annotations:
    #cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/project-id: prj-bdrck-preview-svpc2
    cnrm.cloud.google.com/reconcile-interval-in-seconds: "600"
spec:
  displayName: Sample Redis Instance
  region: us-central1
  tier: STANDARD_HA
  authorizedNetworkRef:
    external: projects/testing-sample-project/global/networks/non-prod-network
  connectMode: PRIVATE_SERVICE_ACCESS
  memorySizeGb: 6
  readReplicasMode: READ_REPLICAS_ENABLED
  redisVersion: REDIS_6_X
  replicaCount: 2
  locationId: us-central1-a
  alternativeLocationId: us-central1-f
  authEnabled: true
  authString: 103a0776-3b72-49a9-af16-29f0baa25e87
```
