### ISSUE TITLE
Go client and CRD definition for ComputeSSLCertificate are inconsistent

### ISSUE THREAD

**Issue by pantheon-chris** [GoogleCloudPlatform/k8s-config-connector#803]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Looks like a [similar bug exists](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/598) (SQLUser) for this `ComputeSSLCertificate` resource where the `v1alpha1.ResourceRef` type doesn’t align with the CRD ([spec schema](https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computesslcertificate#schema))

```
        spec:
          properties:
            certificate:
              description: |-
                Immutable. The certificate in PEM format.
                The certificate chain must be no greater than 5 certs long.
                The chain must include at least one intermediate cert.
              oneOf:
                - not:
                    required:
                      - valueFrom
                  required:
                    - value
                - not:
                    required:
                      - value
                  required:
                    - valueFrom
              properties:
                value:
                  description: Value of the field. Cannot be used if 'valueFrom' is specified.
                  type: string
                valueFrom:
                  description: Source for the field's value. Cannot be used if 'value' is specified.
                  properties:
                    secretKeyRef:
                      description: Reference to a value with the given key in the given Secret in the resource's namespace.
                      properties:
                        key:
                          description: Key that identifies the value to be extracted.
                          type: string
                        name:
                          description: Name of the Secret to extract a value from.
                          type: string
                      required:
                        - key
                        - name
                      type: object
                  type: object
              type: object
            description:
              description: Immutable. An optional description of this resource.
              type: string
            location:
              description: 'Location represents the geographical location of the ComputeSSLCertificate. Specify a region name or "global" for global resources. Reference: GCP definition of regions/zones (https://cloud.google.com/compute/docs/regions-zones/)'
              type: string
            privateKey:
              description: Immutable. The write-only private key in PEM format.
              oneOf:
                - not:
                    required:
                      - valueFrom
                  required:
                    - value
                - not:
                    required:
                      - value
                  required:
                    - valueFrom
              properties:
                value:
                  description: Value of the field. Cannot be used if 'valueFrom' is specified.
                  type: string
                valueFrom:
                  description: Source for the field's value. Cannot be used if 'value' is specified.
                  properties:
                    secretKeyRef:
                      description: Reference to a value with the given key in the given Secret in the resource's namespace.
                      properties:
                        key:
                          description: Key that identifies the value to be extracted.
                          type: string
                        name:
                          description: Name of the Secret to extract a value from.
                          type: string
                      required:
                        - key
                        - name
                      type: object
                  type: object
              type: object
```

### Additional Diagnostic Information

n/a

### Kubernetes Cluster Version

v1.24.10-gke.2300

### Config Connector Version

1.95.0

### Config Connector Mode

namespaced mode (default)

### Log Output

```
ERROR   failed to create ComputeSSLCertificate "example-certificate". ComputeSSLCertificate.compute.cnrm.cloud.google.com "example-certificate" is invalid: [spec.certificate.valueFrom.secretKeyRef.key: Required value, spec.privateKey.valueFrom.secretKeyRef.key: Required value]
```

### Steps to reproduce the issue

Use the `"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/clients/generated/apis/compute/v1beta1"` and `"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/clients/generated/apis/k8s/v1alpha1"` libraries to generate a `ComputeSSLCertificate` kube object and explore the nested structs.
