### ISSUE TITLE
Referring to kcc resources provisioned in the same namespace is giving error

### ISSUE THREAD

**Issue by snehabiradar027** [GoogleCloudPlatform/k8s-config-connector#808]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Created a LogBucket and LogSink in a single yaml file and referenced the LogBucket in LogSink (spec.destination.LoggingBucketRef) using name /& namespace. This isn't working and giving 'couldn't find resource config' error. 

### Additional Diagnostic Information

Using 'external' as workaround, but found this same issue for PubSub and ClousStorage LogSinks as well.

### Kubernetes Cluster Version

Client Version: v1.26.1 Kustomize Version: v4.5.7 Server Version: v1.24.10-gke.2300

### Config Connector Version

1.89.0

### Config Connector Mode

namespaced mode (default)

### Log Output

"error getting referenced resource from API server: error getting ResourceConfig 
for referenced resource log-sink-lbkt-preview: couldn''t find any ResourceConfig
defined for kind LoggingLogBucket "

### Steps to reproduce the issue

create a LogBucket and LogSink in same yaml file and reference the LogBucket in LogSink (spec.destination.LoggingBucketRef) using name & namespace.

### YAML snippets

```YAML
---
apiVersion: logging.cnrm.cloud.google.com/v1beta1
kind: LoggingLogBucket
metadata:
  name: log-bkt-preview
  namespace: logging-log-bkt
spec:
  projectRef:
    external: "projects/testing-sample-project"
  location: "us-central1"
  description: "Centralized Logging Bucket for Preview"
  retentionDays: 180
---
apiVersion: logging.cnrm.cloud.google.com/v1beta1
kind: LoggingLogSink
metadata:
  name: log-sink-lbkt-preview
  namespace: logging-log-bkt
spec:
  folderRef:
    external: "326646603286" 
  destination:
    loggingLogBucketRef:
      name: log-bkt-preview
      namespace: logging-log-bkt
    # external: "logging.googleapis.com/projects/testing-sample-project/locations/global/buckets/log-bkt-preview"
  filter: logName:"cloudaudit.googleapis.com/activity" OR logName:"cloudaudit.googleapis.com/policy" OR logName:"cloudaudit.>
```
