### ISSUE TITLE
Namespace scope

### ISSUE THREAD

**Issue by kaldvelski** [GoogleCloudPlatform/k8s-config-connector#809]
### Describe your question

Apologies if this seems a basic question but I can't seem to get it straight in my head from the docs.

If I'm creating the same types of resources but are namespace scoped within the same project (e.g. int_bucket and prod_bucket) then when I create the resource is simply specifying the namespace in the kubectl command sufficient? (assuming each namespace is annotated with cnrm.cloud.google.com/project-id="myProject") 
Will this create the resource within each namespace separately or do I need a single 'holder' namespace to create all the resources in?

Or is this what the namespaced installation mode is for?

As an addendum, if I provide both metadata.name and spec.resourceID, to avoid naming rules on the name, then can I reuse the name across namespaces or could it cause a clash?

TIA
Craig

Example of the sort of resource definition I want to deploy multiple times where the resourceID is scoped to a namespace:
```
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  annotations:
    cnrm.cloud.google.com/reconcile-interval-in-seconds: "0"
    cnrm.cloud.google.com/force-destroy: "false"  
  name: my-bucket
spec:
  resourceID: "{{.namespace}}_bucket"  
  uniformBucketLevelAccess: true
  storageClass: STANDARD
```
