### ISSUE TITLE
Service usage don't support enabling the same API on multiple projects

### ISSUE THREAD

**Issue by Scorpiion** [GoogleCloudPlatform/k8s-config-connector#81]
Hi,

I've been tried to setup service usage for multiple projects but it seems this is not possible (unless I missed something). The "problem" seem to be that the "matadata.name" parameter is used as a key/name for the k8s object and at the same time it's used for specifiing the API to enable. This makes it such that you can only enable a specific API once per config connector namespace, if you try to enable the same API for two project you will get an error. I think this is a bug because you can create both folders and projects, but you can enable the same API twice (common API will be enabled for multiple projects).

This works for one project:
```
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "project-id-that-exists-number-one"
  name: run.googleapis.com
```

However when you add a second one for your second project with a different `project-id` annotation it does not work:
```
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "project-id-that-exists-number-two"
  name: run.googleapis.com
```

You get this error:
```
service.serviceusage.cnrm.cloud.google.com/run.googleapis.com unchanged
Error from server (error validing container annotations: cannot make change to container annotation cnrm.cloud.google.com/project-id): error when applying patch:
{"metadata":{"annotations":{"cnrm.cloud.google.com/project-id":"project-id-that-exists-number-two","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"serviceusage.cnrm.cloud.google.com/v1beta1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{\"cnrm.cloud.google.com/deletion-policy\":\"abandon\",\"cnrm.cloud.google.com/disable-dependent-services\":\"false\",\"cnrm.cloud.google.com/project-id\":\"project-id-that-exists-number-two\"},\"name\":\"run.googleapis.com\",\"namespace\":\"robert-deployment-testing\"}}\n"}}}
to:
Resource: "serviceusage.cnrm.cloud.google.com/v1beta1, Resource=services", GroupVersionKind: "serviceusage.cnrm.cloud.google.com/v1beta1, Kind=Service"
Name: "run.googleapis.com", Namespace: "robert-deployment-testing"
Object: &{map["apiVersion":"serviceusage.cnrm.cloud.google.com/v1beta1" "kind":"Service" "metadata":map["annotations":map["cnrm.cloud.google.com/deletion-policy":"abandon" "cnrm.cloud.google.com/disable-dependent-services":"false" "cnrm.cloud.google.com/project-id":"project-id-that-exists-number-one" "kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"serviceusage.cnrm.cloud.google.com/v1beta1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{\"cnrm.cloud.google.com/deletion-policy\":\"abandon\",\"cnrm.cloud.google.com/disable-dependent-services\":\"false\",\"cnrm.cloud.google.com/project-id\":\"project-id-that-exists-number-one\"},\"name\":\"run.googleapis.com\",\"namespace\":\"robert-deployment-testing\"}}\n"] "creationTimestamp":"2020-02-05T08:02:26Z" "finalizers":["cnrm.cloud.google.com/finalizer"] "generation":'\x03' "name":"run.googleapis.com" "namespace":"robert-deployment-testing" "resourceVersion":"538401" "selfLink":"/apis/serviceusage.cnrm.cloud.google.com/v1beta1/namespaces/robert-deployment-testing/services/run.googleapis.com" "uid":"d9154ab2-47ed-11ea-a578-42010aa6006c"] "status":map["conditions":[map["lastTransitionTime":"2020-02-05T08:02:54Z" "message":"The resource is up to date" "reason":"UpToDate" "status":"True" "type":"Ready"]]]]}
for: "cluster.yaml": admission webhook "deny-immutable-field-updates.cnrm.cloud.google.com" denied the request: error validing container annotations: cannot make change to container annotation cnrm.cloud.google.com/project-id
```

kubectl is trying to change the project id of the first serviceusage object, since they have the same name (the name of the API), that does not work. 

I would have preferred if the specification of the service/apis to enable was a list among the annotations if possible. If the name instead of refering to an API refered to the project id and the list of services was an annotation, so it would work like this:
```
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/services: "compute.googleapis.com,appengine.googleapis.com,run.googleapis.com"
  name: project-id-that-exists-number-one
```

Or a more verbose version if the above is not possible:
```
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "project-id-that-exists-number-one"
    cnrm.cloud.google.com/service: "compute.googleapis.com"
  name: my-project-services-compute
---

apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "project-id-that-exists-number-one"
    cnrm.cloud.google.com/service: "appengine.googleapis.com"
  name: my-project-services-appengine
---

apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: "project-id-that-exists-number-one"
    cnrm.cloud.google.com/service: "run.googleapis.com"
  name: my-project-services-run
```

(Note: I removed some optional annotation in the samples to make them shorter)
Relevant docs: https://cloud.google.com/config-connector/docs/reference/resources#service

I'm using config connector in a project right now, I'm thinking of doing a work around for now where I write a program that executes the needed gcloud commands. However it would be nice to know if this is something that will be supported soonish or not? (config connector support for enabling the same API on multiple projects)

**Comment by Scorpiion** [comment]
Reading through the docs a second time I realize that maybe I can accomplish this by creating namespaces for each project. I will try this, don't spend any time on this issue for now. 

https://cloud.google.com/config-connector/docs/concepts/namespaces-and-projects

**Comment by kibbles-n-bytes** [comment]
Yes, using a namespace per project is the recommended approach in this case. In the future we will support resource ID overrides that would allow you to enable the same API on two separate projects via one namespace.

**Comment by Scorpiion** [comment]
Okay, yeah I got it to work now. It's a little verbose but it works. :+1:

**Comment by lostick** [comment]
@kibbles-n-bytes do you guys plan on supporting this feature in the near future? It would come in handy.
I'm also happy to contribute to the existing `serviceusage.cnrm.cloud.google.com/v1beta1` API, I reckon adding an extra annotation would work fine here.

**Comment by jcanseco** [comment]
Hi @lostick, yes we already support the feature that was previously described.

Here is an example of how you can enable the Pub/Sub API for two different projects using two different `Service` resources within the same namespace:

```yaml
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/project-id: project-1
  name: pubsub-service-for-project-1
spec:
  resourceID: pubsub.googleapis.com
---
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/deletion-policy: abandon
    cnrm.cloud.google.com/project-id: project-2
  name: pubsub-service-for-project-2
spec:
  resourceID: pubsub.googleapis.com
```

See [this page](https://cloud.google.com/config-connector/docs/how-to/managing-resources-with-resource-ids) for more documentation on the `resourceID` field.
