### ISSUE TITLE
RunService: Environment variables can't be updated to an empty array

### ISSUE THREAD

**Issue by prismec** [GoogleCloudPlatform/k8s-config-connector#813]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Removing all environment variables or setting it to an empty array does not result in any changes

### Additional Diagnostic Information

None

### Kubernetes Cluster Version

Client Version: v1.27.1 Kustomize Version: v5.0.1 Server Version: v1.24.10-gke.2300 WARNING: version difference between client (1.27) and server (1.24) exceeds the supported minor version skew of +/-1

### Config Connector Version

1.90.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

```
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: xxx
spec:
  template:
    containers:
      - env:
          - name: "ENV_VAR"
            value: "value"
```

`kubectl apply` -> Everythings fine

```
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: xxx
spec:
  template:
    containers:
      - env: []
```

`kubectl apply`-> ENV_VAR is not removed
