### ISSUE TITLE
Error 409: Requested entity already exists

### ISSUE THREAD

**Issue by msmagnanijr** [GoogleCloudPlatform/k8s-config-connector#815]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Hey folks, I encountered an error while attempting to create a project. The following message was displayed: "Update call failed: error applying desired state: summary: error creating project project (dev-poc-iac-config-connector): googleapi: Error 409: Requested entity already exists, alreadyExists."

I check and the project doesn't actually exist, I used random names and nothing worked. Any idea what could cause this?  Thanks.

### Additional Diagnostic Information

Try to create a simple project using ArgoCD.

### Kubernetes Cluster Version

1.24.10-gke.2300

### Config Connector Version

1.89.0

### Config Connector Mode

namespaced mode (default)

### Log Output

 "Update call failed: error applying desired state: summary: error creating project project (dev-poc-iac-config-connector): googleapi: Error 409: Requested entity already exists, alreadyExists."

### Steps to reproduce the issue

Try to create a simple project using ArgoCD.

### YAML snippets

```YAML
apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/auto-create-network: 'false'
  labels:
    app.kubernetes.io/instance: iac-dev-poc-config-connector
  name: project
  namespace: dev-poc-config-connector
spec:
  billingAccountRef:
    external: xxxxxx
  name: dev-poc-iac-config-connector
  organizationRef:
    external: 'xxxxxx'
status:
  conditions:
    - lastTransitionTime: '2023-04-21T20:55:41Z'
      message: >-
        Update call failed: error applying desired state: summary: error
        creating project project (dev-poc-iac-config-connector): googleapi:
        Error 409: Requested entity already exists, alreadyExists. If you
        received a 403 error, make sure you have the
        `roles/resourcemanager.projectCreator` permission
      reason: UpdateFailed
      status: 'False'
      type: Ready
  observedGeneration: 12
```
