### ISSUE TITLE
ComputeFirewallPolicy and ComputeFirewallPolicyAssociation do not work as expected

### ISSUE THREAD

**Issue by mikesharpton-bestbuy** [GoogleCloudPlatform/k8s-config-connector#816]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

While attempting to use the CRD's below, I run into a creation loop and abandoned resource for ComputeFirewallPolicy.   While attempting to create an association to the policy with this CRD ComputeFirewallPolicyAssociation, I am being told the  spec.attachmentTargetRef.name: Required value is a required value.  

The documentation does not say this is a required field, and I cannot use name as the folder resource I need to associate with is not managed by this KCC cluster.  

My last step would be to create a ComputeFirewallPolicyRule that would be based on FQDN.  I did not attempt to move forward until I can get these two working first.  I have granted roles/compute.admin on the folder I am trying to create this objects on to my KCC SA.  I am able to do the same things vi the Console, but I may have an org level permission on my user account that my KCC SA does not.

### Additional Diagnostic Information

When trying to create a policy, the policy is created, but then loop fails trying to create again saying the name is already in use.

This is the error for this CRD ComputeFirewallPolicy.

`  ----     ------        ----               ----                              -------
  Warning  UpdateFailed  50s                computefirewallpolicy-controller  Update call failed: error applying desired state: googleapi: Error 403: Required 'compute.globalOperations.get' permission for 'locations/global/operations/org-XXXXXX-1684957311202-5fc75b1fef560-ba4c3bac-a6cb79db', forbidden
  Normal   Updating      19s (x5 over 50s)  computefirewallpolicy-controller  Update in progress
  Warning  UpdateFailed  18s (x4 over 47s)  computefirewallpolicy-controller  Update call failed: error applying desired state: googleapi: Error 400: Invalid value for field 'resource.shortName': 'testpolicy-kcc'. The display name is already used. Please choose another one, invalid`

The policy creates, but when you delete the object from KCC it does not remove it from GCP.  The items stays.  This makes some sense as it appears KCC never knows it got created or not based off the first error.

For the ComputeFirewallPolicyAssociation CRD, I need to ref an external folder as the folder is not managed by this KCC instance.  When I try this, the output tells me the spec.attachmentTargetRef.name is a required value.  

`The ComputeFirewallPolicyAssociation "test-association-kcc" is invalid: 
* <nil>: Invalid value: "": "spec.attachmentTargetRef" must validate one and only one schema (oneOf). Found none valid
* <nil>: Invalid value: "": "spec.attachmentTargetRef" must not validate the schema (not)
* spec.attachmentTargetRef.name: Required value`

I cannot pass a name, I need to pass external.

### Kubernetes Cluster Version

1.24.11-gke.1000

### Config Connector Version

1.104.0

### Config Connector Mode

namespaced mode (default)

### Log Output

Errors are listed above from describing the objects.  I can also see the looping policy creation failure in the activity logs for my org.

### Steps to reproduce the issue

Granted roles/compute.admin on the folder I am trying to create the policy in to my KCC SA. I then try to apply the sample yamls below.  One CRD has one issue, the other has another issue which I explained above.

### YAML snippets

```YAML
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewallPolicy
metadata:
  name: testpolicy-kcc
spec:
  folderRef:
    external: "folders/XXXXXX"
  description: "A folder level policy created with kcc"
  shortName: testpolicy-kcc

---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewallPolicyAssociation
metadata:
  name: test-association-kcc
spec:
  attachmentTargetRef:
    kind: Folder
    external: "folders/XXXXXX"
  firewallPolicyRef:
    external: locations/global/firewallPolicies/testpolicy-kcc
```

**Comment by mikesharpton-bestbuy** [comment]
Update.  From my GCP support ticket we have trial and error'd our way to the yamls which do work below. We have also requested documentation updates to the config connector page.  Support has done this.

To fix the looping policy create, permissions had to be granted at the org level so the config connector SA could see the status of the deployment and know it was created.  This also fixed the policy being orphaned when the object was deleted from config connector as it can actually track the deployment.

For the association issue, you cannot pass "kind" or the CRD will fail as described above.  This worked to associate to a folder.

```
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeFirewallPolicyAssociation
metadata:
  name: test-association-kcc
spec:
  attachmentTargetRef:
    #kind: Folder
    external: "folders/XXXXXX"
  firewallPolicyRef:
    external: firewallPolicies/XXXXXXXXX
```
