### ISSUE TITLE
Project creation ignoriing spec.resourceID

### ISSUE THREAD

**Issue by KingBain** [GoogleCloudPlatform/k8s-config-connector#818]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

When creating new projects using KCC,  This yaml fails to deploy. 
```

apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  name: "ph-fishsauce-project" # kpt-set: ${project-dept}-${project-vanity-name}-project
  namespace: "config-control"
  labels:
    intake-id: "phx-01h28kjpmp42v8xh59v0qvfpxa" # kpt-set: ${project-dept}${project-env}-${project-unique-id}
  annotations:
    cnrm.cloud.google.com/blueprint: 'kpt-fn'
spec:
  name: phx-dhis2 # kpt-set: ${project-dept}${project-env}-${project-vanity-name}
  resourceID: "phx-01h28kjpmp42v8xh59v0qvfpxa" # kpt-set: ${project-dept}${project-env}-${project-unique-id}
  billingAccountRef:
    external: "016B6D-6AB281-505940" # kpt-set: ${billing-id}
  folderRef:
    name: ph-fishsauce# kpt-set: ${project-dept}-${project-vanity-name}
```

No error messages, but KCC is constly stuck in "in progress" for reconciliation

Reading the documentation for the resource I would expect a project to be created with the **projectID** of `phx-01h28kjpmp42v8xh59v0qvfpxa`
https://cloud.google.com/config-connector/docs/reference/resource-docs/resourcemanager/project?authuser=1
![image](https://github.com/GoogleCloudPlatform/k8s-config-connector/assets/367922/f67c0387-5239-4b72-a4a4-6d30ddb0dc5c)

### Additional Diagnostic Information

I get 1.104.0

### Kubernetes Cluster Version

kubectl version --short Flag --short has been deprecated, and will be removed in the future. The --short output will become the default. Client Version: v1.27.2 Kustomize Version: v5.0.1 Server Version: v1.24.12-gke.500 WARNING: version difference between client (1.27) and server (1.24) exceeds the supported minor version skew of +/-1

### Config Connector Version

1.104.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

deploy yaml to github repo KCC is watching
