### ISSUE TITLE
Cloud Run service fails to apply update

### ISSUE THREAD

**Issue by knowhoper** [GoogleCloudPlatform/k8s-config-connector#832]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

I am seeing the error 

```
{"name":"xxx-api","namespace":"xxx-api"},"namespace":"xxx-api","name":"xxx-api","reconcileID":"feb918c5-8c38-4e40-b0c6-e4f080b2660b","error":"Update call failed: error generating the diffs from desired state: \"Location\" must be set"}
```

When updating the CloudRun service. Below is the resource YAML. Noting deleting and re-creating works.

```YAML
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: xxx-api
  namespace: xxx-api
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    cnrm.cloud.google.com/project-id: acme-uat
spec:
  ingress: "INGRESS_TRAFFIC_ALL"
  launchStage: "GA"
  location: australia-southeast1
  projectRef:
    external: projects/acme-uat
  template:
    containerConcurrency:  80
    scaling:
      minInstanceCount: 1
      maxInstanceCount: 2
    revision: xxx-api-v1-4-44-uatj
    serviceAccountRef:
      external: "serviceAccount:svc-xxx-api@acme-uat.iam.gserviceaccount.com"
    containers:
      - env:
          - name: default_badge_limit
            value: "6"
          - name: bucket_id
            value: "acme-public-images-uat"
        image: "australia-southeast1-docker.pkg.dev/acme-dev-tooling/acme-docker/xxx-api:v1.4.44-uat"
        ports:
          - name: http1
            containerPort: 5000
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
    serviceAccountRef:
      external: svc-xxx-api@acme-uat.iam.gserviceaccount.com
    vpcAccess:
      connectorRef:
        external: projects/acme-uat/locations/australia-southeast1/connectors/acme-svpc
      egress: PRIVATE_RANGES_ONLY
  traffic:
    - percent: 100
      type: "TRAFFIC_TARGET_ALLOCATION_TYPE_REVISION"
      revision: xxx-api-v1-4-44-uatj



```

### Additional Diagnostic Information

None

### Kubernetes Cluster Version

1.25.8-gke.1000

### Config Connector Version

1.105.0

### Config Connector Mode

cluster mode

### Log Output

{"severity":"info","timestamp":"2023-06-23T08:59:13.837Z","logger":"runservice-controller","msg":"starting reconcile","resource":{"namespace":"xxx-api","name":"xxx-api"}}
{"severity":"error","timestamp":"2023-06-23T08:59:13.917Z","msg":"Reconciler error","controller":"runservice-controller","controllerGroup":"run.cnrm.cloud.google.com","controllerKind":"RunService","RunService":{"name":"xxx-api","namespace":"xxx-api"},"namespace":"xxx-api","name":"xxx-api","reconcileID":"f405ed57-31a1-4aab-a1f0-f1e4977dec34","error":"Update call failed: error generating the diffs from desired state: \"Location\" must be set"}

### Steps to reproduce the issue

Create CloudRun service. Add a revision.

### YAML snippets

```YAML
apiVersion: run.cnrm.cloud.google.com/v1beta1
kind: RunService
metadata:
  name: xxx-api
  namespace: xxx-api
  annotations:
    argocd.argoproj.io/sync-wave: "20"
    cnrm.cloud.google.com/project-id: acme-uat
spec:
  ingress: "INGRESS_TRAFFIC_ALL"
  launchStage: "GA"
  location: australia-southeast1
  projectRef:
    external: projects/acme-uat
  template:
    containerConcurrency:  80
    scaling:
      minInstanceCount: 1
      maxInstanceCount: 2
    revision: xxx-api-v1-4-44-uatj
    serviceAccountRef:
      external: "serviceAccount:svc-xxx-api@acme-uat.iam.gserviceaccount.com"
    containers:
      - env:
          - name: default_badge_limit
            value: "6"
          - name: bucket_id
            value: "acme-public-images-uat"
        image: "australia-southeast1-docker.pkg.dev/acme-dev-tooling/acme-docker/xxx-api:v1.4.44-uat"
        ports:
          - name: http1
            containerPort: 5000
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
    serviceAccountRef:
      external: svc-xxx-api@acme-uat.iam.gserviceaccount.com
  traffic:
    - percent: 100
      type: "TRAFFIC_TARGET_ALLOCATION_TYPE_REVISION"
      revision: xxx-api-v1-4-44-uatj
```
