### ISSUE TITLE
Updating locationPolicy on GKE nodepool with autoscaling enabled will remove autoscaling in some cases.

### ISSUE THREAD

**Issue by olga-mir** [GoogleCloudPlatform/k8s-config-connector#833]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

In GKE, adding `locationPolicy: BALANCED` to a nodepool with following autoscaling settings 
```
   autoscaling:
      totalMinNodeCount: 1
      totalMaxNodeCount: 3
```
will result in autoscaling getting turned off completely, even though the configuration is valid from GKE perspective. It will also cause the nodepool KCC resource to be constantly updated (observedGeneration creeping up constantly which doesn't happen in normal operation).

There is something similar in this issue: https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/163#issuecomment-624887641 but it is not the same and the issue is not resolved.

### Additional Diagnostic Information

After performing steps in the Steps section below, nodepool autoscaling is turned off, but it is not intended behaviour. There is no error on KCC or cloud resource, but the actual resource state does not match source code.

`observedGeneration` on nodepool KCC resource keeps increasing:
```
kubectl get gcpcontainernodepools cluster-test-with-total -o yaml | yq e .status.observedGeneration
```

This combination of autoscaling parameters is valid. When creating a node pool with these settings from the beginning the nodepool has autoscaling on with locationPolicy BALANCED. e.i. if I commit source code:
```
   autoscaling:
     locationPolicy: BALANCED
     totalMinNodeCount: 1
     totalMaxNodeCount: 3
```
I'll get the nodepool with autoscaling enabled.

Another test that I did was to create a node pool with
```
   autoscaling:
     totalMinNodeCount: 1
     totalMaxNodeCount: 3
```
and then update `locationPolicy` using gcloud command. That also worked. The property was updated and autoscaling was not turned off.

So there is no issue with the parameters, but something that KCC does that leads to this undesireable behaviour.

In the Cloud Logs I've observed that when applying change from step 3, there is no update operation on nodepool cloud resource. Instead there is an update operation on the Cluster resource and payload contains explicitly empty autoscaling block:
```
desiredNodePoolAutoscaling: {}
desiredNodePoolId: "<MY_NODEPOOL>"
```

All the experiments described here were performed on KCC cluster with following Cluster Auto Scaling settings:
```
  clusterAutoscaling:
    autoscalingProfile: BALANCED # not to confuse with nodepool locationPolicy
    enabled: false
```

### Kubernetes Cluster Version

Flag --short has been deprecated, and will be removed in the future. The --short output will become the default. Client Version: v1.24.10-dispatcher-dirty Kustomize Version: v4.5.4 Server Version: v1.24.12-gke.500

### Config Connector Version

1.104.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

1. Create new nodepool with following config in the source code without providing location policy. Commit and push
```
  autoscaling:
    totalMinNodeCount: 1
    totalMaxNodeCount: 3
```

2. Describe new nodepool with gcloud and kcc resource. Both will include default setting for location policy, which is expected as described in https://cloud.google.com/config-connector/docs/concepts/managing-fields-externally
```
  autoscaling:
    locationPolicy: ANY
    totalMaxNodeCount: 3
    totalMinNodeCount: 1
```

3. Change location policy to BALANCED, commit and push.
section of the applied patch:
```
   autoscaling:
+    locationPolicy: BALANCED
     totalMinNodeCount: 1
     totalMaxNodeCount: 3
```

4. When resource is synced observe that the whole autoscaling block is gone both from kcc resource and when describing the nodepool with gcloud.
```
% kubectl get gcpcontainernodepools
NAME                                       AGE     READY   STATUS     STATUS AGE
cluster-test-with-total   2d15h   True    UpToDate   66s
% kubectl get gcpcontainernodepools cluster-test-with-total -o yaml | grep -i autoscaling
% gcloud container node-pools describe cluster-test-with-total --cluster=cluster-test  | grep -i autoscaling
autoscaling: {}
```

(there is no output from the kubectl command that contains autoscaling)

### YAML snippets

```YAML
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerNodePool
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: <MY_PROJECT>
    cnrm.cloud.google.com/state-into-spec: merge
```
