### ISSUE TITLE
Update on DataflowJob support

### ISSUE THREAD

**Issue by jcanseco** [GoogleCloudPlatform/k8s-config-connector#84]
Hi all, we're currently experimenting with what support for Dataflow Jobs would look like, and we would like to hear your feedback.

## Creating Dataflow Jobs

Let's use the job described in [Quickstart Using Templates](https://cloud.google.com/dataflow/docs/quickstarts/quickstart-templates) as an example to demonstrate how you can create Dataflow Jobs using Config Connector. 

Summary of the quickstart: we create a Dataflow Job which reads and processes messages from a PubSub topic and then writes the output to a BigQuery table. We also create a GCS bucket that the job uses to store temporary data in.

In our prototype today, the configuration for the Dataflow Job would look like the following (please take the time to read and understand what each field does):

```yaml
# dataflow_job.yaml
apiVersion: dataflow.cnrm.cloud.google.com/v1beta1
kind: DataflowJob
metadata:
  annotations:
    cnrm.cloud.google.com/on-delete: "drain"  # Configures Config Connector to drain the job instead of cancelling it when this Config Connector resource is deleted
  name: job-abcdef
spec:
  # Required fields for any Dataflow Job
  templateGcsPath: gs://dataflow-templates/latest/PubSub_to_BigQuery  # GCS path to the Dataflow Job template to run (this template is public and maintained by Google)
  tempGcsLocation: gs://storagebucket-abcdef/tmp  # GCS directory to store temporary data files in (we need to create this)
  zone: us-west1-a  # Zone in which the job should run

  # Required fields for this Dataflow Job
  parameters:
    inputTopic: projects/pubsub-public-data/topics/taxirides-realtime  # PubSub topic to read data from (this topic is public and maintained by Google)
    outputTableSpec: [PROJECT_ID]:taxirides.realtime  # BigQuery table to write data to (we need to create this and the dataset it belongs to); must replace [PROJECT_ID] with project ID
```

The job's dependencies (StorageBucket, BigQueryDataset, and BigQueryTable) would look like:

```yaml
# storage_bucket.yaml
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: storagebucket-abcdef
```
```yaml
# bigquery_dataset.yaml
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryDataset
metadata:
  name: taxirides
```
```yaml
# bigquery_table.yaml
apiVersion: bigquery.cnrm.cloud.google.com/v1beta1
kind: BigQueryTable
metadata:
  name: realtime
spec:
  datasetRef:
    name: taxirides
``` 

Then, just like any other Config Connector resource, you can create these resources on GCP by applying the YAMLs using `kubectl apply`: 
```console
$ ls dataflowjob/
dataflow_job.yaml    storage_bucket.yaml    bigquery_dataset.yaml    bigquery_table.yaml
$ kubectl apply -f dataflowjob/
bigquerydataset.bigquery.cnrm.cloud.google.com/taxirides created
bigquerytable.bigquery.cnrm.cloud.google.com/realtime created
dataflowjob.dataflow.cnrm.cloud.google.com/job-abcdef created
storagebucket.storage.cnrm.cloud.google.com/storagebucket-abcdef created
```

This will start the Dataflow Job.

Please note that I omitted fields from the `DataflowJob` config that were not strictly required by the quickstart guide. You can also define:
- The machine type to use (e.g. `n1-standard-1`) for running the job
- The max number of workers to use
- The service account to use with the job
- etc.

All fields supported by the Terraform resource [google_dataflow_job](https://www.terraform.io/docs/providers/google/r/dataflow_job.html) are supported by Config Connector.

## Getting the state of a Dataflow Job

You can get the state of a Dataflow Job using `kubectl describe`. For example:

```console
$ kubectl describe dataflowjob job-abcdef
Name:         job-abcdef
Namespace:    default
Labels:       <none>
Annotations:  cnrm.cloud.google.com/on-delete: drain
              cnrm.cloud.google.com/project-id: cnrm-jcanseco-2
              kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"dataflow.cnrm.cloud.google.com/v1beta1","kind":"DataflowJob","metadata":{"annotations":{"cnrm.cloud.google.com/on-delete":"...
API Version:  dataflow.cnrm.cloud.google.com/v1beta1
Kind:         DataflowJob
Metadata:
  Creation Timestamp:  2020-02-11T01:12:00Z
  Finalizers:
    cnrm.cloud.google.com/finalizer
  Generation:        3
  Resource Version:  8062040
  Self Link:         /apis/dataflow.cnrm.cloud.google.com/v1beta1/namespaces/default/dataflowjobs/job-abcdef
  UID:               819dea63-4c6b-11ea-b60f-42010a8a008c
Spec:
  Parameters:
    Input Topic:        projects/pubsub-public-data/topics/taxirides-realtime
    Output Table Spec:  cnrm-jcanseco-2:taxirides.realtime
  Temp Gcs Location:    gs://storagebucket-abcdef/tmp
  Template Gcs Path:    gs://dataflow-templates/latest/PubSub_to_BigQuery
  Zone:                 us-west1-a
Status:
  Conditions:
    Last Transition Time:  2020-02-11T01:12:09Z
    Message:               The resource is up to date
    Reason:                UpToDate
    Status:                True
    Type:                  Ready
  Job Id:                  2020-02-10_17_12_03-323619607536147469
  Job Type:                JOB_TYPE_STREAMING
  State:                   JOB_STATE_RUNNING
Events:
  Type    Reason    Age   From                    Message
  ----    ------    ----  ----                    -------
  Normal  Updating  70s   dataflowjob-controller  Update in progress
  Normal  UpToDate  62s   dataflowjob-controller  The resource is up to date
```

Notice how this job has a state of `JOB_STATE_RUNNING`. List of other possible states can be found [here](https://cloud.google.com/dataflow/docs/reference/rest/v1b3/projects.jobs#jobstate).

## Stopping Dataflow Jobs (Cancelling vs Draining)

Jobs can be stopped by deleting the `DataflowJob` resource from the Kubernetes cluster:

```console
$ kubectl delete -f dataflow_job.yaml # will wait for the job to finish cancelling/draining before returning
dataflowjob.dataflow.cnrm.cloud.google.com "job-abcdef" deleted
```

The value of the annotation `cnrm.cloud.google.com/on-delete` decides what the job does when it is stopped. If set to "cancel", the job terminates - any data written remains where it is, but no new data will be processed. If set to "drain", no new data will enter the pipeline, but any data currently in the pipeline will finish being processed. The default is "cancel".

## Restarting Jobs

Jobs can effectively be restarted by deleting the `DataflowJob` resource and then recreating it:

```console
$ kubectl delete -f dataflow_job.yaml && kubectl apply -f dataflow_job.yaml
```

## Managing Existing Dataflow Jobs

"I have a Dataflow Job already running that I want to start managing using Config Connector."

This is unfortunately not yet possible, but it is something we plan to support in the near future.

## Dependencies on Other Resources

Dataflow jobs often need to depend on other GCP resources. For example, the job in the quickstart example had dependencies on a PubSub topic and a BigQuery table.

In Config Connector, if a dependency on a resource is specified as a [resource reference](https://cloud.google.com/config-connector/docs/how-to/creating-resource-references), Config Connector waits for those dependencies to exist and be in a ready state before creating the resource.

However, for Dataflow jobs, dependencies on resources are specified as arbitrary string parameters (e.g. in the `parameters` field for `DataflowJob` in Config Connector and text boxes in Pantheon) and are indistinguishable from any other string parameter, so it is not possible for Config Connector to wait for those dependencies to exist and be in a ready state. That task will fall to the job itself.

## Automatic Restarts

We will not be adding direct support for automatic restarts since it is outside the scope of Config Connector. The goal behind Config Connector is to provide a Kubernetes-native surface for Google Cloud -- a way to represent GCP resources as K8s resources in a 1:1 mapping. The only way to restart a Dataflow Job, however, is to create a new job, and the automatic creation of new resources on behalf of users falls outside this goal. Therefore, to avoid increasing the scope and mission of the product, we will not be adding support for automatic restarts.

However, Config Connector makes it easy for users to implement their own automatic restart functionality using the K8s toolchain, since Config Connector allows users to represent GCP resources as K8s resources, and the K8s toolchain enables users to build management layers on top of any K8s resource. An example from K8s core would be the `Deployment` resource and controller which manages `Pod` resources.

Taking the `Deployment` controller as an inspiration, one way to achieve automatic restarts of Dataflow Jobs is to build a controller that watches for the state of `DataflowJob` resources and automatically deletes and recreates them if needed. If building such a controller is something our customers need, we would be happy to provide the support needed to make it happen.

Please let us know your thoughts.
