### ISSUE TITLE
Resolving IAP Brand Support Email Issue - How to Ensure Email Validity?

### ISSUE THREAD

**Issue by ericmalen** [GoogleCloudPlatform/k8s-config-connector#849]
### Describe your question

Has anyone had any luck creating an IAP Brand through config connector? Having issues with the spec.supportEmail field.
This is my .yaml file:

```
apiVersion: iap.cnrm.cloud.google.com/v1beta1
kind: IAPBrand
metadata:
  name: jitaccess-iap-brand
spec:
  applicationTitle: "Just-In-Time Access"
  supportEmail: "example@example.com"
```

The resources seems to be syncing without any issues (sync status on GCP is SYNCED), but the reconcile status stays in the RECONCILING state. When I run `nomos status`, I can see that I am getting this error: `googleapi: Error 400: Support email is not allowed: fake@my-domain.com`. I've tried several emails, some internal to my organization, some external to my organization, as well as the email of the account that is the admin of my project.

The only place I have found information on this issue is at the following link: https://github.com/hashicorp/terraform-provider-google/issues/6104. Hoping that since this worked for terraform, that it would also work for config connector, we tried doing what they said in that thread but haven't had any luck. We created a group, added the email (the support email we want to use) as a member and assigned the config connector service account as owner of the group - same error...

Any help or tips would be greatly appreciated, thanks!
