### ISSUE TITLE
Adding IAMPolicyMember resources takes very long

### ISSUE THREAD

**Issue by prismec** [GoogleCloudPlatform/k8s-config-connector#855]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

Adding a new IAMPolicyMember resource takes a very long time (15-30 minutes). 
We have around 10.000 IAMPolicyMember resources. 

### Additional Diagnostic Information

-

### Kubernetes Cluster Version

v1.24.14-gke.2700

### Config Connector Version

1.95.0

### Config Connector Mode

cluster mode

### Steps to reproduce the issue

- Create a lot IAMPolicyMembers
- Create an additional IAMPolicyMember
- Resource is created quickly, but it takes a long time for the changes to take effect. No status is available until the changes are actually applied

### YAML snippets

```YAML
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: my-policy-member
spec:
  memberFrom:
    serviceAccountRef:
      name: my-service-account
  role: roles/bigquery.dataViewer
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: my-project
```
