### ISSUE TITLE
How to attach instance in ComputeNetworkEndpointGroup

### ISSUE THREAD

**Issue by marandalucas** [GoogleCloudPlatform/k8s-config-connector#856]
### Describe your question

Hello first of all, thank you so much for this awesome project

We were able to create a zonal neg and attach a VM.

Now, We have some trouble attaching the VM in the NEG.
https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computenetworkendpointgroup

```yaml
# The neg has been created with the following manifest
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetworkEndpointGroup
metadata:
  name: instance-a-neg-vm
spec:
  networkEndpointType: GCE_VM_IP_PORT
  location: asia-east1-a
  resourceID: instance-a-neg-vm
  networkRef:
    external: https://www.googleapis.com/compute/v1/projects/appspace-engineering/global/networks/appspace # Specify the network reference
  subnetworkRef:
    external: https://www.googleapis.com/compute/v1/projects/appspace-engineering/global/networks/production # Specify the network reference
```

**Unfortunately, we can not attach the instance to the neg, there's no documentation about it. 
How can we perform it?**

Thanks in advance
