### ISSUE TITLE
How to expose information about created resources to other workloads in the cluster ?

### ISSUE THREAD

**Issue by primeroz** [GoogleCloudPlatform/k8s-config-connector#88]
In my case i created a `Redis Instance` and would like to make the ip address automatically available to other workloads in the cluster so that i can actually use the redis instance itself.

* some resources create a Secret once they are reconcilde, like the iam service account key one
* some other have predictable names like `sql` or `buckets` 

But in the case of redis for example this is not the case

I was expecting / hoping that once the resource was reconciled i would get a configmap with the same fields as the resource status so that i could then use them in the workloads as ENV / volume mounts

```
kubectl get redisinstances.redis.cnrm.cloud.google.com -n sandbox redis-test1 -o yaml | yq read - 'status'
conditions:
- lastTransitionTime: "2020-02-18T16:06:26Z"
  message: The resource is up to date
  reason: UpToDate
  status: "True"
  type: Ready
createTime: "2020-02-18T16:02:11.444222567Z"
currentLocationId: europe-west1-d
host: 10.8.217.52
port: 6379
```

**Comment by TMaYaD** [comment]
Alternatively an admission controller that catches cnrm references in resources spec and replaces them would also work.

**Comment by TMaYaD** [comment]
@primeroz I found https://github.com/IBM/composable#namespaces which can be used to reference KCC resources.

**Comment by primeroz** [comment]
@TMaYaD interesting, your `google-fu` must be better then mine! 

I will give it a shot, but unfortunately in my case this might not be a good solution because i push my manifests using `flux` gitops operator ... and so i kind of rely on the manifests to be created as their kind for flux to be able to properly track them and delete them 

It might work though so i will surely try it

I actually had started to write a simple wrapper to run the entrypoint of a workload and be able to fetch any REF from any resource and export as env variable ... 

to be honest though i really believe that an operator like the `config connector` should provide a solution to this problem out of the box to be really usable

**Comment by maqiuyujoyce** [comment]
Hi @primeroz, thank you for your feedback. We've also received the same request from another customer. We are currently looking into how to best handle this scenario. Will let you know when we have any updates.

**Comment by zarbis** [comment]
Any progress on this? Or at least some sort of workaround for a time being?

**Comment by mikebryant** [comment]
A use-case I have is getting the connection details for an SQLInstance out of the resource

**Comment by TMaYaD** [comment]
@mikebryant The way I handle it is by using composable with external service.
```yaml
apiVersion: sql.cnrm.cloud.google.com/v1beta1
kind: SQLInstance
metadata:
  name: instance-name
spec:
  databaseVersion: POSTGRES_12
  region: us-central1
  settings:
    tier: db-custom-1-3840
    availabilityType: ZONAL
    ipConfiguration:
      ipv4Enabled: false
      privateNetworkRef:
        name: default
      requireSsl: false
    locationPreference:
      zone: us-central1-a
    backupConfiguration:
      enabled: true
---
# Turn into composable to skip kustomize from adding selectors
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Composable
metadata:
  name: cloudsql-instance-service
spec:
  template:
    kind: Service
    apiVersion: v1
    metadata:
      name: cloudsql-instance
    spec:
      type: ClusterIP
      ports:
      - port: 5432
        targetPort: 5432
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Composable
metadata:
  name: cloudsql-instance-endpoint
spec:
  template:
    apiVersion: v1
    kind: Endpoints
    metadata:
      name: cloudsql-instance
      labels:
        component: cloudsql
    subsets:
    - addresses:
        - ip:
            getValueFrom:
              kind: SQLInstance
              name: instance-name
              path: '{.status.firstIpAddress}'
              format-transformers:
                - ToString
      ports:
        - port: 5432

```
