### ISSUE TITLE
[CloudFunctionsFunction] GCS bucket resource does not match the expected pattern

### ISSUE THREAD

**Issue by b4nst** [GoogleCloudPlatform/k8s-config-connector#886]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

After following example on [CloudFunctionsFunction](https://cloud.google.com/config-connector/docs/reference/resource-docs/cloudfunctions/cloudfunctionsfunction), I ended up with an error on the event trigger resource.

### Additional Diagnostic Information

```
kubectl describe -n banst-dev storagebucket <redacted_bucket>
[...]
Normal  UpToDate  48m (x2 over 48m)  storagebucket-controller  The resource is up to date
```

### Kubernetes Cluster Version

v1.24.17-gke.200

### Config Connector Version

1.89.0

### Config Connector Mode

cluster mode

### Log Output

```
Events:
  Type     Reason        Age              From                               Message
  ----     ------        ----             ----                               -------
  Normal   Updating      4s (x3 over 6s)  cloudfunctionsfunction-controller  Update in progress
  Warning  UpdateFailed  4s (x3 over 6s)  cloudfunctionsfunction-controller  Update call failed: error applying desired state: googleapi: Error 400: The request has errors
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "GCS bucket resource <redacted_bucket> does not match the expected pattern, which is projects/{project}/buckets/{bucket}",
        "field": "event_trigger.resource"
      }
    ]
  }
]
```

### Steps to reproduce the issue

Apply resources, wait for result

### YAML snippets

```YAML
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  labels:
    app.kubernetes.io/name: opkg-registry
    app.kubernetes.io/version: 0.0.0-devel
  name: <redacted_bucket>
  namespace: banst-dev
---
apiVersion: cloudfunctions.cnrm.cloud.google.com/v1beta1
kind: CloudFunctionsFunction
metadata:
  annotations:
    action.timoni.sh/force: enabled
  labels:
    app.kubernetes.io/name: opkg-registry
    app.kubernetes.io/version: 0.0.0-devel
  name: opkg-registry-indexer-remove
  namespace: banst-dev
spec:
  description: Indexer for opkg-registry
  entryPoint: HandleDelete
  eventTrigger:
    eventType: google.storage.object.delete
    resourceRef:
      kind: StorageBucket
      name: <redacted_bucket>
    service: storage.googleapis.com
  projectRef:
    external: projects/<redacted>
  region: <redacted>
  runtime: go121
  sourceArchiveUrl: gs://<redacted>.zip
---
```
