### ISSUE TITLE
Container cluster stuck in delete phase

### ISSUE THREAD

**Issue by Scorpiion** [GoogleCloudPlatform/k8s-config-connector#92]
Hi,

I created a project and container cluster (GKE) using cc (config connector, do you have any other short?). Then I deleted the project, then I tried to delete the container cluster in cc I got this error:
```
status:
  conditions:
  - lastTransitionTime: "2020-02-12T12:43:22Z"
    message: 'Delete call failed: error fetching live state: error reading underlying
      resource: Cluster "cluster-b" has status "ERROR" with message "\n\t(1) Google
      Compute Engine: Project #XXXXXXXXXX has been deleted\n\t(2) Google Compute
      Engine: Project XXXXXXXXXX has been scheduled for deletion and cannot be used
      for API calls. Visit https://console.developers.google.com/iam-admin/projects?pendingDeletion=true
      to undelete the project."'
    reason: DeleteFailed
    status: "False"
    type: Ready
  endpoint: x.x.x.x
  instanceGroupUrls:
  - https://www.googleapis.com/compute/beta/projects/XXXXXXXXXX/zones/europe-north1-c/instanceGroups/gke-cluster-b-default-pool-8cb0f2ed-grp
  masterVersion: 1.14.10-gke.17
  servicesIpv4Cidr: 10.3.240.0/20
```

Okay, so my next step is that I "undelete" the project, then I would expect that cc can do it job and remove the resource, but it does not. I still have the cluster listed in `kubectl get containerclusters.container.cnrm.cloud.google.com --all-namespace`.

1. I assume this is a bug, but to avoid these situations I guess the recommended way is to always delete things with kubectl and delete everything under a project before the project? 
2. Is there some way to force delete a resource that is "dangling" like this? This is a dev cluster, so it's not a huge deal, but in a production cluster I would not like to have these "zombie object".

Thanks for your work on cc, I really like it!
