### ISSUE TITLE
Support importing existing GCP resource configuration into Config Connector

### ISSUE THREAD

**Issue by Scorpiion** [GoogleCloudPlatform/k8s-config-connector#93]
Hi, 

I'm sitting now and going thru all the settings of a container cluster, it's a bit of a manual process (mapping all these https://cloud.google.com/config-connector/docs/reference/resources#spec_49 to what I otherwise would have setup via UI or CLI). One thing I think is really nice in the GCP UI is that you can use the create UI of some resource and then get a gcloud/REST version that you can use as a base for scripts etc. Since that logic is already there, would be feasible to build a small tool/service that took a gcloud CLI command as input (or the JSON from the REST example) and produced the corresponding cc yaml file? 

Example input:
```
POST https://container.googleapis.com/v1beta1/projects/xxxxxxxxxxxx/zones/us-central1-a/clusters
{
  "cluster": {
    "name": "standard-cluster-1",
    "masterAuth": {
      "clientCertificateConfig": {}
    },
    "network": "projects/r-test-3/global/networks/default",
    "addonsConfig": {
      "httpLoadBalancing": {},
      "horizontalPodAutoscaling": {},
      "kubernetesDashboard": {
        "disabled": true
      },
      "istioConfig": {
        "disabled": true
      }
    },
    "subnetwork": "projects/r-test-3/regions/us-central1/subnetworks/default",
    "nodePools": [
      {
        "name": "default-pool",
        "config": {
          "machineType": "n1-standard-1",
          "diskSizeGb": 100,
          "oauthScopes": [
            "https://www.googleapis.com/auth/devstorage.read_only",
            "https://www.googleapis.com/auth/logging.write",
            "https://www.googleapis.com/auth/monitoring",
            "https://www.googleapis.com/auth/servicecontrol",
            "https://www.googleapis.com/auth/service.management.readonly",
            "https://www.googleapis.com/auth/trace.append"
          ],
          "imageType": "COS",
          "diskType": "pd-standard"
        },
        "initialNodeCount": 3,
        "autoscaling": {},
        "management": {
          "autoUpgrade": true,
          "autoRepair": true
        },
        "version": "1.14.10-gke.17"
      }
    ],
    "networkPolicy": {},
    "ipAllocationPolicy": {
      "useIpAliases": true
    },
    "masterAuthorizedNetworksConfig": {},
    "defaultMaxPodsConstraint": {
      "maxPodsPerNode": "110"
    },
    "authenticatorGroupsConfig": {},
    "privateClusterConfig": {},
    "databaseEncryption": {
      "state": "DECRYPTED"
    },
    "clusterTelemetry": {
      "type": "ENABLED"
    },
    "initialClusterVersion": "1.14.10-gke.17",
    "location": "us-central1-a"
  }
}
```

Example output (not a correct match, this is copied from the reference example):
```
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/remove-default-node-pool: "false"
  labels:
    label-one: "value-one"
  name: containercluster-sample
spec:
  location: us-central1-a
  initialNodeCount: 1
  loggingService: logging.googleapis.com/kubernetes
  monitoringService: monitoring.googleapis.com/kubernetes
....
```

I don't know how closely CC follows the underlying GCP API, but maybe it's quite close so this would not be too much work? 

I think it would be a very powerful tool that would make it a lot easier to get those initial yaml files by reusing your existing knowledge of the UI/CLI and/or REST api.
