### ISSUE TITLE
DNSManagedZone status.nameServers is not updated with custom NS record

### ISSUE THREAD

**Issue by ssmall** [GoogleCloudPlatform/k8s-config-connector#98]
`kubectl version`: 
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.9-gke.9", GitCommit:"a9973cbb2722793e2ea08d20880633ca61d3e669", GitTreeState:"clean", BuildDate:"2020-02-07T22:35:02Z", GoVersion:"go1.12.12b4", Compiler:"gc", Platform:"linux/amd64"}
```

# Steps to Reproduce
1. Install Config Connector using Workload Identity per [guide](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall)
2. Apply the following YAML using `kubectl apply -f`:
```yaml
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: my-dns-zone
spec:
  dnsName: "example.com."
  visibility: public
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: my-dns-ns-record
spec:
  name: "example.com."
  type: "NS"
  ttl: 300
  managedZoneRef:
    name: my-dns-zone
  rrdatas:
  - "not-a-real-nameserver1.example.com."
  - "not-a-real-nameserver2.example.com."
  - "not-a-real-nameserver3.example.com."
  - "not-a-real-nameserver4.example.com."
```

*NOTE:* This doesn't actually work with `example.com.` -- you will need to substitute a domain that you actually own to avoid errors creating the managed zone.

# Expected Behavior

Output of `kubectl get dnsmanagedzone/my-dns-zone -o jsonpath="{$.status.nameServers}"` matches output of `gcloud dns record-sets list -z my-dns-zone --filter="type:NS"`

# Actual Behavior

Output of `kubectl get dnsmanagedzone/my-dns-zone -o jsonpath="{$.status.nameServers}"`  is:

```
[ns-cloud-a1.googledomains.com. ns-cloud-a2.googledomains.com. ns-cloud-a3.googledomains.com. ns-cloud-a4.googledomains.com.]
```

whereas `gcloud dns record-sets list -z my-dns-zone --filter="type:NS"` returns:
```
NAME               TYPE  TTL  DATA
example.com.  NS    300  not-a-real-nameserver1.example.com.,not-a-real-nameserver2.example.com.,not-a-real-nameserver3.example.com.,not-a-real-nameserver4.example.com.
```
